In [53]:
import pandas as pd
import json
import re

# Import Separate DataFrames

## Import Listing Details

In [3]:
genre_imports = []
for i in range(1,41):
    genre_imports.append('genre_exports/export_%s.json' %(str(i)))

genre_imports

In [4]:
genre_scrape_df = pd.DataFrame()
for imp in genre_imports:
    genre_scrape_df = genre_scrape_df.append(pd.read_json(imp,orient='index'))

In [5]:
genre_scrape_df.head()

,Certificate,Director,Genre,Gross,Metascore,Rating,Runtime,Star1,Star1_URL,Star2,Star2_URL,Star3,Star3_URL,Star4,Star4_URL,Title,Votes,Year
http://www.imdb.com/title/tt0006206/,Not Rated,Louis Feuillade,"Action, Adventure, Crime",NaN,NaN,6.9,421 min,Musidora,http://www.imdb.com/name/nm0615736/?ref_=adv_l...,Édouard Mathé,http://www.imdb.com/name/nm0559013/?ref_=adv_l...,Marcel Lévesque,http://www.imdb.com/name/nm0529695/?ref_=adv_l...,Jean Aymé,http://www.imdb.com/name/nm0043923/?ref_=adv_l...,Les vampires,"3,519",1915
http://www.imdb.com/title/tt0009682/,Not Rated,Scott Sidney,"Action, Adventure",3.27,NaN,5.9,73 min,Elmo Lincoln,http://www.imdb.com/name/nm0511104/?ref_=adv_l...,Enid Markey,http://www.imdb.com/name/nm0548402/?ref_=adv_l...,True Boardman,http://www.imdb.com/name/nm0090204/?ref_=adv_l...,Kathleen Kirkham,http://www.imdb.com/name/nm0456615/?ref_=adv_l...,Tarzan of the Apes,541,1918
http://www.imdb.com/title/tt0014720/,Passed,James P. Hogan,"Action, Adventure, Drama",NaN,NaN,4.7,60 min,Thunder the Dog,http://www.imdb.com/name/nm1299062/?ref_=adv_l...,Clara Bow,http://www.imdb.com/name/nm0001966/?ref_=adv_l...,Harold Austin,http://www.imdb.com/name/nm0042395/?ref_=adv_l...,Eddie Phillips,http://www.imdb.com/name/nm0680376/?ref_=adv_l...,Black Lightning,9,1924
http://www.imdb.com/title/tt0015163/,Unrated,Donald Crisp,"Action, Comedy, Romance",0.30,NaN,8.0,59 min,Buster Keaton,http://www.imdb.com/name/nm0000036/?ref_=adv_l...,Buster Keaton,http://www.imdb.com/name/nm0000036/?ref_=adv_l...,Kathryn McGuire,http://www.imdb.com/name/nm0570230/?ref_=adv_l...,Frederick Vroom,http://www.imdb.com/name/nm0089162/?ref_=adv_l...,The Navigator,"7,287",1924
http://www.imdb.com/title/tt0015324/,Not Rated,Buster Keaton,"Action, Comedy, Romance",NaN,NaN,8.3,45 min,Buster Keaton,http://www.imdb.com/name/nm0000036/?ref_=adv_l...,Kathryn McGuire,http://www.imdb.com/name/nm0570230/?ref_=adv_l...,Joe Keaton,http://www.imdb.com/name/nm0444172/?ref_=adv_l...,Erwin Connelly,http://www.imdb.com/name/nm0175068/?ref_=adv_l...,Sherlock Jr.,"24,694",1924

In [6]:
genre_df = pd.DataFrame(genre_scrape_df)

In [7]:
genre_df.head()

,Certificate,Director,Genre,Gross,Metascore,Rating,Runtime,Star1,Star1_URL,Star2,Star2_URL,Star3,Star3_URL,Star4,Star4_URL,Title,Votes,Year
http://www.imdb.com/title/tt0006206/,Not Rated,Louis Feuillade,"Action, Adventure, Crime",NaN,NaN,6.9,421 min,Musidora,http://www.imdb.com/name/nm0615736/?ref_=adv_l...,Édouard Mathé,http://www.imdb.com/name/nm0559013/?ref_=adv_l...,Marcel Lévesque,http://www.imdb.com/name/nm0529695/?ref_=adv_l...,Jean Aymé,http://www.imdb.com/name/nm0043923/?ref_=adv_l...,Les vampires,"3,519",1915
http://www.imdb.com/title/tt0009682/,Not Rated,Scott Sidney,"Action, Adventure",3.27,NaN,5.9,73 min,Elmo Lincoln,http://www.imdb.com/name/nm0511104/?ref_=adv_l...,Enid Markey,http://www.imdb.com/name/nm0548402/?ref_=adv_l...,True Boardman,http://www.imdb.com/name/nm0090204/?ref_=adv_l...,Kathleen Kirkham,http://www.imdb.com/name/nm0456615/?ref_=adv_l...,Tarzan of the Apes,541,1918
http://www.imdb.com/title/tt0014720/,Passed,James P. Hogan,"Action, Adventure, Drama",NaN,NaN,4.7,60 min,Thunder the Dog,http://www.imdb.com/name/nm1299062/?ref_=adv_l...,Clara Bow,http://www.imdb.com/name/nm0001966/?ref_=adv_l...,Harold Austin,http://www.imdb.com/name/nm0042395/?ref_=adv_l...,Eddie Phillips,http://www.imdb.com/name/nm0680376/?ref_=adv_l...,Black Lightning,9,1924
http://www.imdb.com/title/tt0015163/,Unrated,Donald Crisp,"Action, Comedy, Romance",0.30,NaN,8.0,59 min,Buster Keaton,http://www.imdb.com/name/nm0000036/?ref_=adv_l...,Buster Keaton,http://www.imdb.com/name/nm0000036/?ref_=adv_l...,Kathryn McGuire,http://www.imdb.com/name/nm0570230/?ref_=adv_l...,Frederick Vroom,http://www.imdb.com/name/nm0089162/?ref_=adv_l...,The Navigator,"7,287",1924
http://www.imdb.com/title/tt0015324/,Not Rated,Buster Keaton,"Action, Comedy, Romance",NaN,NaN,8.3,45 min,Buster Keaton,http://www.imdb.com/name/nm0000036/?ref_=adv_l...,Kathryn McGuire,http://www.imdb.com/name/nm0570230/?ref_=adv_l...,Joe Keaton,http://www.imdb.com/name/nm0444172/?ref_=adv_l...,Erwin Connelly,http://www.imdb.com/name/nm0175068/?ref_=adv_l...,Sherlock Jr.,"24,694",1924

In [8]:
genre_df['ID']=genre_df.index

In [9]:
len(genre_df)

188326

In [10]:
genre_df = genre_df.drop_duplicates(subset="ID", keep='first')

In [11]:
len(genre_df)

106906

In [12]:
genre_df['Rating'].isnull().sum()

29609

In [13]:
genre_df = genre_df.dropna(subset = ['Rating'])

In [14]:
len(genre_df)

77297

In [15]:
genre_df['Votes'] = genre_df['Votes'].str.replace(',','')

genre_df['Votes']

In [16]:
genre_df['Votes'] = genre_df['Votes'].astype(int)

In [17]:
len(genre_df[genre_df['Votes'] >= 500])

29717

In [18]:
genre_df = genre_df[genre_df['Votes'] >= 500]

In [19]:
len(genre_df)

29717

In [20]:
genre_df.head()

,Certificate,Director,Genre,Gross,Metascore,Rating,Runtime,Star1,Star1_URL,Star2,Star2_URL,Star3,Star3_URL,Star4,Star4_URL,Title,Votes,Year,ID
http://www.imdb.com/title/tt0006206/,Not Rated,Louis Feuillade,"Action, Adventure, Crime",NaN,NaN,6.9,421 min,Musidora,http://www.imdb.com/name/nm0615736/?ref_=adv_l...,Édouard Mathé,http://www.imdb.com/name/nm0559013/?ref_=adv_l...,Marcel Lévesque,http://www.imdb.com/name/nm0529695/?ref_=adv_l...,Jean Aymé,http://www.imdb.com/name/nm0043923/?ref_=adv_l...,Les vampires,3519,1915,http://www.imdb.com/title/tt0006206/
http://www.imdb.com/title/tt0009682/,Not Rated,Scott Sidney,"Action, Adventure",3.27,NaN,5.9,73 min,Elmo Lincoln,http://www.imdb.com/name/nm0511104/?ref_=adv_l...,Enid Markey,http://www.imdb.com/name/nm0548402/?ref_=adv_l...,True Boardman,http://www.imdb.com/name/nm0090204/?ref_=adv_l...,Kathleen Kirkham,http://www.imdb.com/name/nm0456615/?ref_=adv_l...,Tarzan of the Apes,541,1918,http://www.imdb.com/title/tt0009682/
http://www.imdb.com/title/tt0015163/,Unrated,Donald Crisp,"Action, Comedy, Romance",0.30,NaN,8.0,59 min,Buster Keaton,http://www.imdb.com/name/nm0000036/?ref_=adv_l...,Buster Keaton,http://www.imdb.com/name/nm0000036/?ref_=adv_l...,Kathryn McGuire,http://www.imdb.com/name/nm0570230/?ref_=adv_l...,Frederick Vroom,http://www.imdb.com/name/nm0089162/?ref_=adv_l...,The Navigator,7287,1924,http://www.imdb.com/title/tt0015163/
http://www.imdb.com/title/tt0015324/,Not Rated,Buster Keaton,"Action, Comedy, Romance",NaN,NaN,8.3,45 min,Buster Keaton,http://www.imdb.com/name/nm0000036/?ref_=adv_l...,Kathryn McGuire,http://www.imdb.com/name/nm0570230/?ref_=adv_l...,Joe Keaton,http://www.imdb.com/name/nm0444172/?ref_=adv_l...,Erwin Connelly,http://www.imdb.com/name/nm0175068/?ref_=adv_l...,Sherlock Jr.,24694,1924,http://www.imdb.com/title/tt0015324/
http://www.imdb.com/title/tt0017925/,Not Rated,Clyde Bruckman,"Action, Adventure, Comedy",NaN,NaN,8.2,67 min,Buster Keaton,http://www.imdb.com/name/nm0000036/?ref_=adv_l...,Buster Keaton,http://www.imdb.com/name/nm0000036/?ref_=adv_l...,Marion Mack,http://www.imdb.com/name/nm0533045/?ref_=adv_l...,Glen Cavender,http://www.imdb.com/name/nm0147070/?ref_=adv_l...,The General,61402,1926,http://www.imdb.com/title/tt0017925/

In [21]:
genre_df.drop(columns = ['Star1','Star1_URL', 'Star2','Star2_URL', 'Star3','Star3_URL', 'Star4','Star4_URL', 'Gross', 'Director'],inplace=True)

In [22]:
genre_df.head()

,Certificate,Genre,Metascore,Rating,Runtime,Title,Votes,Year,ID
http://www.imdb.com/title/tt0006206/,Not Rated,"Action, Adventure, Crime",NaN,6.9,421 min,Les vampires,3519,1915,http://www.imdb.com/title/tt0006206/
http://www.imdb.com/title/tt0009682/,Not Rated,"Action, Adventure",NaN,5.9,73 min,Tarzan of the Apes,541,1918,http://www.imdb.com/title/tt0009682/
http://www.imdb.com/title/tt0015163/,Unrated,"Action, Comedy, Romance",NaN,8.0,59 min,The Navigator,7287,1924,http://www.imdb.com/title/tt0015163/
http://www.imdb.com/title/tt0015324/,Not Rated,"Action, Comedy, Romance",NaN,8.3,45 min,Sherlock Jr.,24694,1924,http://www.imdb.com/title/tt0015324/
http://www.imdb.com/title/tt0017925/,Not Rated,"Action, Adventure, Comedy",NaN,8.2,67 min,The General,61402,1926,http://www.imdb.com/title/tt0017925/

In [23]:
genre_df.columns

Index(['Certificate', 'Genre', 'Metascore', 'Rating', 'Runtime', 'Title',
       'Votes', 'Year', 'ID'],
      dtype='object')

## Import Movie Details

In [24]:
detail_imports = []
detail_import_numbers = [1,2,3,5,6,7,10,11,12,15,16,17,20,21,22,25,26,27,30,31,32,35,36,37,40,41,42,45,46,47]   
for num in detail_import_numbers:
    detail_imports.append('movie_details_exports/movie_details_export_%s.json' %(str(num)))

detail_imports

In [25]:
details_scrape_df = pd.DataFrame()
for imp in detail_imports:
    details_scrape_df = details_scrape_df.append(pd.read_json(imp,orient='index'))

In [26]:
details_scrape_df.head()

,Budget,Country,Cumulative Worldwide Gross,Director,Director_URL,Gross USA,Language,Opening Weekend USA,Primary Filming Location,Production Company,Release Date,Star1,Star1_URL,Star2,Star2_URL,Star3,Star3_URL,Title
http://www.imdb.com/title/tt4937564/,2500000.0,UK,NaN,Sylvie Verheyde,http://www.imdb.com/name/nm0894173,NaN,English,NaN,None,Les Films du Veyrier,2017-02-10,Hafsia Herzi,http://www.imdb.com/name/nm2082567,Ash Stymest,http://www.imdb.com/name/nm7514839,Karole Rocher,http://www.imdb.com/name/nm0734039,Sex Doll
http://www.imdb.com/title/tt4937812/,500000000.0,India,NaN,Rajesh M. Selva,http://www.imdb.com/name/nm4301161,NaN,Tamil,NaN,"Chennai, Tamil Nadu, India",Raajkamal Films International,2015-11-13,Kamal Haasan,http://www.imdb.com/name/nm0352032,Prakash Raj,http://www.imdb.com/name/nm0695177,Trisha Krishnan,http://www.imdb.com/name/nm1375534,Thoongaavanam
http://www.imdb.com/title/tt4939066/,12620000.0,South Korea,NaN,John H. Lee,http://www.imdb.com/name/nm0497565,1.022720e+12,Korean,3.166272e+09,"Seoul, South Korea",Taewon Entertainment,2016-08-12,Liam Neeson,http://www.imdb.com/name/nm0000553,Jung-jae Lee,http://www.imdb.com/name/nm0497631,Beom-su Lee,http://www.imdb.com/name/nm1045934,Battle for Incheon: Operation Chromite
http://www.imdb.com/title/tt4940370/,63000000.0,Sweden,NaN,Felix Herngren,http://www.imdb.com/name/nm0379773,NaN,Swedish,NaN,None,NICE FLX Pictures,2017-04-25,Robert Gustafsson,http://www.imdb.com/name/nm0349052,Iwar Wiklander,http://www.imdb.com/name/nm0928002,David Wiberg,http://www.imdb.com/name/nm2433382,The 101-Year-Old Man Who Skipped Out on the Bi...
http://www.imdb.com/title/tt4940456/,NaN,India,NaN,Rakeysh Omprakash Mehra,http://www.imdb.com/name/nm1018493,NaN,Hindi,NaN,None,Cinestaan Film Company,2016-10-07,Harshvardhan Kapoor,http://www.imdb.com/name/nm7561367,Saiyami Kher,http://www.imdb.com/name/nm7517362,Art Malik,http://www.imdb.com/name/nm0539562,Mirzya

In [27]:
len(details_scrape_df)

29717

In [28]:
details_df = pd.DataFrame(details_scrape_df)

In [29]:
details_df.head()

,Budget,Country,Cumulative Worldwide Gross,Director,Director_URL,Gross USA,Language,Opening Weekend USA,Primary Filming Location,Production Company,Release Date,Star1,Star1_URL,Star2,Star2_URL,Star3,Star3_URL,Title
http://www.imdb.com/title/tt4937564/,2500000.0,UK,NaN,Sylvie Verheyde,http://www.imdb.com/name/nm0894173,NaN,English,NaN,None,Les Films du Veyrier,2017-02-10,Hafsia Herzi,http://www.imdb.com/name/nm2082567,Ash Stymest,http://www.imdb.com/name/nm7514839,Karole Rocher,http://www.imdb.com/name/nm0734039,Sex Doll
http://www.imdb.com/title/tt4937812/,500000000.0,India,NaN,Rajesh M. Selva,http://www.imdb.com/name/nm4301161,NaN,Tamil,NaN,"Chennai, Tamil Nadu, India",Raajkamal Films International,2015-11-13,Kamal Haasan,http://www.imdb.com/name/nm0352032,Prakash Raj,http://www.imdb.com/name/nm0695177,Trisha Krishnan,http://www.imdb.com/name/nm1375534,Thoongaavanam
http://www.imdb.com/title/tt4939066/,12620000.0,South Korea,NaN,John H. Lee,http://www.imdb.com/name/nm0497565,1.022720e+12,Korean,3.166272e+09,"Seoul, South Korea",Taewon Entertainment,2016-08-12,Liam Neeson,http://www.imdb.com/name/nm0000553,Jung-jae Lee,http://www.imdb.com/name/nm0497631,Beom-su Lee,http://www.imdb.com/name/nm1045934,Battle for Incheon: Operation Chromite
http://www.imdb.com/title/tt4940370/,63000000.0,Sweden,NaN,Felix Herngren,http://www.imdb.com/name/nm0379773,NaN,Swedish,NaN,None,NICE FLX Pictures,2017-04-25,Robert Gustafsson,http://www.imdb.com/name/nm0349052,Iwar Wiklander,http://www.imdb.com/name/nm0928002,David Wiberg,http://www.imdb.com/name/nm2433382,The 101-Year-Old Man Who Skipped Out on the Bi...
http://www.imdb.com/title/tt4940456/,NaN,India,NaN,Rakeysh Omprakash Mehra,http://www.imdb.com/name/nm1018493,NaN,Hindi,NaN,None,Cinestaan Film Company,2016-10-07,Harshvardhan Kapoor,http://www.imdb.com/name/nm7561367,Saiyami Kher,http://www.imdb.com/name/nm7517362,Art Malik,http://www.imdb.com/name/nm0539562,Mirzya

In [30]:
len(details_df)

29717

In [31]:
details_df['ID'] = details_df.index

In [32]:
details_df.head()

,Budget,Country,Cumulative Worldwide Gross,Director,Director_URL,Gross USA,Language,Opening Weekend USA,Primary Filming Location,Production Company,Release Date,Star1,Star1_URL,Star2,Star2_URL,Star3,Star3_URL,Title,ID
http://www.imdb.com/title/tt4937564/,2500000.0,UK,NaN,Sylvie Verheyde,http://www.imdb.com/name/nm0894173,NaN,English,NaN,None,Les Films du Veyrier,2017-02-10,Hafsia Herzi,http://www.imdb.com/name/nm2082567,Ash Stymest,http://www.imdb.com/name/nm7514839,Karole Rocher,http://www.imdb.com/name/nm0734039,Sex Doll,http://www.imdb.com/title/tt4937564/
http://www.imdb.com/title/tt4937812/,500000000.0,India,NaN,Rajesh M. Selva,http://www.imdb.com/name/nm4301161,NaN,Tamil,NaN,"Chennai, Tamil Nadu, India",Raajkamal Films International,2015-11-13,Kamal Haasan,http://www.imdb.com/name/nm0352032,Prakash Raj,http://www.imdb.com/name/nm0695177,Trisha Krishnan,http://www.imdb.com/name/nm1375534,Thoongaavanam,http://www.imdb.com/title/tt4937812/
http://www.imdb.com/title/tt4939066/,12620000.0,South Korea,NaN,John H. Lee,http://www.imdb.com/name/nm0497565,1.022720e+12,Korean,3.166272e+09,"Seoul, South Korea",Taewon Entertainment,2016-08-12,Liam Neeson,http://www.imdb.com/name/nm0000553,Jung-jae Lee,http://www.imdb.com/name/nm0497631,Beom-su Lee,http://www.imdb.com/name/nm1045934,Battle for Incheon: Operation Chromite,http://www.imdb.com/title/tt4939066/
http://www.imdb.com/title/tt4940370/,63000000.0,Sweden,NaN,Felix Herngren,http://www.imdb.com/name/nm0379773,NaN,Swedish,NaN,None,NICE FLX Pictures,2017-04-25,Robert Gustafsson,http://www.imdb.com/name/nm0349052,Iwar Wiklander,http://www.imdb.com/name/nm0928002,David Wiberg,http://www.imdb.com/name/nm2433382,The 101-Year-Old Man Who Skipped Out on the Bi...,http://www.imdb.com/title/tt4940370/
http://www.imdb.com/title/tt4940456/,NaN,India,NaN,Rakeysh Omprakash Mehra,http://www.imdb.com/name/nm1018493,NaN,Hindi,NaN,None,Cinestaan Film Company,2016-10-07,Harshvardhan Kapoor,http://www.imdb.com/name/nm7561367,Saiyami Kher,http://www.imdb.com/name/nm7517362,Art Malik,http://www.imdb.com/name/nm0539562,Mirzya,http://www.imdb.com/title/tt4940456/

In [33]:
details_df['Cumulative Worldwide Gross'].notnull().sum()

3735

In [34]:
round((details_df['Cumulative Worldwide Gross'].notnull().sum() / len(details_df))*100,2)

12.57

In [35]:
details_df['Opening Weekend USA'].notnull().sum()

8830

In [36]:
round((details_df['Opening Weekend USA'].notnull().sum() / len(details_df))*100,2)

29.710000000000001

In [37]:
details_df['Gross USA'].notnull().sum()

11584

In [38]:
round((details_df['Gross USA'].notnull().sum() / len(details_df))*100,2)

38.979999999999997

In [39]:
details_df.head()

,Budget,Country,Cumulative Worldwide Gross,Director,Director_URL,Gross USA,Language,Opening Weekend USA,Primary Filming Location,Production Company,Release Date,Star1,Star1_URL,Star2,Star2_URL,Star3,Star3_URL,Title,ID
http://www.imdb.com/title/tt4937564/,2500000.0,UK,NaN,Sylvie Verheyde,http://www.imdb.com/name/nm0894173,NaN,English,NaN,None,Les Films du Veyrier,2017-02-10,Hafsia Herzi,http://www.imdb.com/name/nm2082567,Ash Stymest,http://www.imdb.com/name/nm7514839,Karole Rocher,http://www.imdb.com/name/nm0734039,Sex Doll,http://www.imdb.com/title/tt4937564/
http://www.imdb.com/title/tt4937812/,500000000.0,India,NaN,Rajesh M. Selva,http://www.imdb.com/name/nm4301161,NaN,Tamil,NaN,"Chennai, Tamil Nadu, India",Raajkamal Films International,2015-11-13,Kamal Haasan,http://www.imdb.com/name/nm0352032,Prakash Raj,http://www.imdb.com/name/nm0695177,Trisha Krishnan,http://www.imdb.com/name/nm1375534,Thoongaavanam,http://www.imdb.com/title/tt4937812/
http://www.imdb.com/title/tt4939066/,12620000.0,South Korea,NaN,John H. Lee,http://www.imdb.com/name/nm0497565,1.022720e+12,Korean,3.166272e+09,"Seoul, South Korea",Taewon Entertainment,2016-08-12,Liam Neeson,http://www.imdb.com/name/nm0000553,Jung-jae Lee,http://www.imdb.com/name/nm0497631,Beom-su Lee,http://www.imdb.com/name/nm1045934,Battle for Incheon: Operation Chromite,http://www.imdb.com/title/tt4939066/
http://www.imdb.com/title/tt4940370/,63000000.0,Sweden,NaN,Felix Herngren,http://www.imdb.com/name/nm0379773,NaN,Swedish,NaN,None,NICE FLX Pictures,2017-04-25,Robert Gustafsson,http://www.imdb.com/name/nm0349052,Iwar Wiklander,http://www.imdb.com/name/nm0928002,David Wiberg,http://www.imdb.com/name/nm2433382,The 101-Year-Old Man Who Skipped Out on the Bi...,http://www.imdb.com/title/tt4940370/
http://www.imdb.com/title/tt4940456/,NaN,India,NaN,Rakeysh Omprakash Mehra,http://www.imdb.com/name/nm1018493,NaN,Hindi,NaN,None,Cinestaan Film Company,2016-10-07,Harshvardhan Kapoor,http://www.imdb.com/name/nm7561367,Saiyami Kher,http://www.imdb.com/name/nm7517362,Art Malik,http://www.imdb.com/name/nm0539562,Mirzya,http://www.imdb.com/title/tt4940456/

## Import Director Details

In [40]:
director_imports = []
director_import_numbers = [1,2,5,6,10,11,15,16,20,21,25,26]   
for num in director_import_numbers:
    director_imports.append('director_details_exports/director_details_export_%s.json' %(str(num)))

director_imports

In [41]:
directors_scrape_df = pd.DataFrame()
for imp in director_imports:
    directors_scrape_df = directors_scrape_df.append(pd.read_json(imp,orient='index'))

In [42]:
directors_scrape_df.head()

,Acting Roles,Age at Death,Award Info,Birth Country,Birthdate,Birthplace,Birthyear,Cinematographic Roles,Deathyear,Directing Roles,Editing Roles,Gender,Height in m,Name,Producing Roles,Publicity Listings,Star Sign,TV Appearances,Writing Roles
http://www.imdb.com/name/nm3174584,NaN,NaN,Won 1 Oscar. Another 23 wins & 33 nominations.,None,None,None,NaN,NaN,NaN,3,1.0,None,NaN,Armando Bo,3.0,NaN,None,5.0,5.0
http://www.imdb.com/name/nm3176551,6.0,NaN,3 wins & 6 nominations.,France,1978-5-5,"Paris, France",1978.0,NaN,NaN,2,NaN,Male,NaN,Riad Sattouf,1.0,NaN,Taurus,20.0,2.0
http://www.imdb.com/name/nm3177320,NaN,NaN,9 wins & 5 nominations.,None,None,None,NaN,NaN,NaN,1,NaN,None,NaN,Christina Yao,2.0,NaN,None,1.0,1.0
http://www.imdb.com/name/nm3179860,10.0,NaN,12 wins & 10 nominations.,None,None,None,NaN,13.0,NaN,15,14.0,Male,NaN,Doug Roos,71.0,NaN,None,NaN,15.0
http://www.imdb.com/name/nm3179896,5.0,NaN,5 wins.,USA,1970-1-6,"Shreveport, Louisiana, USA",1970.0,NaN,NaN,3,1.0,Male,1.78,Norman Gregory McGuire,6.0,NaN,Capricorn,NaN,2.0

In [43]:
len(directors_scrape_df)

11939

In [44]:
directors_df = pd.DataFrame(directors_scrape_df)

In [45]:
directors_df.head()

,Acting Roles,Age at Death,Award Info,Birth Country,Birthdate,Birthplace,Birthyear,Cinematographic Roles,Deathyear,Directing Roles,Editing Roles,Gender,Height in m,Name,Producing Roles,Publicity Listings,Star Sign,TV Appearances,Writing Roles
http://www.imdb.com/name/nm3174584,NaN,NaN,Won 1 Oscar. Another 23 wins & 33 nominations.,None,None,None,NaN,NaN,NaN,3,1.0,None,NaN,Armando Bo,3.0,NaN,None,5.0,5.0
http://www.imdb.com/name/nm3176551,6.0,NaN,3 wins & 6 nominations.,France,1978-5-5,"Paris, France",1978.0,NaN,NaN,2,NaN,Male,NaN,Riad Sattouf,1.0,NaN,Taurus,20.0,2.0
http://www.imdb.com/name/nm3177320,NaN,NaN,9 wins & 5 nominations.,None,None,None,NaN,NaN,NaN,1,NaN,None,NaN,Christina Yao,2.0,NaN,None,1.0,1.0
http://www.imdb.com/name/nm3179860,10.0,NaN,12 wins & 10 nominations.,None,None,None,NaN,13.0,NaN,15,14.0,Male,NaN,Doug Roos,71.0,NaN,None,NaN,15.0
http://www.imdb.com/name/nm3179896,5.0,NaN,5 wins.,USA,1970-1-6,"Shreveport, Louisiana, USA",1970.0,NaN,NaN,3,1.0,Male,1.78,Norman Gregory McGuire,6.0,NaN,Capricorn,NaN,2.0

In [46]:
len(directors_df)

11939

In [47]:
directors_df['Director_URL'] = directors_df.index

In [48]:
directors_df.head()

,Acting Roles,Age at Death,Award Info,Birth Country,Birthdate,Birthplace,Birthyear,Cinematographic Roles,Deathyear,Directing Roles,Editing Roles,Gender,Height in m,Name,Producing Roles,Publicity Listings,Star Sign,TV Appearances,Writing Roles,Director_URL
http://www.imdb.com/name/nm3174584,NaN,NaN,Won 1 Oscar. Another 23 wins & 33 nominations.,None,None,None,NaN,NaN,NaN,3,1.0,None,NaN,Armando Bo,3.0,NaN,None,5.0,5.0,http://www.imdb.com/name/nm3174584
http://www.imdb.com/name/nm3176551,6.0,NaN,3 wins & 6 nominations.,France,1978-5-5,"Paris, France",1978.0,NaN,NaN,2,NaN,Male,NaN,Riad Sattouf,1.0,NaN,Taurus,20.0,2.0,http://www.imdb.com/name/nm3176551
http://www.imdb.com/name/nm3177320,NaN,NaN,9 wins & 5 nominations.,None,None,None,NaN,NaN,NaN,1,NaN,None,NaN,Christina Yao,2.0,NaN,None,1.0,1.0,http://www.imdb.com/name/nm3177320
http://www.imdb.com/name/nm3179860,10.0,NaN,12 wins & 10 nominations.,None,None,None,NaN,13.0,NaN,15,14.0,Male,NaN,Doug Roos,71.0,NaN,None,NaN,15.0,http://www.imdb.com/name/nm3179860
http://www.imdb.com/name/nm3179896,5.0,NaN,5 wins.,USA,1970-1-6,"Shreveport, Louisiana, USA",1970.0,NaN,NaN,3,1.0,Male,1.78,Norman Gregory McGuire,6.0,NaN,Capricorn,NaN,2.0,http://www.imdb.com/name/nm3179896

In [51]:
awards_dir = directors_df['Award Info']

In [54]:
numbers_dir = [re.findall(r'\d+',x) if x is not None else None for x in awards_dir]
numbers_dir = [[int(i) for i in x] if x is not None else None for x in numbers_dir]
numbers_dir = [sum(x) if x is not None else None for x in numbers_dir]
awards_dir = numbers_dir
awards_dir

[57,
 9,
 14,
 22,
 5,
 None,
 20,
 3,
 None,
 None,
 None,
 41,
 None,
 16,
 None,
 None,
 1,
 30,
 3,
 6,
 2,
 None,
 None,
 17,
 None,
 177,
 1,
 None,
 None,
 2,
 26,
 1,
 1,
 2,
 1,
 1,
 3,
 None,
 None,
 None,
 None,
 2,
 None,
 None,
 None,
 5,
 1,
 None,
 None,
 None,
 9,
 7,
 None,
 1,
 None,
 8,
 10,
 1,
 3,
 36,
 13,
 None,
 1,
 7,
 None,
 1,
 None,
 1,
 None,
 7,
 24,
 5,
 2,
 2,
 6,
 2,
 None,
 14,
 None,
 22,
 19,
 17,
 2,
 None,
 14,
 1,
 12,
 6,
 9,
 None,
 None,
 1,
 1,
 None,
 None,
 6,
 None,
 33,
 None,
 None,
 None,
 2,
 None,
 2,
 None,
 2,
 None,
 None,
 None,
 3,
 None,
 2,
 None,
 56,
 None,
 3,
 1,
 1,
 3,
 4,
 18,
 None,
 2,
 None,
 1,
 None,
 5,
 3,
 None,
 2,
 8,
 5,
 4,
 None,
 None,
 None,
 15,
 None,
 1,
 4,
 None,
 3,
 None,
 None,
 41,
 9,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 7,
 None,
 22,
 3,
 None,
 2,
 19,
 12,
 2,
 3,
 None,
 1,
 None,
 6,
 1,
 None,
 2,
 None,
 10,
 None,
 2,
 3,
 1,
 17,
 8,
 None,
 9,
 59,
 None,
 None,
 12,
 4,
 5,
 None,
 3,
 2,
 68,
 15,
 5,
 5,
 25,
 None,
 4,
 None,
 18,
 17,
 None,
 None,
 1,
 2,
 None,
 None,
 20,
 None,
 16,
 None,
 None,
 None,
 7,
 2,
 None,
 None,
 2,
 12,
 1,
 None,
 12,
 2,
 None,
 4,
 None,
 2,
 None,
 20,
 None,
 1,
 1,
 None,
 2,
 6,
 5,
 8,
 3,
 None,
 3,
 42,
 None,
 None,
 None,
 None,
 None,
 6,
 13,
 2,
 None,
 1,
 None,
 3,
 15,
 9,
 9,
 10,
 39,
 None,
 2,
 2,
 18,
 1,
 None,
 5,
 1,
 None,
 None,
 11,
 2,
 6,
 8,
 13,
 1,
 None,
 8,
 None,
 1,
 None,
 7,
 None,
 2,
 15,
 None,
 None,
 10,
 None,
 6,
 4,
 None,
 1,
 8,
 2,
 None,
 6,
 18,
 4,
 2,
 23,
 17,
 None,
 None,
 None,
 None,
 2,
 1,
 None,
 None,
 4,
 2,
 None,
 None,
 None,
 None,
 4,
 12,
 None,
 8,
 2,
 12,
 5,
 2,
 2,
 None,
 21,
 3,
 4,
 16,
 None,
 None,
 5,
 26,
 None,
 5,
 None,
 1,
 2,
 None,
 None,
 13,
 17,
 6,
 2,
 1,
 2,
 None,
 2,
 None,
 9,
 None,
 None,
 1,
 None,
 2,
 1,
 14,
 None,
 4,
 25,
 None,
 1,
 None,
 1,
 6,
 3,
 23,
 None,
 10,
 3,
 1,
 None,
 3,
 6,
 1,
 None,
 1,
 2,
 None,
 3,
 None,
 2,
 None,
 None,
 None,
 13,
 None,
 None,
 None,
 2,
 None,
 7,
 None,
 None,
 None,
 None,
 1,
 None,
 3,
 None,
 4,
 2,
 70,
 2,
 None,
 2,
 7,
 2,
 6,
 None,
 3,
 None,
 None,
 21,
 4,
 None,
 None,
 2,
 None,
 1,
 8,
 4,
 None,
 None,
 36,
 None,
 7,
 1,
 None,
 None,
 2,
 3,
 1,
 5,
 None,
 None,
 4,
 1,
 2,
 4,
 None,
 3,
 30,
 3,
 None,
 None,
 1,
 19,
 1,
 26,
 1,
 34,
 2,
 26,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 11,
 None,
 None,
 None,
 None,
 None,
 None,
 3,
 None,
 None,
 2,
 6,
 17,
 None,
 1,
 25,
 1,
 None,
 4,
 21,
 None,
 None,
 None,
 10,
 None,
 10,
 None,
 7,
 4,
 None,
 None,
 1,
 6,
 None,
 10,
 6,
 1,
 4,
 2,
 11,
 2,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 2,
 14,
 8,
 12,
 None,
 15,
 None,
 None,
 None,
 3,
 1,
 None,
 None,
 None,
 1,
 None,
 3,
 None,
 None,
 None,
 None,
 None,
 None,
 15,
 1,
 1,
 5,
 1,
 None,
 7,
 None,
 2,
 1,
 29,
 None,
 None,
 None,
 None,
 2,
 None,
 None,
 None,
 None,
 13,
 4,
 10,
 None,
 1,
 1,
 None,
 None,
 5,
 24,
 11,
 None,
 11,
 None,
 1,
 None,
 None,
 1,
 None,
 6,
 None,
 2,
 None,
 None,
 None,
 2,
 None,
 None,
 4,
 1,
 37,
 None,
 None,
 3,
 2,
 None,
 5,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 2,
 None,
 2,
 None,
 None,
 None,
 19,
 None,
 None,
 None,
 14,
 4,
 10,
 None,
 10,
 22,
 27,
 4,
 None,
 2,
 9,
 None,
 3,
 None,
 3,
 3,
 None,
 None,
 None,
 None,
 8,
 None,
 17,
 None,
 1,
 None,
 1,
 None,
 None,
 10,
 None,
 None,
 None,
 2,
 None,
 1,
 3,
 11,
 21,
 2,
 None,
 3,
 1,
 None,
 None,
 12,
 None,
 2,
 None,
 5,
 None,
 7,
 None,
 2,
 13,
 5,
 1,
 23,
 13,
 None,
 8,
 3,
 4,
 None,
 1,
 19,
 10,
 3,
 None,
 None,
 None,
 1,
 None,
 1,
 None,
 None,
 None,
 None,
 4,
 1,
 None,
 None,
 3,
 None,
 None,
 None,
 7,
 1,
 12,
 None,
 4,
 None,
 6,
 3,
 1,
 None,
 None,
 1,
 None,
 None,
 2,
 None,
 6,
 None,
 2,
 None,
 None,
 None,
 None,
 3,
 2,
 1,
 4,
 None,
 3,
 6,
 6,
 1,
 11,
 2,
 7,
 None,
 5,
 None,
 None,
 None,
 2,
 6,
 1,
 None,
 1,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 9,
 None,
 2,
 4,
 None,
 1,
 1,
 1,
 None,
 1,
 None,
 None,
 None,
 1,
 3,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 12,
 18,
 None,
 2,
 None,
 None,
 2,
 None,
 3,
 3,
 None,
 2,
 3,
 None,
 7,
 None,
 1,
 9,
 None,
 None,
 None,
 None,
 None,
 2,
 7,
 4,
 None,
 None,
 None,
 3,
 1,
 8,
 None,
 2,
 None,
 1,
 None,
 None,
 None,
 1,
 None,
 23,
 1,
 1,
 None,
 None,
 None,
 2,
 None,
 None,
 None,
 14,
 2,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 1,
 4,
 1,
 18,
 None,
 None,
 None,
 None,
 None,
 None,
 8,
 2,
 None,
 None,
 None,
 2,
 None,
 None,
 None,
 None,
 None,
 2,
 None,
 None,
 1,
 None,
 None,
 1,
 1,
 3,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 11,
 None,
 3,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 14,
 None,
 18,
 4,
 1,
 None,
 None,
 4,
 None,
 1,
 None,
 4,
 None,
 None,
 2,
 2,
 None,
 None,
 None,
 2,
 None,
 1,
 None,
 None,
 13,
 1,
 6,
 1,
 11,
 None,
 None,
 1,
 None,
 None,
 2,
 1,
 6,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 7,
 3,
 None,
 None,
 5,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 21,
 None,
 None,
 2,
 None,
 1,
 4,
 None,
 None,
 1,
 None,
 2,
 None,
 None,
 None,
 1,
 None,
 1,
 None,
 None,
 1,
 1,
 3,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 13,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 ...]

In [55]:
directors_df['Award Nominations and Wins Director'] = awards_dir

In [59]:
directors_df.columns

Index(['Acting Roles', 'Age at Death', 'Award Info', 'Birth Country',
       'Birthdate', 'Birthplace', 'Birthyear', 'Cinematographic Roles',
       'Deathyear', 'Directing Roles', 'Editing Roles', 'Gender',
       'Height in m', 'Name', 'Producing Roles', 'Publicity Listings',
       'Star Sign', 'TV Appearances', 'Writing Roles', 'Director_URL',
       'Award Nominations and Wins Director'],
      dtype='object')

In [62]:
directors_df['Other Roles Director'] = sum([directors_df['Acting Roles'],
                                           directors_df['Cinematographic Roles'],
                                           directors_df['Editing Roles'],
                                           directors_df['Producing Roles'],
                                           directors_df['Writing Roles']])

In [63]:
directors_df['Other Roles Director']

http://www.imdb.com/name/nm3174584      NaN
http://www.imdb.com/name/nm3176551      NaN
http://www.imdb.com/name/nm3177320      NaN
http://www.imdb.com/name/nm3179860    123.0
http://www.imdb.com/name/nm3179896      NaN
http://www.imdb.com/name/nm3183376      NaN
http://www.imdb.com/name/nm3189793      NaN
http://www.imdb.com/name/nm3191889      NaN
http://www.imdb.com/name/nm3192191      NaN
http://www.imdb.com/name/nm3193346      NaN
http://www.imdb.com/name/nm3193712      NaN
http://www.imdb.com/name/nm3199492      NaN
http://www.imdb.com/name/nm3201973      NaN
http://www.imdb.com/name/nm3205815      NaN
http://www.imdb.com/name/nm3209872      NaN
http://www.imdb.com/name/nm3209937      NaN
http://www.imdb.com/name/nm3210041      NaN
http://www.imdb.com/name/nm3211470      NaN
http://www.imdb.com/name/nm3212856      NaN
http://www.imdb.com/name/nm3215871      NaN
http://www.imdb.com/name/nm3218978      NaN
http://www.imdb.com/name/nm3221483      NaN
http://www.imdb.com/name/nm3222230      NaN
http://www.imdb.com/name/nm3225709      NaN
http://www.imdb.com/name/nm3226283      NaN
http://www.imdb.com/name/nm3227090     17.0
http://www.imdb.com/name/nm3228270      NaN
http://www.imdb.com/name/nm3230448      NaN
http://www.imdb.com/name/nm3231736      NaN
http://www.imdb.com/name/nm3235590      NaN
                                      ...
http://www.imdb.com/name/nm0023469      NaN
http://www.imdb.com/name/nm0023517      NaN
http://www.imdb.com/name/nm0023551      NaN
http://www.imdb.com/name/nm0023747      NaN
http://www.imdb.com/name/nm0023753      NaN
http://www.imdb.com/name/nm0023832      NaN
http://www.imdb.com/name/nm0023859      NaN
http://www.imdb.com/name/nm0023929      NaN
http://www.imdb.com/name/nm0024120      NaN
http://www.imdb.com/name/nm0024617      NaN
http://www.imdb.com/name/nm0024622      NaN
http://www.imdb.com/name/nm0024887      NaN
http://www.imdb.com/name/nm0024912      NaN
http://www.imdb.com/name/nm0024925      NaN
http://www.imdb.com/name/nm0025008      NaN
http://www.imdb.com/name/nm0025241      NaN
http://www.imdb.com/name/nm0025399      NaN
http://www.imdb.com/name/nm0025435      NaN
http://www.imdb.com/name/nm0025534      NaN
http://www.imdb.com/name/nm0025538      NaN
http://www.imdb.com/name/nm0025627      NaN
http://www.imdb.com/name/nm0025629      NaN
http://www.imdb.com/name/nm0025640     30.0
http://www.imdb.com/name/nm0025778      NaN
http://www.imdb.com/name/nm0025805      NaN
http://www.imdb.com/name/nm0025823      NaN
http://www.imdb.com/name/nm0025955      NaN
http://www.imdb.com/name/nm0025978      NaN
http://www.imdb.com/name/nm0026442      NaN
http://www.imdb.com/name/nm0026824      NaN
Name: Other Roles Director, Length: 11939, dtype: float64

In [56]:
len(directors_df)

11939

In [57]:
directors_df.head(20)

,Acting Roles,Age at Death,Award Info,Birth Country,Birthdate,Birthplace,Birthyear,Cinematographic Roles,Deathyear,Directing Roles,...,Gender,Height in m,Name,Producing Roles,Publicity Listings,Star Sign,TV Appearances,Writing Roles,Director_URL,Award Nominations and Wins Director
http://www.imdb.com/name/nm3174584,NaN,NaN,Won 1 Oscar. Another 23 wins & 33 nominations.,None,None,None,NaN,NaN,NaN,3,...,None,NaN,Armando Bo,3.0,NaN,None,5.0,5.0,http://www.imdb.com/name/nm3174584,57.0
http://www.imdb.com/name/nm3176551,6.0,NaN,3 wins & 6 nominations.,France,1978-5-5,"Paris, France",1978.0,NaN,NaN,2,...,Male,NaN,Riad Sattouf,1.0,NaN,Taurus,20.0,2.0,http://www.imdb.com/name/nm3176551,9.0
http://www.imdb.com/name/nm3177320,NaN,NaN,9 wins & 5 nominations.,None,None,None,NaN,NaN,NaN,1,...,None,NaN,Christina Yao,2.0,NaN,None,1.0,1.0,http://www.imdb.com/name/nm3177320,14.0
http://www.imdb.com/name/nm3179860,10.0,NaN,12 wins & 10 nominations.,None,None,None,NaN,13.0,NaN,15,...,Male,NaN,Doug Roos,71.0,NaN,None,NaN,15.0,http://www.imdb.com/name/nm3179860,22.0
http://www.imdb.com/name/nm3179896,5.0,NaN,5 wins.,USA,1970-1-6,"Shreveport, Louisiana, USA",1970.0,NaN,NaN,3,...,Male,1.78,Norman Gregory McGuire,6.0,NaN,Capricorn,NaN,2.0,http://www.imdb.com/name/nm3179896,5.0
http://www.imdb.com/name/nm3183376,NaN,NaN,None,None,None,None,NaN,1.0,NaN,5,...,None,NaN,Rachid Dhibou,1.0,NaN,None,NaN,4.0,http://www.imdb.com/name/nm3183376,NaN
http://www.imdb.com/name/nm3189793,NaN,NaN,8 wins & 12 nominations.,None,None,None,NaN,NaN,NaN,5,...,Male,NaN,Alexandros Avranas,1.0,NaN,None,NaN,4.0,http://www.imdb.com/name/nm3189793,20.0
http://www.imdb.com/name/nm3191889,NaN,NaN,3 wins.,USA,1985-1-14,"New York City, New York, USA",1985.0,NaN,NaN,3,...,Male,1.85,Jack Bryan,3.0,2.0,Capricorn,NaN,2.0,http://www.imdb.com/name/nm3191889,3.0
http://www.imdb.com/name/nm3192191,NaN,NaN,None,None,None,None,NaN,NaN,NaN,4,...,None,NaN,Stephen Cognetti,1.0,NaN,None,NaN,4.0,http://www.imdb.com/name/nm3192191,NaN
http://www.imdb.com/name/nm3193346,NaN,NaN,None,None,None,None,NaN,1.0,NaN,3,...,None,NaN,Darrell Wheat,NaN,NaN,None,NaN,3.0,http://www.imdb.com/name/nm3193346,NaN
http://www.imdb.com/name/nm3193712,NaN,NaN,None,None,None,None,NaN,1.0,NaN,2,...,None,NaN,Zach Hamer,1.0,NaN,None,NaN,2.0,http://www.imdb.com/name/nm3193712,NaN
http://www.imdb.com/name/nm3199492,NaN,NaN,17 wins & 24 nominations.,None,None,None,NaN,NaN,NaN,2,...,None,NaN,Michael Mayer,3.0,NaN,None,NaN,2.0,http://www.imdb.com/name/nm3199492,41.0
http://www.imdb.com/name/nm3201973,NaN,NaN,None,None,None,None,NaN,NaN,NaN,2,...,None,NaN,Anand Shankar,NaN,NaN,None,NaN,2.0,http://www.imdb.com/name/nm3201973,NaN
http://www.imdb.com/name/nm3205815,NaN,NaN,7 wins & 9 nominations.,Norway,1978-1-12,"Stavern, Norway",1978.0,NaN,NaN,10,...,None,NaN,Anne Sewitsky,NaN,NaN,Capricorn,NaN,4.0,http://www.imdb.com/name/nm3205815,16.0
http://www.imdb.com/name/nm3209872,1.0,NaN,None,None,None,None,NaN,NaN,NaN,7,...,None,NaN,Joe Chien,2.0,NaN,None,NaN,6.0,http://www.imdb.com/name/nm3209872,NaN
http://www.imdb.com/name/nm3209937,NaN,NaN,None,None,None,None,NaN,2.0,NaN,3,...,None,NaN,Oklahoma Ward,7.0,NaN,None,NaN,3.0,http://www.imdb.com/name/nm3209937,NaN
http://www.imdb.com/name/nm3210041,NaN,NaN,1 win.,None,None,None,NaN,1.0,NaN,5,...,None,NaN,Abel Vang,2.0,NaN,None,NaN,2.0,http://www.imdb.com/name/nm3210041,1.0
http://www.imdb.com/name/nm3211470,1.0,NaN,17 wins & 13 nominations.,None,None,None,NaN,NaN,NaN,4,...,None,NaN,Robert Eggers,NaN,NaN,None,6.0,4.0,http://www.imdb.com/name/nm3211470,30.0
http://www.imdb.com/name/nm3212856,NaN,NaN,1 win & 2 nominations.,None,None,None,NaN,NaN,NaN,6,...,None,NaN,Daniel Sandu,1.0,NaN,None,NaN,6.0,http://www.imdb.com/name/nm3212856,3.0
http://www.imdb.com/name/nm3215871,NaN,NaN,6 nominations.,None,None,None,NaN,1.0,NaN,2,...,None,NaN,Derek Hui,NaN,NaN,None,NaN,NaN,http://www.imdb.com/name/nm3215871,6.0

### Convert Variables in Useful Ones

In [64]:
directors_df.columns

Index(['Acting Roles', 'Age at Death', 'Award Info', 'Birth Country',
       'Birthdate', 'Birthplace', 'Birthyear', 'Cinematographic Roles',
       'Deathyear', 'Directing Roles', 'Editing Roles', 'Gender',
       'Height in m', 'Name', 'Producing Roles', 'Publicity Listings',
       'Star Sign', 'TV Appearances', 'Writing Roles', 'Director_URL',
       'Award Nominations and Wins Director', 'Other Roles Director'],
      dtype='object')

In [111]:
directors_df.rename(columns={
                            'TV Appearances':'TV Appearances Director',
                             'Birthyear':'Birthyear Director',
                             'Gender':'Gender Director',
                             'Directing Roles' : 'Directing Roles Director',
                             'Publicity Listings' : 'Publicity Listings Director',
                             'Name': 'Name Director',
                             'Height in m' :'Height Director'
                            }, inplace=True)

In [112]:
directors_df.columns

Index(['Directing Roles Director', 'Gender Director', 'Height Director',
       'Name Director', 'Publicity Listings Director',
       'TV Appearances Director', 'Director_URL',
       'Award Nominations and Wins Director', 'Other Roles Director'],
      dtype='object')

In [73]:
directors_df.drop(columns=[
    'Acting Roles',
    'Age at Death',
    'Award Info',
    'Birth Country',
    'Birthdate',
    'Birthplace', 
    'Cinematographic Roles',
    'Deathyear',
    'Editing Roles', 
    'Producing Roles',
    'Star Sign', 
    'Writing Roles',
    'Birthyear Director'
],inplace=True)

In [942]:
directors_df.columns

Index(['Directing Roles Director', 'Gender Director', 'Height Director',
       'Name Director', 'Publicity Listings Director',
       'TV Appearances Director', 'Director_URL',
       'Award Nominations and Wins Director', 'Other Roles Director'],
      dtype='object')

In [1011]:
directors_final_df = pd.DataFrame(
    directors_df[['Directing Roles Director', 
                                   'Gender Director', 
                                   'Height Director',
                                   'Publicity Listings Director', 
                                   'TV Appearances Director',
                                   'Director_URL', 
                                   'Award Nominations and Wins Director',
                                   'Other Roles Director']])

In [1012]:
directors_final_df.head()

,Directing Roles Director,Gender Director,Height Director,Publicity Listings Director,TV Appearances Director,Director_URL,Award Nominations and Wins Director,Other Roles Director
http://www.imdb.com/name/nm3174584,3,None,NaN,NaN,5.0,http://www.imdb.com/name/nm3174584,57.0,NaN
http://www.imdb.com/name/nm3176551,2,Male,NaN,NaN,20.0,http://www.imdb.com/name/nm3176551,9.0,NaN
http://www.imdb.com/name/nm3177320,1,None,NaN,NaN,1.0,http://www.imdb.com/name/nm3177320,14.0,NaN
http://www.imdb.com/name/nm3179860,15,Male,NaN,NaN,NaN,http://www.imdb.com/name/nm3179860,22.0,123.0
http://www.imdb.com/name/nm3179896,3,Male,1.78,NaN,NaN,http://www.imdb.com/name/nm3179896,5.0,NaN

In [1013]:
directors_final_df['Publicity Listings Director'].fillna(0.0,inplace=True)

In [1015]:
directors_final_df['TV Appearances Director'].fillna(0.0,inplace=True)

In [1016]:
directors_final_df['Other Roles Director'].fillna(0.0,inplace=True)

In [1017]:
directors_final_df['Directing Roles Director'].fillna(1.0,inplace=True)

In [1021]:
directors_final_df['Award Nominations and Wins Director'].fillna(0.0,inplace=True)

In [1022]:
directors_final_df.sample(30)

,Directing Roles Director,Gender Director,Height Director,Publicity Listings Director,TV Appearances Director,Director_URL,Award Nominations and Wins Director,Other Roles Director
http://www.imdb.com/name/nm0446109,23,None,NaN,0.0,0.0,http://www.imdb.com/name/nm0446109,3.0,0.0
http://www.imdb.com/name/nm0423646,25,Male,NaN,2.0,16.0,http://www.imdb.com/name/nm0423646,25.0,0.0
http://www.imdb.com/name/nm0994330,19,Male,NaN,0.0,0.0,http://www.imdb.com/name/nm0994330,3.0,0.0
http://www.imdb.com/name/nm0344927,49,Male,NaN,0.0,2.0,http://www.imdb.com/name/nm0344927,2.0,0.0
http://www.imdb.com/name/nm0826164,4,Male,NaN,1.0,3.0,http://www.imdb.com/name/nm0826164,0.0,0.0
http://www.imdb.com/name/nm1633002,2,None,NaN,0.0,0.0,http://www.imdb.com/name/nm1633002,4.0,0.0
http://www.imdb.com/name/nm0686375,16,Male,1.77,3.0,23.0,http://www.imdb.com/name/nm0686375,61.0,0.0
http://www.imdb.com/name/nm0452134,2,None,NaN,0.0,0.0,http://www.imdb.com/name/nm0452134,5.0,0.0
http://www.imdb.com/name/nm2759892,6,None,NaN,0.0,0.0,http://www.imdb.com/name/nm2759892,0.0,0.0
http://www.imdb.com/name/nm0689659,17,Male,NaN,0.0,0.0,http://www.imdb.com/name/nm0689659,0.0,0.0
http://www.imdb.com/name/nm0184323,14,None,NaN,0.0,3.0,http://www.imdb.com/name/nm0184323,17.0,0.0
http://www.imdb.com/name/nm0000814,29,Male,1.65,7.0,18.0,http://www.imdb.com/name/nm0000814,11.0,35.0
http://www.imdb.com/name/nm0014160,18,Male,NaN,0.0,2.0,http://www.imdb.com/name/nm0014160,4.0,0.0
http://www.imdb.com/name/nm0958778,16,Male,NaN,0.0,1.0,http://www.imdb.com/name/nm0958778,2.0,0.0
http://www.imdb.com/name/nm1042371,5,Male,NaN,0.0,0.0,http://www.imdb.com/name/nm1042371,0.0,0.0
http://www.imdb.com/name/nm3258390,4,Male,NaN,2.0,1.0,http://www.imdb.com/name/nm3258390,9.0,0.0
http://www.imdb.com/name/nm1376310,2,None,NaN,0.0,1.0,http://www.imdb.com/name/nm1376310,0.0,0.0
http://www.imdb.com/name/nm4399063,4,None,NaN,0.0,0.0,http://www.imdb.com/name/nm4399063,1.0,0.0
http://www.imdb.com/name/nm1980444,3,None,NaN,0.0,0.0,http://www.imdb.com/name/nm1980444,3.0,0.0
http://www.imdb.com/name/nm0717449,7,Male,1.75,5.0,2.0,http://www.imdb.com/name/nm0717449,0.0,0.0
http://www.imdb.com/name/nm0191685,4,Male,1.85,14.0,71.0,http://www.imdb.com/name/nm0191685,5.0,0.0
http://www.imdb.com/name/nm1197318,1,None,NaN,0.0,0.0,http://www.imdb.com/name/nm1197318,0.0,0.0
http://www.imdb.com/name/nm6119117,3,None,NaN,0.0,0.0,http://www.imdb.com/name/nm6119117,0.0,0.0
http://www.imdb.com/name/nm0611932,7,Male,1.73,2.0,14.0,http://www.imdb.com/name/nm0611932,74.0,0.0
http://www.imdb.com/name/nm0333641,10,Male,NaN,0.0,1.0,http://www.imdb.com/name/nm0333641,4.0,0.0
http://www.imdb.com/name/nm1885212,6,Male,1.89,0.0,0.0,http://www.imdb.com/name/nm1885212,3.0,0.0
http://www.imdb.com/name/nm0295007,10,Male,NaN,0.0,0.0,http://www.imdb.com/name/nm0295007,0.0,0.0
http://www.imdb.com/name/nm0150897,21,Male,NaN,1.0,2.0,http://www.imdb.com/name/nm0150897,71.0,0.0
http://www.imdb.com/name/nm0016234,17,Male,NaN,0.0,13.0,http://www.imdb.com/name/nm0016234,32.0,0.0
http://www.imdb.com/name/nm0087595,6,Male,NaN,0.0,2.0,http://www.imdb.com/name/nm0087595,2.0,0.0

## Import Star Details

In [148]:
imports = []
import_numbers = [1,2,3,5,6,7,10,11,12,15,16,17,20,21,22,25,26,27,30,31,32,35,36,37,40,41,42,45,46,47,50,51,52,55]   
for num in import_numbers:
    imports.append('star_details_exports/star_details_export_%s.json' %(str(num)))

In [149]:
imports

['star_details_exports/star_details_export_1.json',
 'star_details_exports/star_details_export_2.json',
 'star_details_exports/star_details_export_3.json',
 'star_details_exports/star_details_export_5.json',
 'star_details_exports/star_details_export_6.json',
 'star_details_exports/star_details_export_7.json',
 'star_details_exports/star_details_export_10.json',
 'star_details_exports/star_details_export_11.json',
 'star_details_exports/star_details_export_12.json',
 'star_details_exports/star_details_export_15.json',
 'star_details_exports/star_details_export_16.json',
 'star_details_exports/star_details_export_17.json',
 'star_details_exports/star_details_export_20.json',
 'star_details_exports/star_details_export_21.json',
 'star_details_exports/star_details_export_22.json',
 'star_details_exports/star_details_export_25.json',
 'star_details_exports/star_details_export_26.json',
 'star_details_exports/star_details_export_27.json',
 'star_details_exports/star_details_export_30.json',
 'star_details_exports/star_details_export_31.json',
 'star_details_exports/star_details_export_32.json',
 'star_details_exports/star_details_export_35.json',
 'star_details_exports/star_details_export_36.json',
 'star_details_exports/star_details_export_37.json',
 'star_details_exports/star_details_export_40.json',
 'star_details_exports/star_details_export_41.json',
 'star_details_exports/star_details_export_42.json',
 'star_details_exports/star_details_export_45.json',
 'star_details_exports/star_details_export_46.json',
 'star_details_exports/star_details_export_47.json',
 'star_details_exports/star_details_export_50.json',
 'star_details_exports/star_details_export_51.json',
 'star_details_exports/star_details_export_52.json',
 'star_details_exports/star_details_export_55.json']

In [150]:
stars_scrape_df = pd.DataFrame()
for imp in imports:
    stars_scrape_df = stars_scrape_df.append(pd.read_json(imp,orient='index'))

In [229]:
stars_scrape_df['Birth Country'].unique()

array([None, 'United States', 'USA', 'UK', 'Germany', 'Japan', 'India',
       '1985', 'South Korea', 'Israel', 'Brazil', 'Romania', 'Taiwan',
       '1992', 'USSR [now Russia]', 'Turkey', 'Italy', 'Netherlands',
       '1993', 'France', 'Canada', 'Ghana', 'Ukraine', 'China',
       'United Arab Emirates', 'Switzerland', 'Bangladesh', 'Ireland',
       'Belgium', 'Istanbul', 'British India', 'Hungary', 'Argentina',
       '1994', 'Malaysia', 'Sweden', 'Russia', 'Spain', 'Pakistan',
       'Poland', 'Estonia', 'Mexico', 'Norway', 'Russia]', '1983', '2003',
       '1932', 'Vietnam', '1999', 'Ukraine]', '2002', 'Uruguay',
       'Saudi Arabia', 'United Kingdom', 'West Germany', 'Finland', '2005',
       'Denmark', 'Sri Lanka', 'São Paulo', 'USSR', 'New Zealand', 'Iran',
       '1974', '2000', '1982', 'Somalia', 'Kenya', 'Paris', 'Australia',
       'Yugoslavia', '1956', 'Chile', 'Morocco', 'Korea', '1991', 'Jordan',
       'Bulgaria', 'German Democratic Republic',
       'Czechoslovakia [now Slovakia]', 'Serbia', 'Thailand',
       'Yugoslavia [now Serbia]', 'Austria', 'South Africa',
       'Netherlands Antilles', 'Lithuania', 'Belarus]', 'Macedonia',
       'British Crown Colony', 'London', 'Greece', '1989', '1996',
       'Kazakhstan]', '1988', '1986', '1980', 'Hong Kong', 'Armenia',
       'Czechoslovakia', '1968', 'Puerto Rico', 'USSR [now Belarus]',
       '1997', 'Gabon', 'Kuwait', '1990', '1984', 'Lebanon',
       'Bosnia and Herzegovina', 'Philippines', 'Iceland', 'India]',
       'Albania', 'Czechoslovakia [now Czech Republic]', '1998',
       'Indonesia', 'Croatia', 'Grand-Duchy of Luxembourg', 'Egypt',
       'Chinchwad', 'Brunei', 'El Salvador', 'Singapore', '2001', '1973',
       '1981', 'Isle of Man', 'Afghanistan', '1970', 'USSR [now Ukraine]',
       'North Vietnam [now Vietnam]', '1959', 'Moldova]',
       'Dominican Republic', 'USSR [now Turkmenistan]',
       'USSR [now Latvia]', '1977', 'French Polynesia', 'Portugal', '1975',
       'Bahrain', 'Stockholm', '1995', '1987', 'Berlin', '1961',
       'Trinidad and Tobago', 'Cuba', 'DC', '1978', 'Bucharest', '1965',
       '1953', '1957', '1963', 'USSR [now Lithuania]', 'Portuguese Macau',
       'Nepal', 'Cyprus', 'Zimbabwe', 'Northern Ireland', 'Bermuda',
       'Barbados', 'Peru', '1964', 'Uzbekistan', 'Angola',
       'USSR [now Uzbekistan]', '1979', '1947', 'Nigeria', 'Mongolia',
       'Germany]', '1976', 'Moldavia', 'Colombia', 'Serbia and Montenegro',
       'USSR [now Estonia]', 'Burkina Faso', 'Oman',
       'USSR [now Azerbaijan]', 'Yugoslavia [now Croatia]', '1943', '1944',
       'Bahamas', '1952', 'Costa Rica', 'Ethiopia', 'Iraq', '1972',
       'Suriname', 'Tunisia', '1966', 'Algeria', 'Syria', 'Venezuela',
       'Moldova', '1931', '1945', '1971',
       'Czechoslovakia [now Slovak Republic]',
       'Yugoslavia [now Bosnia and Herzegovina]', '1949', 'Aruba',
       'Trinidad', '1969', '1942', 'Croatia]', 'Mauritius', '1937',
       'Turkey]', 'Haiti', '1958', '1921',
       'German Democratic Republic [now Federal Republic of Germany]',
       'East Germany', '1940', '1951', 'Persia', '1955',
       'Czechoslovakia [now in Czech Republic]', 'Guatemala', '1962',
       '1912', 'Poland]', '1948', '1928', 'Russian Empire [now Ukraine]',
       'Russian Empire [now Azerbaijan]', 'Lithuania]', '1954',
       'Austria-Hungary', 'France [now Algeria]', 'Congo', 'Samoa',
       'Bosnia and Herzegovina]', 'Ecuador', '1946', 'Hungary]', '1874',
       'Algeria]', '1918', 'Russian Empire [now Russia]', '1900',
       'Austria-Hungary [now Czech Republic]',
       'First Slovak Republic [now Slovakia]',
       'Austria-Hungary [now Austria]', 'Indonesia]', '1967', 'Romania]',
       'Dutch East Indies', '1924', 'Myanmar]', 'British West Indies',
       '1908', 'East Germany [now Germany]', '1939',
       'British India [now Pakistan]', 'UK]',
       'Austria-Hungary [now Hungary]', '1925', 'North Korea', '1950',
       '1922', 'Republic of Georgia]', '1910', 'Bronx New York', '1929',
       'Burma', 'Tibet', 'China]', 'Palestine [now Israel]', '1930',
       'Russian Empire', '1920', 'Russian Empire [now Latvia]',
       'Malaya [now Malaysia]',
       'British West Indies [now Saint Vincent and the Grenadines]',
       '1927', '1915', 'French Mandate of Syria and Lebanon [now Lebanon]',
       '1896', 'Sudan', 'Jamaica]', 'Russian Empire [now Belarus]',
       'French Protectorate of Morocco [now Morocco]', '1868',
       'British West Indies [now Trinidad and Tobago]', '1941',
       'Czech Republic', 'USA [now Oklahoma]',
       'Austria-Hungary [now Croatia]', '1909', '1960', 'Czech Republic]',
       '1897', 'Slovakia [now Slovak Republic]', 'Laos', '1934',
       'Protectorate of Bohemia and Moravia [now Czech Republic]',
       'Hungary [now Slovakia]', '1887', 'Slovenia',
       'USSR [now Tajikistan]', '1923', 'Libya', 'Bolivia',
       'Protectorate Bohemia and Moravia [now Czech Republic]', 'Latvia',
       'Republic of China', '1892', 'British India [now India]', 'Jamaica',
       'French Protectorate in Morocco [now Morocco]',
       'UK [now Republic of Ireland]', 'Zimbabwe]', 'Namibia', '1926',
       'Cambodia', 'Vietnam]', 'USSR [now Republic of Georgia]',
       'British India [now Bangladesh]', 'Luxembourg', 'USA]',
       'Irish Free State [now Ireland]', 'Fukuoka Prefecture]', 'Italy]',
       '1891', 'July 30', 'USA (some sources say 1907)', 'Honduras',
       'French Protectorate Tunisia [now Tunisia]', 'Armenia]', '1938',
       'Union of South Africa [now South Africa]', 'U.S', '1913',
       'Pakistan]', 'West Indies',
       'French Mandate for Syria and the Lebanon [now Lebanon]',
       'Martinique', '1902', 'Georgia', 'Yugoslavia [now Slovenia]',
       '1936', '1919', 'Senegal', 'Slovakia]', 'Mali',
       'Federal Republic of Germany]', '1935', 'Monaco', 'Palestine',
       'September 17', 'April 21', 'French West Indies',
       'Rakouská republika', 'USSR [now Georgia]', 'Uganda', '1914',
       'Austria-Hungary [now Slovakia]', 'British Burma', 'Norway]',
       'Greenland', 'Malta', 'Occupied Manchuria', '1933', 'Belarus',
       'Yemen', 'Eritrea', 'RSFSR [now Russia]', 'Ceylon [now Sri Lanka]',
       'Italy [now Fidenza]', 'Ukrainian SSR [now Ukraine]', 'Mozambique]',
       '1866', 'Western Samoa', 'British West Indies [now Grenada]',
       'Mozambique [now Maputo]', 'Austria-Hungary [now Serbia]',
       'Russia [now Finland]', 'French Protectorate Morocco [now Morocco]',
       'Sikkim', 'Irish Free State', 'England', 'Nicaragua',
       'Central America', 'Austrian Empire [now Hungary]',
       'Fehéroroszország', 'British Mandate of Palestine [now Israel]',
       'Ivory Coast', 'West Germany [now Germany]',
       'Russian Empire [now Uzbekistan]', 'Rhodesia', 'Channel Islands',
       '1898', 'Tahiti', 'Japan (some sources say 28 April 1917)', '1880',
       'Russia [now Georgia]', 'Romania [now Moldova]', '1905', 'Georgia]',
       'September 9', 'Panama', 'France [now Châlons-en-Champagne]',
       'East Pakistan', 'Ottoman Empire', 'Austria]',
       'British Guiana [now Guyana]', 'February 12', 'British Guiana',
       'Bangladesh]', '1889', 'Benin', 'Texas', 'USSR [now Armenia]',
       'Nyasaland [now Malawi]', 'British Malaya [now Malaysia]',
       'U.S. Virgin Islands', 'Union of South Africa [now Swaziland]',
       'Macau', 'often given in error)', 'Republic of Ireland]'], dtype=object)

In [233]:
stars_scrape_df[stars_scrape_df['Birth Country'] == '2003']

,Acting Roles,Age at Death,Award Info,Birth Country,Birthdate,Birthplace,Birthyear,Deathyear,Directing Roles,Gender,Height in m,Name,Producing Roles,Publicity Listings,Star Sign,TV Appearances,Star_URL,Other Roles Star,Award Nominations and Wins Star
http://www.imdb.com/name/nm8115247,NaN,NaN,None,2003,2003-9-9,2003,2003.0,NaN,NaN,Female,NaN,Jacqueline Chan,NaN,NaN,Virgo,NaN,http://www.imdb.com/name/nm8115247,NaN,NaN
http://www.imdb.com/name/nm4881741,16.0,NaN,None,2003,2003-7-18,2003,2003.0,NaN,NaN,Male,1.64,Hays Wellford,NaN,3.0,Cancer,1.0,http://www.imdb.com/name/nm4881741,NaN,NaN

In [559]:
stars_df = pd.DataFrame(stars_scrape_df)

In [560]:
stars_df.head(50)

,Acting Roles,Age at Death,Award Info,Birth Country,Birthdate,Birthplace,Birthyear,Deathyear,Directing Roles,Gender,Height in m,Name,Producing Roles,Publicity Listings,Star Sign,TV Appearances,Star_URL,Other Roles Star,Award Nominations and Wins Star
http://www.imdb.com/name/nm6178091,1.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,NaN,Giorgos Karakantas,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6178091,NaN,NaN
http://www.imdb.com/name/nm6178115,19.0,NaN,1 win.,None,None,None,NaN,NaN,NaN,Male,1.47,Kiefer O'Reilly,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6178115,NaN,1.0
http://www.imdb.com/name/nm6178682,2.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,NaN,Shadi Alfons,NaN,NaN,None,3.0,http://www.imdb.com/name/nm6178682,NaN,NaN
http://www.imdb.com/name/nm6179030,8.0,NaN,None,United States,2007-11-27,United States,2007.0,NaN,NaN,Male,1.35,Sage Correa,NaN,NaN,Sagittarius,3.0,http://www.imdb.com/name/nm6179030,NaN,NaN
http://www.imdb.com/name/nm6186725,1.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,NaN,Bogey,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6186725,NaN,NaN
http://www.imdb.com/name/nm6186788,NaN,NaN,None,None,None,None,NaN,NaN,NaN,Female,1.63,Francesca Santoro,1.0,NaN,None,NaN,http://www.imdb.com/name/nm6186788,NaN,NaN
http://www.imdb.com/name/nm6188875,NaN,NaN,None,None,None,None,NaN,NaN,NaN,Female,NaN,Kéfera Buchmann,NaN,NaN,None,6.0,http://www.imdb.com/name/nm6188875,NaN,NaN
http://www.imdb.com/name/nm6189602,NaN,NaN,None,None,None,None,NaN,NaN,NaN,Female,NaN,Ansiba,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6189602,NaN,NaN
http://www.imdb.com/name/nm6191250,NaN,NaN,None,USA,2003-1-1,"New York, USA",2003.0,NaN,NaN,Female,NaN,Ekaterina Samsonov,NaN,NaN,Capricorn,NaN,http://www.imdb.com/name/nm6191250,NaN,NaN
http://www.imdb.com/name/nm6192494,8.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,NaN,Tara-Alisha Berry,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6192494,NaN,NaN
http://www.imdb.com/name/nm6192976,6.0,NaN,1 nomination.,None,None,None,NaN,NaN,NaN,Male,NaN,Markees Christmas,NaN,NaN,None,1.0,http://www.imdb.com/name/nm6192976,NaN,1.0
http://www.imdb.com/name/nm6195447,10.0,NaN,None,None,None,None,NaN,NaN,1.0,Male,1.81,Sajjad Delafrooz,1.0,NaN,None,NaN,http://www.imdb.com/name/nm6195447,2.0,NaN
http://www.imdb.com/name/nm6199189,1.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,NaN,Ashutosh Acharya,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6199189,NaN,NaN
http://www.imdb.com/name/nm6200770,3.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,NaN,Julian Walker,NaN,NaN,None,2.0,http://www.imdb.com/name/nm6200770,NaN,NaN
http://www.imdb.com/name/nm6203418,9.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,NaN,Daran Somers,NaN,3.0,None,NaN,http://www.imdb.com/name/nm6203418,NaN,NaN
http://www.imdb.com/name/nm6208096,NaN,NaN,None,None,None,None,NaN,NaN,NaN,Female,NaN,Shelean Newman,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6208096,NaN,NaN
http://www.imdb.com/name/nm6210704,1.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,NaN,Ali Safina,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6210704,NaN,NaN
http://www.imdb.com/name/nm6210707,2.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,1.85,Wiqar Ali Khan,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6210707,NaN,NaN
http://www.imdb.com/name/nm6211008,2.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,NaN,Elisha Ali,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6211008,NaN,NaN
http://www.imdb.com/name/nm6216593,NaN,NaN,None,UK,1994-2-18,"Ealing, London, England, UK",1994.0,NaN,NaN,Female,NaN,Rose Williams,NaN,NaN,Aquarius,NaN,http://www.imdb.com/name/nm6216593,NaN,NaN
http://www.imdb.com/name/nm6216987,NaN,NaN,2 wins & 1 nomination.,Germany,1999-2-20,Germany,1999.0,NaN,NaN,Female,NaN,Lea van Acken,NaN,NaN,Pisces,NaN,http://www.imdb.com/name/nm6216987,NaN,3.0
http://www.imdb.com/name/nm6220383,NaN,NaN,None,None,None,None,NaN,NaN,NaN,Female,NaN,Brooke Skylar Baptist,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6220383,NaN,NaN
http://www.imdb.com/name/nm6220384,NaN,NaN,None,None,None,None,NaN,NaN,NaN,Female,NaN,Delta Storm Baptist,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6220384,NaN,NaN
http://www.imdb.com/name/nm6222008,3.0,NaN,1 win & 1 nomination.,None,None,None,NaN,NaN,NaN,Male,NaN,Ivo Pietzcker,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6222008,NaN,2.0
http://www.imdb.com/name/nm6223103,NaN,NaN,2 wins & 1 nomination.,None,None,None,NaN,NaN,1.0,Female,NaN,Saga Becker,NaN,NaN,None,2.0,http://www.imdb.com/name/nm6223103,NaN,3.0
http://www.imdb.com/name/nm6223116,11.0,NaN,None,Germany,1991-1-27,"Immenstadt, Bavaria, Germany",1991.0,NaN,NaN,Male,NaN,Kamil Szeptycki,NaN,NaN,Aquarius,NaN,http://www.imdb.com/name/nm6223116,NaN,NaN
http://www.imdb.com/name/nm6226698,NaN,NaN,None,None,None,None,NaN,NaN,NaN,Female,NaN,Saida Barmaki,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6226698,NaN,NaN
http://www.imdb.com/name/nm6226944,4.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,NaN,Thales Cavalcanti,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6226944,NaN,NaN
http://www.imdb.com/name/nm6228149,1.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,NaN,Rich Hamilton,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6228149,NaN,NaN
http://www.imdb.com/name/nm6228629,1.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,NaN,Santos,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6228629,NaN,NaN
http://www.imdb.com/name/nm6229748,11.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,NaN,Roshan Ravindra,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6229748,NaN,NaN
http://www.imdb.com/name/nm6229968,27.0,NaN,None,None,None,None,NaN,NaN,1.0,Male,NaN,Soubin Shahir,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6229968,NaN,NaN
http://www.imdb.com/name/nm6230258,35.0,NaN,None,UK,1967-8-16,"London, England, UK",1967.0,NaN,1.0,Male,NaN,Donovan Leitch Jr.,10.0,NaN,Leo,17.0,http://www.imdb.com/name/nm6230258,11.0,NaN
http://www.imdb.com/name/nm6231136,NaN,NaN,1 nomination.,USA,1991-10-19,"New York City, New York, USA",1991.0,NaN,NaN,Female,1.65,Samantha Robinson,NaN,NaN,Libra,1.0,http://www.imdb.com/name/nm6231136,NaN,1.0
http://www.imdb.com/name/nm6232988,2.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,NaN,Phoeung Kompheak,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6232988,NaN,NaN
http://www.imdb.com/name/nm6233165,NaN,NaN,2 nominations.,None,None,None,NaN,NaN,NaN,Female,NaN,Trang Le Hong,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6233165,NaN,2.0
http://www.imdb.com/name/nm6233871,NaN,NaN,None,Japan,1993-8-28,"Tokyo, Japan",1993.0,NaN,NaN,Female,1.60,Sora Amamiya,NaN,NaN,Virgo,NaN,http://www.imdb.com/name/nm6233871,NaN,NaN
http://www.imdb.com/name/nm6234020,NaN,NaN,None,None,None,None,NaN,NaN,NaN,Female,NaN,Nina Taylor,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6234020,NaN,NaN
http://www.imdb.com/name/nm6234427,4.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,NaN,Justin Gerhard,NaN,NaN,None,1.0,http://www.imdb.com/name/nm6234427,NaN,NaN
http://www.imdb.com/name/nm6237346,7.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,1.75,Judah Lewis,NaN,NaN,None,1.0,http://www.imdb.com/name/nm6237346,NaN,NaN
http://www.imdb.com/name/nm6237589,6.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,1.87,Gringe,NaN,NaN,None,6.0,http://www.imdb.com/name/nm6237589,NaN,NaN
http://www.imdb.com/name/nm6241625,7.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,NaN,Jörgen Liik,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6241625,NaN,NaN
http://www.imdb.com/name/nm6244732,NaN,NaN,None,None,None,None,NaN,NaN,NaN,Female,NaN,Jenifer Rodríguez,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6244732,NaN,NaN
http://www.imdb.com/name/nm6261003,4.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,NaN,Raphaël Thiéry,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6261003,NaN,NaN
http://www.imdb.com/name/nm6261738,3.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,NaN,Romy Beckman,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6261738,NaN,NaN
http://www.imdb.com/name/nm6264169,3.0,NaN,1 nomination.,None,None,None,NaN,NaN,NaN,Male,NaN,Hugo Bolton,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6264169,NaN,1.0
http://www.imdb.com/name/nm6264344,5.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,NaN,Enrique Arrizon,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6264344,NaN,NaN
http://www.imdb.com/name/nm6264784,NaN,NaN,None,None,None,None,NaN,NaN,NaN,Female,NaN,Nikki Galrani,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6264784,NaN,NaN
http://www.imdb.com/name/nm6276713,NaN,NaN,None,None,None,None,NaN,NaN,NaN,Female,NaN,Allegra Masters,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6276713,NaN,NaN
http://www.imdb.com/name/nm6277267,NaN,NaN,5 wins & 2 nominations.,India,1989-7-18,"Bombay, Maharashtra, India",1989.0,NaN,NaN,Female,NaN,Bhumi Pednekar,NaN,NaN,Cancer,NaN,http://www.imdb.com/name/nm6277267,NaN,7.0

In [561]:
stars_df['Star_URL'] = stars_df.index

In [562]:
stars_df.head()

,Acting Roles,Age at Death,Award Info,Birth Country,Birthdate,Birthplace,Birthyear,Deathyear,Directing Roles,Gender,Height in m,Name,Producing Roles,Publicity Listings,Star Sign,TV Appearances,Star_URL,Other Roles Star,Award Nominations and Wins Star
http://www.imdb.com/name/nm6178091,1.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,NaN,Giorgos Karakantas,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6178091,NaN,NaN
http://www.imdb.com/name/nm6178115,19.0,NaN,1 win.,None,None,None,NaN,NaN,NaN,Male,1.47,Kiefer O'Reilly,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6178115,NaN,1.0
http://www.imdb.com/name/nm6178682,2.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,NaN,Shadi Alfons,NaN,NaN,None,3.0,http://www.imdb.com/name/nm6178682,NaN,NaN
http://www.imdb.com/name/nm6179030,8.0,NaN,None,United States,2007-11-27,United States,2007.0,NaN,NaN,Male,1.35,Sage Correa,NaN,NaN,Sagittarius,3.0,http://www.imdb.com/name/nm6179030,NaN,NaN
http://www.imdb.com/name/nm6186725,1.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,NaN,Bogey,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6186725,NaN,NaN

In [563]:
stars_df.columns

Index(['Acting Roles', 'Age at Death', 'Award Info', 'Birth Country',
       'Birthdate', 'Birthplace', 'Birthyear', 'Deathyear', 'Directing Roles',
       'Gender', 'Height in m', 'Name', 'Producing Roles',
       'Publicity Listings', 'Star Sign', 'TV Appearances', 'Star_URL',
       'Other Roles Star', 'Award Nominations and Wins Star'],
      dtype='object')

In [564]:
stars_df['Other Roles Star'] = sum([stars_df['Directing Roles'],stars_df['Producing Roles']])

In [565]:
stars_df['Other Roles Star']

http://www.imdb.com/name/nm6178091     NaN
http://www.imdb.com/name/nm6178115     NaN
http://www.imdb.com/name/nm6178682     NaN
http://www.imdb.com/name/nm6179030     NaN
http://www.imdb.com/name/nm6186725     NaN
http://www.imdb.com/name/nm6186788     NaN
http://www.imdb.com/name/nm6188875     NaN
http://www.imdb.com/name/nm6189602     NaN
http://www.imdb.com/name/nm6191250     NaN
http://www.imdb.com/name/nm6192494     NaN
http://www.imdb.com/name/nm6192976     NaN
http://www.imdb.com/name/nm6195447     2.0
http://www.imdb.com/name/nm6199189     NaN
http://www.imdb.com/name/nm6200770     NaN
http://www.imdb.com/name/nm6203418     NaN
http://www.imdb.com/name/nm6208096     NaN
http://www.imdb.com/name/nm6210704     NaN
http://www.imdb.com/name/nm6210707     NaN
http://www.imdb.com/name/nm6211008     NaN
http://www.imdb.com/name/nm6216593     NaN
http://www.imdb.com/name/nm6216987     NaN
http://www.imdb.com/name/nm6220383     NaN
http://www.imdb.com/name/nm6220384     NaN
http://www.imdb.com/name/nm6222008     NaN
http://www.imdb.com/name/nm6223103     NaN
http://www.imdb.com/name/nm6223116     NaN
http://www.imdb.com/name/nm6226698     NaN
http://www.imdb.com/name/nm6226944     NaN
http://www.imdb.com/name/nm6228149     NaN
http://www.imdb.com/name/nm6228629     NaN
                                      ...
http://www.imdb.com/name/nm0000995     4.0
http://www.imdb.com/name/nm0000996    18.0
http://www.imdb.com/name/nm0000997     NaN
http://www.imdb.com/name/nm0000998     NaN
http://www.imdb.com/name/nm0000999     NaN
http://www.imdb.com/name/nm0001001     NaN
http://www.imdb.com/name/nm0001002    15.0
http://www.imdb.com/name/nm0001003     NaN
http://www.imdb.com/name/nm0001004     NaN
http://www.imdb.com/name/nm0001006     6.0
http://www.imdb.com/name/nm0001007     5.0
http://www.imdb.com/name/nm0001009     NaN
http://www.imdb.com/name/nm0001010     NaN
http://www.imdb.com/name/nm0001011     NaN
http://www.imdb.com/name/nm0001012     NaN
http://www.imdb.com/name/nm0001013     NaN
http://www.imdb.com/name/nm0001014    32.0
http://www.imdb.com/name/nm0001015     NaN
http://www.imdb.com/name/nm0001016    18.0
http://www.imdb.com/name/nm0001017     NaN
http://www.imdb.com/name/nm0001018     NaN
http://www.imdb.com/name/nm0001019     4.0
http://www.imdb.com/name/nm0001020     NaN
http://www.imdb.com/name/nm0001021     NaN
http://www.imdb.com/name/nm0001022     NaN
http://www.imdb.com/name/nm0001023    18.0
http://www.imdb.com/name/nm0001024    15.0
http://www.imdb.com/name/nm0001025     NaN
http://www.imdb.com/name/nm0001026     NaN
http://www.imdb.com/name/nm0001028     NaN
Name: Other Roles Star, Length: 33838, dtype: float64

In [566]:
awards_star = stars_df['Award Info']

In [567]:
numbers_star = [re.findall(r'\d+',x) if x is not None else None for x in awards_star]
numbers_star = [[int(i) for i in x] if x is not None else None for x in numbers_star]
numbers_star = [sum(x) if x is not None else None for x in numbers_star]
awards_star = numbers_star
awards_star

[None,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 3,
 None,
 None,
 2,
 3,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 2,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 7,
 None,
 None,
 None,
 2,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 3,
 1,
 1,
 None,
 2,
 1,
 None,
 None,
 4,
 None,
 None,
 1,
 3,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 1,
 None,
 None,
 2,
 None,
 2,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 2,
 None,
 1,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 1,
 1,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 2,
 1,
 2,
 11,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 2,
 1,
 7,
 None,
 None,
 None,
 None,
 3,
 4,
 None,
 1,
 3,
 6,
 2,
 None,
 3,
 None,
 None,
 None,
 2,
 2,
 1,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 9,
 None,
 None,
 1,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 3,
 None,
 1,
 None,
 None,
 1,
 None,
 1,
 None,
 None,
 1,
 None,
 2,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 3,
 None,
 None,
 None,
 2,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 7,
 None,
 None,
 None,
 None,
 None,
 None,
 2,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 4,
 None,
 13,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 7,
 None,
 None,
 2,
 2,
 25,
 2,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 1,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 2,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 3,
 2,
 None,
 None,
 1,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 5,
 3,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 4,
 None,
 1,
 None,
 None,
 1,
 None,
 None,
 None,
 3,
 21,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 2,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 1,
 3,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 2,
 None,
 None,
 7,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 1,
 None,
 None,
 1,
 None,
 None,
 1,
 None,
 None,
 None,
 3,
 None,
 None,
 1,
 None,
 1,
 6,
 6,
 5,
 None,
 None,
 2,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 3,
 3,
 3,
 3,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 9,
 None,
 None,
 None,
 None,
 1,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 2,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 11,
 None,
 1,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 14,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 21,
 None,
 2,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 2,
 None,
 None,
 None,
 1,
 None,
 None,
 3,
 1,
 None,
 1,
 None,
 None,
 None,
 None,
 None,
 3,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 4,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 1,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 6,
 None,
 1,
 None,
 None,
 2,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 3,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 2,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 2,
 None,
 2,
 None,
 None,
 None,
 5,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 3,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 2,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 2,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 1,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 ...]

In [568]:
stars_df['Award Nominations and Wins Star'] = awards_star

In [569]:
stars_df.head()

,Acting Roles,Age at Death,Award Info,Birth Country,Birthdate,Birthplace,Birthyear,Deathyear,Directing Roles,Gender,Height in m,Name,Producing Roles,Publicity Listings,Star Sign,TV Appearances,Star_URL,Other Roles Star,Award Nominations and Wins Star
http://www.imdb.com/name/nm6178091,1.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,NaN,Giorgos Karakantas,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6178091,NaN,NaN
http://www.imdb.com/name/nm6178115,19.0,NaN,1 win.,None,None,None,NaN,NaN,NaN,Male,1.47,Kiefer O'Reilly,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6178115,NaN,1.0
http://www.imdb.com/name/nm6178682,2.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,NaN,Shadi Alfons,NaN,NaN,None,3.0,http://www.imdb.com/name/nm6178682,NaN,NaN
http://www.imdb.com/name/nm6179030,8.0,NaN,None,United States,2007-11-27,United States,2007.0,NaN,NaN,Male,1.35,Sage Correa,NaN,NaN,Sagittarius,3.0,http://www.imdb.com/name/nm6179030,NaN,NaN
http://www.imdb.com/name/nm6186725,1.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,NaN,Bogey,NaN,NaN,None,NaN,http://www.imdb.com/name/nm6186725,NaN,NaN

In [570]:
stars_df.drop(columns=[
    'Age at Death',
    'Award Info',
    'Birthplace', 
    'Deathyear', 
    'Birthdate',
    'Producing Roles',
    'Directing Roles',
    'Star Sign'
],inplace=True)

In [571]:
stars_df.columns

Index(['Acting Roles', 'Birth Country', 'Birthyear', 'Gender', 'Height in m',
       'Name', 'Publicity Listings', 'TV Appearances', 'Star_URL',
       'Other Roles Star', 'Award Nominations and Wins Star'],
      dtype='object')

In [572]:
stars_df.rename(columns={
    'Acting Roles' : 'Acting Roles Star',
    'Birth Country':'Birth Country Star',
    'Birthyear':'Birthyear Star',
    'Gender':'Gender Star',
    'Height in m' : 'Height Star',
    'Name' : 'Name Star',
    'Publicity Listings': 'Publicity Listings Star',
    'TV Appearances': 'TV Appearances Star'
},inplace=True)

In [573]:
stars_df.columns

Index(['Acting Roles Star', 'Birth Country Star', 'Birthyear Star',
       'Gender Star', 'Height Star', 'Name Star', 'Publicity Listings Star',
       'TV Appearances Star', 'Star_URL', 'Other Roles Star',
       'Award Nominations and Wins Star'],
      dtype='object')

In [574]:
stars_df.sample(40)

,Acting Roles Star,Birth Country Star,Birthyear Star,Gender Star,Height Star,Name Star,Publicity Listings Star,TV Appearances Star,Star_URL,Other Roles Star,Award Nominations and Wins Star
http://www.imdb.com/name/nm2411369,NaN,None,NaN,Female,1.70,Kate Madison,NaN,1.0,http://www.imdb.com/name/nm2411369,11.0,6.0
http://www.imdb.com/name/nm0292841,42.0,USA,1924.0,Male,1.88,Dean Fredericks,NaN,1.0,http://www.imdb.com/name/nm0292841,NaN,NaN
http://www.imdb.com/name/nm2168632,NaN,Spain,1987.0,Female,NaN,Manuela Vellés,NaN,28.0,http://www.imdb.com/name/nm2168632,NaN,3.0
http://www.imdb.com/name/nm0001625,NaN,USA,1957.0,Female,1.63,Amanda Plummer,5.0,20.0,http://www.imdb.com/name/nm0001625,NaN,19.0
http://www.imdb.com/name/nm3776087,1.0,None,NaN,Male,NaN,Eliú Armas,NaN,NaN,http://www.imdb.com/name/nm3776087,NaN,NaN
http://www.imdb.com/name/nm0354283,15.0,None,NaN,Male,NaN,Richard Haines,NaN,NaN,http://www.imdb.com/name/nm0354283,NaN,NaN
http://www.imdb.com/name/nm2440445,NaN,USA,1970.0,Female,1.70,Darra Like Dat Boyd,NaN,5.0,http://www.imdb.com/name/nm2440445,NaN,NaN
http://www.imdb.com/name/nm0447220,96.0,USA,1921.0,Male,1.83,Ed Kemmer,7.0,NaN,http://www.imdb.com/name/nm0447220,NaN,NaN
http://www.imdb.com/name/nm0493179,NaN,1963,1963.0,Female,1.68,Cheryl Lawson,NaN,4.0,http://www.imdb.com/name/nm0493179,NaN,NaN
http://www.imdb.com/name/nm1388984,NaN,India,1982.0,Female,1.60,Nauheed Cyrusi,NaN,NaN,http://www.imdb.com/name/nm1388984,NaN,NaN
http://www.imdb.com/name/nm0021780,3.0,None,NaN,Male,NaN,Noam Almaz,NaN,NaN,http://www.imdb.com/name/nm0021780,NaN,NaN
http://www.imdb.com/name/nm0857576,43.0,None,NaN,Male,NaN,Michael Therriault,NaN,1.0,http://www.imdb.com/name/nm0857576,NaN,3.0
http://www.imdb.com/name/nm0895752,32.0,None,NaN,Male,NaN,Arnaud Viard,NaN,NaN,http://www.imdb.com/name/nm0895752,4.0,1.0
http://www.imdb.com/name/nm0537146,99.0,USA,1919.0,Male,1.93,Jock Mahoney,6.0,7.0,http://www.imdb.com/name/nm0537146,NaN,1.0
http://www.imdb.com/name/nm3805567,1.0,None,NaN,Male,NaN,Blondin Miguel,NaN,NaN,http://www.imdb.com/name/nm3805567,NaN,NaN
http://www.imdb.com/name/nm0111944,31.0,USA,1947.0,Male,NaN,David Allen Brooks,1.0,NaN,http://www.imdb.com/name/nm0111944,NaN,NaN
http://www.imdb.com/name/nm0845489,5.0,Sweden,1964.0,Male,NaN,Lars Söderdahl,NaN,NaN,http://www.imdb.com/name/nm0845489,NaN,NaN
http://www.imdb.com/name/nm0945280,28.0,Japan,1932.0,Male,1.67,Yasuo Yamada,NaN,2.0,http://www.imdb.com/name/nm0945280,NaN,NaN
http://www.imdb.com/name/nm0000044,86.0,USA,1913.0,Male,1.84,Burt Lancaster,28.0,80.0,http://www.imdb.com/name/nm0000044,17.0,46.0
http://www.imdb.com/name/nm4042042,NaN,None,NaN,Female,NaN,Christine Donlon,NaN,NaN,http://www.imdb.com/name/nm4042042,NaN,NaN
http://www.imdb.com/name/nm2122082,NaN,None,NaN,Female,NaN,Setareh Eskandari,NaN,NaN,http://www.imdb.com/name/nm2122082,NaN,NaN
http://www.imdb.com/name/nm0550318,222.0,USA,1935.0,Male,1.91,Kenneth Mars,NaN,11.0,http://www.imdb.com/name/nm0550318,NaN,1.0
http://www.imdb.com/name/nm0891927,9.0,Chile,NaN,Male,NaN,Vladimir Vega,NaN,1.0,http://www.imdb.com/name/nm0891927,NaN,1.0
http://www.imdb.com/name/nm0491701,34.0,Italy,1938.0,Male,NaN,Gino Lavagetto,NaN,NaN,http://www.imdb.com/name/nm0491701,NaN,NaN
http://www.imdb.com/name/nm0518821,24.0,Hong Kong,1952.0,Male,1.72,John Lone,4.0,3.0,http://www.imdb.com/name/nm0518821,NaN,4.0
http://www.imdb.com/name/nm0000142,70.0,USA,1930.0,Male,1.93,Clint Eastwood,208.0,278.0,http://www.imdb.com/name/nm0000142,83.0,304.0
http://www.imdb.com/name/nm0927641,73.0,Germany,1966.0,Male,1.86,Kai Wiesinger,NaN,16.0,http://www.imdb.com/name/nm0927641,2.0,6.0
http://www.imdb.com/name/nm0713614,65.0,USSR [now Russia],1965.0,Male,NaN,Vyacheslav Razbegaev,NaN,1.0,http://www.imdb.com/name/nm0713614,NaN,NaN
http://www.imdb.com/name/nm0058290,4.0,1889,1889.0,Male,NaN,Vladimir Barskiy,NaN,NaN,http://www.imdb.com/name/nm0058290,NaN,NaN
http://www.imdb.com/name/nm0001207,120.0,Puerto Rico,1912.0,Male,1.78,José Ferrer,5.0,58.0,http://www.imdb.com/name/nm0001207,8.0,10.0
http://www.imdb.com/name/nm0611561,45.0,None,NaN,Male,NaN,Shailen Mukherjee,NaN,NaN,http://www.imdb.com/name/nm0611561,NaN,NaN
http://www.imdb.com/name/nm1771676,2.0,None,NaN,Male,NaN,Sam Butler,NaN,NaN,http://www.imdb.com/name/nm1771676,NaN,NaN
http://www.imdb.com/name/nm0375631,NaN,East Germany,1983.0,Female,1.62,Luise Helm,NaN,2.0,http://www.imdb.com/name/nm0375631,2.0,1.0
http://www.imdb.com/name/nm0883195,68.0,USA,1970.0,Male,1.78,Jason Vail,1.0,4.0,http://www.imdb.com/name/nm0883195,NaN,6.0
http://www.imdb.com/name/nm3036925,NaN,None,NaN,Female,NaN,Greta Fernández,NaN,11.0,http://www.imdb.com/name/nm3036925,NaN,2.0
http://www.imdb.com/name/nm0303715,NaN,France,NaN,Female,NaN,Karine Gambier,NaN,NaN,http://www.imdb.com/name/nm0303715,NaN,NaN
http://www.imdb.com/name/nm4098287,NaN,None,NaN,Female,NaN,Audrey Bastien,NaN,NaN,http://www.imdb.com/name/nm4098287,NaN,NaN
http://www.imdb.com/name/nm0001518,57.0,USA,1961.0,Male,1.83,Dylan McDermott,20.0,70.0,http://www.imdb.com/name/nm0001518,3.0,21.0
http://www.imdb.com/name/nm1062847,1.0,None,NaN,Male,NaN,Mads Ravn,NaN,1.0,http://www.imdb.com/name/nm1062847,NaN,NaN
http://www.imdb.com/name/nm3889842,NaN,None,NaN,Female,NaN,Florencia Colucci,NaN,NaN,http://www.imdb.com/name/nm3889842,NaN,NaN

In [575]:
stars_df['Birth Country Star'] = stars_df['Birth Country Star'].str.replace(']','')

In [576]:
stars_df.head(10)

,Acting Roles Star,Birth Country Star,Birthyear Star,Gender Star,Height Star,Name Star,Publicity Listings Star,TV Appearances Star,Star_URL,Other Roles Star,Award Nominations and Wins Star
http://www.imdb.com/name/nm6178091,1.0,None,NaN,Male,NaN,Giorgos Karakantas,NaN,NaN,http://www.imdb.com/name/nm6178091,NaN,NaN
http://www.imdb.com/name/nm6178115,19.0,None,NaN,Male,1.47,Kiefer O'Reilly,NaN,NaN,http://www.imdb.com/name/nm6178115,NaN,1.0
http://www.imdb.com/name/nm6178682,2.0,None,NaN,Male,NaN,Shadi Alfons,NaN,3.0,http://www.imdb.com/name/nm6178682,NaN,NaN
http://www.imdb.com/name/nm6179030,8.0,United States,2007.0,Male,1.35,Sage Correa,NaN,3.0,http://www.imdb.com/name/nm6179030,NaN,NaN
http://www.imdb.com/name/nm6186725,1.0,None,NaN,Male,NaN,Bogey,NaN,NaN,http://www.imdb.com/name/nm6186725,NaN,NaN
http://www.imdb.com/name/nm6186788,NaN,None,NaN,Female,1.63,Francesca Santoro,NaN,NaN,http://www.imdb.com/name/nm6186788,NaN,NaN
http://www.imdb.com/name/nm6188875,NaN,None,NaN,Female,NaN,Kéfera Buchmann,NaN,6.0,http://www.imdb.com/name/nm6188875,NaN,NaN
http://www.imdb.com/name/nm6189602,NaN,None,NaN,Female,NaN,Ansiba,NaN,NaN,http://www.imdb.com/name/nm6189602,NaN,NaN
http://www.imdb.com/name/nm6191250,NaN,USA,2003.0,Female,NaN,Ekaterina Samsonov,NaN,NaN,http://www.imdb.com/name/nm6191250,NaN,NaN
http://www.imdb.com/name/nm6192494,8.0,None,NaN,Male,NaN,Tara-Alisha Berry,NaN,NaN,http://www.imdb.com/name/nm6192494,NaN,NaN

In [577]:
import numpy as np

In [578]:
stars_df['Birthyear Star'] = stars_df['Birthyear Star'].fillna(0.0).astype(int)

In [579]:
stars_df['Award Nominations and Wins Star'] = stars_df['Award Nominations and Wins Star'].fillna(0.0).astype(int)

In [580]:
stars_df['Other Roles Star'] = stars_df['Other Roles Star'].fillna(0.0).astype(int)

In [581]:
stars_df['Acting Roles Star'].isnull().sum()

13401

In [582]:
len(stars_df)

33838

In [583]:
stars_df['Acting Roles Star'] = stars_df['Acting Roles Star'].fillna(1.0).astype(int)

In [584]:
stars_df['Publicity Listings Star'] = stars_df['Publicity Listings Star'].fillna(0.0).astype(int)
stars_df['TV Appearances Star'] = stars_df['TV Appearances Star'].fillna(0.0).astype(int)

In [585]:
stars_df['Birth Country Star'].unique()

array([None, 'United States', 'USA', 'UK', 'Germany', 'Japan', 'India',
       '1985', 'South Korea', 'Israel', 'Brazil', 'Romania', 'Taiwan',
       '1992', 'USSR [now Russia', 'Turkey', 'Italy', 'Netherlands',
       '1993', 'France', 'Canada', 'Ghana', 'Ukraine', 'China',
       'United Arab Emirates', 'Switzerland', 'Bangladesh', 'Ireland',
       'Belgium', 'Istanbul', 'British India', 'Hungary', 'Argentina',
       '1994', 'Malaysia', 'Sweden', 'Russia', 'Spain', 'Pakistan',
       'Poland', 'Estonia', 'Mexico', 'Norway', '1983', '2003', '1932',
       'Vietnam', '1999', '2002', 'Uruguay', 'Saudi Arabia',
       'United Kingdom', 'West Germany', 'Finland', '2005', 'Denmark',
       'Sri Lanka', 'São Paulo', 'USSR', 'New Zealand', 'Iran', '1974',
       '2000', '1982', 'Somalia', 'Kenya', 'Paris', 'Australia',
       'Yugoslavia', '1956', 'Chile', 'Morocco', 'Korea', '1991', 'Jordan',
       'Bulgaria', 'German Democratic Republic',
       'Czechoslovakia [now Slovakia', 'Serbia', 'Thailand',
       'Yugoslavia [now Serbia', 'Austria', 'South Africa',
       'Netherlands Antilles', 'Lithuania', 'Belarus', 'Macedonia',
       'British Crown Colony', 'London', 'Greece', '1989', '1996',
       'Kazakhstan', '1988', '1986', '1980', 'Hong Kong', 'Armenia',
       'Czechoslovakia', '1968', 'Puerto Rico', 'USSR [now Belarus',
       '1997', 'Gabon', 'Kuwait', '1990', '1984', 'Lebanon',
       'Bosnia and Herzegovina', 'Philippines', 'Iceland', 'Albania',
       'Czechoslovakia [now Czech Republic', '1998', 'Indonesia',
       'Croatia', 'Grand-Duchy of Luxembourg', 'Egypt', 'Chinchwad',
       'Brunei', 'El Salvador', 'Singapore', '2001', '1973', '1981',
       'Isle of Man', 'Afghanistan', '1970', 'USSR [now Ukraine',
       'North Vietnam [now Vietnam', '1959', 'Moldova',
       'Dominican Republic', 'USSR [now Turkmenistan', 'USSR [now Latvia',
       '1977', 'French Polynesia', 'Portugal', '1975', 'Bahrain',
       'Stockholm', '1995', '1987', 'Berlin', '1961',
       'Trinidad and Tobago', 'Cuba', 'DC', '1978', 'Bucharest', '1965',
       '1953', '1957', '1963', 'USSR [now Lithuania', 'Portuguese Macau',
       'Nepal', 'Cyprus', 'Zimbabwe', 'Northern Ireland', 'Bermuda',
       'Barbados', 'Peru', '1964', 'Uzbekistan', 'Angola',
       'USSR [now Uzbekistan', '1979', '1947', 'Nigeria', 'Mongolia',
       '1976', 'Moldavia', 'Colombia', 'Serbia and Montenegro',
       'USSR [now Estonia', 'Burkina Faso', 'Oman', 'USSR [now Azerbaijan',
       'Yugoslavia [now Croatia', '1943', '1944', 'Bahamas', '1952',
       'Costa Rica', 'Ethiopia', 'Iraq', '1972', 'Suriname', 'Tunisia',
       '1966', 'Algeria', 'Syria', 'Venezuela', '1931', '1945', '1971',
       'Czechoslovakia [now Slovak Republic',
       'Yugoslavia [now Bosnia and Herzegovina', '1949', 'Aruba',
       'Trinidad', '1969', '1942', 'Mauritius', '1937', 'Haiti', '1958',
       '1921',
       'German Democratic Republic [now Federal Republic of Germany',
       'East Germany', '1940', '1951', 'Persia', '1955',
       'Czechoslovakia [now in Czech Republic', 'Guatemala', '1962',
       '1912', '1948', '1928', 'Russian Empire [now Ukraine',
       'Russian Empire [now Azerbaijan', '1954', 'Austria-Hungary',
       'France [now Algeria', 'Congo', 'Samoa', 'Ecuador', '1946', '1874',
       '1918', 'Russian Empire [now Russia', '1900',
       'Austria-Hungary [now Czech Republic',
       'First Slovak Republic [now Slovakia',
       'Austria-Hungary [now Austria', '1967', 'Dutch East Indies', '1924',
       'Myanmar', 'British West Indies', '1908',
       'East Germany [now Germany', '1939', 'British India [now Pakistan',
       'Austria-Hungary [now Hungary', '1925', 'North Korea', '1950',
       '1922', 'Republic of Georgia', '1910', 'Bronx New York', '1929',
       'Burma', 'Tibet', 'Palestine [now Israel', '1930', 'Russian Empire',
       '1920', 'Russian Empire [now Latvia', 'Malaya [now Malaysia',
       'British West Indies [now Saint Vincent and the Grenadines', '1927',
       '1915', 'French Mandate of Syria and Lebanon [now Lebanon', '1896',
       'Sudan', 'Jamaica', 'Russian Empire [now Belarus',
       'French Protectorate of Morocco [now Morocco', '1868',
       'British West Indies [now Trinidad and Tobago', '1941',
       'Czech Republic', 'USA [now Oklahoma',
       'Austria-Hungary [now Croatia', '1909', '1960', '1897',
       'Slovakia [now Slovak Republic', 'Laos', '1934',
       'Protectorate of Bohemia and Moravia [now Czech Republic',
       'Hungary [now Slovakia', '1887', 'Slovenia', 'USSR [now Tajikistan',
       '1923', 'Libya', 'Bolivia',
       'Protectorate Bohemia and Moravia [now Czech Republic', 'Latvia',
       'Republic of China', '1892', 'British India [now India',
       'French Protectorate in Morocco [now Morocco',
       'UK [now Republic of Ireland', 'Namibia', '1926', 'Cambodia',
       'USSR [now Republic of Georgia', 'British India [now Bangladesh',
       'Luxembourg', 'Irish Free State [now Ireland', 'Fukuoka Prefecture',
       '1891', 'July 30', 'USA (some sources say 1907)', 'Honduras',
       'French Protectorate Tunisia [now Tunisia', '1938',
       'Union of South Africa [now South Africa', 'U.S', '1913',
       'West Indies',
       'French Mandate for Syria and the Lebanon [now Lebanon',
       'Martinique', '1902', 'Georgia', 'Yugoslavia [now Slovenia', '1936',
       '1919', 'Senegal', 'Slovakia', 'Mali',
       'Federal Republic of Germany', '1935', 'Monaco', 'Palestine',
       'September 17', 'April 21', 'French West Indies',
       'Rakouská republika', 'USSR [now Georgia', 'Uganda', '1914',
       'Austria-Hungary [now Slovakia', 'British Burma', 'Greenland',
       'Malta', 'Occupied Manchuria', '1933', 'Yemen', 'Eritrea',
       'RSFSR [now Russia', 'Ceylon [now Sri Lanka', 'Italy [now Fidenza',
       'Ukrainian SSR [now Ukraine', 'Mozambique', '1866', 'Western Samoa',
       'British West Indies [now Grenada', 'Mozambique [now Maputo',
       'Austria-Hungary [now Serbia', 'Russia [now Finland',
       'French Protectorate Morocco [now Morocco', 'Sikkim',
       'Irish Free State', 'England', 'Nicaragua', 'Central America',
       'Austrian Empire [now Hungary', 'Fehéroroszország',
       'British Mandate of Palestine [now Israel', 'Ivory Coast',
       'West Germany [now Germany', 'Russian Empire [now Uzbekistan',
       'Rhodesia', 'Channel Islands', '1898', 'Tahiti',
       'Japan (some sources say 28 April 1917)', '1880',
       'Russia [now Georgia', 'Romania [now Moldova', '1905',
       'September 9', 'Panama', 'France [now Châlons-en-Champagne',
       'East Pakistan', 'Ottoman Empire', 'British Guiana [now Guyana',
       'February 12', 'British Guiana', '1889', 'Benin', 'Texas',
       'USSR [now Armenia', 'Nyasaland [now Malawi',
       'British Malaya [now Malaysia', 'U.S. Virgin Islands',
       'Union of South Africa [now Swaziland', 'Macau',
       'often given in error)', 'Republic of Ireland'], dtype=object)

In [586]:
stars_df['Birth Country Star'] = stars_df['Birth Country Star'].str.replace('[^A-Za-z ]+','')

In [587]:
stars_df['Birth Country Star'] = stars_df['Birth Country Star'].str.strip()

stars_df['Birth Country Star'] = [x.split(' now ')[0] if x is not None else None for x in stars_df['Birth Country Star']]

stars_df['Birth Country Star'] = stars_df['Birth Country Star'].replace(
    {'':None,
     'January':None,
     'February':None,
     'March':None,
     'April':None,
     'May':None,
     'June':None,
     'July':None,
     'August':None,
     'September':None,
     'October':None,
     'November':None,
     'December':None,
     'often given in error':'USA',
     'DC':'USA',
     'USA some sources say':'USA',
     'USA':'United States',
     'US':'United States',
     'Japan some sources say  April':'Japan',
     'Protectorate Bohemia and Moravia':'Protectorate of Bohemia and Moravia',
     'UK':'United Kingdom',
     'French Protectorate Morocco': 'French Protectorate of Morocco',
     'French Protectorate in Morocco': 'French Protectorate of Morocco'
      })

stars_df['Birth Country Star'] = [x.split(' now ')[0] if x is not None else None for x in stars_df['Birth Country Star']]

In [588]:
stars_df['Birth Country Star'].unique()

array([None, 'United States', 'United Kingdom', 'Germany', 'Japan',
       'India', 'South Korea', 'Israel', 'Brazil', 'Romania', 'Taiwan',
       'USSR', 'Turkey', 'Italy', 'Netherlands', 'France', 'Canada',
       'Ghana', 'Ukraine', 'China', 'United Arab Emirates', 'Switzerland',
       'Bangladesh', 'Ireland', 'Belgium', 'Istanbul', 'British India',
       'Hungary', 'Argentina', 'Malaysia', 'Sweden', 'Russia', 'Spain',
       'Pakistan', 'Poland', 'Estonia', 'Mexico', 'Norway', 'Vietnam',
       'Uruguay', 'Saudi Arabia', 'West Germany', 'Finland', 'Denmark',
       'Sri Lanka', 'So Paulo', 'New Zealand', 'Iran', 'Somalia', 'Kenya',
       'Paris', 'Australia', 'Yugoslavia', 'Chile', 'Morocco', 'Korea',
       'Jordan', 'Bulgaria', 'German Democratic Republic',
       'Czechoslovakia', 'Serbia', 'Thailand', 'Austria', 'South Africa',
       'Netherlands Antilles', 'Lithuania', 'Belarus', 'Macedonia',
       'British Crown Colony', 'London', 'Greece', 'Kazakhstan',
       'Hong Kong', 'Armenia', 'Puerto Rico', 'Gabon', 'Kuwait', 'Lebanon',
       'Bosnia and Herzegovina', 'Philippines', 'Iceland', 'Albania',
       'Indonesia', 'Croatia', 'GrandDuchy of Luxembourg', 'Egypt',
       'Chinchwad', 'Brunei', 'El Salvador', 'Singapore', 'Isle of Man',
       'Afghanistan', 'North Vietnam', 'Moldova', 'Dominican Republic',
       'French Polynesia', 'Portugal', 'Bahrain', 'Stockholm', 'Berlin',
       'Trinidad and Tobago', 'Cuba', 'Bucharest', 'Portuguese Macau',
       'Nepal', 'Cyprus', 'Zimbabwe', 'Northern Ireland', 'Bermuda',
       'Barbados', 'Peru', 'Uzbekistan', 'Angola', 'Nigeria', 'Mongolia',
       'Moldavia', 'Colombia', 'Serbia and Montenegro', 'Burkina Faso',
       'Oman', 'Bahamas', 'Costa Rica', 'Ethiopia', 'Iraq', 'Suriname',
       'Tunisia', 'Algeria', 'Syria', 'Venezuela', 'Aruba', 'Trinidad',
       'Mauritius', 'Haiti', 'East Germany', 'Persia', 'Guatemala',
       'Russian Empire', 'AustriaHungary', 'Congo', 'Samoa', 'Ecuador',
       'First Slovak Republic', 'Dutch East Indies', 'Myanmar',
       'British West Indies', 'North Korea', 'Republic of Georgia',
       'Bronx New York', 'Burma', 'Tibet', 'Palestine', 'Malaya',
       'French Mandate of Syria and Lebanon', 'Sudan', 'Jamaica',
       'French Protectorate of Morocco', 'Czech Republic', 'Slovakia',
       'Laos', 'Protectorate of Bohemia and Moravia', 'Slovenia', 'Libya',
       'Bolivia', 'Latvia', 'Republic of China', 'Namibia', 'Cambodia',
       'Luxembourg', 'Irish Free State', 'Fukuoka Prefecture', 'Honduras',
       'French Protectorate Tunisia', 'Union of South Africa',
       'West Indies', 'French Mandate for Syria and the Lebanon',
       'Martinique', 'Georgia', 'Senegal', 'Mali',
       'Federal Republic of Germany', 'Monaco', 'French West Indies',
       'Rakousk republika', 'Uganda', 'British Burma', 'Greenland',
       'Malta', 'Occupied Manchuria', 'Yemen', 'Eritrea', 'RSFSR',
       'Ceylon', 'Ukrainian SSR', 'Mozambique', 'Western Samoa', 'Sikkim',
       'England', 'Nicaragua', 'Central America', 'Austrian Empire',
       'Fehroroszorszg', 'British Mandate of Palestine', 'Ivory Coast',
       'Rhodesia', 'Channel Islands', 'Tahiti', 'Panama', 'East Pakistan',
       'Ottoman Empire', 'British Guiana', 'Benin', 'Texas', 'Nyasaland',
       'British Malaya', 'US Virgin Islands', 'Macau',
       'Republic of Ireland'], dtype=object)

In [589]:
stars_df.head(50)

,Acting Roles Star,Birth Country Star,Birthyear Star,Gender Star,Height Star,Name Star,Publicity Listings Star,TV Appearances Star,Star_URL,Other Roles Star,Award Nominations and Wins Star
http://www.imdb.com/name/nm6178091,1,None,0,Male,NaN,Giorgos Karakantas,0,0,http://www.imdb.com/name/nm6178091,0,0
http://www.imdb.com/name/nm6178115,19,None,0,Male,1.47,Kiefer O'Reilly,0,0,http://www.imdb.com/name/nm6178115,0,1
http://www.imdb.com/name/nm6178682,2,None,0,Male,NaN,Shadi Alfons,0,3,http://www.imdb.com/name/nm6178682,0,0
http://www.imdb.com/name/nm6179030,8,United States,2007,Male,1.35,Sage Correa,0,3,http://www.imdb.com/name/nm6179030,0,0
http://www.imdb.com/name/nm6186725,1,None,0,Male,NaN,Bogey,0,0,http://www.imdb.com/name/nm6186725,0,0
http://www.imdb.com/name/nm6186788,1,None,0,Female,1.63,Francesca Santoro,0,0,http://www.imdb.com/name/nm6186788,0,0
http://www.imdb.com/name/nm6188875,1,None,0,Female,NaN,Kéfera Buchmann,0,6,http://www.imdb.com/name/nm6188875,0,0
http://www.imdb.com/name/nm6189602,1,None,0,Female,NaN,Ansiba,0,0,http://www.imdb.com/name/nm6189602,0,0
http://www.imdb.com/name/nm6191250,1,United States,2003,Female,NaN,Ekaterina Samsonov,0,0,http://www.imdb.com/name/nm6191250,0,0
http://www.imdb.com/name/nm6192494,8,None,0,Male,NaN,Tara-Alisha Berry,0,0,http://www.imdb.com/name/nm6192494,0,0
http://www.imdb.com/name/nm6192976,6,None,0,Male,NaN,Markees Christmas,0,1,http://www.imdb.com/name/nm6192976,0,1
http://www.imdb.com/name/nm6195447,10,None,0,Male,1.81,Sajjad Delafrooz,0,0,http://www.imdb.com/name/nm6195447,2,0
http://www.imdb.com/name/nm6199189,1,None,0,Male,NaN,Ashutosh Acharya,0,0,http://www.imdb.com/name/nm6199189,0,0
http://www.imdb.com/name/nm6200770,3,None,0,Male,NaN,Julian Walker,0,2,http://www.imdb.com/name/nm6200770,0,0
http://www.imdb.com/name/nm6203418,9,None,0,Male,NaN,Daran Somers,3,0,http://www.imdb.com/name/nm6203418,0,0
http://www.imdb.com/name/nm6208096,1,None,0,Female,NaN,Shelean Newman,0,0,http://www.imdb.com/name/nm6208096,0,0
http://www.imdb.com/name/nm6210704,1,None,0,Male,NaN,Ali Safina,0,0,http://www.imdb.com/name/nm6210704,0,0
http://www.imdb.com/name/nm6210707,2,None,0,Male,1.85,Wiqar Ali Khan,0,0,http://www.imdb.com/name/nm6210707,0,0
http://www.imdb.com/name/nm6211008,2,None,0,Male,NaN,Elisha Ali,0,0,http://www.imdb.com/name/nm6211008,0,0
http://www.imdb.com/name/nm6216593,1,United Kingdom,1994,Female,NaN,Rose Williams,0,0,http://www.imdb.com/name/nm6216593,0,0
http://www.imdb.com/name/nm6216987,1,Germany,1999,Female,NaN,Lea van Acken,0,0,http://www.imdb.com/name/nm6216987,0,3
http://www.imdb.com/name/nm6220383,1,None,0,Female,NaN,Brooke Skylar Baptist,0,0,http://www.imdb.com/name/nm6220383,0,0
http://www.imdb.com/name/nm6220384,1,None,0,Female,NaN,Delta Storm Baptist,0,0,http://www.imdb.com/name/nm6220384,0,0
http://www.imdb.com/name/nm6222008,3,None,0,Male,NaN,Ivo Pietzcker,0,0,http://www.imdb.com/name/nm6222008,0,2
http://www.imdb.com/name/nm6223103,1,None,0,Female,NaN,Saga Becker,0,2,http://www.imdb.com/name/nm6223103,0,3
http://www.imdb.com/name/nm6223116,11,Germany,1991,Male,NaN,Kamil Szeptycki,0,0,http://www.imdb.com/name/nm6223116,0,0
http://www.imdb.com/name/nm6226698,1,None,0,Female,NaN,Saida Barmaki,0,0,http://www.imdb.com/name/nm6226698,0,0
http://www.imdb.com/name/nm6226944,4,None,0,Male,NaN,Thales Cavalcanti,0,0,http://www.imdb.com/name/nm6226944,0,0
http://www.imdb.com/name/nm6228149,1,None,0,Male,NaN,Rich Hamilton,0,0,http://www.imdb.com/name/nm6228149,0,0
http://www.imdb.com/name/nm6228629,1,None,0,Male,NaN,Santos,0,0,http://www.imdb.com/name/nm6228629,0,0
http://www.imdb.com/name/nm6229748,11,None,0,Male,NaN,Roshan Ravindra,0,0,http://www.imdb.com/name/nm6229748,0,0
http://www.imdb.com/name/nm6229968,27,None,0,Male,NaN,Soubin Shahir,0,0,http://www.imdb.com/name/nm6229968,0,0
http://www.imdb.com/name/nm6230258,35,United Kingdom,1967,Male,NaN,Donovan Leitch Jr.,0,17,http://www.imdb.com/name/nm6230258,11,0
http://www.imdb.com/name/nm6231136,1,United States,1991,Female,1.65,Samantha Robinson,0,1,http://www.imdb.com/name/nm6231136,0,1
http://www.imdb.com/name/nm6232988,2,None,0,Male,NaN,Phoeung Kompheak,0,0,http://www.imdb.com/name/nm6232988,0,0
http://www.imdb.com/name/nm6233165,1,None,0,Female,NaN,Trang Le Hong,0,0,http://www.imdb.com/name/nm6233165,0,2
http://www.imdb.com/name/nm6233871,1,Japan,1993,Female,1.60,Sora Amamiya,0,0,http://www.imdb.com/name/nm6233871,0,0
http://www.imdb.com/name/nm6234020,1,None,0,Female,NaN,Nina Taylor,0,0,http://www.imdb.com/name/nm6234020,0,0
http://www.imdb.com/name/nm6234427,4,None,0,Male,NaN,Justin Gerhard,0,1,http://www.imdb.com/name/nm6234427,0,0
http://www.imdb.com/name/nm6237346,7,None,0,Male,1.75,Judah Lewis,0,1,http://www.imdb.com/name/nm6237346,0,0
http://www.imdb.com/name/nm6237589,6,None,0,Male,1.87,Gringe,0,6,http://www.imdb.com/name/nm6237589,0,0
http://www.imdb.com/name/nm6241625,7,None,0,Male,NaN,Jörgen Liik,0,0,http://www.imdb.com/name/nm6241625,0,0
http://www.imdb.com/name/nm6244732,1,None,0,Female,NaN,Jenifer Rodríguez,0,0,http://www.imdb.com/name/nm6244732,0,0
http://www.imdb.com/name/nm6261003,4,None,0,Male,NaN,Raphaël Thiéry,0,0,http://www.imdb.com/name/nm6261003,0,0
http://www.imdb.com/name/nm6261738,3,None,0,Male,NaN,Romy Beckman,0,0,http://www.imdb.com/name/nm6261738,0,0
http://www.imdb.com/name/nm6264169,3,None,0,Male,NaN,Hugo Bolton,0,0,http://www.imdb.com/name/nm6264169,0,1
http://www.imdb.com/name/nm6264344,5,None,0,Male,NaN,Enrique Arrizon,0,0,http://www.imdb.com/name/nm6264344,0,0
http://www.imdb.com/name/nm6264784,1,None,0,Female,NaN,Nikki Galrani,0,0,http://www.imdb.com/name/nm6264784,0,0
http://www.imdb.com/name/nm6276713,1,None,0,Female,NaN,Allegra Masters,0,0,http://www.imdb.com/name/nm6276713,0,0
http://www.imdb.com/name/nm6277267,1,India,1989,Female,NaN,Bhumi Pednekar,0,0,http://www.imdb.com/name/nm6277267,0,7

## With Stars per Movie, Create intermediate DataFrame to Process Actor Details

In [656]:
prelim_stars = pd.DataFrame(gd_df[['ID','Year','Star1_URL']])

In [657]:
prelim_stars.head()

,ID,Year,Star1_URL
http://www.imdb.com/title/tt0006206/,http://www.imdb.com/title/tt0006206/,1915,http://www.imdb.com/name/nm0615736
http://www.imdb.com/title/tt0009682/,http://www.imdb.com/title/tt0009682/,1918,http://www.imdb.com/name/nm0511104
http://www.imdb.com/title/tt0015163/,http://www.imdb.com/title/tt0015163/,1924,http://www.imdb.com/name/nm0000036
http://www.imdb.com/title/tt0015324/,http://www.imdb.com/title/tt0015324/,1924,http://www.imdb.com/name/nm0000036
http://www.imdb.com/title/tt0017925/,http://www.imdb.com/title/tt0017925/,1926,http://www.imdb.com/name/nm0000036

In [658]:
prelim_stars.rename(columns={'Star1_URL':'Star_URL'},inplace=True)

In [659]:
prelim_stars.reset_index(drop=True,inplace=True)

In [660]:
prelim_stars.head()

,ID,Year,Star_URL
0,http://www.imdb.com/title/tt0006206/,1915,http://www.imdb.com/name/nm0615736
1,http://www.imdb.com/title/tt0009682/,1918,http://www.imdb.com/name/nm0511104
2,http://www.imdb.com/title/tt0015163/,1924,http://www.imdb.com/name/nm0000036
3,http://www.imdb.com/title/tt0015324/,1924,http://www.imdb.com/name/nm0000036
4,http://www.imdb.com/title/tt0017925/,1926,http://www.imdb.com/name/nm0000036

In [661]:
int_stars = pd.DataFrame(gd_df[['ID','Year','Star2_URL']],index=None)

In [662]:
int_stars.reset_index(drop=True,inplace=True)

In [663]:
int_stars.head()

,ID,Year,Star2_URL
0,http://www.imdb.com/title/tt0006206/,1915,http://www.imdb.com/name/nm0559013
1,http://www.imdb.com/title/tt0009682/,1918,http://www.imdb.com/name/nm0548402
2,http://www.imdb.com/title/tt0015163/,1924,http://www.imdb.com/name/nm0570230
3,http://www.imdb.com/title/tt0015324/,1924,http://www.imdb.com/name/nm0570230
4,http://www.imdb.com/title/tt0017925/,1926,http://www.imdb.com/name/nm0533045

In [664]:
int_stars.rename(columns={'Star2_URL':'Star_URL'},inplace=True)

In [665]:
prelim_stars = prelim_stars.append(int_stars)

In [666]:
len(prelim_stars)

59434

In [667]:
prelim_stars.head()

,ID,Year,Star_URL
0,http://www.imdb.com/title/tt0006206/,1915,http://www.imdb.com/name/nm0615736
1,http://www.imdb.com/title/tt0009682/,1918,http://www.imdb.com/name/nm0511104
2,http://www.imdb.com/title/tt0015163/,1924,http://www.imdb.com/name/nm0000036
3,http://www.imdb.com/title/tt0015324/,1924,http://www.imdb.com/name/nm0000036
4,http://www.imdb.com/title/tt0017925/,1926,http://www.imdb.com/name/nm0000036

In [668]:
int_stars2 = pd.DataFrame(gd_df[['ID','Year','Star3_URL']],index=None)

In [669]:
int_stars2.reset_index(drop=True,inplace=True)

In [670]:
int_stars2.head()

,ID,Year,Star3_URL
0,http://www.imdb.com/title/tt0006206/,1915,http://www.imdb.com/name/nm0529695
1,http://www.imdb.com/title/tt0009682/,1918,http://www.imdb.com/name/nm0090204
2,http://www.imdb.com/title/tt0015163/,1924,http://www.imdb.com/name/nm0089162
3,http://www.imdb.com/title/tt0015324/,1924,http://www.imdb.com/name/nm0444172
4,http://www.imdb.com/title/tt0017925/,1926,http://www.imdb.com/name/nm0147070

In [671]:
int_stars2.rename(columns={'Star3_URL':'Star_URL'},inplace=True)

In [672]:
prelim_stars = prelim_stars.append(int_stars2)

In [673]:
len(prelim_stars)

89151

In [674]:
prelim_stars.head()

,ID,Year,Star_URL
0,http://www.imdb.com/title/tt0006206/,1915,http://www.imdb.com/name/nm0615736
1,http://www.imdb.com/title/tt0009682/,1918,http://www.imdb.com/name/nm0511104
2,http://www.imdb.com/title/tt0015163/,1924,http://www.imdb.com/name/nm0000036
3,http://www.imdb.com/title/tt0015324/,1924,http://www.imdb.com/name/nm0000036
4,http://www.imdb.com/title/tt0017925/,1926,http://www.imdb.com/name/nm0000036

In [675]:
prelim_stars = prelim_stars.sort_values(['ID'],ascending=True)

In [676]:
prelim_stars.reset_index(drop=True,inplace=True)

In [677]:
prelim_stars.head()

,ID,Year,Star_URL
0,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0209738
1,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0685283
2,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0660139
3,http://www.imdb.com/title/tt0002423/,1919,http://www.imdb.com/name/nm0509573
4,http://www.imdb.com/title/tt0002423/,1919,http://www.imdb.com/name/nm0417837

### Add in Star Details to Cumulate and Average

In [757]:
adding_stars = pd.DataFrame(prelim_stars)

In [758]:
adding_stars = adding_stars.merge(stars_df,how='inner',on='Star_URL')

In [759]:
adding_stars.sort_values(['ID','Year','Star_URL'])

,ID,Year,Star_URL,Acting Roles Star,Birth Country Star,Birthyear Star,Gender Star,Height Star,Name Star,Publicity Listings Star,TV Appearances Star,Other Roles Star,Award Nominations and Wins Star
0,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0209738,16,Italy,1869,Male,NaN,Giuseppe de Liguoro,0,0,92,0
2,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0660139,15,None,0,Male,NaN,Salvatore Papa,0,0,0,0
1,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0685283,6,None,0,Male,NaN,Arturo Pirovano,0,0,0,0
4,http://www.imdb.com/title/tt0002423/,1919,http://www.imdb.com/name/nm0417837,82,Switzerland,1884,Male,1.83,Emil Jannings,8,3,6,4
3,http://www.imdb.com/title/tt0002423/,1919,http://www.imdb.com/name/nm0509573,162,Russia,1882,Male,NaN,Harry Liedtke,2,3,0,0
12,http://www.imdb.com/title/tt0002423/,1919,http://www.imdb.com/name/nm0624470,1,Poland,1897,Female,1.52,Pola Negri,69,6,0,2
19,http://www.imdb.com/title/tt0002844/,1913,http://www.imdb.com/name/nm0107631,82,United Kingdom,1882,Male,NaN,Edmund Breon,0,0,0,0
22,http://www.imdb.com/title/tt0002844/,1913,http://www.imdb.com/name/nm0577476,68,France,1889,Male,NaN,Georges Melchior,1,0,0,0
16,http://www.imdb.com/title/tt0002844/,1913,http://www.imdb.com/name/nm0622772,119,France,1877,Male,NaN,René Navarre,0,0,8,0
20,http://www.imdb.com/title/tt0003037/,1913,http://www.imdb.com/name/nm0107631,82,United Kingdom,1882,Male,NaN,Edmund Breon,0,0,0,0
23,http://www.imdb.com/title/tt0003037/,1913,http://www.imdb.com/name/nm0577476,68,France,1889,Male,NaN,Georges Melchior,1,0,0,0
17,http://www.imdb.com/title/tt0003037/,1913,http://www.imdb.com/name/nm0622772,119,France,1877,Male,NaN,René Navarre,0,0,8,0
21,http://www.imdb.com/title/tt0003165/,1913,http://www.imdb.com/name/nm0107631,82,United Kingdom,1882,Male,NaN,Edmund Breon,0,0,0,0
24,http://www.imdb.com/title/tt0003165/,1913,http://www.imdb.com/name/nm0577476,68,France,1889,Male,NaN,Georges Melchior,1,0,0,0
18,http://www.imdb.com/title/tt0003165/,1913,http://www.imdb.com/name/nm0622772,119,France,1877,Male,NaN,René Navarre,0,0,8,0
27,http://www.imdb.com/title/tt0003419/,1913,http://www.imdb.com/name/nm0074186,1,Czech Republic,1883,Female,NaN,Grete Berger,0,0,0,0
25,http://www.imdb.com/title/tt0003419/,1913,http://www.imdb.com/name/nm0758802,1,AustriaHungary,1889,Female,NaN,Lyda Salmonova,1,0,0,0
28,http://www.imdb.com/title/tt0003419/,1913,http://www.imdb.com/name/nm0917467,71,Poland,1874,Male,1.98,Paul Wegener,3,1,23,0
33,http://www.imdb.com/title/tt0003740/,1914,http://www.imdb.com/name/nm0021935,1,Italy,1890,Female,NaN,Italia Almirante-Manzini,0,0,0,0
34,http://www.imdb.com/title/tt0003740/,1914,http://www.imdb.com/name/nm0656034,32,Italy,1878,Male,1.83,Bartolomeo Pagano,5,0,0,0
35,http://www.imdb.com/title/tt0003740/,1914,http://www.imdb.com/name/nm0702894,1,Italy,1891,Female,NaN,Lidia Quaranta,0,0,0,0
36,http://www.imdb.com/title/tt0003772/,1914,http://www.imdb.com/name/nm0601698,286,Ireland,1884,Male,1.78,Owen Moore,19,1,2,1
40,http://www.imdb.com/title/tt0003772/,1914,http://www.imdb.com/name/nm0681933,1,Canada,1892,Female,1.54,Mary Pickford,173,44,37,3
39,http://www.imdb.com/title/tt0003772/,1914,http://www.imdb.com/name/nm0894679,1,None,1874,Female,NaN,Isabel Vernon,1,0,0,0
45,http://www.imdb.com/title/tt0004026/,1915,http://www.imdb.com/name/nm0301961,6,AustriaHungary,1881,Male,NaN,Henrik Galeen,2,0,0,0
26,http://www.imdb.com/title/tt0004026/,1915,http://www.imdb.com/name/nm0758802,1,AustriaHungary,1889,Female,NaN,Lyda Salmonova,1,0,0,0
29,http://www.imdb.com/title/tt0004026/,1915,http://www.imdb.com/name/nm0917467,71,Poland,1874,Male,1.98,Paul Wegener,3,1,23,0
46,http://www.imdb.com/title/tt0004465/,1914,http://www.imdb.com/name/nm0659947,394,Germany,1872,Male,1.79,Paul Panzer,14,3,0,1
47,http://www.imdb.com/title/tt0004465/,1914,http://www.imdb.com/name/nm0925310,1,United States,1889,Female,NaN,Pearl White,35,3,0,1
48,http://www.imdb.com/title/tt0004465/,1914,http://www.imdb.com/name/nm0928108,89,United States,1886,Male,1.78,Crane Wilbur,9,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
87094,http://www.imdb.com/title/tt7549484/,2017,http://www.imdb.com/name/nm6151574,8,India,1981,Male,1.77,Kapil Sharma,0,3,0,3
89060,http://www.imdb.com/title/tt7549484/,2017,http://www.imdb.com/name/nm7181900,1,India,1990,Female,1.68,Ishita Dutta,0,0,0,0
88425,http://www.imdb.com/title/tt7549484/,2017,http://www.imdb.com/name/nm8033021,1,None,0,Female,NaN,Monica Gill,0,0,0,0
89061,http://www.imdb.com/title/tt7608028/,2018,http://www.imdb.com/name/nm0404656,1,None,0,Female,NaN,Patricia Bethune,2,0,0,1
73655,http://www.imdb.com/title/tt7608028/,2018,http://www.imdb.com/name/nm1910255,42,None,1996,Male,1.80,Dylan Minnette,0,12,0,9
89062,http://www.imdb.com/title/tt7608028/,2018,http://www.imdb.com/name/nm4572072,1,None,0,Female,1.70,Piercey Dalton,0,0,0,5
28835,http://www.imdb.com/title/tt7608418/,2017,http://www.imdb.com/name/nm0000481,1,South Africa,1954,Female,1.65,Alice Krige,7,6,0,9
80680,http://www.imdb.com/title/tt7608418/,2017,http://www.imdb.com/name/nm0570860,1,New Zealand,1988,Female,1.62,Rose McIver,0,13,0,2
86840,http://www.imdb.com/title/tt7608418/,2017,http://www.imdb.com/name/nm3858223,15,United Kingdom,1989,Male,1.88,Ben Lamb,1,0,0,0
32260,http://www.imdb.com/title/tt7608534/,2017,http://www.imdb.com/name/nm0000510,1,United States,1958,Female,1.73,Andie MacDowell,86,87,0,16
88524,http://www.imdb.com/title/tt7608534/,2017,http://www.imdb.com/name/nm1343638,1,Australia,1989,Female,1.65,Eliza Taylor,0,6,0,1
84482,http://www.imdb.com/title/tt7608534/,2017,http://www.imdb.com/name/nm3821405,25,United States,0,Male,1.77,Jake Lacy,0,6,0,3
89063,http://www.imdb.com/title/tt7642818/,2017,http://www.imdb.com/name/nm0654874,45,Turkey,1948,Male,NaN,Erdal Özyagcilar,0,2,0,0
77973,http://www.imdb.com/title/tt7642818/,2017,http://www.imdb.com/name/nm1085525,14,Turkey,1972,Male,1.75,Engin Günaydin,0,1,0,6
69436,http://www.imdb.com/title/tt7642818/,2017,http://www.imdb.com/name/nm1728411,1,Turkey,1980,Female,1.62,Demet Evgar,0,2,0,0
89065,http://www.imdb.com/title/tt7668842/,2018,http://www.imdb.com/name/nm9442261,1,None,0,Male,NaN,Enes Batur,0,1,0,0
89064,http://www.imdb.com/title/tt7668842/,2018,http://www.imdb.com/name/nm9442262,1,None,0,Male,NaN,Bilal Hanci,0,0,0,0
89066,http://www.imdb.com/title/tt7668842/,2018,http://www.imdb.com/name/nm9442263,1,None,0,Male,NaN,Atakan Özyurt,0,0,0,0
89067,http://www.imdb.com/title/tt7691572/,2017,http://www.imdb.com/name/nm1194362,5,None,0,Male,NaN,Vyacheslav Dovzhenko,0,0,0,0
89068,http://www.imdb.com/title/tt7691572/,2017,http://www.imdb.com/name/nm4875310,6,None,0,Male,NaN,Andriy Isayenko,0,0,0,0
89069,http://www.imdb.com/title/tt7691572/,2017,http://www.imdb.com/name/nm7424662,3,None,0,Male,NaN,Roman Yasinovsky,0,0,0,0
57935,http://www.imdb.com/title/tt7711342/,2018,http://www.imdb.com/name/nm0436302,28,India,1971,Male,1.78,Pawan Kalyan,1,1,3,3
88268,http://www.imdb.com/title/tt7711342/,2018,http://www.imdb.com/name/nm5245022,1,None,0,Female,NaN,Anu Emmanuel,0,0,0,0
87229,http://www.imdb.com/title/tt7711342/,2018,http://www.imdb.com/name/nm7146337,1,None,0,Female,NaN,Keerthi Suresh,0,0,0,1
89072,http://www.imdb.com/title/tt7717440/,2018,http://www.imdb.com/name/nm8746395,2,None,0,Male,NaN,Kanokchat Manyaton,0,0,0,0
89070,http://www.imdb.com/title/tt7717440/,2018,http://www.imdb.com/name/nm9479673,1,None,0,Female,NaN,Savitree Suttichanond,0,0,0,0
89071,http://www.imdb.com/title/tt7717440/,2018,http://www.imdb.com/name/nm9549343,1,None,0,Male,NaN,Sirichai Charoenkijtanakul,0,0,0,0
52257,http://www.imdb.com/title/tt7871636/,2018,http://www.imdb.com/name/nm0015764,1,Turkey,1959,Female,NaN,Derya Alabora,0,1,0,7
89073,http://www.imdb.com/title/tt7871636/,2018,http://www.imdb.com/name/nm0019783,23,Turkey,1963,Male,NaN,Caner Alkaya,0,1,0,0
89074,http://www.imdb.com/title/tt7871636/,2018,http://www.imdb.com/name/nm2604473,1,None,0,Female,NaN,Özlem Akinözü,0,0,0,0

In [760]:
adding_stars.tail(100)

,ID,Year,Star_URL,Acting Roles Star,Birth Country Star,Birthyear Star,Gender Star,Height Star,Name Star,Publicity Listings Star,TV Appearances Star,Other Roles Star,Award Nominations and Wins Star
88975,http://www.imdb.com/title/tt6791886/,2017,http://www.imdb.com/name/nm0290616,13,Brazil,1936,Male,NaN,Moacyr Franco,0,5,0,1
88976,http://www.imdb.com/title/tt6809030/,2017,http://www.imdb.com/name/nm8927784,1,None,0,Female,NaN,Destina Baser,0,0,0,0
88977,http://www.imdb.com/title/tt6809030/,2017,http://www.imdb.com/name/nm8927783,2,None,0,Male,NaN,Berke Bük,0,0,0,0
88978,http://www.imdb.com/title/tt6822518/,2017,http://www.imdb.com/name/nm4264654,8,None,0,Male,NaN,Renan Bilek,0,1,0,0
88979,http://www.imdb.com/title/tt6822518/,2017,http://www.imdb.com/name/nm5271229,4,None,0,Male,NaN,Onur Dilber,0,1,0,0
88980,http://www.imdb.com/title/tt6822518/,2017,http://www.imdb.com/name/nm0040512,1,None,0,Female,NaN,Aysegül Atik,0,1,0,0
88981,http://www.imdb.com/title/tt6872436/,2018,http://www.imdb.com/name/nm1417060,38,None,0,Male,NaN,Sriman,0,0,0,0
88982,http://www.imdb.com/title/tt6880058/,2017,http://www.imdb.com/name/nm8987625,1,None,0,Male,NaN,Rafathar Malik Ahmad,0,0,0,0
88983,http://www.imdb.com/title/tt6880058/,2017,http://www.imdb.com/name/nm2680186,12,None,0,Male,NaN,Raffi Ahmad,0,0,0,0
88984,http://www.imdb.com/title/tt6895746/,2017,http://www.imdb.com/name/nm2009186,1,Spain,1980,Female,NaN,Miren Ibarguren,1,14,0,2
88985,http://www.imdb.com/title/tt6896536/,2017,http://www.imdb.com/name/nm0012239,1,France,1978,Female,NaN,Sarah Adler,0,0,0,5
88986,http://www.imdb.com/title/tt6896536/,2017,http://www.imdb.com/name/nm8277519,2,None,0,Male,NaN,Yonaton Shiray,0,0,0,0
88987,http://www.imdb.com/title/tt6952604/,2017,http://www.imdb.com/name/nm6331932,1,None,0,Female,NaN,Galina Averyanova,0,0,0,0
88988,http://www.imdb.com/title/tt6952604/,2017,http://www.imdb.com/name/nm9029723,1,None,0,Female,NaN,Polina Ilyukhina,0,0,0,0
88989,http://www.imdb.com/title/tt6952604/,2017,http://www.imdb.com/name/nm3999292,1,None,0,Female,NaN,Irina Gorbacheva,0,1,0,2
88990,http://www.imdb.com/title/tt6973386/,2017,http://www.imdb.com/name/nm7684264,5,None,0,Male,NaN,Ertugrul Sakar,0,0,0,0
88991,http://www.imdb.com/title/tt6973386/,2017,http://www.imdb.com/name/nm1773045,5,None,0,Male,NaN,Erhan Ufak,0,0,0,0
88992,http://www.imdb.com/title/tt6990206/,2017,http://www.imdb.com/name/nm4125693,15,None,0,Male,NaN,Roman Kurtsyn,0,1,0,1
88993,http://www.imdb.com/title/tt6990206/,2017,http://www.imdb.com/name/nm4152537,1,None,0,Female,NaN,Evgeniya Lapova,0,1,0,0
88994,http://www.imdb.com/title/tt6990206/,2017,http://www.imdb.com/name/nm0469340,4,None,0,Male,NaN,Pavel Kraynov,0,0,0,0
88995,http://www.imdb.com/title/tt6996016/,2017,http://www.imdb.com/name/nm8224244,1,None,0,Female,NaN,Nivetha Thomas,0,0,0,0
88996,http://www.imdb.com/title/tt7010156/,2017,http://www.imdb.com/name/nm1686962,28,None,0,Male,NaN,Anandraj,0,0,0,0
88997,http://www.imdb.com/title/tt7010156/,2017,http://www.imdb.com/name/nm8139553,4,None,0,Male,NaN,M.S. Baskar,0,0,0,0
88998,http://www.imdb.com/title/tt7010412/,2017,http://www.imdb.com/name/nm3818786,29,Taiwan,1975,Male,NaN,Bamboo Chu-Sheng Chen,0,0,0,2
88999,http://www.imdb.com/title/tt7010412/,2017,http://www.imdb.com/name/nm5394312,2,Taiwan,1966,Male,NaN,Cres Chuang,0,0,0,0
89000,http://www.imdb.com/title/tt7010412/,2017,http://www.imdb.com/name/nm0197240,52,Taiwan,1966,Male,NaN,Leon Dai,0,0,4,21
89001,http://www.imdb.com/title/tt7014110/,2017,http://www.imdb.com/name/nm9235502,2,None,0,Male,NaN,Stephan Benson,0,3,0,0
89002,http://www.imdb.com/title/tt7014110/,2017,http://www.imdb.com/name/nm9240445,1,None,0,Male,NaN,Kai Luke Brummer,0,0,0,0
89003,http://www.imdb.com/title/tt7014110/,2017,http://www.imdb.com/name/nm9240441,1,None,0,Female,NaN,Sophie de Bruyn,0,0,0,0
89004,http://www.imdb.com/title/tt7019812/,2017,http://www.imdb.com/name/nm9317994,1,None,0,Male,NaN,Riaz Ahmed,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
89045,http://www.imdb.com/title/tt7431894/,2017,http://www.imdb.com/name/nm9156629,2,None,0,Male,NaN,Allen Ai,0,0,0,0
89046,http://www.imdb.com/title/tt7441032/,2017,http://www.imdb.com/name/nm7036568,1,None,0,Female,NaN,Ema Horvath,0,0,0,0
89047,http://www.imdb.com/title/tt7441032/,2017,http://www.imdb.com/name/nm2920533,13,None,0,Male,1.82,Keiynan Lonsdale,0,7,0,0
89048,http://www.imdb.com/title/tt7468056/,2017,http://www.imdb.com/name/nm5887272,5,None,0,Male,NaN,Sun-gyu Jin,0,0,0,1
89049,http://www.imdb.com/title/tt7468056/,2017,http://www.imdb.com/name/nm3780600,14,None,0,Male,NaN,Gwi-hwa Choi,0,0,0,1
89050,http://www.imdb.com/title/tt7469726/,2017,http://www.imdb.com/name/nm1320935,1,None,0,Female,NaN,Alka Amin,0,0,0,0
89051,http://www.imdb.com/title/tt7531040/,2017,http://www.imdb.com/name/nm9350575,1,None,0,Male,NaN,Arun Prasath,0,0,0,0
89052,http://www.imdb.com/title/tt7531040/,2017,http://www.imdb.com/name/nm9350576,1,None,0,Female,NaN,Indhuja,0,0,0,0
89053,http://www.imdb.com/title/tt7531040/,2017,http://www.imdb.com/name/nm8995905,2,None,0,Male,NaN,Vivek Prasanna,0,0,0,0
89054,http://www.imdb.com/title/tt7533846/,2017,http://www.imdb.com/name/nm5724370,1,Turkey,1985,Female,NaN,Elçin Sangu,0,0,0,0
89055,http://www.imdb.com/title/tt7533846/,2017,http://www.imdb.com/name/nm6882090,9,Switzerland,1987,Male,1.87,Baris Arduç,1,1,0,0
89056,http://www.imdb.com/title/tt7535792/,2017,http://www.imdb.com/name/nm3635856,7,None,0,Male,NaN,Ibrahim Büyükak,0,1,0,0
89057,http://www.imdb.com/title/tt7535868/,2017,http://www.imdb.com/name/nm7973077,2,None,0,Male,NaN,Alper Rende,0,0,0,0
89058,http://www.imdb.com/title/tt7535868/,2017,http://www.imdb.com/name/nm9315493,1,None,0,Male,NaN,Melih Abuaf,0,0,0,0
89059,http://www.imdb.com/title/tt7535868/,2017,http://www.imdb.com/name/nm9359190,1,None,0,Male,NaN,Mert Karadas,0,0,0,0
89060,http://www.imdb.com/title/tt7549484/,2017,http://www.imdb.com/name/nm7181900,1,India,1990,Female,1.68,Ishita Dutta,0,0,0,0
89061,http://www.imdb.com/title/tt7608028/,2018,http://www.imdb.com/name/nm0404656,1,None,0,Female,NaN,Patricia Bethune,2,0,0,1
89062,http://www.imdb.com/title/tt7608028/,2018,http://www.imdb.com/name/nm4572072,1,None,0,Female,1.70,Piercey Dalton,0,0,0,5
89063,http://www.imdb.com/title/tt7642818/,2017,http://www.imdb.com/name/nm0654874,45,Turkey,1948,Male,NaN,Erdal Özyagcilar,0,2,0,0
89064,http://www.imdb.com/title/tt7668842/,2018,http://www.imdb.com/name/nm9442262,1,None,0,Male,NaN,Bilal Hanci,0,0,0,0
89065,http://www.imdb.com/title/tt7668842/,2018,http://www.imdb.com/name/nm9442261,1,None,0,Male,NaN,Enes Batur,0,1,0,0
89066,http://www.imdb.com/title/tt7668842/,2018,http://www.imdb.com/name/nm9442263,1,None,0,Male,NaN,Atakan Özyurt,0,0,0,0
89067,http://www.imdb.com/title/tt7691572/,2017,http://www.imdb.com/name/nm1194362,5,None,0,Male,NaN,Vyacheslav Dovzhenko,0,0,0,0
89068,http://www.imdb.com/title/tt7691572/,2017,http://www.imdb.com/name/nm4875310,6,None,0,Male,NaN,Andriy Isayenko,0,0,0,0
89069,http://www.imdb.com/title/tt7691572/,2017,http://www.imdb.com/name/nm7424662,3,None,0,Male,NaN,Roman Yasinovsky,0,0,0,0
89070,http://www.imdb.com/title/tt7717440/,2018,http://www.imdb.com/name/nm9479673,1,None,0,Female,NaN,Savitree Suttichanond,0,0,0,0
89071,http://www.imdb.com/title/tt7717440/,2018,http://www.imdb.com/name/nm9549343,1,None,0,Male,NaN,Sirichai Charoenkijtanakul,0,0,0,0
89072,http://www.imdb.com/title/tt7717440/,2018,http://www.imdb.com/name/nm8746395,2,None,0,Male,NaN,Kanokchat Manyaton,0,0,0,0
89073,http://www.imdb.com/title/tt7871636/,2018,http://www.imdb.com/name/nm0019783,23,Turkey,1963,Male,NaN,Caner Alkaya,0,1,0,0
89074,http://www.imdb.com/title/tt7871636/,2018,http://www.imdb.com/name/nm2604473,1,None,0,Female,NaN,Özlem Akinözü,0,0,0,0

In [761]:
adding_stars.head(200)

,ID,Year,Star_URL,Acting Roles Star,Birth Country Star,Birthyear Star,Gender Star,Height Star,Name Star,Publicity Listings Star,TV Appearances Star,Other Roles Star,Award Nominations and Wins Star
0,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0209738,16,Italy,1869,Male,NaN,Giuseppe de Liguoro,0,0,92,0
1,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0685283,6,None,0,Male,NaN,Arturo Pirovano,0,0,0,0
2,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0660139,15,None,0,Male,NaN,Salvatore Papa,0,0,0,0
3,http://www.imdb.com/title/tt0002423/,1919,http://www.imdb.com/name/nm0509573,162,Russia,1882,Male,NaN,Harry Liedtke,2,3,0,0
4,http://www.imdb.com/title/tt0002423/,1919,http://www.imdb.com/name/nm0417837,82,Switzerland,1884,Male,1.83,Emil Jannings,8,3,6,4
5,http://www.imdb.com/title/tt0014586/,1924,http://www.imdb.com/name/nm0417837,82,Switzerland,1884,Male,1.83,Emil Jannings,8,3,6,4
6,http://www.imdb.com/title/tt0015064/,1924,http://www.imdb.com/name/nm0417837,82,Switzerland,1884,Male,1.83,Emil Jannings,8,3,6,4
7,http://www.imdb.com/title/tt0016481/,1925,http://www.imdb.com/name/nm0417837,82,Switzerland,1884,Male,1.83,Emil Jannings,8,3,6,4
8,http://www.imdb.com/title/tt0016847/,1926,http://www.imdb.com/name/nm0417837,82,Switzerland,1884,Male,1.83,Emil Jannings,8,3,6,4
9,http://www.imdb.com/title/tt0019071/,1928,http://www.imdb.com/name/nm0417837,82,Switzerland,1884,Male,1.83,Emil Jannings,8,3,6,4
10,http://www.imdb.com/title/tt0020697/,1930,http://www.imdb.com/name/nm0417837,82,Switzerland,1884,Male,1.83,Emil Jannings,8,3,6,4
11,http://www.imdb.com/title/tt3565328/,1930,http://www.imdb.com/name/nm0417837,82,Switzerland,1884,Male,1.83,Emil Jannings,8,3,6,4
12,http://www.imdb.com/title/tt0002423/,1919,http://www.imdb.com/name/nm0624470,1,Poland,1897,Female,1.52,Pola Negri,69,6,0,2
13,http://www.imdb.com/title/tt0011742/,1920,http://www.imdb.com/name/nm0624470,1,Poland,1897,Female,1.52,Pola Negri,69,6,0,2
14,http://www.imdb.com/title/tt0011960/,1921,http://www.imdb.com/name/nm0624470,1,Poland,1897,Female,1.52,Pola Negri,69,6,0,2
15,http://www.imdb.com/title/tt0058371/,1964,http://www.imdb.com/name/nm0624470,1,Poland,1897,Female,1.52,Pola Negri,69,6,0,2
16,http://www.imdb.com/title/tt0002844/,1913,http://www.imdb.com/name/nm0622772,119,France,1877,Male,NaN,René Navarre,0,0,8,0
17,http://www.imdb.com/title/tt0003037/,1913,http://www.imdb.com/name/nm0622772,119,France,1877,Male,NaN,René Navarre,0,0,8,0
18,http://www.imdb.com/title/tt0003165/,1913,http://www.imdb.com/name/nm0622772,119,France,1877,Male,NaN,René Navarre,0,0,8,0
19,http://www.imdb.com/title/tt0002844/,1913,http://www.imdb.com/name/nm0107631,82,United Kingdom,1882,Male,NaN,Edmund Breon,0,0,0,0
20,http://www.imdb.com/title/tt0003037/,1913,http://www.imdb.com/name/nm0107631,82,United Kingdom,1882,Male,NaN,Edmund Breon,0,0,0,0
21,http://www.imdb.com/title/tt0003165/,1913,http://www.imdb.com/name/nm0107631,82,United Kingdom,1882,Male,NaN,Edmund Breon,0,0,0,0
22,http://www.imdb.com/title/tt0002844/,1913,http://www.imdb.com/name/nm0577476,68,France,1889,Male,NaN,Georges Melchior,1,0,0,0
23,http://www.imdb.com/title/tt0003037/,1913,http://www.imdb.com/name/nm0577476,68,France,1889,Male,NaN,Georges Melchior,1,0,0,0
24,http://www.imdb.com/title/tt0003165/,1913,http://www.imdb.com/name/nm0577476,68,France,1889,Male,NaN,Georges Melchior,1,0,0,0
25,http://www.imdb.com/title/tt0003419/,1913,http://www.imdb.com/name/nm0758802,1,AustriaHungary,1889,Female,NaN,Lyda Salmonova,1,0,0,0
26,http://www.imdb.com/title/tt0004026/,1915,http://www.imdb.com/name/nm0758802,1,AustriaHungary,1889,Female,NaN,Lyda Salmonova,1,0,0,0
27,http://www.imdb.com/title/tt0003419/,1913,http://www.imdb.com/name/nm0074186,1,Czech Republic,1883,Female,NaN,Grete Berger,0,0,0,0
28,http://www.imdb.com/title/tt0003419/,1913,http://www.imdb.com/name/nm0917467,71,Poland,1874,Male,1.98,Paul Wegener,3,1,23,0
29,http://www.imdb.com/title/tt0004026/,1915,http://www.imdb.com/name/nm0917467,71,Poland,1874,Male,1.98,Paul Wegener,3,1,23,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,http://www.imdb.com/title/tt0015624/,1925,http://www.imdb.com/name/nm0318105,99,United States,1897,Male,1.80,John Gilbert,50,9,0,1
171,http://www.imdb.com/title/tt0016104/,1925,http://www.imdb.com/name/nm0318105,99,United States,1897,Male,1.80,John Gilbert,50,9,0,1
172,http://www.imdb.com/title/tt0016627/,1926,http://www.imdb.com/name/nm0318105,99,United States,1897,Male,1.80,John Gilbert,50,9,0,1
173,http://www.imdb.com/title/tt0016669/,1926,http://www.imdb.com/name/nm0318105,99,United States,1897,Male,1.80,John Gilbert,50,9,0,1
174,http://www.imdb.com/title/tt0016884/,1926,http://www.imdb.com/name/nm0318105,99,United States,1897,Male,1.80,John Gilbert,50,9,0,1
175,http://www.imdb.com/title/tt0019811/,1929,http://www.imdb.com/name/nm0318105,99,United States,1897,Male,1.80,John Gilbert,50,9,0,1
176,http://www.imdb.com/title/tt0019993/,1929,http://www.imdb.com/name/nm0318105,99,United States,1897,Male,1.80,John Gilbert,50,9,0,1
177,http://www.imdb.com/title/tt0024481/,1933,http://www.imdb.com/name/nm0318105,99,United States,1897,Male,1.80,John Gilbert,50,9,0,1
178,http://www.imdb.com/title/tt0010247/,1919,http://www.imdb.com/name/nm0074129,24,Sweden,1874,Male,NaN,Bror Berger,0,0,6,0
179,http://www.imdb.com/title/tt0010247/,1919,http://www.imdb.com/name/nm0830862,4,Sweden,1878,Male,NaN,Erik Stocklassa,0,0,0,0
180,http://www.imdb.com/title/tt0010247/,1919,http://www.imdb.com/name/nm0526234,74,Sweden,1885,Male,NaN,Richard Lund,0,0,0,0
181,http://www.imdb.com/title/tt0010281/,1918,http://www.imdb.com/name/nm0652661,1,Germany,1897,Female,NaN,Ossi Oswalda,0,0,0,0
182,http://www.imdb.com/title/tt0010600/,1919,http://www.imdb.com/name/nm0652661,1,Germany,1897,Female,NaN,Ossi Oswalda,0,0,0,0
183,http://www.imdb.com/title/tt0010281/,1918,http://www.imdb.com/name/nm0797728,63,Germany,1865,Male,NaN,Ferry Sikla,0,1,0,0
184,http://www.imdb.com/title/tt0010281/,1918,http://www.imdb.com/name/nm0324506,21,Germany,1888,Male,NaN,Curt Goetz,1,0,5,1
185,http://www.imdb.com/title/tt0010307/,1919,http://www.imdb.com/name/nm0431069,49,France,1876,Male,NaN,Romuald Joubé,0,0,0,0
186,http://www.imdb.com/title/tt0010307/,1919,http://www.imdb.com/name/nm0786313,13,France,1873,Male,NaN,Séverin-Mars,0,0,0,0
187,http://www.imdb.com/title/tt0010307/,1919,http://www.imdb.com/name/nm0221298,33,France,1861,Male,NaN,Maxime Desjardins,0,0,0,0
188,http://www.imdb.com/title/tt0010323/,1920,http://www.imdb.com/name/nm0270415,31,AustriaHungary,1889,Male,NaN,Friedrich Feher,0,0,36,2
189,http://www.imdb.com/title/tt0010323/,1920,http://www.imdb.com/name/nm0470328,144,Germany,1884,Male,NaN,Werner Krauss,5,3,0,0
190,http://www.imdb.com/title/tt0014586/,1924,http://www.imdb.com/name/nm0470328,144,Germany,1884,Male,NaN,Werner Krauss,5,3,0,0
191,http://www.imdb.com/title/tt0010418/,1919,http://www.imdb.com/name/nm0731623,106,United States,1861,Male,NaN,Theodore Roberts,10,6,0,1
192,http://www.imdb.com/title/tt0010635/,1919,http://www.imdb.com/name/nm0731623,106,United States,1861,Male,NaN,Theodore Roberts,10,6,0,1
193,http://www.imdb.com/title/tt0014532/,1923,http://www.imdb.com/name/nm0731623,106,United States,1861,Male,NaN,Theodore Roberts,10,6,0,1
194,http://www.imdb.com/title/tt0010418/,1919,http://www.imdb.com/name/nm0576762,82,United States,1879,Male,1.85,Thomas Meighan,36,6,0,1
195,http://www.imdb.com/title/tt0019304/,1928,http://www.imdb.com/name/nm0576762,82,United States,1879,Male,1.85,Thomas Meighan,36,6,0,1
196,http://www.imdb.com/title/tt0010600/,1919,http://www.imdb.com/name/nm0418131,134,Russian Empire,1884,Male,NaN,Victor Janson,0,0,0,0
197,http://www.imdb.com/title/tt0011960/,1921,http://www.imdb.com/name/nm0418131,134,Russian Empire,1884,Male,NaN,Victor Janson,0,0,0,0
198,http://www.imdb.com/title/tt0010600/,1919,http://www.imdb.com/name/nm0858164,108,AustriaHungary,1890,Male,NaN,Hermann Thimig,0,2,0,1
199,http://www.imdb.com/title/tt0010635/,1919,http://www.imdb.com/name/nm0717468,214,United States,1891,Male,1.85,Wallace Reid,35,10,0,1

In [762]:
(adding_stars['Birthyear Star']==0).sum()

12025

In [763]:
len(adding_stars)

89075

In [764]:
adding_stars['Year'] = [int(x) for x in adding_stars['Year']]

In [765]:
adding_stars['Age at time of Release'] = adding_stars['Year'] - adding_stars['Birthyear Star']

# adding_stars['Age at time of Release'] = [x - y if x>0 else np.nan for x,y in adding_stars[['Birthyear Star','Year']]]
#     adding_stars['Birthyear Star'] - adding_stars['Year'] if adding_stars['Birthyear Star']>0 else np.nan

In [766]:
ages = list(adding_stars['Age at time of Release'].unique())

In [767]:
sorted(ages)

[-15,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 96,
 99,
 107,
 108,
 131,
 134,
 151,
 1911,
 1918,
 1920,
 1921,
 1923,
 1924,
 1925,
 1926,
 1928,
 1929,
 1930,
 1931,
 1932,
 1933,
 1934,
 1938,
 1939,
 1940,
 1941,
 1942,
 1943,
 1944,
 1946,
 1947,
 1948,
 1950,
 1951,
 1952,
 1953,
 1955,
 1956,
 1957,
 1958,
 1959,
 1960,
 1961,
 1962,
 1963,
 1964,
 1965,
 1966,
 1967,
 1968,
 1969,
 1970,
 1971,
 1972,
 1973,
 1974,
 1975,
 1976,
 1977,
 1978,
 1979,
 1980,
 1981,
 1982,
 1983,
 1984,
 1985,
 1986,
 1987,
 1988,
 1989,
 1990,
 1991,
 1992,
 1993,
 1994,
 1995,
 1996,
 1997,
 1998,
 1999,
 2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018]

In [768]:
adding_stars[adding_stars['Age at time of Release']==42]

,ID,Year,Star_URL,Acting Roles Star,Birth Country Star,Birthyear Star,Gender Star,Height Star,Name Star,Publicity Listings Star,TV Appearances Star,Other Roles Star,Award Nominations and Wins Star,Age at time of Release
0,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0209738,16,Italy,1869,Male,NaN,Giuseppe de Liguoro,0,0,92,0,42
8,http://www.imdb.com/title/tt0016847/,1926,http://www.imdb.com/name/nm0417837,82,Switzerland,1884,Male,1.83,Emil Jannings,8,3,6,4,42
37,http://www.imdb.com/title/tt0016655/,1926,http://www.imdb.com/name/nm0601698,286,Ireland,1884,Male,1.78,Owen Moore,19,1,2,1,42
46,http://www.imdb.com/title/tt0004465/,1914,http://www.imdb.com/name/nm0659947,394,Germany,1872,Male,1.79,Paul Panzer,14,3,0,1,42
88,http://www.imdb.com/title/tt0008443/,1917,http://www.imdb.com/name/nm0871337,1,United States,1875,Female,1.75,Madlaine Traverse,16,0,0,0,42
94,http://www.imdb.com/title/tt0012364/,1921,http://www.imdb.com/name/nm0803705,44,Sweden,1879,Male,1.80,Victor Sjöström,17,2,61,5,42
107,http://www.imdb.com/title/tt0021749/,1931,http://www.imdb.com/name/nm0000122,87,United Kingdom,1889,Male,1.65,Charles Chaplin,275,31,108,27,42
266,http://www.imdb.com/title/tt0016123/,1925,http://www.imdb.com/name/nm0151606,162,United States,1883,Male,1.70,Lon Chaney,54,3,0,2,42
267,http://www.imdb.com/title/tt0016220/,1925,http://www.imdb.com/name/nm0151606,162,United States,1883,Male,1.70,Lon Chaney,54,3,0,2,42
268,http://www.imdb.com/title/tt0016473/,1925,http://www.imdb.com/name/nm0151606,162,United States,1883,Male,1.70,Lon Chaney,54,3,0,2,42
308,http://www.imdb.com/title/tt0022879/,1932,http://www.imdb.com/name/nm0579663,150,United States,1890,Male,1.79,Adolphe Menjou,21,21,0,3,42
309,http://www.imdb.com/title/tt0022905/,1932,http://www.imdb.com/name/nm0579663,150,United States,1890,Male,1.79,Adolphe Menjou,21,21,0,3,42
363,http://www.imdb.com/title/tt0013571/,1922,http://www.imdb.com/name/nm0507568,215,United States,1880,Male,1.88,Mitchell Lewis,10,1,0,0,42
374,http://www.imdb.com/title/tt0019585/,1928,http://www.imdb.com/name/nm0361319,34,Sweden,1886,Male,1.78,Lars Hanson,8,0,0,0,42
455,http://www.imdb.com/title/tt0037017/,1944,http://www.imdb.com/name/nm0805790,97,AustriaHungary,1902,Male,1.83,Walter Slezak,3,39,0,0,42
557,http://www.imdb.com/title/tt0028174/,1936,http://www.imdb.com/name/nm0195460,53,United States,1894,Male,1.80,Roy D'Arcy,10,1,0,0,42
584,http://www.imdb.com/title/tt0024852/,1934,http://www.imdb.com/name/nm0001316,415,United States,1892,Male,1.83,Oliver Hardy,56,16,0,1,42
585,http://www.imdb.com/title/tt0025263/,1934,http://www.imdb.com/name/nm0001316,415,United States,1892,Male,1.83,Oliver Hardy,56,16,0,1,42
609,http://www.imdb.com/title/tt0016641/,1925,http://www.imdb.com/name/nm0124279,227,United States,1883,Male,1.80,Francis X. Bushman,51,13,0,2,42
612,http://www.imdb.com/title/tt0016654/,1926,http://www.imdb.com/name/nm0683114,1,United Kingdom,1884,Female,NaN,Tempe Pigott,0,0,0,0,42
726,http://www.imdb.com/title/tt0017483/,1926,http://www.imdb.com/name/nm0003377,94,United States,1884,Male,1.70,Harry Langdon,22,3,8,1,42
769,http://www.imdb.com/title/tt0035896/,1943,http://www.imdb.com/name/nm0000011,117,United States,1901,Male,1.88,Gary Cooper,51,35,0,21,42
799,http://www.imdb.com/title/tt0017739/,1927,http://www.imdb.com/name/nm0822477,76,United Kingdom,1885,Male,1.80,Forrest Stanley,5,1,0,0,42
905,http://www.imdb.com/title/tt0018937/,1928,http://www.imdb.com/name/nm0572142,124,United Kingdom,1886,Male,1.89,Victor McLaglen,18,9,0,4,42
914,http://www.imdb.com/title/tt0023151/,1932,http://www.imdb.com/name/nm0035877,183,United States,1890,Male,1.78,Robert Armstrong,8,5,0,1,42
915,http://www.imdb.com/title/tt0023327/,1932,http://www.imdb.com/name/nm0035877,183,United States,1890,Male,1.78,Robert Armstrong,8,5,0,1,42
925,http://www.imdb.com/title/tt0025091/,1934,http://www.imdb.com/name/nm0001635,96,United States,1892,Male,1.79,William Powell,22,5,0,5,42
926,http://www.imdb.com/title/tt0025101/,1934,http://www.imdb.com/name/nm0001635,96,United States,1892,Male,1.79,William Powell,22,5,0,5,42
927,http://www.imdb.com/title/tt0025464/,1934,http://www.imdb.com/name/nm0001635,96,United States,1892,Male,1.79,William Powell,22,5,0,5,42
928,http://www.imdb.com/title/tt0025878/,1934,http://www.imdb.com/name/nm0001635,96,United States,1892,Male,1.79,William Powell,22,5,0,5,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85000,http://www.imdb.com/title/tt5813366/,2017,http://www.imdb.com/name/nm0612534,34,New Zealand,1975,Male,1.88,Callan Mulvey,0,7,0,4,42
85144,http://www.imdb.com/title/tt3183630/,2013,http://www.imdb.com/name/nm6457441,1,Brazil,1971,Female,NaN,Lu Horta,0,0,0,0,42
85325,http://www.imdb.com/title/tt5154896/,2016,http://www.imdb.com/name/nm1164552,45,Germany,1974,Male,1.86,Florian David Fitz,0,15,0,19,42
85326,http://www.imdb.com/title/tt5500148/,2016,http://www.imdb.com/name/nm1164552,45,Germany,1974,Male,1.86,Florian David Fitz,0,15,0,19,42
85335,http://www.imdb.com/title/tt3275216/,2015,http://www.imdb.com/name/nm0243231,16,United States,1973,Male,1.75,Jay Duplass,2,22,44,18,42
85647,http://www.imdb.com/title/tt3438354/,2014,http://www.imdb.com/name/nm0502412,55,Italy,1972,Male,NaN,Edoardo Leo,0,5,0,24,42
85653,http://www.imdb.com/title/tt3444184/,2014,http://www.imdb.com/name/nm0864779,104,British Crown Colony,1972,Male,1.65,Chapman To,0,0,9,19,42
85654,http://www.imdb.com/title/tt3740242/,2014,http://www.imdb.com/name/nm0864779,104,British Crown Colony,1972,Male,1.65,Chapman To,0,0,9,19,42
85971,http://www.imdb.com/title/tt3597732/,2017,http://www.imdb.com/name/nm1340370,59,United States,1975,Male,1.75,Brian Caspe,0,0,0,0,42
86001,http://www.imdb.com/title/tt3613314/,2016,http://www.imdb.com/name/nm1360283,48,United Kingdom,1974,Male,NaN,Tom Meeten,0,1,0,1,42
86058,http://www.imdb.com/title/tt3644730/,2015,http://www.imdb.com/name/nm0071078,43,Sweden,1973,Male,1.79,Björn Bengtsson,0,1,0,0,42
86165,http://www.imdb.com/title/tt3705822/,2017,http://www.imdb.com/name/nm1541479,1,Canada,1975,Female,1.68,Niki Spiridakos,0,0,0,0,42
86185,http://www.imdb.com/title/tt3717252/,2016,http://www.imdb.com/name/nm0580014,57,United Kingdom,1974,Male,1.85,Tobias Menzies,2,13,0,3,42
86412,http://www.imdb.com/title/tt4944658/,2016,http://www.imdb.com/name/nm0299078,30,Argentina,1974,Male,NaN,Joaquín Furriel,18,28,0,14,42
86557,http://www.imdb.com/title/tt3952900/,2016,http://www.imdb.com/name/nm1346713,31,Spain,1974,Male,1.80,Paco León,1,94,9,40,42
86558,http://www.imdb.com/title/tt5517438/,2016,http://www.imdb.com/name/nm1346713,31,Spain,1974,Male,1.80,Paco León,1,94,9,40,42
86641,http://www.imdb.com/title/tt4009460/,2014,http://www.imdb.com/name/nm0229544,2,United States,1972,Male,NaN,Darren Doane,0,1,30,2,42
86747,http://www.imdb.com/title/tt4079152/,2015,http://www.imdb.com/name/nm1443336,22,China,1973,Male,NaN,Yihong Duan,0,0,0,8,42
87131,http://www.imdb.com/title/tt4332114/,2015,http://www.imdb.com/name/nm0037019,1,India,1973,Female,1.68,Malaika Arora,0,5,0,3,42
87247,http://www.imdb.com/title/tt4426656/,2015,http://www.imdb.com/name/nm1600229,30,France,1973,Male,NaN,Marc Robert,0,0,0,1,42
87355,http://www.imdb.com/title/tt5352846/,2017,http://www.imdb.com/name/nm1150775,98,Canada,1975,Male,1.80,Patrick Sabongui,0,1,8,4,42
87719,http://www.imdb.com/title/tt4817256/,2015,http://www.imdb.com/name/nm0941575,62,Poland,1973,Male,1.84,Adam Woronowicz,0,1,0,5,42
88205,http://www.imdb.com/title/tt5268648/,2015,http://www.imdb.com/name/nm0087789,34,Poland,1973,Male,1.80,Waldemar Blaszczyk,0,0,0,0,42
88250,http://www.imdb.com/title/tt5310412/,2017,http://www.imdb.com/name/nm1523032,16,Bulgaria,1975,Male,NaN,Kiril Efremov,0,1,0,0,42
88297,http://www.imdb.com/title/tt6359554/,2017,http://www.imdb.com/name/nm2500160,22,India,1975,Male,1.75,Puneeth Rajkumar,0,1,0,3,42
88305,http://www.imdb.com/title/tt5357556/,2016,http://www.imdb.com/name/nm0721460,1,Belgium,1974,Female,NaN,Tine Reymer,1,3,0,0,42
88457,http://www.imdb.com/title/tt5608972/,2016,http://www.imdb.com/name/nm1195585,19,None,1974,Male,NaN,Sermiyan Midyat,0,1,0,2,42
88470,http://www.imdb.com/title/tt5631456/,2017,http://www.imdb.com/name/nm0722902,1,Brazil,1975,Female,NaN,Maria Ribeiro,1,10,0,3,42
88805,http://www.imdb.com/title/tt6194530/,2017,http://www.imdb.com/name/nm2662182,1,France,1975,Female,NaN,Laure Calamy,0,3,0,1,42
88998,http://www.imdb.com/title/tt7010412/,2017,http://www.imdb.com/name/nm3818786,29,Taiwan,1975,Male,NaN,Bamboo Chu-Sheng Chen,0,0,0,2,42

In [769]:
adding_stars['Age at time of Release'] = [np.nan if x>99 else x for x in adding_stars['Age at time of Release']]

In [770]:
adding_stars['Age at time of Release'] = [np.nan if x<0 else x for x in adding_stars['Age at time of Release']]

In [771]:
adding_stars['Age at time of Release'].isnull().sum()

12031

In [772]:
adding_stars['Age at time of Release'].notnull().sum()

77044

In [773]:
age_corrected = sorted(list(adding_stars['Age at time of Release'].unique()))
sorted(age_corrected)

[2.0,
 42.0,
 nan,
 3.0,
 4.0,
 5.0,
 6.0,
 7.0,
 8.0,
 9.0,
 10.0,
 11.0,
 12.0,
 13.0,
 14.0,
 15.0,
 16.0,
 17.0,
 18.0,
 19.0,
 20.0,
 21.0,
 22.0,
 23.0,
 24.0,
 25.0,
 26.0,
 27.0,
 28.0,
 29.0,
 30.0,
 31.0,
 32.0,
 33.0,
 34.0,
 35.0,
 36.0,
 37.0,
 38.0,
 39.0,
 40.0,
 41.0,
 43.0,
 44.0,
 45.0,
 46.0,
 47.0,
 48.0,
 49.0,
 50.0,
 51.0,
 52.0,
 53.0,
 54.0,
 55.0,
 56.0,
 57.0,
 58.0,
 59.0,
 60.0,
 61.0,
 62.0,
 63.0,
 64.0,
 65.0,
 66.0,
 67.0,
 68.0,
 69.0,
 70.0,
 71.0,
 72.0,
 73.0,
 74.0,
 75.0,
 76.0,
 77.0,
 78.0,
 79.0,
 80.0,
 81.0,
 82.0,
 83.0,
 84.0,
 85.0,
 86.0,
 87.0,
 88.0,
 89.0,
 90.0,
 91.0,
 92.0,
 93.0,
 94.0,
 96.0,
 99.0]

In [774]:
adding_stars.head(100)

,ID,Year,Star_URL,Acting Roles Star,Birth Country Star,Birthyear Star,Gender Star,Height Star,Name Star,Publicity Listings Star,TV Appearances Star,Other Roles Star,Award Nominations and Wins Star,Age at time of Release
0,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0209738,16,Italy,1869,Male,NaN,Giuseppe de Liguoro,0,0,92,0,42.0
1,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0685283,6,None,0,Male,NaN,Arturo Pirovano,0,0,0,0,NaN
2,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0660139,15,None,0,Male,NaN,Salvatore Papa,0,0,0,0,NaN
3,http://www.imdb.com/title/tt0002423/,1919,http://www.imdb.com/name/nm0509573,162,Russia,1882,Male,NaN,Harry Liedtke,2,3,0,0,37.0
4,http://www.imdb.com/title/tt0002423/,1919,http://www.imdb.com/name/nm0417837,82,Switzerland,1884,Male,1.83,Emil Jannings,8,3,6,4,35.0
5,http://www.imdb.com/title/tt0014586/,1924,http://www.imdb.com/name/nm0417837,82,Switzerland,1884,Male,1.83,Emil Jannings,8,3,6,4,40.0
6,http://www.imdb.com/title/tt0015064/,1924,http://www.imdb.com/name/nm0417837,82,Switzerland,1884,Male,1.83,Emil Jannings,8,3,6,4,40.0
7,http://www.imdb.com/title/tt0016481/,1925,http://www.imdb.com/name/nm0417837,82,Switzerland,1884,Male,1.83,Emil Jannings,8,3,6,4,41.0
8,http://www.imdb.com/title/tt0016847/,1926,http://www.imdb.com/name/nm0417837,82,Switzerland,1884,Male,1.83,Emil Jannings,8,3,6,4,42.0
9,http://www.imdb.com/title/tt0019071/,1928,http://www.imdb.com/name/nm0417837,82,Switzerland,1884,Male,1.83,Emil Jannings,8,3,6,4,44.0
10,http://www.imdb.com/title/tt0020697/,1930,http://www.imdb.com/name/nm0417837,82,Switzerland,1884,Male,1.83,Emil Jannings,8,3,6,4,46.0
11,http://www.imdb.com/title/tt3565328/,1930,http://www.imdb.com/name/nm0417837,82,Switzerland,1884,Male,1.83,Emil Jannings,8,3,6,4,46.0
12,http://www.imdb.com/title/tt0002423/,1919,http://www.imdb.com/name/nm0624470,1,Poland,1897,Female,1.52,Pola Negri,69,6,0,2,22.0
13,http://www.imdb.com/title/tt0011742/,1920,http://www.imdb.com/name/nm0624470,1,Poland,1897,Female,1.52,Pola Negri,69,6,0,2,23.0
14,http://www.imdb.com/title/tt0011960/,1921,http://www.imdb.com/name/nm0624470,1,Poland,1897,Female,1.52,Pola Negri,69,6,0,2,24.0
15,http://www.imdb.com/title/tt0058371/,1964,http://www.imdb.com/name/nm0624470,1,Poland,1897,Female,1.52,Pola Negri,69,6,0,2,67.0
16,http://www.imdb.com/title/tt0002844/,1913,http://www.imdb.com/name/nm0622772,119,France,1877,Male,NaN,René Navarre,0,0,8,0,36.0
17,http://www.imdb.com/title/tt0003037/,1913,http://www.imdb.com/name/nm0622772,119,France,1877,Male,NaN,René Navarre,0,0,8,0,36.0
18,http://www.imdb.com/title/tt0003165/,1913,http://www.imdb.com/name/nm0622772,119,France,1877,Male,NaN,René Navarre,0,0,8,0,36.0
19,http://www.imdb.com/title/tt0002844/,1913,http://www.imdb.com/name/nm0107631,82,United Kingdom,1882,Male,NaN,Edmund Breon,0,0,0,0,31.0
20,http://www.imdb.com/title/tt0003037/,1913,http://www.imdb.com/name/nm0107631,82,United Kingdom,1882,Male,NaN,Edmund Breon,0,0,0,0,31.0
21,http://www.imdb.com/title/tt0003165/,1913,http://www.imdb.com/name/nm0107631,82,United Kingdom,1882,Male,NaN,Edmund Breon,0,0,0,0,31.0
22,http://www.imdb.com/title/tt0002844/,1913,http://www.imdb.com/name/nm0577476,68,France,1889,Male,NaN,Georges Melchior,1,0,0,0,24.0
23,http://www.imdb.com/title/tt0003037/,1913,http://www.imdb.com/name/nm0577476,68,France,1889,Male,NaN,Georges Melchior,1,0,0,0,24.0
24,http://www.imdb.com/title/tt0003165/,1913,http://www.imdb.com/name/nm0577476,68,France,1889,Male,NaN,Georges Melchior,1,0,0,0,24.0
25,http://www.imdb.com/title/tt0003419/,1913,http://www.imdb.com/name/nm0758802,1,AustriaHungary,1889,Female,NaN,Lyda Salmonova,1,0,0,0,24.0
26,http://www.imdb.com/title/tt0004026/,1915,http://www.imdb.com/name/nm0758802,1,AustriaHungary,1889,Female,NaN,Lyda Salmonova,1,0,0,0,26.0
27,http://www.imdb.com/title/tt0003419/,1913,http://www.imdb.com/name/nm0074186,1,Czech Republic,1883,Female,NaN,Grete Berger,0,0,0,0,30.0
28,http://www.imdb.com/title/tt0003419/,1913,http://www.imdb.com/name/nm0917467,71,Poland,1874,Male,1.98,Paul Wegener,3,1,23,0,39.0
29,http://www.imdb.com/title/tt0004026/,1915,http://www.imdb.com/name/nm0917467,71,Poland,1874,Male,1.98,Paul Wegener,3,1,23,0,41.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,http://www.imdb.com/title/tt0005960/,1915,http://www.imdb.com/name/nm0271503,62,Canada,1883,Male,1.80,Rockliffe Fellowes,3,0,0,0,32.0
71,http://www.imdb.com/title/tt0006206/,1915,http://www.imdb.com/name/nm0559013,89,Australia,1886,Male,NaN,Édouard Mathé,0,0,0,0,29.0
72,http://www.imdb.com/title/tt0006206/,1915,http://www.imdb.com/name/nm0529695,102,France,1877,Male,NaN,Marcel Lévesque,0,0,0,0,38.0
73,http://www.imdb.com/title/tt0006206/,1915,http://www.imdb.com/name/nm0615736,1,France,1889,Female,NaN,Musidora,1,1,10,0,26.0
74,http://www.imdb.com/title/tt0006886/,1916,http://www.imdb.com/name/nm0615736,1,France,1889,Female,NaN,Musidora,1,1,10,0,27.0
75,http://www.imdb.com/title/tt0006333/,1916,http://www.imdb.com/name/nm0392709,38,United States,1888,Male,1.83,Allen Holubar,9,1,37,0,28.0
76,http://www.imdb.com/title/tt0006333/,1916,http://www.imdb.com/name/nm0671728,1,None,1887,Female,NaN,Edna Pendleton,1,0,0,0,29.0
77,http://www.imdb.com/title/tt0006333/,1916,http://www.imdb.com/name/nm0360132,3,None,1866,Male,NaN,Dan Hanlon,0,0,0,0,50.0
78,http://www.imdb.com/title/tt0006780/,1916,http://www.imdb.com/name/nm0930290,1,United States,1888,Female,NaN,Clara Williams,5,0,0,0,28.0
79,http://www.imdb.com/title/tt0006780/,1916,http://www.imdb.com/name/nm0822060,58,United Kingdom,1886,Male,NaN,Jack Standing,4,0,0,0,30.0
80,http://www.imdb.com/title/tt0006780/,1916,http://www.imdb.com/name/nm0366586,74,United States,1864,Male,1.88,William S. Hart,84,11,72,2,52.0
81,http://www.imdb.com/title/tt0006864/,1916,http://www.imdb.com/name/nm0366008,223,United States,1893,Male,1.80,Robert Harron,12,1,0,0,23.0
82,http://www.imdb.com/title/tt0006886/,1916,http://www.imdb.com/name/nm0100270,84,France,1908,Male,NaN,René Poyen,0,0,0,0,8.0
83,http://www.imdb.com/title/tt0006886/,1916,http://www.imdb.com/name/nm0187612,54,France,1881,Male,NaN,René Cresté,0,0,2,0,35.0
84,http://www.imdb.com/title/tt0008188/,1917,http://www.imdb.com/name/nm0392442,191,United States,1888,Male,1.83,Jack Holt,10,19,0,1,29.0
85,http://www.imdb.com/title/tt0026641/,1935,http://www.imdb.com/name/nm0392442,191,United States,1888,Male,1.83,Jack Holt,10,19,0,1,47.0
86,http://www.imdb.com/title/tt0008188/,1917,http://www.imdb.com/name/nm0369058,419,United States,1887,Male,1.70,Raymond Hatton,13,3,0,1,30.0
87,http://www.imdb.com/title/tt0010418/,1919,http://www.imdb.com/name/nm0369058,419,United States,1887,Male,1.70,Raymond Hatton,13,3,0,1,32.0
88,http://www.imdb.com/title/tt0008443/,1917,http://www.imdb.com/name/nm0871337,1,United States,1875,Female,1.75,Madlaine Traverse,16,0,0,0,42.0
89,http://www.imdb.com/title/tt0008443/,1917,http://www.imdb.com/name/nm0919966,93,Ireland,1873,Male,NaN,Charles Wellesley,1,0,0,0,44.0
90,http://www.imdb.com/title/tt0008519/,1917,http://www.imdb.com/name/nm0551222,196,United States,1864,Male,1.79,Tully Marshall,10,0,0,0,53.0
91,http://www.imdb.com/title/tt0008519/,1917,http://www.imdb.com/name/nm0223296,59,United States,1879,Male,1.83,Elliott Dexter,14,3,0,1,38.0
92,http://www.imdb.com/title/tt0008663/,1917,http://www.imdb.com/name/nm0265890,11,Sweden,1882,Male,NaN,August Falck,0,0,0,0,35.0
93,http://www.imdb.com/title/tt0008663/,1917,http://www.imdb.com/name/nm0803705,44,Sweden,1879,Male,1.80,Victor Sjöström,17,2,61,5,38.0
94,http://www.imdb.com/title/tt0012364/,1921,http://www.imdb.com/name/nm0803705,44,Sweden,1879,Male,1.80,Victor Sjöström,17,2,61,5,42.0
95,http://www.imdb.com/title/tt0050986/,1957,http://www.imdb.com/name/nm0803705,44,Sweden,1879,Male,1.80,Victor Sjöström,17,2,61,5,78.0
96,http://www.imdb.com/title/tt0008663/,1917,http://www.imdb.com/name/nm0258611,1,Finland,1887,Female,NaN,Edith Erastoff,0,0,0,0,30.0
97,http://www.imdb.com/title/tt0008891/,1918,http://www.imdb.com/name/nm0532031,1,United States,1907,Male,NaN,Robin Macdougall,0,0,0,0,11.0
98,http://www.imdb.com/title/tt0008891/,1918,http://www.imdb.com/name/nm0715410,1,None,0,Male,NaN,Edwin E. Reed,0,0,0,0,NaN
99,http://www.imdb.com/title/tt0008891/,1918,http://www.imdb.com/name/nm0068818,1,Norway,1906,Female,NaN,Tula Belle,2,0,0,0,12.0

In [775]:
adding_stars['Acting Roles Stars Cumulative'] = adding_stars[
    'Acting Roles Star'].groupby(adding_stars['ID']).transform('sum')

In [780]:
adding_stars['Award Nominations and Wins Stars Cumulative'] = adding_stars[
    'Award Nominations and Wins Star'].groupby(adding_stars['ID']).transform('sum')

In [782]:
adding_stars['Other Roles Stars Cumulative'] = adding_stars[
    'Other Roles Star'].groupby(adding_stars['ID']).transform('sum')

In [790]:
adding_stars['TV Appearances Stars Cumulative'] = adding_stars[
    'TV Appearances Star'].groupby(adding_stars['ID']).transform('sum')

In [791]:
adding_stars['Publicity Listings Stars Cumulative'] = adding_stars[
    'Publicity Listings Star'].groupby(adding_stars['ID']).transform('sum')

In [792]:
adding_stars.sort_values(['ID','Age at time of Release'],inplace = True)

In [796]:
adding_stars['Age Differences Stars'] = adding_stars[
    'Age at time of Release'].groupby(adding_stars['ID']).transform(lambda x: x.diff(1))

In [803]:
adding_stars['Sum of Age Differences Stars'] = adding_stars[
    'Age Differences Stars'].groupby(adding_stars['ID']).transform('sum')

In [806]:
adding_stars['Sum of Age Differences Stars'].max()

88.0

In [808]:
adding_stars['Sum of Age Differences Stars'].min()

0.0

In [810]:
adding_stars['Sum of Age Differences Stars'].mean()

15.98733651417345

In [807]:
adding_stars[adding_stars['Sum of Age Differences Stars']==88.0]

,ID,Year,Star_URL,Acting Roles Star,Birth Country Star,Birthyear Star,Gender Star,Height Star,Name Star,Publicity Listings Star,...,Other Roles Star,Award Nominations and Wins Star,Age at time of Release,Acting Roles Stars Cumulative,Award Nominations and Wins Stars Cumulative,Other Roles Stars Cumulative,TV Appearances Stars Cumulative,Publicity Listings Stars Cumulative,Age Differences Stars,Sum of Age Differences Stars
77015,http://www.imdb.com/title/tt2452042/,2015,http://www.imdb.com/name/nm6907855,9,United States,2004,Male,1.55,Noah Schnapp,3,...,0,2,11.0,64,46,116,37,11,NaN,88.0
77014,http://www.imdb.com/title/tt2452042/,2015,http://www.imdb.com/name/nm0006837,54,Mexico,1916,Male,NaN,Bill Melendez,8,...,116,43,99.0,64,46,116,37,11,88.0,88.0
77013,http://www.imdb.com/title/tt2452042/,2015,http://www.imdb.com/name/nm5295511,1,None,0,Female,1.37,Hadley Belle Miller,0,...,0,1,NaN,64,46,116,37,11,NaN,88.0

In [838]:
adding_stars['Genders of Stars'] = adding_stars[
    'Gender Star'].groupby(adding_stars['ID']).transform(lambda x: [x])

In [829]:
adding_stars.drop(columns=['Number of Females Stars'],inplace=True)

In [843]:
adding_stars.head(30)

,ID,Year,Star_URL,Acting Roles Star,Birth Country Star,Birthyear Star,Gender Star,Height Star,Name Star,Publicity Listings Star,...,Award Nominations and Wins Star,Age at time of Release,Acting Roles Stars Cumulative,Award Nominations and Wins Stars Cumulative,Other Roles Stars Cumulative,TV Appearances Stars Cumulative,Publicity Listings Stars Cumulative,Age Differences Stars,Sum of Age Differences Stars,Genders of Stars
0,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0209738,16,Italy,1869,Male,NaN,Giuseppe de Liguoro,0,...,0,42.0,37,0,92,0,0,NaN,0.0,0 Male 1 Male 2 Male Name: http://www...
1,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0685283,6,None,0,Male,NaN,Arturo Pirovano,0,...,0,NaN,37,0,92,0,0,NaN,0.0,0 Male 1 Male 2 Male Name: http://www...
2,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0660139,15,None,0,Male,NaN,Salvatore Papa,0,...,0,NaN,37,0,92,0,0,NaN,0.0,0 Male 1 Male 2 Male Name: http://www...
3,http://www.imdb.com/title/tt0002423/,1919,http://www.imdb.com/name/nm0624470,1,Poland,1897,Female,1.52,Pola Negri,69,...,2,22.0,245,6,6,12,79,NaN,15.0,5 Female 4 Male 3 Male Name: http...
4,http://www.imdb.com/title/tt0002423/,1919,http://www.imdb.com/name/nm0417837,82,Switzerland,1884,Male,1.83,Emil Jannings,8,...,4,35.0,245,6,6,12,79,13.0,15.0,5 Female 4 Male 3 Male Name: http...
5,http://www.imdb.com/title/tt0002423/,1919,http://www.imdb.com/name/nm0509573,162,Russia,1882,Male,NaN,Harry Liedtke,2,...,0,37.0,245,6,6,12,79,2.0,15.0,5 Female 4 Male 3 Male Name: http...
6,http://www.imdb.com/title/tt0002844/,1913,http://www.imdb.com/name/nm0577476,68,France,1889,Male,NaN,Georges Melchior,1,...,0,24.0,269,0,8,0,1,NaN,12.0,6 Male 7 Male 8 Male Name: http://www...
7,http://www.imdb.com/title/tt0002844/,1913,http://www.imdb.com/name/nm0107631,82,United Kingdom,1882,Male,NaN,Edmund Breon,0,...,0,31.0,269,0,8,0,1,7.0,12.0,6 Male 7 Male 8 Male Name: http://www...
8,http://www.imdb.com/title/tt0002844/,1913,http://www.imdb.com/name/nm0622772,119,France,1877,Male,NaN,René Navarre,0,...,0,36.0,269,0,8,0,1,5.0,12.0,6 Male 7 Male 8 Male Name: http://www...
9,http://www.imdb.com/title/tt0003037/,1913,http://www.imdb.com/name/nm0577476,68,France,1889,Male,NaN,Georges Melchior,1,...,0,24.0,269,0,8,0,1,NaN,12.0,9 Male 10 Male 11 Male Name: http://...
10,http://www.imdb.com/title/tt0003037/,1913,http://www.imdb.com/name/nm0107631,82,United Kingdom,1882,Male,NaN,Edmund Breon,0,...,0,31.0,269,0,8,0,1,7.0,12.0,9 Male 10 Male 11 Male Name: http://...
11,http://www.imdb.com/title/tt0003037/,1913,http://www.imdb.com/name/nm0622772,119,France,1877,Male,NaN,René Navarre,0,...,0,36.0,269,0,8,0,1,5.0,12.0,9 Male 10 Male 11 Male Name: http://...
12,http://www.imdb.com/title/tt0003165/,1913,http://www.imdb.com/name/nm0577476,68,France,1889,Male,NaN,Georges Melchior,1,...,0,24.0,269,0,8,0,1,NaN,12.0,14 Male 13 Male 12 Male Name: http://...
13,http://www.imdb.com/title/tt0003165/,1913,http://www.imdb.com/name/nm0107631,82,United Kingdom,1882,Male,NaN,Edmund Breon,0,...,0,31.0,269,0,8,0,1,7.0,12.0,14 Male 13 Male 12 Male Name: http://...
14,http://www.imdb.com/title/tt0003165/,1913,http://www.imdb.com/name/nm0622772,119,France,1877,Male,NaN,René Navarre,0,...,0,36.0,269,0,8,0,1,5.0,12.0,14 Male 13 Male 12 Male Name: http://...
15,http://www.imdb.com/title/tt0003419/,1913,http://www.imdb.com/name/nm0758802,1,AustriaHungary,1889,Female,NaN,Lyda Salmonova,1,...,0,24.0,73,0,23,1,4,NaN,15.0,17 Female 16 Female 15 Male Name: h...
16,http://www.imdb.com/title/tt0003419/,1913,http://www.imdb.com/name/nm0074186,1,Czech Republic,1883,Female,NaN,Grete Berger,0,...,0,30.0,73,0,23,1,4,6.0,15.0,17 Female 16 Female 15 Male Name: h...
17,http://www.imdb.com/title/tt0003419/,1913,http://www.imdb.com/name/nm0917467,71,Poland,1874,Male,1.98,Paul Wegener,3,...,0,39.0,73,0,23,1,4,9.0,15.0,17 Female 16 Female 15 Male Name: h...
18,http://www.imdb.com/title/tt0003740/,1914,http://www.imdb.com/name/nm0702894,1,Italy,1891,Female,NaN,Lidia Quaranta,0,...,0,23.0,34,0,0,0,5,NaN,13.0,19 Female 20 Female 18 Male Name: h...
19,http://www.imdb.com/title/tt0003740/,1914,http://www.imdb.com/name/nm0021935,1,Italy,1890,Female,NaN,Italia Almirante-Manzini,0,...,0,24.0,34,0,0,0,5,1.0,13.0,19 Female 20 Female 18 Male Name: h...
20,http://www.imdb.com/title/tt0003740/,1914,http://www.imdb.com/name/nm0656034,32,Italy,1878,Male,1.83,Bartolomeo Pagano,5,...,0,36.0,34,0,0,0,5,12.0,13.0,19 Female 20 Female 18 Male Name: h...
21,http://www.imdb.com/title/tt0003772/,1914,http://www.imdb.com/name/nm0681933,1,Canada,1892,Female,1.54,Mary Pickford,173,...,3,22.0,288,4,39,45,193,NaN,18.0,21 Female 22 Male 23 Female Name: h...
22,http://www.imdb.com/title/tt0003772/,1914,http://www.imdb.com/name/nm0601698,286,Ireland,1884,Male,1.78,Owen Moore,19,...,1,30.0,288,4,39,45,193,8.0,18.0,21 Female 22 Male 23 Female Name: h...
23,http://www.imdb.com/title/tt0003772/,1914,http://www.imdb.com/name/nm0894679,1,None,1874,Female,NaN,Isabel Vernon,1,...,0,40.0,288,4,39,45,193,10.0,18.0,21 Female 22 Male 23 Female Name: h...
24,http://www.imdb.com/title/tt0004026/,1915,http://www.imdb.com/name/nm0758802,1,AustriaHungary,1889,Female,NaN,Lyda Salmonova,1,...,0,26.0,78,0,23,1,6,NaN,15.0,26 Female 24 Male 25 Male Name: h...
25,http://www.imdb.com/title/tt0004026/,1915,http://www.imdb.com/name/nm0301961,6,AustriaHungary,1881,Male,NaN,Henrik Galeen,2,...,0,34.0,78,0,23,1,6,8.0,15.0,26 Female 24 Male 25 Male Name: h...
26,http://www.imdb.com/title/tt0004026/,1915,http://www.imdb.com/name/nm0917467,71,Poland,1874,Male,1.98,Paul Wegener,3,...,0,41.0,78,0,23,1,6,7.0,15.0,26 Female 24 Male 25 Male Name: h...
27,http://www.imdb.com/title/tt0004465/,1914,http://www.imdb.com/name/nm0925310,1,United States,1889,Female,NaN,Pearl White,35,...,1,25.0,484,2,0,6,58,NaN,17.0,29 Female 27 Male 28 Male Name: h...
28,http://www.imdb.com/title/tt0004465/,1914,http://www.imdb.com/name/nm0928108,89,United States,1886,Male,1.78,Crane Wilbur,9,...,0,28.0,484,2,0,6,58,3.0,17.0,29 Female 27 Male 28 Male Name: h...
29,http://www.imdb.com/title/tt0004465/,1914,http://www.imdb.com/name/nm0659947,394,Germany,1872,Male,1.79,Paul Panzer,14,...,1,42.0,484,2,0,6,58,14.0,17.0,29 Female 27 Male 28 Male Name: h...

In [842]:
adding_stars.reset_index(drop=True,inplace=True)

In [854]:
len(adding_stars)

89075

In [ ]:
star_gender_counting = [x.str.split() for x in adding_stars['Genders of Stars']]

In [850]:
star_gender_counting[0][0]

['Male']

In [865]:
star_gender_counts = []
for i in star_gender_counting:
    counter = 0
    items = 0
    for g in i:
        items+=1
        if g == ['Female']:
            counter+=1
    star_gender_counts.append(counter)
star_gender_counts

[0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 2,
 2,
 2,
 3,
 3,
 3,
 0,
 0,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 0,
 0,
 0,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 3,
 3,
 3,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 0,
 0,
 0,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 0,
 ...]

In [866]:
len(star_gender_counts)

89075

In [863]:
adding_stars['Gender Value Counter'] = adding_stars[
    'Gender Star'].groupby(adding_stars['ID']).transform('count')

In [877]:
adding_stars['Number of Female Stars'] = star_gender_counts

In [903]:
adding_stars.head(100)

,ID,Year,Star_URL,Acting Roles Star,Birth Country Star,Birthyear Star,Gender Star,Height Star,Name Star,Publicity Listings Star,...,Other Roles Stars Cumulative,TV Appearances Stars Cumulative,Publicity Listings Stars Cumulative,Age Differences Stars,Sum of Age Differences Stars,Genders of Stars,Gender Value Counter,Number of Female Stars,Share of Female Stars,Country Diversity Actors
0,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0209738,16,Italy,1869,Male,NaN,Giuseppe de Liguoro,0,...,92,0,0,NaN,0.0,0 Male 1 Male 2 Male Name: http://www...,3,0,0.000000,0 Italy 1 None 2 None Name: http://...
1,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0685283,6,None,0,Male,NaN,Arturo Pirovano,0,...,92,0,0,NaN,0.0,0 Male 1 Male 2 Male Name: http://www...,3,0,0.000000,0 Italy 1 None 2 None Name: http://...
2,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0660139,15,None,0,Male,NaN,Salvatore Papa,0,...,92,0,0,NaN,0.0,0 Male 1 Male 2 Male Name: http://www...,3,0,0.000000,0 Italy 1 None 2 None Name: http://...
3,http://www.imdb.com/title/tt0002423/,1919,http://www.imdb.com/name/nm0624470,1,Poland,1897,Female,1.52,Pola Negri,69,...,6,12,79,NaN,15.0,5 Female 4 Male 3 Male Name: http...,3,1,0.333333,3 Poland 4 Switzerland 5 Ru...
4,http://www.imdb.com/title/tt0002423/,1919,http://www.imdb.com/name/nm0417837,82,Switzerland,1884,Male,1.83,Emil Jannings,8,...,6,12,79,13.0,15.0,5 Female 4 Male 3 Male Name: http...,3,1,0.333333,3 Poland 4 Switzerland 5 Ru...
5,http://www.imdb.com/title/tt0002423/,1919,http://www.imdb.com/name/nm0509573,162,Russia,1882,Male,NaN,Harry Liedtke,2,...,6,12,79,2.0,15.0,5 Female 4 Male 3 Male Name: http...,3,1,0.333333,3 Poland 4 Switzerland 5 Ru...
6,http://www.imdb.com/title/tt0002844/,1913,http://www.imdb.com/name/nm0577476,68,France,1889,Male,NaN,Georges Melchior,1,...,8,0,1,NaN,12.0,6 Male 7 Male 8 Male Name: http://www...,3,0,0.000000,6 France 7 United Kingdom 8 ...
7,http://www.imdb.com/title/tt0002844/,1913,http://www.imdb.com/name/nm0107631,82,United Kingdom,1882,Male,NaN,Edmund Breon,0,...,8,0,1,7.0,12.0,6 Male 7 Male 8 Male Name: http://www...,3,0,0.000000,6 France 7 United Kingdom 8 ...
8,http://www.imdb.com/title/tt0002844/,1913,http://www.imdb.com/name/nm0622772,119,France,1877,Male,NaN,René Navarre,0,...,8,0,1,5.0,12.0,6 Male 7 Male 8 Male Name: http://www...,3,0,0.000000,6 France 7 United Kingdom 8 ...
9,http://www.imdb.com/title/tt0003037/,1913,http://www.imdb.com/name/nm0577476,68,France,1889,Male,NaN,Georges Melchior,1,...,8,0,1,NaN,12.0,9 Male 10 Male 11 Male Name: http://...,3,0,0.000000,9 France 10 United Kingdom 11 ...
10,http://www.imdb.com/title/tt0003037/,1913,http://www.imdb.com/name/nm0107631,82,United Kingdom,1882,Male,NaN,Edmund Breon,0,...,8,0,1,7.0,12.0,9 Male 10 Male 11 Male Name: http://...,3,0,0.000000,9 France 10 United Kingdom 11 ...
11,http://www.imdb.com/title/tt0003037/,1913,http://www.imdb.com/name/nm0622772,119,France,1877,Male,NaN,René Navarre,0,...,8,0,1,5.0,12.0,9 Male 10 Male 11 Male Name: http://...,3,0,0.000000,9 France 10 United Kingdom 11 ...
12,http://www.imdb.com/title/tt0003165/,1913,http://www.imdb.com/name/nm0577476,68,France,1889,Male,NaN,Georges Melchior,1,...,8,0,1,NaN,12.0,14 Male 13 Male 12 Male Name: http://...,3,0,0.000000,12 France 13 United Kingdom 14 ...
13,http://www.imdb.com/title/tt0003165/,1913,http://www.imdb.com/name/nm0107631,82,United Kingdom,1882,Male,NaN,Edmund Breon,0,...,8,0,1,7.0,12.0,14 Male 13 Male 12 Male Name: http://...,3,0,0.000000,12 France 13 United Kingdom 14 ...
14,http://www.imdb.com/title/tt0003165/,1913,http://www.imdb.com/name/nm0622772,119,France,1877,Male,NaN,René Navarre,0,...,8,0,1,5.0,12.0,14 Male 13 Male 12 Male Name: http://...,3,0,0.000000,12 France 13 United Kingdom 14 ...
15,http://www.imdb.com/title/tt0003419/,1913,http://www.imdb.com/name/nm0758802,1,AustriaHungary,1889,Female,NaN,Lyda Salmonova,1,...,23,1,4,NaN,15.0,17 Female 16 Female 15 Male Name: h...,3,2,0.666667,15 AustriaHungary 16 Czech Republic 17 ...
16,http://www.imdb.com/title/tt0003419/,1913,http://www.imdb.com/name/nm0074186,1,Czech Republic,1883,Female,NaN,Grete Berger,0,...,23,1,4,6.0,15.0,17 Female 16 Female 15 Male Name: h...,3,2,0.666667,15 AustriaHungary 16 Czech Republic 17 ...
17,http://www.imdb.com/title/tt0003419/,1913,http://www.imdb.com/name/nm0917467,71,Poland,1874,Male,1.98,Paul Wegener,3,...,23,1,4,9.0,15.0,17 Female 16 Female 15 Male Name: h...,3,2,0.666667,15 AustriaHungary 16 Czech Republic 17 ...
18,http://www.imdb.com/title/tt0003740/,1914,http://www.imdb.com/name/nm0702894,1,Italy,1891,Female,NaN,Lidia Quaranta,0,...,0,0,5,NaN,13.0,19 Female 20 Female 18 Male Name: h...,3,2,0.666667,18 Italy 19 Italy 20 Italy Name: http...
19,http://www.imdb.com/title/tt0003740/,1914,http://www.imdb.com/name/nm0021935,1,Italy,1890,Female,NaN,Italia Almirante-Manzini,0,...,0,0,5,1.0,13.0,19 Female 20 Female 18 Male Name: h...,3,2,0.666667,18 Italy 19 Italy 20 Italy Name: http...
20,http://www.imdb.com/title/tt0003740/,1914,http://www.imdb.com/name/nm0656034,32,Italy,1878,Male,1.83,Bartolomeo Pagano,5,...,0,0,5,12.0,13.0,19 Female 20 Female 18 Male Name: h...,3,2,0.666667,18 Italy 19 Italy 20 Italy Name: http...
21,http://www.imdb.com/title/tt0003772/,1914,http://www.imdb.com/name/nm0681933,1,Canada,1892,Female,1.54,Mary Pickford,173,...,39,45,193,NaN,18.0,21 Female 22 Male 23 Female Name: h...,3,2,0.666667,21 Canada 22 Ireland 23 None Name...
22,http://www.imdb.com/title/tt0003772/,1914,http://www.imdb.com/name/nm0601698,286,Ireland,1884,Male,1.78,Owen Moore,19,...,39,45,193,8.0,18.0,21 Female 22 Male 23 Female Name: h...,3,2,0.666667,21 Canada 22 Ireland 23 None Name...
23,http://www.imdb.com/title/tt0003772/,1914,http://www.imdb.com/name/nm0894679,1,None,1874,Female,NaN,Isabel Vernon,1,...,39,45,193,10.0,18.0,21 Female 22 Male 23 Female Name: h...,3,2,0.666667,21 Canada 22 Ireland 23 None Name...
24,http://www.imdb.com/title/tt0004026/,1915,http://www.imdb.com/name/nm0758802,1,AustriaHungary,1889,Female,NaN,Lyda Salmonova,1,...,23,1,6,NaN,15.0,26 Female 24 Male 25 Male Name: h...,3,1,0.333333,24 AustriaHungary 25 AustriaHungary 26 ...
25,http://www.imdb.com/title/tt0004026/,1915,http://www.imdb.com/name/nm0301961,6,AustriaHungary,1881,Male,NaN,Henrik Galeen,2,...,23,1,6,8.0,15.0,26 Female 24 Male 25 Male Name: h...,3,1,0.333333,24 AustriaHungary 25 AustriaHungary 26 ...
26,http://www.imdb.com/title/tt0004026/,1915,http://www.imdb.com/name/nm0917467,71,Poland,1874,Male,1.98,Paul Wegener,3,...,23,1,6,7.0,15.0,26 Female 24 Male 25 Male Name: h...,3,1,0.333333,24 AustriaHungary 25 AustriaHungary 26 ...
27,http://www.imdb.com/title/tt0004465/,1914,http://www.imdb.com/name/nm0925310,1,United States,1889,Female,NaN,Pearl White,35,...,0,6,58,NaN,17.0,29 Female 27 Male 28 Male Name: h...,3,1,0.333333,27 United States 28 United States 29 ...
28,http://www.imdb.com/title/tt0004465/,1914,http://www.imdb.com/name/nm0928108,89,United States,1886,Male,1.78,Crane Wilbur,9,...,0,6,58,3.0,17.0,29 Female 27 Male 28 Male Name: h...,3,1,0.333333,27 United States 28 United States 29 ...
29,http://www.imdb.com/title/tt0004465/,1914,http://www.imdb.com/name/nm0659947,394,Germany,1872,Male,1.79,Paul Panzer,14,...,0,6,58,14.0,17.0,29 Female 27 Male 28 Male Name: h...,3,1,0.333333,27 United States 28 United States 29 ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,http://www.imdb.com/title/tt0009150/,1918,http://www.imdb.com/name/nm0001273,1,United States,1893,Female,1.63,Lillian Gish,84,...,4,55,117,5.0,37.0,70 Female 71 Female 69 Male Name: h...,3,2,0.666667,69 United States 70 United States 71 ...
71,http://www.imdb.com/title/tt0009150/,1918,http://www.imdb.com/name/nm0504551,77,United States,1861,Male,NaN,Adolph Lestina,1,...,4,55,117,32.0,37.0,70 Female 71 Female 69 Male Name: h...,3,2,0.666667,69 United States 70 United States 71 ...
72,http://www.imdb.com/title/tt0009611/,1918,http://www.imdb.com/name/nm0701012,1,United States,1895,Female,1.57,Edna Purviance,9,...,108,33,306,NaN,10.0,73 Female 72 Male 74 Male Name: h...,3,1,0.333333,72 United States 73 United Kingdom 74 ...
73,http://www.imdb.com/title/tt0009611/,1918,http://www.imdb.com/name/nm0000122,87,United Kingdom,1889,Male,1.65,Charles Chaplin,275,...,108,33,306,6.0,10.0,73 Female 72 Male 74 Male Name: h...,3,1,0.333333,72 United States 73 United Kingdom 74 ...
74,http://www.imdb.com/title/tt0009611/,1918,http://www.imdb.com/name/nm0152260,34,United Kingdom,1885,Male,1.71,Syd Chaplin,22,...,108,33,306,4.0,10.0,73 Female 72 Male 74 Male Name: h...,3,1,0.333333,72 United States 73 United Kingdom 74 ...
75,http://www.imdb.com/title/tt0009682/,1918,http://www.imdb.com/name/nm0548402,1,United States,1894,Female,1.64,Enid Markey,7,...,0,0,26,NaN,14.0,76 Female 75 Male 77 Male Name: h...,3,1,0.333333,75 United States 76 United States 77 ...
76,http://www.imdb.com/title/tt0009682/,1918,http://www.imdb.com/name/nm0511104,81,United States,1889,Male,1.82,Elmo Lincoln,13,...,0,0,26,5.0,14.0,76 Female 75 Male 77 Male Name: h...,3,1,0.333333,75 United States 76 United States 77 ...
77,http://www.imdb.com/title/tt0009682/,1918,http://www.imdb.com/name/nm0090204,164,United States,1880,Male,NaN,True Boardman,6,...,0,0,26,9.0,14.0,76 Female 75 Male 77 Male Name: h...,3,1,0.333333,75 United States 76 United States 77 ...
78,http://www.imdb.com/title/tt0009878/,1919,http://www.imdb.com/name/nm0891998,119,Germany,1893,Male,1.89,Conrad Veidt,20,...,4,3,20,NaN,33.0,78 Male 79 Female 80 Male Name: h...,3,1,0.333333,78 Germany 79 None 80...
79,http://www.imdb.com/title/tt0009878/,1919,http://www.imdb.com/name/nm0903095,1,None,1874,Female,NaN,Ilse von Tasso-Lind,0,...,4,3,20,19.0,33.0,78 Male 79 Female 80 Male Name: h...,3,1,0.333333,78 Germany 79 None 80...
80,http://www.imdb.com/title/tt0009878/,1919,http://www.imdb.com/name/nm0174925,36,Austrian Empire,1860,Male,NaN,Leo Connard,0,...,4,3,20,14.0,33.0,78 Male 79 Female 80 Male Name: h...,3,1,0.333333,78 Germany 79 None 80...
81,http://www.imdb.com/title/tt0009892/,1919,http://www.imdb.com/name/nm0546295,1,Turkey,1901,Female,NaN,Aurora Mardiganian,3,...,97,14,47,NaN,13.0,83 Female 81 Female 82 Male Name: h...,3,2,0.666667,81 Turkey 82 Sweden 83 ...
82,http://www.imdb.com/title/tt0009892/,1919,http://www.imdb.com/name/nm0632160,1,Sweden,1888,Female,1.70,Anna Q. Nilsson,28,...,97,14,47,13.0,13.0,83 Female 81 Female 82 Male Name: h...,3,2,0.666667,81 Turkey 82 Sweden 83 ...
83,http://www.imdb.com/title/tt0009892/,1919,http://www.imdb.com/name/nm0191899,148,United States,1888,Male,NaN,Irving Cummings,16,...,97,14,47,0.0,13.0,83 Female 81 Female 82 Male Name: h...,3,2,0.666667,81 Turkey 82 Sweden 83 ...
84,http://www.imdb.com/title/tt0009900/,1919,http://www.imdb.com/name/nm0794109,1,Canada,1892,Female,NaN,Nell Shipman,18,...,15,3,31,NaN,12.0,84 Female 86 Male 85 Male Name: h...,3,1,0.333333,84 Canada 85 United States 86 ...
85,http://www.imdb.com/title/tt0009900/,1919,http://www.imdb.com/name/nm0643048,287,United States,1890,Male,1.80,Wheeler Oakman,11,...,15,3,31,2.0,12.0,84 Female 86 Male 85 Male Name: h...,3,1,0.333333,84 Canada 85 United States 86 ...
86,http://www.imdb.com/title/tt0009900/,1919,http://www.imdb.com/name/nm0035187,131,Canada,1880,Male,NaN,Charles Arling,2,...,15,3,31,10.0,12.0,84 Female 86 Male 85 Male Name: h...,3,1,0.333333,84 Canada 85 United States 86 ...
87,http://www.imdb.com/title/tt0009937/,1919,http://www.imdb.com/name/nm0082537,1,United States,1895,Female,1.70,Francelia Billington,11,...,16,9,56,NaN,20.0,89 Female 87 Male 88 Male Name: h...,3,1,0.333333,87 United States 88 AustriaHungary 89 ...
88,http://www.imdb.com/title/tt0009937/,1919,http://www.imdb.com/name/nm0002233,74,AustriaHungary,1885,Male,1.68,Erich von Stroheim,42,...,16,9,56,10.0,20.0,89 Female 87 Male 88 Male Name: h...,3,1,0.333333,87 United States 88 AustriaHungary 89 ...
89,http://www.imdb.com/title/tt0009937/,1919,http://www.imdb.com/name/nm0208659,120,Canada,1875,Male,1.79,Sam De Grasse,3,...,16,9,56,10.0,20.0,89 Female 87 Male 88 Male Name: h...,3,1,0.333333,87 United States 88 AustriaHungary 89 ...
90,http://www.imdb.com/title/tt0009968/,1919,http://www.imdb.com/name/nm0001932,80,United States,1895,Male,1.75,Richard Barthelmess,33,...,75,71,138,NaN,13.0,90 Male 91 Female 92 Male Name: h...,3,1,0.333333,90 United States 91 United States 92 ...
91,http://www.imdb.com/title/tt0009968/,1919,http://www.imdb.com/name/nm0001273,1,United States,1893,Female,1.63,Lillian Gish,84,...,75,71,138,2.0,13.0,90 Male 91 Female 92 Male Name: h...,3,1,0.333333,90 United States 91 United States 92 ...
92,http://www.imdb.com/title/tt0009968/,1919,http://www.imdb.com/name/nm0187981,172,United Kingdom,1882,Male,1.74,Donald Crisp,21,...,75,71,138,11.0,13.0,90 Male 91 Female 92 Male Name: h...,3,1,0.333333,90 United States 91 United States 92 ...
93,http://www.imdb.com/title/tt0009976/,1919,http://www.imdb.com/name/nm0601067,1,United States,1899,Female,1.60,Colleen Moore,37,...,19,41,144,NaN,8.0,95 Female 94 Male 93 Male Name: h...,3,1,0.333333,93 United States 94 United States 95 ...
94,http://www.imdb.com/title/tt0009976/,1919,http://www.imdb.com/name/nm0318105,99,United States,1897,Male,1.80,John Gilbert,50,...,19,41,144,2.0,8.0,95 Female 94 Male 93 Male Name: h...,3,1,0.333333,93 United States 94 United States 95 ...
95,http://www.imdb.com/title/tt0009976/,1919,http://www.imdb.com/name/nm0712776,174,United States,1891,Male,NaN,Charles Ray,57,...,19,41,144,6.0,8.0,95 Female 94 Male 93 Male Name: h...,3,1,0.333333,93 United States 94 United States 95 ...
96,http://www.imdb.com/title/tt0010247/,1919,http://www.imdb.com/name/nm0526234,74,Sweden,1885,Male,NaN,Richard Lund,0,...,6,0,0,NaN,11.0,96 Male 97 Male 98 Male Name: http://...,3,0,0.000000,96 Sweden 97 Sweden 98 Sweden Name: h...
97,http://www.imdb.com/title/tt0010247/,1919,http://www.imdb.com/name/nm0830862,4,Sweden,1878,Male,NaN,Erik Stocklassa,0,...,6,0,0,7.0,11.0,96 Male 97 Male 98 Male Name: http://...,3,0,0.000000,96 Sweden 97 Sweden 98 Sweden Name: h...
98,http://www.imdb.com/title/tt0010247/,1919,http://www.imdb.com/name/nm0074129,24,Sweden,1874,Male,NaN,Bror Berger,0,...,6,0,0,4.0,11.0,96 Male 97 Male 98 Male Name: http://...,3,0,0.000000,96 Sweden 97 Sweden 98 Sweden Name: h...
99,http://www.imdb.com/title/tt0010281/,1918,http://www.imdb.com/name/nm0652661,1,Germany,1897,Female,NaN,Ossi Oswalda,0,...,5,1,1,NaN,32.0,99 Female 101 Male 100 Male Name...,3,1,0.333333,99 Germany 100 Germany 101 Germany N...

In [872]:
adding_stars['Gender Star'].isnull().sum()

71

In [875]:
adding_stars['Star Counter'].value_counts()

3    88818
2      231
1       22
0        4
Name: Star Counter, dtype: int64

In [880]:
adding_stars['Share of Female Stars'] = adding_stars['Number of Female Stars'].divide(adding_stars['Star Counter'])

In [882]:
adding_stars['Share of Female Stars'].value_counts()

0.333333    49104
0.666667    19383
0.000000    17896
1.000000     2576
0.500000      112
Name: Share of Female Stars, dtype: int64

In [905]:
adding_stars.head()

,ID,Year,Star_URL,Acting Roles Star,Birth Country Star,Birthyear Star,Gender Star,Height Star,Name Star,Publicity Listings Star,...,TV Appearances Stars Cumulative,Publicity Listings Stars Cumulative,Age Differences Stars,Sum of Age Differences Stars,Genders of Stars,Gender Value Counter,Number of Female Stars,Share of Female Stars,Country Diversity Actors,Country Value Counter
0,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0209738,16,Italy,1869,Male,NaN,Giuseppe de Liguoro,0,...,0,0,NaN,0.0,0 Male 1 Male 2 Male Name: http://www...,3,0,0.000000,0 Italy 1 None 2 None Name: http://...,1
1,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0685283,6,None,0,Male,NaN,Arturo Pirovano,0,...,0,0,NaN,0.0,0 Male 1 Male 2 Male Name: http://www...,3,0,0.000000,0 Italy 1 None 2 None Name: http://...,1
2,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0660139,15,None,0,Male,NaN,Salvatore Papa,0,...,0,0,NaN,0.0,0 Male 1 Male 2 Male Name: http://www...,3,0,0.000000,0 Italy 1 None 2 None Name: http://...,1
3,http://www.imdb.com/title/tt0002423/,1919,http://www.imdb.com/name/nm0624470,1,Poland,1897,Female,1.52,Pola Negri,69,...,12,79,NaN,15.0,5 Female 4 Male 3 Male Name: http...,3,1,0.333333,3 Poland 4 Switzerland 5 Ru...,3
4,http://www.imdb.com/title/tt0002423/,1919,http://www.imdb.com/name/nm0417837,82,Switzerland,1884,Male,1.83,Emil Jannings,8,...,12,79,13.0,15.0,5 Female 4 Male 3 Male Name: http...,3,1,0.333333,3 Poland 4 Switzerland 5 Ru...,3

In [904]:
adding_stars['Country Value Counter'] = adding_stars[
    'Birth Country Star'].groupby(adding_stars['ID']).transform('count')

In [888]:
adding_stars['Countries of Stars'] = adding_stars[
    'Birth Country Star'].groupby(adding_stars['ID']).transform(lambda x: [x])

In [908]:
country_stars_counting = adding_stars['Countries of Stars']

In [909]:
country_stars_counting[0][0]

'Italy'

In [917]:
star_country_set = []
for i in country_stars_counting:
    counter = 0
    items = []
    for g in i:
        if g != None:
            items.append(g)
            counter+=1
    star_country_set.append(items)
star_country_set

[['Italy'],
 ['Italy'],
 ['Italy'],
 ['Poland', 'Switzerland', 'Russia'],
 ['Poland', 'Switzerland', 'Russia'],
 ['Poland', 'Switzerland', 'Russia'],
 ['France', 'United Kingdom', 'France'],
 ['France', 'United Kingdom', 'France'],
 ['France', 'United Kingdom', 'France'],
 ['France', 'United Kingdom', 'France'],
 ['France', 'United Kingdom', 'France'],
 ['France', 'United Kingdom', 'France'],
 ['France', 'United Kingdom', 'France'],
 ['France', 'United Kingdom', 'France'],
 ['France', 'United Kingdom', 'France'],
 ['AustriaHungary', 'Czech Republic', 'Poland'],
 ['AustriaHungary', 'Czech Republic', 'Poland'],
 ['AustriaHungary', 'Czech Republic', 'Poland'],
 ['Italy', 'Italy', 'Italy'],
 ['Italy', 'Italy', 'Italy'],
 ['Italy', 'Italy', 'Italy'],
 ['Canada', 'Ireland'],
 ['Canada', 'Ireland'],
 ['Canada', 'Ireland'],
 ['AustriaHungary', 'AustriaHungary', 'Poland'],
 ['AustriaHungary', 'AustriaHungary', 'Poland'],
 ['AustriaHungary', 'AustriaHungary', 'Poland'],
 ['United States', 'United States', 'Germany'],
 ['United States', 'United States', 'Germany'],
 ['United States', 'United States', 'Germany'],
 ['United Kingdom', 'United States', 'United States'],
 ['United Kingdom', 'United States', 'United States'],
 ['United Kingdom', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United Kingdom', 'Sweden', 'Canada'],
 ['United Kingdom', 'Sweden', 'Canada'],
 ['United Kingdom', 'Sweden', 'Canada'],
 ['France', 'Australia', 'France'],
 ['France', 'Australia', 'France'],
 ['France', 'Australia', 'France'],
 ['United States'],
 ['United States'],
 ['United States'],
 ['United States', 'United Kingdom', 'United States'],
 ['United States', 'United Kingdom', 'United States'],
 ['United States', 'United Kingdom', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['France', 'France', 'France'],
 ['France', 'France', 'France'],
 ['France', 'France', 'France'],
 ['Canada', 'United States', 'United States'],
 ['Canada', 'United States', 'United States'],
 ['Canada', 'United States', 'United States'],
 ['Canada', 'United States', 'Ireland'],
 ['Canada', 'United States', 'Ireland'],
 ['Canada', 'United States', 'Ireland'],
 ['Canada', 'United States', 'United States'],
 ['Canada', 'United States', 'United States'],
 ['Canada', 'United States', 'United States'],
 ['Finland', 'Sweden', 'Sweden'],
 ['Finland', 'Sweden', 'Sweden'],
 ['Finland', 'Sweden', 'Sweden'],
 ['United States', 'Norway'],
 ['United States', 'Norway'],
 ['United States', 'Norway'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United Kingdom', 'United Kingdom'],
 ['United States', 'United Kingdom', 'United Kingdom'],
 ['United States', 'United Kingdom', 'United Kingdom'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['Germany', 'Austrian Empire'],
 ['Germany', 'Austrian Empire'],
 ['Germany', 'Austrian Empire'],
 ['Turkey', 'Sweden', 'United States'],
 ['Turkey', 'Sweden', 'United States'],
 ['Turkey', 'Sweden', 'United States'],
 ['Canada', 'United States', 'Canada'],
 ['Canada', 'United States', 'Canada'],
 ['Canada', 'United States', 'Canada'],
 ['United States', 'AustriaHungary', 'Canada'],
 ['United States', 'AustriaHungary', 'Canada'],
 ['United States', 'AustriaHungary', 'Canada'],
 ['United States', 'United States', 'United Kingdom'],
 ['United States', 'United States', 'United Kingdom'],
 ['United States', 'United States', 'United Kingdom'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['Sweden', 'Sweden', 'Sweden'],
 ['Sweden', 'Sweden', 'Sweden'],
 ['Sweden', 'Sweden', 'Sweden'],
 ['Germany', 'Germany', 'Germany'],
 ['Germany', 'Germany', 'Germany'],
 ['Germany', 'Germany', 'Germany'],
 ['France', 'France', 'France'],
 ['France', 'France', 'France'],
 ['France', 'France', 'France'],
 ['Germany', 'AustriaHungary', 'Germany'],
 ['Germany', 'AustriaHungary', 'Germany'],
 ['Germany', 'AustriaHungary', 'Germany'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['Germany', 'AustriaHungary', 'Russian Empire'],
 ['Germany', 'AustriaHungary', 'Russian Empire'],
 ['Germany', 'AustriaHungary', 'Russian Empire'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['Italy', 'Germany', 'Poland'],
 ['Italy', 'Germany', 'Poland'],
 ['Italy', 'Germany', 'Poland'],
 ['United States', 'United States', 'United Kingdom'],
 ['United States', 'United States', 'United Kingdom'],
 ['United States', 'United States', 'United Kingdom'],
 ['Sweden', 'Sweden', 'Sweden'],
 ['Sweden', 'Sweden', 'Sweden'],
 ['Sweden', 'Sweden', 'Sweden'],
 ['Poland', 'United States', 'Lithuania'],
 ['Poland', 'United States', 'Lithuania'],
 ['Poland', 'United States', 'Lithuania'],
 ['AustriaHungary', 'Poland', 'Germany'],
 ['AustriaHungary', 'Poland', 'Germany'],
 ['AustriaHungary', 'Poland', 'Germany'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'France', 'United States'],
 ['United States', 'France', 'United States'],
 ['United States', 'France', 'United States'],
 ['Sweden', 'Sweden'],
 ['Sweden', 'Sweden'],
 ['Sweden', 'Sweden'],
 ['Italy', 'Germany', 'Poland'],
 ['Italy', 'Germany', 'Poland'],
 ['Italy', 'Germany', 'Poland'],
 ['Poland', 'Germany', 'Poland'],
 ['Poland', 'Germany', 'Poland'],
 ['Poland', 'Germany', 'Poland'],
 ['United States', 'United States'],
 ['United States', 'United States'],
 ['United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['Poland', 'Germany', 'Russian Empire'],
 ['Poland', 'Germany', 'Russian Empire'],
 ['Poland', 'Germany', 'Russian Empire'],
 ['United States', 'Italy', 'United States'],
 ['United States', 'Italy', 'United States'],
 ['United States', 'Italy', 'United States'],
 ['United States', 'United States', 'United Kingdom'],
 ['United States', 'United States', 'United Kingdom'],
 ['United States', 'United States', 'United Kingdom'],
 ['Sweden', 'Sweden', 'Sweden'],
 ['Sweden', 'Sweden', 'Sweden'],
 ['Sweden', 'Sweden', 'Sweden'],
 ['Germany', 'Indonesia', 'Germany'],
 ['Germany', 'Indonesia', 'Germany'],
 ['Germany', 'Indonesia', 'Germany'],
 ['United States', 'AustriaHungary', 'United States'],
 ['United States', 'AustriaHungary', 'United States'],
 ['United States', 'AustriaHungary', 'United States'],
 ['Germany', 'AustriaHungary'],
 ['Germany', 'AustriaHungary'],
 ['Germany', 'AustriaHungary'],
 ['United States', 'United States', 'Italy'],
 ['United States', 'United States', 'Italy'],
 ['United States', 'United States', 'Italy'],
 ['United States', 'United States', 'United Kingdom'],
 ['United States', 'United States', 'United Kingdom'],
 ['United States', 'United States', 'United Kingdom'],
 ['United States', 'Italy', 'United States'],
 ['United States', 'Italy', 'United States'],
 ['United States', 'Italy', 'United States'],
 ['Italy', 'United States', 'Russian Empire'],
 ['Italy', 'United States', 'Russian Empire'],
 ['Italy', 'United States', 'Russian Empire'],
 ['Germany', 'Norway', 'Germany'],
 ['Germany', 'Norway', 'Germany'],
 ['Germany', 'Norway', 'Germany'],
 ['United States', 'United States', 'Germany'],
 ['United States', 'United States', 'Germany'],
 ['United States', 'United States', 'Germany'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['Germany', 'Ukraine', 'Germany'],
 ['Germany', 'Ukraine', 'Germany'],
 ['Germany', 'Ukraine', 'Germany'],
 ['Norway', 'Germany', 'AustriaHungary'],
 ['Norway', 'Germany', 'AustriaHungary'],
 ['Norway', 'Germany', 'AustriaHungary'],
 ['Australia', 'United States', 'Canada'],
 ['Australia', 'United States', 'Canada'],
 ['Australia', 'United States', 'Canada'],
 ['United States', 'Ukraine', 'United Kingdom'],
 ['United States', 'Ukraine', 'United Kingdom'],
 ['United States', 'Ukraine', 'United Kingdom'],
 ['Ukraine', 'Russia'],
 ['Ukraine', 'Russia'],
 ['Ukraine', 'Russia'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['Sweden', 'Sweden', 'Sweden'],
 ['Sweden', 'Sweden', 'Sweden'],
 ['Sweden', 'Sweden', 'Sweden'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'France', 'United States'],
 ['United States', 'France', 'United States'],
 ['United States', 'France', 'United States'],
 ['Germany', 'Germany', 'Switzerland'],
 ['Germany', 'Germany', 'Switzerland'],
 ['Germany', 'Germany', 'Switzerland'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'Canada'],
 ['United States', 'United States', 'Canada'],
 ['United States', 'United States', 'Canada'],
 ['Russian Empire', 'Russian Empire', 'Russian Empire'],
 ['Russian Empire', 'Russian Empire', 'Russian Empire'],
 ['Russian Empire', 'Russian Empire', 'Russian Empire'],
 ['United States', 'United States', 'United Kingdom'],
 ['United States', 'United States', 'United Kingdom'],
 ['United States', 'United States', 'United Kingdom'],
 ['Canada', 'United States', 'United States'],
 ['Canada', 'United States', 'United States'],
 ['Canada', 'United States', 'United States'],
 ['France', 'France'],
 ['France', 'France'],
 ['France', 'France'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['Germany', 'Switzerland'],
 ['Germany', 'Switzerland'],
 ['Germany', 'Switzerland'],
 ['AustriaHungary', 'Italy', 'Germany'],
 ['AustriaHungary', 'Italy', 'Germany'],
 ['AustriaHungary', 'Italy', 'Germany'],
 ['United States', 'United States', 'Canada'],
 ['United States', 'United States', 'Canada'],
 ['United States', 'United States', 'Canada'],
 ['Germany', 'Germany', 'Poland'],
 ['Germany', 'Germany', 'Poland'],
 ['Germany', 'Germany', 'Poland'],
 ['Germany', 'AustriaHungary', 'Germany'],
 ['Germany', 'AustriaHungary', 'Germany'],
 ['Germany', 'AustriaHungary', 'Germany'],
 ['Belarus', 'Germany'],
 ['Belarus', 'Germany'],
 ['Belarus', 'Germany'],
 ['United States', 'United Kingdom'],
 ['United States', 'United Kingdom'],
 ['United States', 'United Kingdom'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'AustriaHungary'],
 ['United States', 'United States', 'AustriaHungary'],
 ['United States', 'United States', 'AustriaHungary'],
 ['France', 'United States', 'United States'],
 ['France', 'United States', 'United States'],
 ['France', 'United States', 'United States'],
 ['Russian Empire', 'Russian Empire'],
 ['Russian Empire', 'Russian Empire'],
 ['Russian Empire', 'Russian Empire'],
 ['AustriaHungary', 'Italy', 'United States'],
 ['AustriaHungary', 'Italy', 'United States'],
 ['AustriaHungary', 'Italy', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United Kingdom', 'United States', 'United States'],
 ['United Kingdom', 'United States', 'United States'],
 ['United Kingdom', 'United States', 'United States'],
 ['United States', 'Denmark', 'United Kingdom'],
 ['United States', 'Denmark', 'United Kingdom'],
 ['United States', 'Denmark', 'United Kingdom'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United Kingdom'],
 ['United States', 'United States', 'United Kingdom'],
 ['United States', 'United States', 'United Kingdom'],
 ['United States', 'United States', 'United Kingdom'],
 ['United States', 'United States', 'United Kingdom'],
 ['United States', 'United States', 'United Kingdom'],
 ['Australia', 'Ireland', 'United States'],
 ['Australia', 'Ireland', 'United States'],
 ['Australia', 'Ireland', 'United States'],
 ['Germany', 'Slovakia', 'Switzerland'],
 ['Germany', 'Slovakia', 'Switzerland'],
 ['Germany', 'Slovakia', 'Switzerland'],
 ['France', 'France'],
 ['France', 'France'],
 ['France', 'France'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['Australia', 'United States', 'United Kingdom'],
 ['Australia', 'United States', 'United Kingdom'],
 ['Australia', 'United States', 'United Kingdom'],
 ['United States', 'Mexico', 'United States'],
 ['United States', 'Mexico', 'United States'],
 ['United States', 'Mexico', 'United States'],
 ['United States', 'United Kingdom', 'United States'],
 ['United States', 'United Kingdom', 'United States'],
 ['United States', 'United Kingdom', 'United States'],
 ['France', 'Ireland', 'United States'],
 ['France', 'Ireland', 'United States'],
 ['France', 'Ireland', 'United States'],
 ['France', 'United States', 'United States'],
 ['France', 'United States', 'United States'],
 ['France', 'United States', 'United States'],
 ['United States', 'United States', 'Canada'],
 ['United States', 'United States', 'Canada'],
 ['United States', 'United States', 'Canada'],
 ['United States', 'United States', 'Sweden'],
 ['United States', 'United States', 'Sweden'],
 ['United States', 'United States', 'Sweden'],
 ['Germany', 'Sweden', 'Switzerland'],
 ['Germany', 'Sweden', 'Switzerland'],
 ['Germany', 'Sweden', 'Switzerland'],
 ['Sweden', 'United States', 'Sweden'],
 ['Sweden', 'United States', 'Sweden'],
 ['Sweden', 'United States', 'Sweden'],
 ['Japan', 'Japan'],
 ['Japan', 'Japan'],
 ['Japan', 'Japan'],
 ['United Kingdom', 'United Kingdom', 'United Kingdom'],
 ['United Kingdom', 'United Kingdom', 'United Kingdom'],
 ['United Kingdom', 'United Kingdom', 'United Kingdom'],
 ['Germany', 'Germany', 'Germany'],
 ['Germany', 'Germany', 'Germany'],
 ['Germany', 'Germany', 'Germany'],
 ['France', 'France', 'France'],
 ['France', 'France', 'France'],
 ['France', 'France', 'France'],
 ['AustriaHungary', 'Italy', 'United States'],
 ['AustriaHungary', 'Italy', 'United States'],
 ['AustriaHungary', 'Italy', 'United States'],
 ['Sweden', 'Spain', 'Australia'],
 ['Sweden', 'Spain', 'Australia'],
 ['Sweden', 'Spain', 'Australia'],
 ['United States', 'United States', 'Netherlands'],
 ['United States', 'United States', 'Netherlands'],
 ['United States', 'United States', 'Netherlands'],
 ['Sweden', 'United States', 'United States'],
 ['Sweden', 'United States', 'United States'],
 ['Sweden', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'AustriaHungary', 'United Kingdom'],
 ['United States', 'AustriaHungary', 'United Kingdom'],
 ['United States', 'AustriaHungary', 'United Kingdom'],
 ['United States', 'Germany', 'United States'],
 ['United States', 'Germany', 'United States'],
 ['United States', 'Germany', 'United States'],
 ['United States', 'Ireland', 'United Kingdom'],
 ['United States', 'Ireland', 'United Kingdom'],
 ['United States', 'Ireland', 'United Kingdom'],
 ['United Kingdom', 'United States', 'United States'],
 ['United Kingdom', 'United States', 'United States'],
 ['United Kingdom', 'United States', 'United States'],
 ['United Kingdom', 'United Kingdom', 'United Kingdom'],
 ['United Kingdom', 'United Kingdom', 'United Kingdom'],
 ['United Kingdom', 'United Kingdom', 'United Kingdom'],
 ['United Kingdom', 'United Kingdom', 'United Kingdom'],
 ['United Kingdom', 'United Kingdom', 'United Kingdom'],
 ['United Kingdom', 'United Kingdom', 'United Kingdom'],
 ['United States', 'United States'],
 ['United States', 'United States'],
 ['United States', 'United States'],
 ['United States', 'Spain', 'British Guiana'],
 ['United States', 'Spain', 'British Guiana'],
 ['United States', 'Spain', 'British Guiana'],
 ['United States', 'Lithuania', 'Sweden'],
 ['United States', 'Lithuania', 'Sweden'],
 ['United States', 'Lithuania', 'Sweden'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['Australia', 'United Kingdom', 'United Kingdom'],
 ['Australia', 'United Kingdom', 'United Kingdom'],
 ['Australia', 'United Kingdom', 'United Kingdom'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],
 ['France', 'France', 'France'],
 ['France', 'France', 'France'],
 ['France', 'France', 'France'],
 ['Russian Empire'],
 ['Russian Empire'],
 ['Russian Empire'],
 ['South Africa', 'United Kingdom', 'Denmark'],
 ['South Africa', 'United Kingdom', 'Denmark'],
 ['South Africa', 'United Kingdom', 'Denmark'],
 ['United States', 'United States', 'United States'],
 ['United States', 'United States', 'United States'],

In [918]:
diversity_countries = []
for c in star_country_set:
    diversity_countries.append(len(set(c)))
diversity_countries

[1,
 1,
 1,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 3,
 3,
 3,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 3,
 3,
 3,
 2,
 2,
 2,
 3,
 3,
 3,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 3,
 3,
 3,
 1,
 1,
 1,
 3,
 3,
 3,
 2,
 2,
 2,
 1,
 1,
 1,
 3,
 3,
 3,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 3,
 3,
 3,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 3,
 3,
 3,
 2,
 2,
 2,
 3,
 3,
 3,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 3,
 3,
 3,
 3,
 3,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 3,
 3,
 1,
 1,
 1,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 3,
 3,
 3,
 2,
 2,
 2,
 1,
 1,
 1,
 3,
 3,
 3,
 2,
 2,
 2,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 3,
 3,
 2,
 2,
 2,
 1,
 1,
 1,
 3,
 3,
 3,
 3,
 3,
 3,
 1,
 1,
 1,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 3,
 3,
 3,
 3,
 3,
 1,
 1,
 1,
 3,
 3,
 3,
 2,
 2,
 2,
 0,
 0,
 0,
 1,
 1,
 1,
 3,
 3,
 3,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 3,
 3,
 3,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 3,
 3,
 3,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 3,
 3,
 3,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 3,
 3,
 3,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 3,
 3,
 3,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 3,
 3,
 2,
 2,
 2,
 3,
 3,
 3,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 3,
 3,
 3,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 3,
 3,
 3,
 1,
 1,
 1,
 3,
 3,
 3,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 ...]

In [919]:
len(diversity_countries)

89075

In [920]:
adding_stars['Number of Different Countries Stars'] = diversity_countries

In [921]:
adding_stars.sample(50)

,ID,Year,Star_URL,Acting Roles Star,Birth Country Star,Birthyear Star,Gender Star,Height Star,Name Star,Publicity Listings Star,...,Publicity Listings Stars Cumulative,Age Differences Stars,Sum of Age Differences Stars,Genders of Stars,Gender Value Counter,Number of Female Stars,Share of Female Stars,Countries of Stars,Country Value Counter,Number of Different Countries Stars
66580,http://www.imdb.com/title/tt1485763/,2009,http://www.imdb.com/name/nm1215197,81,United States,1973,Male,NaN,Christopher Bevins,0,...,0,13.0,34.0,66579 Female 66580 Male 66581 Mal...,3,1,0.333333,66579 United States 66580 United States ...,3,1
42946,http://www.imdb.com/title/tt0245501/,2001,http://www.imdb.com/name/nm0022393,1,None,0,Female,NaN,Aria Alpert Adjani,0,...,4,NaN,7.0,42945 Male 42946 Female 42944 Femal...,3,2,0.666667,42944 United States 42945 United States ...,2,1
55443,http://www.imdb.com/title/tt0481610/,2005,http://www.imdb.com/name/nm0005528,34,Canada,1975,Male,1.75,Scott Vickaryous,1,...,8,7.0,9.0,55441 Female 55442 Female 55443 Mal...,3,2,0.666667,55441 United States 55442 United States ...,3,2
13712,http://www.imdb.com/title/tt0063374/,1968,http://www.imdb.com/name/nm0275835,193,United States,1925,Male,1.63,John Fiedler,6,...,66,NaN,5.0,13713 Male 13714 Male 13712 Male Name...,3,0,0.000000,13712 United States 13713 United States ...,3,1
42760,http://www.imdb.com/title/tt0242587/,2001,http://www.imdb.com/name/nm0004051,215,United Kingdom,1946,Male,1.71,Brian Cox,10,...,15,9.0,38.0,42759 Male 42760 Male 42758 Male Name...,3,0,0.000000,42758 United States 42759 United State...,3,2
56975,http://www.imdb.com/title/tt0795505/,2007,http://www.imdb.com/name/nm0027520,20,None,0,Male,NaN,Todd Anderson,0,...,0,NaN,0.0,56974 Male 56975 Male 56976 Male Name...,3,0,0.000000,56974 None 56975 None 56976 None Name...,0,0
83999,http://www.imdb.com/title/tt4176826/,2015,http://www.imdb.com/name/nm0557908,32,Germany,1968,Male,1.87,Oliver Masucci,0,...,0,NaN,0.0,83999 Male 84000 Male 84001 Male Name...,3,0,0.000000,83999 Germany 84000 None 84001 ...,1,1
87124,http://www.imdb.com/title/tt5376196/,2017,http://www.imdb.com/name/nm1514571,1,Austria,1972,Female,NaN,Pia Hierzegger,0,...,0,NaN,10.0,87124 Female 87125 Male 87126 Mal...,3,1,0.333333,87124 Austria 87125 Germany 87126 Aus...,3,2
23301,http://www.imdb.com/title/tt0086978/,1984,http://www.imdb.com/name/nm0098733,53,United States,1954,Male,1.83,Joseph Bottoms,2,...,50,NaN,4.0,23302 Male 23301 Female 23303 Mal...,3,1,0.333333,23301 United States 23302 United States ...,3,1
501,http://www.imdb.com/title/tt0019098/,1928,http://www.imdb.com/name/nm0000011,117,United States,1901,Male,1.88,Gary Cooper,51,...,93,NaN,33.0,503 Male 502 Female 501 Female Name...,3,2,0.666667,501 United States 502 United States 503 ...,3,1
4952,http://www.imdb.com/title/tt0039887/,1947,http://www.imdb.com/name/nm0919321,38,Romania,1904,Male,1.91,Johnny Weissmuller,21,...,40,13.0,27.0,4952 Male 4950 Female 4951 Male N...,3,1,0.333333,4950 United States 4951 United States 49...,3,2
62712,http://www.imdb.com/title/tt1205489/,2008,http://www.imdb.com/name/nm0000142,70,United States,1930,Male,1.93,Clint Eastwood,208,...,209,48.0,61.0,62710 Male 62712 Male 62711 Male Name...,3,0,0.000000,62710 United States 62711 United States ...,3,1
38777,http://www.imdb.com/title/tt0144084/,2000,http://www.imdb.com/name/nm0857620,54,United States,1971,Male,1.75,Justin Theroux,10,...,97,0.0,3.0,38775 Male 38776 Male 38777 Male Name...,3,0,0.000000,38775 United Kingdom 38776 United State...,3,2
33393,http://www.imdb.com/title/tt0111666/,1994,http://www.imdb.com/name/nm0622543,1,None,0,Male,NaN,Darragh Naughton,0,...,0,NaN,0.0,33391 Male 33392 Male 33393 Male Name...,3,0,0.000000,33391 Ireland 33392 None 33393 ...,1,1
4881,http://www.imdb.com/title/tt0039677/,1947,http://www.imdb.com/name/nm0159258,138,South Africa,1910,Male,NaN,Cyril Cusack,2,...,49,NaN,5.0,4882 Male 4881 Male 4883 Male Name: h...,3,0,0.000000,4881 South Africa 4882 United Kingdom ...,3,2
34084,http://www.imdb.com/title/tt0113682/,1996,http://www.imdb.com/name/nm0001101,93,United States,1947,Male,1.89,Ted Danson,24,...,59,18.0,34.0,34083 Female 34085 Male 34084 Mal...,3,1,0.333333,34083 United Kingdom 34084 United State...,3,2
58017,http://www.imdb.com/title/tt0848537/,2013,http://www.imdb.com/name/nm1242688,48,United States,1992,Male,1.70,Josh Hutcherson,4,...,267,NaN,11.0,58018 Male 58017 Female 58019 Femal...,3,2,0.666667,58017 United States 58018 United States ...,3,1
26592,http://www.imdb.com/title/tt0094641/,1989,http://www.imdb.com/name/nm1771790,1,None,0,Male,NaN,Francisco Martínez,0,...,0,NaN,1.0,26592 Female 26590 Male 26591 Mal...,3,1,0.333333,26590 Spain 26591 Spain 26592 None N...,2,1
73202,http://www.imdb.com/title/tt2048804/,2011,http://www.imdb.com/name/nm0411384,57,Japan,1950,Male,1.73,Tsutomu Isobe,0,...,0,17.0,23.0,73202 Female 73200 Female 73201 Mal...,3,2,0.666667,73200 United States 73201 Japan ...,3,2
25800,http://www.imdb.com/title/tt0092860/,1987,http://www.imdb.com/name/nm0493677,20,United States,1946,Male,1.83,John Lazar,0,...,31,15.0,17.0,25798 Female 25799 Male 25800 Mal...,3,1,0.333333,25798 United States 25799 United States ...,3,1
69771,http://www.imdb.com/title/tt1717229/,2010,http://www.imdb.com/name/nm4052349,1,None,0,Female,NaN,Claire Opperman,0,...,0,NaN,0.0,69769 Male 69770 Male 69771 Femal...,3,1,0.333333,69769 None 69770 None 69771 None Name...,0,0
33758,http://www.imdb.com/title/tt0112922/,1995,http://www.imdb.com/name/nm0029962,106,Spain,1953,Male,NaN,Álex Angulo,0,...,0,2.0,12.0,33757 Male 33756 Male 33758 Male Name...,3,0,0.000000,33756 Spain 33757 Italy 33758 Spain N...,3,2
30031,http://www.imdb.com/title/tt0102690/,1991,http://www.imdb.com/name/nm0908914,1,United States,1948,Female,1.63,Dee Wallace,2,...,4,5.0,15.0,30030 Female 30029 Male 30031 Femal...,3,2,0.666667,30029 United States 30030 United States ...,3,1
5751,http://www.imdb.com/title/tt0042338/,1950,http://www.imdb.com/name/nm0738746,1,United States,1922,Female,NaN,Ruth Roman,5,...,58,NaN,24.0,5753 Female 5752 Male 5751 Male N...,3,1,0.333333,5751 United States 5752 United States 57...,3,1
35516,http://www.imdb.com/title/tt0117581/,1996,http://www.imdb.com/name/nm0001356,146,United States,1953,Male,1.92,Hulk Hogan,33,...,50,1.0,29.0,35516 Male 35515 Female 35514 Mal...,3,1,0.333333,35514 United States 35515 United Kingdo...,3,2
70877,http://www.imdb.com/title/tt1807944/,2013,http://www.imdb.com/name/nm0290556,147,United States,1978,Male,1.80,James Franco,67,...,68,3.0,17.0,70876 Male 70878 Male 70877 Male Name...,3,0,0.000000,70876 United States 70877 United States ...,3,1
21837,http://www.imdb.com/title/tt0083276/,1981,http://www.imdb.com/name/nm0116339,69,Sweden,1947,Male,1.82,Ulf Brunnberg,0,...,6,NaN,15.0,21839 Male 21838 Male 21837 Male Name...,3,0,0.000000,21837 Sweden 21838 Sweden 21839 Fin...,3,2
50362,http://www.imdb.com/title/tt0387925/,2004,http://www.imdb.com/name/nm0875684,1,United States,1967,Female,NaN,Christine Tucci,1,...,12,27.0,29.0,50361 Female 50362 Female 50360 Femal...,3,3,1.000000,50360 United States 50361 United States ...,3,1
58209,http://www.imdb.com/title/tt0865496/,2006,http://www.imdb.com/name/nm1884816,1,Portuguese Macau,1988,Female,1.72,Isabella Leong,0,...,0,NaN,6.0,58211 Female 58210 Female 58209 Mal...,3,2,0.666667,58209 Portuguese Macau 58210 C...,2,2
87654,http://www.imdb.com/title/tt5699154/,2017,http://www.imdb.com/name/nm0500976,66,None,0,Male,NaN,Gilles Lellouche,0,...,3,NaN,16.0,87654 Male 87653 Male 87652 Male Name...,3,0,0.000000,87652 France 87653 Algeria 87654 ...,2,2
77710,http://www.imdb.com/title/tt2587914/,2014,http://www.imdb.com/name/nm0026789,29,United States,1952,Male,1.93,Harry Anderson,3,...,4,9.0,34.0,77709 Female 77710 Male 77708 Mal...,3,1,0.333333,77708 None 77709 United States ...,2,1
68756,http://www.imdb.com/title/tt1651065/,2010,http://www.imdb.com/name/nm3941826,1,None,0,Male,NaN,Gwynn Galitzer,0,...,5,NaN,0.0,68756 Male 68755 Male 68757 Male Name...,3,0,0.000000,68755 United States 68756 None ...,1,1
15302,http://www.imdb.com/title/tt0067321/,1971,http://www.imdb.com/name/nm0626219,1,Italy,1938,Female,1.70,Rosalba Neri,13,...,19,NaN,33.0,15302 Female 15303 Male 15304 Mal...,3,1,0.333333,15302 Italy 15303 Switzerland ...,3,3
58784,http://www.imdb.com/title/tt0907301/,2007,http://www.imdb.com/name/nm0486322,1,Argentina,0,Female,NaN,Verónica Langer,0,...,4,NaN,0.0,58782 Female 58783 Female 58784 Femal...,3,3,1.000000,58782 Mexico 58783 None 58784 ...,2,2
19545,http://www.imdb.com/title/tt0077868/,1978,http://www.imdb.com/name/nm0297143,43,Hong Kong,1954,Male,1.75,Sheng Fu,0,...,0,NaN,24.0,19547 Male 19546 Male 19545 Male Name...,3,0,0.000000,19545 Hong Kong 19546 China 19547 ...,3,2
56271,http://www.imdb.com/title/tt0499435/,2007,http://www.imdb.com/name/nm0432040,115,France,1951,Male,1.70,Gérard Jugnot,11,...,15,16.0,25.0,56269 Female 56270 Male 56271 Mal...,3,1,0.333333,56269 France 56270 France 56271 Franc...,3,1
8879,http://www.imdb.com/title/tt0051437/,1958,http://www.imdb.com/name/nm0445868,148,United States,1908,Male,1.88,Barry Kelley,0,...,54,10.0,20.0,8878 Male 8880 Male 8879 Male Name: h...,3,0,0.000000,8878 United States 8879 United States 88...,3,1
20966,http://www.imdb.com/title/tt0081480/,1980,http://www.imdb.com/name/nm0001301,65,United States,1935,Male,1.83,Charles Grodin,8,...,92,8.0,10.0,20964 Female 20965 Male 20966 Mal...,3,1,0.333333,20964 United States 20965 United States ...,3,1
86421,http://www.imdb.com/title/tt5071886/,2016,http://www.imdb.com/name/nm2331000,1,None,0,Female,NaN,Radhika Apte,0,...,1,NaN,10.0,86419 Male 86420 Male 86421 Femal...,3,1,0.333333,86419 Taiwan 86420 India 86421 Non...,2,2
10571,http://www.imdb.com/title/tt0055852/,1962,http://www.imdb.com/name/nm0100171,19,France,1930,Male,NaN,Antoine Bourseiller,1,...,1,7.0,18.0,10571 Female 10572 Male 10570 Femal...,3,2,0.666667,10570 France 10571 France 10572 Franc...,3,1
13264,http://www.imdb.com/title/tt0062168/,1967,http://www.imdb.com/name/nm0445139,118,United Kingdom,1926,Male,1.83,Andrew Keir,0,...,6,6.0,15.0,13264 Female 13265 Male 13263 Mal...,3,1,0.333333,13263 United Kingdom 13264 United Kingdo...,3,1
25168,http://www.imdb.com/title/tt0091415/,1986,http://www.imdb.com/name/nm0000223,1,United States,1963,Female,1.57,Elisabeth Shue,34,...,45,NaN,25.0,25168 Female 25169 Male 25170 Mal...,3,1,0.333333,25168 United States 25169 United Kingdo...,3,2
14709,http://www.imdb.com/title/tt0065895/,1969,http://www.imdb.com/name/nm0001023,79,United States,1929,Male,1.70,John Cassavetes,31,...,97,13.0,15.0,14710 Female 14708 Male 14709 Mal...,3,1,0.333333,14708 Sweden 14709 United States ...,3,2
49287,http://www.imdb.com/title/tt0371606/,2005,http://www.imdb.com/name/nm0000349,1,United States,1962,Female,1.75,Joan Cusack,4,...,40,13.0,41.0,49286 Male 49288 Female 49287 Mal...,3,1,0.333333,49286 United States 49287 United States ...,3,1
70342,http://www.imdb.com/title/tt1756595/,2011,http://www.imdb.com/name/nm2165214,41,None,1996,Male,NaN,Zacharie Chasseriaud,0,...,0,NaN,2.0,70342 Male 70343 Male 70344 Male Name...,3,0,0.000000,70342 None 70343 None 70344 None Name...,0,0
52288,http://www.imdb.com/title/tt0425601/,2006,http://www.imdb.com/name/nm1033215,27,Canada,1968,Male,1.85,John Paul Tremblay,2,...,3,3.0,4.0,52287 Male 52286 Male 52288 Male Name...,3,0,0.000000,52286 Canada 52287 Canada 52288 Canad...,3,1
75827,http://www.imdb.com/title/tt2324928/,2016,http://www.imdb.com/name/nm4076403,1,United States,1986,Female,1.80,Jaclyn Hales,0,...,0,NaN,2.0,75828 Female 75827 Female 75829 Mal...,3,2,0.666667,75827 United States 75828 None ...,1,1
10538,http://www.imdb.com/title/tt0055797/,1962,http://www.imdb.com/name/nm0000013,1,United States,1922,Female,1.70,Doris Day,90,...,131,9.0,38.0,10538 Male 10537 Female 10539 Mal...,3,1,0.333333,10537 United Kingdom 10538 United State...,3,2
80842,http://www.imdb.com/title/tt3322940/,2014,http://www.imdb.com/name/nm0005569,1,United States,1952,Female,1.61,Alfre Woodard,11,...,13,24.0,32.0,80841 Female 80840 Male 80842 Femal...,3,2,0.666667,80840 United Kingdom 80841 United State...,3,2
76985,http://www.imdb.com/title/tt2446502/,2013,http://www.imdb.com/name/nm3743828,1,None,0,Female,1.55,Clare Niederpruem,0,...,13,NaN,33.0,76984 Male 76983 Male 76985 Femal...,3,1,0.333333,76983 Australia 76984 United States ...,2,2

In [922]:
adding_stars['Share of Different Countries Stars'] = adding_stars['Number of Different Countries Stars'].divide(adding_stars['Country Value Counter'])

In [924]:
adding_stars.head(150)

,ID,Year,Star_URL,Acting Roles Star,Birth Country Star,Birthyear Star,Gender Star,Height Star,Name Star,Publicity Listings Star,...,Age Differences Stars,Sum of Age Differences Stars,Genders of Stars,Gender Value Counter,Number of Female Stars,Share of Female Stars,Countries of Stars,Country Value Counter,Number of Different Countries Stars,Share of Different Countries Stars
0,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0209738,16,Italy,1869,Male,NaN,Giuseppe de Liguoro,0,...,NaN,0.0,0 Male 1 Male 2 Male Name: http://www...,3,0,0.000000,0 Italy 1 None 2 None Name: http://...,1,1,1.000000
1,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0685283,6,None,0,Male,NaN,Arturo Pirovano,0,...,NaN,0.0,0 Male 1 Male 2 Male Name: http://www...,3,0,0.000000,0 Italy 1 None 2 None Name: http://...,1,1,1.000000
2,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0660139,15,None,0,Male,NaN,Salvatore Papa,0,...,NaN,0.0,0 Male 1 Male 2 Male Name: http://www...,3,0,0.000000,0 Italy 1 None 2 None Name: http://...,1,1,1.000000
3,http://www.imdb.com/title/tt0002423/,1919,http://www.imdb.com/name/nm0624470,1,Poland,1897,Female,1.52,Pola Negri,69,...,NaN,15.0,5 Female 4 Male 3 Male Name: http...,3,1,0.333333,3 Poland 4 Switzerland 5 Ru...,3,3,1.000000
4,http://www.imdb.com/title/tt0002423/,1919,http://www.imdb.com/name/nm0417837,82,Switzerland,1884,Male,1.83,Emil Jannings,8,...,13.0,15.0,5 Female 4 Male 3 Male Name: http...,3,1,0.333333,3 Poland 4 Switzerland 5 Ru...,3,3,1.000000
5,http://www.imdb.com/title/tt0002423/,1919,http://www.imdb.com/name/nm0509573,162,Russia,1882,Male,NaN,Harry Liedtke,2,...,2.0,15.0,5 Female 4 Male 3 Male Name: http...,3,1,0.333333,3 Poland 4 Switzerland 5 Ru...,3,3,1.000000
6,http://www.imdb.com/title/tt0002844/,1913,http://www.imdb.com/name/nm0577476,68,France,1889,Male,NaN,Georges Melchior,1,...,NaN,12.0,6 Male 7 Male 8 Male Name: http://www...,3,0,0.000000,6 France 7 United Kingdom 8 ...,3,2,0.666667
7,http://www.imdb.com/title/tt0002844/,1913,http://www.imdb.com/name/nm0107631,82,United Kingdom,1882,Male,NaN,Edmund Breon,0,...,7.0,12.0,6 Male 7 Male 8 Male Name: http://www...,3,0,0.000000,6 France 7 United Kingdom 8 ...,3,2,0.666667
8,http://www.imdb.com/title/tt0002844/,1913,http://www.imdb.com/name/nm0622772,119,France,1877,Male,NaN,René Navarre,0,...,5.0,12.0,6 Male 7 Male 8 Male Name: http://www...,3,0,0.000000,6 France 7 United Kingdom 8 ...,3,2,0.666667
9,http://www.imdb.com/title/tt0003037/,1913,http://www.imdb.com/name/nm0577476,68,France,1889,Male,NaN,Georges Melchior,1,...,NaN,12.0,9 Male 10 Male 11 Male Name: http://...,3,0,0.000000,9 France 10 United Kingdom 11 ...,3,2,0.666667
10,http://www.imdb.com/title/tt0003037/,1913,http://www.imdb.com/name/nm0107631,82,United Kingdom,1882,Male,NaN,Edmund Breon,0,...,7.0,12.0,9 Male 10 Male 11 Male Name: http://...,3,0,0.000000,9 France 10 United Kingdom 11 ...,3,2,0.666667
11,http://www.imdb.com/title/tt0003037/,1913,http://www.imdb.com/name/nm0622772,119,France,1877,Male,NaN,René Navarre,0,...,5.0,12.0,9 Male 10 Male 11 Male Name: http://...,3,0,0.000000,9 France 10 United Kingdom 11 ...,3,2,0.666667
12,http://www.imdb.com/title/tt0003165/,1913,http://www.imdb.com/name/nm0577476,68,France,1889,Male,NaN,Georges Melchior,1,...,NaN,12.0,14 Male 13 Male 12 Male Name: http://...,3,0,0.000000,12 France 13 United Kingdom 14 ...,3,2,0.666667
13,http://www.imdb.com/title/tt0003165/,1913,http://www.imdb.com/name/nm0107631,82,United Kingdom,1882,Male,NaN,Edmund Breon,0,...,7.0,12.0,14 Male 13 Male 12 Male Name: http://...,3,0,0.000000,12 France 13 United Kingdom 14 ...,3,2,0.666667
14,http://www.imdb.com/title/tt0003165/,1913,http://www.imdb.com/name/nm0622772,119,France,1877,Male,NaN,René Navarre,0,...,5.0,12.0,14 Male 13 Male 12 Male Name: http://...,3,0,0.000000,12 France 13 United Kingdom 14 ...,3,2,0.666667
15,http://www.imdb.com/title/tt0003419/,1913,http://www.imdb.com/name/nm0758802,1,AustriaHungary,1889,Female,NaN,Lyda Salmonova,1,...,NaN,15.0,17 Female 16 Female 15 Male Name: h...,3,2,0.666667,15 AustriaHungary 16 Czech Republic 17 ...,3,3,1.000000
16,http://www.imdb.com/title/tt0003419/,1913,http://www.imdb.com/name/nm0074186,1,Czech Republic,1883,Female,NaN,Grete Berger,0,...,6.0,15.0,17 Female 16 Female 15 Male Name: h...,3,2,0.666667,15 AustriaHungary 16 Czech Republic 17 ...,3,3,1.000000
17,http://www.imdb.com/title/tt0003419/,1913,http://www.imdb.com/name/nm0917467,71,Poland,1874,Male,1.98,Paul Wegener,3,...,9.0,15.0,17 Female 16 Female 15 Male Name: h...,3,2,0.666667,15 AustriaHungary 16 Czech Republic 17 ...,3,3,1.000000
18,http://www.imdb.com/title/tt0003740/,1914,http://www.imdb.com/name/nm0702894,1,Italy,1891,Female,NaN,Lidia Quaranta,0,...,NaN,13.0,19 Female 20 Female 18 Male Name: h...,3,2,0.666667,18 Italy 19 Italy 20 Italy Name: http...,3,1,0.333333
19,http://www.imdb.com/title/tt0003740/,1914,http://www.imdb.com/name/nm0021935,1,Italy,1890,Female,NaN,Italia Almirante-Manzini,0,...,1.0,13.0,19 Female 20 Female 18 Male Name: h...,3,2,0.666667,18 Italy 19 Italy 20 Italy Name: http...,3,1,0.333333
20,http://www.imdb.com/title/tt0003740/,1914,http://www.imdb.com/name/nm0656034,32,Italy,1878,Male,1.83,Bartolomeo Pagano,5,...,12.0,13.0,19 Female 20 Female 18 Male Name: h...,3,2,0.666667,18 Italy 19 Italy 20 Italy Name: http...,3,1,0.333333
21,http://www.imdb.com/title/tt0003772/,1914,http://www.imdb.com/name/nm0681933,1,Canada,1892,Female,1.54,Mary Pickford,173,...,NaN,18.0,21 Female 22 Male 23 Female Name: h...,3,2,0.666667,21 Canada 22 Ireland 23 None Name...,2,2,1.000000
22,http://www.imdb.com/title/tt0003772/,1914,http://www.imdb.com/name/nm0601698,286,Ireland,1884,Male,1.78,Owen Moore,19,...,8.0,18.0,21 Female 22 Male 23 Female Name: h...,3,2,0.666667,21 Canada 22 Ireland 23 None Name...,2,2,1.000000
23,http://www.imdb.com/title/tt0003772/,1914,http://www.imdb.com/name/nm0894679,1,None,1874,Female,NaN,Isabel Vernon,1,...,10.0,18.0,21 Female 22 Male 23 Female Name: h...,3,2,0.666667,21 Canada 22 Ireland 23 None Name...,2,2,1.000000
24,http://www.imdb.com/title/tt0004026/,1915,http://www.imdb.com/name/nm0758802,1,AustriaHungary,1889,Female,NaN,Lyda Salmonova,1,...,NaN,15.0,26 Female 24 Male 25 Male Name: h...,3,1,0.333333,24 AustriaHungary 25 AustriaHungary 26 ...,3,2,0.666667
25,http://www.imdb.com/title/tt0004026/,1915,http://www.imdb.com/name/nm0301961,6,AustriaHungary,1881,Male,NaN,Henrik Galeen,2,...,8.0,15.0,26 Female 24 Male 25 Male Name: h...,3,1,0.333333,24 AustriaHungary 25 AustriaHungary 26 ...,3,2,0.666667
26,http://www.imdb.com/title/tt0004026/,1915,http://www.imdb.com/name/nm0917467,71,Poland,1874,Male,1.98,Paul Wegener,3,...,7.0,15.0,26 Female 24 Male 25 Male Name: h...,3,1,0.333333,24 AustriaHungary 25 AustriaHungary 26 ...,3,2,0.666667
27,http://www.imdb.com/title/tt0004465/,1914,http://www.imdb.com/name/nm0925310,1,United States,1889,Female,NaN,Pearl White,35,...,NaN,17.0,29 Female 27 Male 28 Male Name: h...,3,1,0.333333,27 United States 28 United States 29 ...,3,2,0.666667
28,http://www.imdb.com/title/tt0004465/,1914,http://www.imdb.com/name/nm0928108,89,United States,1886,Male,1.78,Crane Wilbur,9,...,3.0,17.0,29 Female 27 Male 28 Male Name: h...,3,1,0.333333,27 United States 28 United States 29 ...,3,2,0.666667
29,http://www.imdb.com/title/tt0004465/,1914,http://www.imdb.com/name/nm0659947,394,Germany,1872,Male,1.79,Paul Panzer,14,...,14.0,17.0,29 Female 27 Male 28 Male Name: h...,3,1,0.333333,27 United States 28 United States 29 ...,3,2,0.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,http://www.imdb.com/title/tt0011130/,1920,http://www.imdb.com/name/nm0543806,1,United States,1899,Female,NaN,Martha Mansfield,14,...,NaN,33.0,120 Female 122 Male 121 Male Name...,3,1,0.333333,120 United States 121 United States 12...,3,2,0.666667
121,http://www.imdb.com/title/tt0011130/,1920,http://www.imdb.com/name/nm0000858,65,United States,1882,Male,1.78,John Barrymore,53,...,17.0,33.0,120 Female 122 Male 121 Male Name...,3,1,0.333333,120 United States 121 United States 12...,3,2,0.666667
122,http://www.imdb.com/title/tt0011130/,1920,http://www.imdb.com/name/nm0403582,132,United Kingdom,1866,Male,1.83,Brandon Hurst,2,...,16.0,33.0,120 Female 122 Male 121 Male Name...,3,1,0.333333,120 United States 121 United States 12...,3,2,0.666667
123,http://www.imdb.com/title/tt0011157/,1920,http://www.imdb.com/name/nm0854189,1,Sweden,1893,Female,NaN,Tora Teje,1,...,NaN,24.0,125 Female 124 Female 123 Male Name...,3,2,0.666667,123 Sweden 124 Sweden 125 Sweden Name...,3,1,0.333333
124,http://www.imdb.com/title/tt0011157/,1920,http://www.imdb.com/name/nm0596417,1,Sweden,1889,Female,NaN,Karin Molander,0,...,4.0,24.0,125 Female 124 Female 123 Male Name...,3,2,0.666667,123 Sweden 124 Sweden 125 Sweden Name...,3,1,0.333333
125,http://www.imdb.com/title/tt0011157/,1920,http://www.imdb.com/name/nm0212333,5,Sweden,1869,Male,NaN,Anders de Wahl,1,...,20.0,24.0,125 Female 124 Female 123 Male Name...,3,2,0.666667,123 Sweden 124 Sweden 125 Sweden Name...,3,1,0.333333
126,http://www.imdb.com/title/tt0011221/,1920,http://www.imdb.com/name/nm0903145,73,Poland,1898,Male,1.83,Hans Heinrich von Twardowski,3,...,NaN,11.0,127 Male 128 Female 126 Male Name...,3,1,0.333333,126 Poland 127 United States 128 ...,3,3,1.000000
127,http://www.imdb.com/title/tt0011221/,1920,http://www.imdb.com/name/nm0027992,1,United States,1893,Female,1.60,Fern Andra,4,...,5.0,11.0,127 Male 128 Female 126 Male Name...,3,1,0.333333,126 Poland 127 United States 128 ...,3,3,1.000000
128,http://www.imdb.com/title/tt0011221/,1920,http://www.imdb.com/name/nm0343069,25,Lithuania,1887,Male,NaN,Ernst Gronau,0,...,6.0,11.0,127 Male 128 Female 126 Male Name...,3,1,0.333333,126 Poland 127 United States 128 ...,3,3,1.000000
129,http://www.imdb.com/title/tt0011237/,1920,http://www.imdb.com/name/nm0222074,68,AustriaHungary,1890,Male,NaN,Ernst Deutsch,5,...,NaN,18.0,130 Male 129 Male 131 Male Name: http...,3,0,0.000000,129 AustriaHungary 130 Poland 13...,3,3,1.000000
130,http://www.imdb.com/title/tt0011237/,1920,http://www.imdb.com/name/nm0917467,71,Poland,1874,Male,1.98,Paul Wegener,3,...,16.0,18.0,130 Male 129 Male 131 Male Name: http...,3,0,0.000000,129 AustriaHungary 130 Poland 13...,3,3,1.000000
131,http://www.imdb.com/title/tt0011237/,1920,http://www.imdb.com/name/nm0826210,88,Germany,1872,Male,NaN,Albert Steinrück,0,...,2.0,18.0,130 Male 129 Male 131 Male Name: http...,3,0,0.000000,129 AustriaHungary 130 Poland 13...,3,3,1.000000
132,http://www.imdb.com/title/tt0011387/,1920,http://www.imdb.com/name/nm0066024,1,United States,1903,Female,1.63,Barbara Bedford,9,...,NaN,18.0,134 Female 133 Male 132 Male Name...,3,1,0.333333,132 United States 133 United States 134 ...,3,1,0.333333
133,http://www.imdb.com/title/tt0011387/,1920,http://www.imdb.com/name/nm0741182,109,United States,1886,Male,NaN,Alan Roscoe,5,...,17.0,18.0,134 Female 133 Male 132 Male Name...,3,1,0.333333,132 United States 133 United States 134 ...,3,1,0.333333
134,http://www.imdb.com/title/tt0011387/,1920,http://www.imdb.com/name/nm0000891,241,United States,1885,Male,1.82,Wallace Beery,28,...,1.0,18.0,134 Female 133 Male 132 Male Name...,3,1,0.333333,132 United States 133 United States 134 ...,3,1,0.333333
135,http://www.imdb.com/title/tt0011439/,1920,http://www.imdb.com/name/nm0209323,1,United States,1902,Female,1.57,Marguerite De La Motte,10,...,NaN,19.0,136 Female 137 Male 135 Male Name...,3,1,0.333333,135 United States 136 United States 137 ...,3,1,0.333333
136,http://www.imdb.com/title/tt0011439/,1920,http://www.imdb.com/name/nm0571770,101,United States,1886,Male,NaN,Robert McKim,5,...,16.0,19.0,136 Female 137 Male 135 Male Name...,3,1,0.333333,135 United States 136 United States 137 ...,3,1,0.333333
137,http://www.imdb.com/title/tt0011439/,1920,http://www.imdb.com/name/nm0001196,51,United States,1883,Male,1.70,Douglas Fairbanks,139,...,3.0,19.0,136 Female 137 Male 135 Male Name...,3,1,0.333333,135 United States 136 United States 137 ...,3,1,0.333333
138,http://www.imdb.com/title/tt0011565/,1920,http://www.imdb.com/name/nm0668084,1,United States,1894,Female,NaN,Doris Pawn,3,...,NaN,21.0,140 Female 138 Male 139 Male Name...,3,1,0.333333,138 United States 139 France 140 ...,3,2,0.666667
139,http://www.imdb.com/title/tt0011565/,1920,http://www.imdb.com/name/nm0556769,197,France,1889,Male,NaN,Jim Mason,0,...,5.0,21.0,140 Female 138 Male 139 Male Name...,3,1,0.333333,138 United States 139 France 140 ...,3,2,0.666667
140,http://www.imdb.com/title/tt0011565/,1920,http://www.imdb.com/name/nm0165134,235,United States,1873,Male,1.84,Charles Clary,6,...,16.0,21.0,140 Female 138 Male 139 Male Name...,3,1,0.333333,138 United States 139 France 140 ...,3,2,0.666667
141,http://www.imdb.com/title/tt0011607/,1920,http://www.imdb.com/name/nm0753885,4,None,1897,Male,NaN,Einar Röd,0,...,NaN,54.0,142 Male 141 Female 143 Female Name...,3,2,0.666667,141 None 142 Sweden 143 Sweden Name...,2,1,0.500000
142,http://www.imdb.com/title/tt0011607/,1920,http://www.imdb.com/name/nm0022011,1,Sweden,1888,Female,NaN,Greta Almroth,0,...,9.0,54.0,142 Male 141 Female 143 Female Name...,3,2,0.666667,141 None 142 Sweden 143 Sweden Name...,2,1,0.500000
143,http://www.imdb.com/title/tt0011607/,1920,http://www.imdb.com/name/nm0137320,1,Sweden,1843,Female,NaN,Hildur Carlberg,0,...,45.0,54.0,142 Male 141 Female 143 Female Name...,3,2,0.666667,141 None 142 Sweden 143 Sweden Name...,2,1,0.500000
144,http://www.imdb.com/title/tt0011723/,1920,http://www.imdb.com/name/nm0649916,1,Italy,1889,Female,NaN,Ressel Orla,1,...,NaN,10.0,145 Female 144 Male 146 Male Name...,3,1,0.333333,144 Italy 145 Germany 146 Poland N...,3,3,1.000000
145,http://www.imdb.com/title/tt0011723/,1920,http://www.imdb.com/name/nm0212234,127,Germany,1885,Male,NaN,Carl de Vogt,0,...,4.0,10.0,145 Female 144 Male 146 Male Name...,3,1,0.333333,144 Italy 145 Germany 146 Poland N...,3,3,1.000000
146,http://www.imdb.com/title/tt0011723/,1920,http://www.imdb.com/name/nm0313308,123,Poland,1879,Male,NaN,Georg John,0,...,6.0,10.0,145 Female 144 Male 146 Male Name...,3,1,0.333333,144 Italy 145 Germany 146 Poland N...,3,3,1.000000
147,http://www.imdb.com/title/tt0011742/,1920,http://www.imdb.com/name/nm0624470,1,Poland,1897,Female,1.52,Pola Negri,69,...,NaN,23.0,149 Female 148 Male 147 Male Name...,3,1,0.333333,147 Poland 148 Germany 149 Poland N...,3,2,0.666667
148,http://www.imdb.com/title/tt0011742/,1920,http://www.imdb.com/name/nm0523932,43,Germany,1892,Male,1.70,Ernst Lubitsch,53,...,5.0,23.0,149 Female 148 Male 147 Male Name...,3,1,0.333333,147 Poland 148 Germany 149 Poland N...,3,2,0.666667
149,http://www.imdb.com/title/tt0011742/,1920,http://www.imdb.com/name/nm0917467,71,Poland,1874,Male,1.98,Paul Wegener,3,...,18.0,23.0,149 Female 148 Male 147 Male Name...,3,1,0.333333,147 Poland 148 Germany 149 Poland N...,3,2,0.666667

In [926]:
sorted(list(adding_stars['Sum of Age Differences Stars'].unique()))

[0.0,
 1.0,
 2.0,
 3.0,
 4.0,
 5.0,
 6.0,
 7.0,
 8.0,
 9.0,
 10.0,
 11.0,
 12.0,
 13.0,
 14.0,
 15.0,
 16.0,
 17.0,
 18.0,
 19.0,
 20.0,
 21.0,
 22.0,
 23.0,
 24.0,
 25.0,
 26.0,
 27.0,
 28.0,
 29.0,
 30.0,
 31.0,
 32.0,
 33.0,
 34.0,
 35.0,
 36.0,
 37.0,
 38.0,
 39.0,
 40.0,
 41.0,
 42.0,
 43.0,
 44.0,
 45.0,
 46.0,
 47.0,
 48.0,
 49.0,
 50.0,
 51.0,
 52.0,
 53.0,
 54.0,
 55.0,
 56.0,
 57.0,
 58.0,
 59.0,
 60.0,
 61.0,
 62.0,
 63.0,
 64.0,
 65.0,
 66.0,
 67.0,
 68.0,
 69.0,
 70.0,
 71.0,
 72.0,
 75.0,
 88.0]

In [927]:
max_age_difference = max(adding_stars['Sum of Age Differences Stars'])
max_age_difference

88.0

In [928]:
adding_stars['Age Difference Rating Stars'] = adding_stars['Sum of Age Differences Stars'].divide(max_age_difference)

In [929]:
adding_stars.head()

,ID,Year,Star_URL,Acting Roles Star,Birth Country Star,Birthyear Star,Gender Star,Height Star,Name Star,Publicity Listings Star,...,Sum of Age Differences Stars,Genders of Stars,Gender Value Counter,Number of Female Stars,Share of Female Stars,Countries of Stars,Country Value Counter,Number of Different Countries Stars,Share of Different Countries Stars,Age Difference Rating Stars
0,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0209738,16,Italy,1869,Male,NaN,Giuseppe de Liguoro,0,...,0.0,0 Male 1 Male 2 Male Name: http://www...,3,0,0.000000,0 Italy 1 None 2 None Name: http://...,1,1,1.0,0.000000
1,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0685283,6,None,0,Male,NaN,Arturo Pirovano,0,...,0.0,0 Male 1 Male 2 Male Name: http://www...,3,0,0.000000,0 Italy 1 None 2 None Name: http://...,1,1,1.0,0.000000
2,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0660139,15,None,0,Male,NaN,Salvatore Papa,0,...,0.0,0 Male 1 Male 2 Male Name: http://www...,3,0,0.000000,0 Italy 1 None 2 None Name: http://...,1,1,1.0,0.000000
3,http://www.imdb.com/title/tt0002423/,1919,http://www.imdb.com/name/nm0624470,1,Poland,1897,Female,1.52,Pola Negri,69,...,15.0,5 Female 4 Male 3 Male Name: http...,3,1,0.333333,3 Poland 4 Switzerland 5 Ru...,3,3,1.0,0.170455
4,http://www.imdb.com/title/tt0002423/,1919,http://www.imdb.com/name/nm0417837,82,Switzerland,1884,Male,1.83,Emil Jannings,8,...,15.0,5 Female 4 Male 3 Male Name: http...,3,1,0.333333,3 Poland 4 Switzerland 5 Ru...,3,3,1.0,0.170455

In [1041]:
adding_stars[adding_stars['Share of Different Countries Stars'].isnull()]

Empty DataFrame
Columns: [ID, Year, Star_URL, Acting Roles Star, Birth Country Star, Birthyear Star, Gender Star, Height Star, Name Star, Publicity Listings Star, TV Appearances Star, Other Roles Star, Award Nominations and Wins Star, Age at time of Release, Acting Roles Stars Cumulative, Award Nominations and Wins Stars Cumulative, Other Roles Stars Cumulative, TV Appearances Stars Cumulative, Publicity Listings Stars Cumulative, Age Differences Stars, Sum of Age Differences Stars, Genders of Stars, Gender Value Counter, Number of Female Stars, Share of Female Stars, Countries of Stars, Country Value Counter, Number of Different Countries Stars, Share of Different Countries Stars, Age Difference Rating Stars, Diversity Index]
Index: []

[0 rows x 31 columns]

In [1040]:
adding_stars['Share of Different Countries Stars'].fillna(0,inplace=True)

In [1042]:
adding_stars[adding_stars['Share of Female Stars'].isnull()]

,ID,Year,Star_URL,Acting Roles Star,Birth Country Star,Birthyear Star,Gender Star,Height Star,Name Star,Publicity Listings Star,...,Genders of Stars,Gender Value Counter,Number of Female Stars,Share of Female Stars,Countries of Stars,Country Value Counter,Number of Different Countries Stars,Share of Different Countries Stars,Age Difference Rating Stars,Diversity Index
44981,http://www.imdb.com/title/tt0282917/,2002,http://www.imdb.com/name/nm1090955,1,Czechoslovakia,1958,None,NaN,Karel Plíhal,0,...,44983 None 44982 None 44981 None Name...,0,0,NaN,44981 Czechoslovakia 44982 Czechoslovaki...,2,1,0.5,0.056818,NaN
44982,http://www.imdb.com/title/tt0282917/,2002,http://www.imdb.com/name/nm0634115,1,Czechoslovakia,1953,None,NaN,Jaromír Nohavica,0,...,44983 None 44982 None 44981 None Name...,0,0,NaN,44981 Czechoslovakia 44982 Czechoslovaki...,2,1,0.5,0.056818,NaN
44983,http://www.imdb.com/title/tt0282917/,2002,http://www.imdb.com/name/nm1186023,1,None,0,None,NaN,Jan Prent,0,...,44983 None 44982 None 44981 None Name...,0,0,NaN,44981 Czechoslovakia 44982 Czechoslovaki...,2,1,0.5,0.056818,NaN
79139,http://www.imdb.com/title/tt2961890/,2014,http://www.imdb.com/name/nm0062189,1,None,0,None,NaN,Signe Baumane,0,...,79139 None Name: http://www.imdb.com/title/...,0,0,NaN,79139 None Name: http://www.imdb.com/title/...,0,0,0.0,0.000000,NaN

In [1043]:
adding_stars['Share of Female Stars'].fillna(0,inplace=True)

In [1045]:
adding_stars[adding_stars['Share of Different Countries Stars'].isnull()]

Empty DataFrame
Columns: [ID, Year, Star_URL, Acting Roles Star, Birth Country Star, Birthyear Star, Gender Star, Height Star, Name Star, Publicity Listings Star, TV Appearances Star, Other Roles Star, Award Nominations and Wins Star, Age at time of Release, Acting Roles Stars Cumulative, Award Nominations and Wins Stars Cumulative, Other Roles Stars Cumulative, TV Appearances Stars Cumulative, Publicity Listings Stars Cumulative, Age Differences Stars, Sum of Age Differences Stars, Genders of Stars, Gender Value Counter, Number of Female Stars, Share of Female Stars, Countries of Stars, Country Value Counter, Number of Different Countries Stars, Share of Different Countries Stars, Age Difference Rating Stars, Diversity Index]
Index: []

[0 rows x 31 columns]

In [1044]:
adding_stars['Share of Different Countries Stars'].fillna(0,inplace=True)

In [1046]:
adding_stars['Diversity Index'] = sum([adding_stars['Share of Female Stars']*100,
                                       adding_stars['Share of Different Countries Stars']*100,
                                       adding_stars['Age Difference Rating Stars']*100])/3

In [1047]:
adding_stars.head()

,ID,Year,Star_URL,Acting Roles Star,Birth Country Star,Birthyear Star,Gender Star,Height Star,Name Star,Publicity Listings Star,...,Genders of Stars,Gender Value Counter,Number of Female Stars,Share of Female Stars,Countries of Stars,Country Value Counter,Number of Different Countries Stars,Share of Different Countries Stars,Age Difference Rating Stars,Diversity Index
0,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0209738,16,Italy,1869,Male,NaN,Giuseppe de Liguoro,0,...,0 Male 1 Male 2 Male Name: http://www...,3,0,0.000000,0 Italy 1 None 2 None Name: http://...,1,1,1.0,0.000000,33.333333
1,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0685283,6,None,0,Male,NaN,Arturo Pirovano,0,...,0 Male 1 Male 2 Male Name: http://www...,3,0,0.000000,0 Italy 1 None 2 None Name: http://...,1,1,1.0,0.000000,33.333333
2,http://www.imdb.com/title/tt0002130/,1911,http://www.imdb.com/name/nm0660139,15,None,0,Male,NaN,Salvatore Papa,0,...,0 Male 1 Male 2 Male Name: http://www...,3,0,0.000000,0 Italy 1 None 2 None Name: http://...,1,1,1.0,0.000000,33.333333
3,http://www.imdb.com/title/tt0002423/,1919,http://www.imdb.com/name/nm0624470,1,Poland,1897,Female,1.52,Pola Negri,69,...,5 Female 4 Male 3 Male Name: http...,3,1,0.333333,3 Poland 4 Switzerland 5 Ru...,3,3,1.0,0.170455,50.126263
4,http://www.imdb.com/title/tt0002423/,1919,http://www.imdb.com/name/nm0417837,82,Switzerland,1884,Male,1.83,Emil Jannings,8,...,5 Female 4 Male 3 Male Name: http...,3,1,0.333333,3 Poland 4 Switzerland 5 Ru...,3,3,1.0,0.170455,50.126263

In [1048]:
adding_stars[adding_stars['Diversity Index'].isnull()]

Empty DataFrame
Columns: [ID, Year, Star_URL, Acting Roles Star, Birth Country Star, Birthyear Star, Gender Star, Height Star, Name Star, Publicity Listings Star, TV Appearances Star, Other Roles Star, Award Nominations and Wins Star, Age at time of Release, Acting Roles Stars Cumulative, Award Nominations and Wins Stars Cumulative, Other Roles Stars Cumulative, TV Appearances Stars Cumulative, Publicity Listings Stars Cumulative, Age Differences Stars, Sum of Age Differences Stars, Genders of Stars, Gender Value Counter, Number of Female Stars, Share of Female Stars, Countries of Stars, Country Value Counter, Number of Different Countries Stars, Share of Different Countries Stars, Age Difference Rating Stars, Diversity Index]
Index: []

[0 rows x 31 columns]

In [1049]:
adding_stars.columns

Index(['ID', 'Year', 'Star_URL', 'Acting Roles Star', 'Birth Country Star',
       'Birthyear Star', 'Gender Star', 'Height Star', 'Name Star',
       'Publicity Listings Star', 'TV Appearances Star', 'Other Roles Star',
       'Award Nominations and Wins Star', 'Age at time of Release',
       'Acting Roles Stars Cumulative',
       'Award Nominations and Wins Stars Cumulative',
       'Other Roles Stars Cumulative', 'TV Appearances Stars Cumulative',
       'Publicity Listings Stars Cumulative', 'Age Differences Stars',
       'Sum of Age Differences Stars', 'Genders of Stars',
       'Gender Value Counter', 'Number of Female Stars',
       'Share of Female Stars', 'Countries of Stars', 'Country Value Counter',
       'Number of Different Countries Stars',
       'Share of Different Countries Stars', 'Age Difference Rating Stars',
       'Diversity Index'],
      dtype='object')

In [1050]:
stars_final_df = pd.DataFrame(adding_stars[['ID',
                                            'Year',
                                            'Acting Roles Stars Cumulative',
                                            'Award Nominations and Wins Stars Cumulative',
                                            'Other Roles Stars Cumulative', 
                                            'TV Appearances Stars Cumulative',
                                            'Publicity Listings Stars Cumulative','Diversity Index']])

In [1051]:
stars_final_df.head()

,ID,Year,Acting Roles Stars Cumulative,Award Nominations and Wins Stars Cumulative,Other Roles Stars Cumulative,TV Appearances Stars Cumulative,Publicity Listings Stars Cumulative,Diversity Index
0,http://www.imdb.com/title/tt0002130/,1911,37,0,92,0,0,33.333333
1,http://www.imdb.com/title/tt0002130/,1911,37,0,92,0,0,33.333333
2,http://www.imdb.com/title/tt0002130/,1911,37,0,92,0,0,33.333333
3,http://www.imdb.com/title/tt0002423/,1919,245,6,6,12,79,50.126263
4,http://www.imdb.com/title/tt0002423/,1919,245,6,6,12,79,50.126263

In [1052]:
stars_final_df.drop_duplicates(subset='ID',keep='first',inplace=True)

In [1053]:
stars_final_df.head()

,ID,Year,Acting Roles Stars Cumulative,Award Nominations and Wins Stars Cumulative,Other Roles Stars Cumulative,TV Appearances Stars Cumulative,Publicity Listings Stars Cumulative,Diversity Index
0,http://www.imdb.com/title/tt0002130/,1911,37,0,92,0,0,33.333333
3,http://www.imdb.com/title/tt0002423/,1919,245,6,6,12,79,50.126263
6,http://www.imdb.com/title/tt0002844/,1913,269,0,8,0,1,26.767677
9,http://www.imdb.com/title/tt0003037/,1913,269,0,8,0,1,26.767677
12,http://www.imdb.com/title/tt0003165/,1913,269,0,8,0,1,26.767677

In [1054]:
stars_final_df.drop(columns=['Year'],inplace=True)

In [1055]:
stars_final_df.reset_index(drop=True,inplace=True)

In [1056]:
stars_final_df.head()

,ID,Acting Roles Stars Cumulative,Award Nominations and Wins Stars Cumulative,Other Roles Stars Cumulative,TV Appearances Stars Cumulative,Publicity Listings Stars Cumulative,Diversity Index
0,http://www.imdb.com/title/tt0002130/,37,0,92,0,0,33.333333
1,http://www.imdb.com/title/tt0002423/,245,6,6,12,79,50.126263
2,http://www.imdb.com/title/tt0002844/,269,0,8,0,1,26.767677
3,http://www.imdb.com/title/tt0003037/,269,0,8,0,1,26.767677
4,http://www.imdb.com/title/tt0003165/,269,0,8,0,1,26.767677

In [1057]:
sorted(list(stars_final_df['Diversity Index'].unique()))

[0.0,
 0.75757575757575768,
 1.8939393939393938,
 3.7878787878787876,
 11.111111111111109,
 11.489898989898988,
 11.742424242424242,
 11.868686868686867,
 12.247474747474746,
 12.626262626262625,
 13.005050505050503,
 13.383838383838382,
 13.762626262626261,
 14.14141414141414,
 14.520202020202019,
 14.898989898989896,
 15.277777777777777,
 15.656565656565654,
 16.035353535353533,
 16.414141414141412,
 16.666666666666668,
 16.792929292929291,
 17.045454545454543,
 17.171717171717173,
 17.424242424242426,
 17.550505050505048,
 17.803030303030301,
 17.929292929292927,
 18.181818181818183,
 18.308080808080806,
 18.560606060606059,
 18.686868686868685,
 18.939393939393941,
 19.065656565656564,
 19.318181818181817,
 19.444444444444443,
 19.696969696969699,
 19.823232323232322,
 20.075757575757574,
 20.202020202020197,
 20.454545454545453,
 20.58080808080808,
 20.833333333333332,
 20.959595959595958,
 21.212121212121211,
 21.338383838383837,
 21.590909090909093,
 21.717171717171713,
 21.969696969696969,
 22.095959595959595,
 22.222222222222218,
 22.348484848484848,
 22.47474747474747,
 22.6010101010101,
 22.72727272727273,
 22.853535353535353,
 22.979797979797976,
 23.106060606060606,
 23.232323232323228,
 23.358585858585855,
 23.484848484848484,
 23.611111111111111,
 23.737373737373733,
 23.863636363636363,
 23.98989898989899,
 24.116161616161616,
 24.242424242424239,
 24.368686868686865,
 24.494949494949491,
 24.621212121212121,
 24.747474747474751,
 24.87373737373737,
 25.0,
 25.126262626262626,
 25.252525252525249,
 25.378787878787879,
 25.505050505050502,
 25.631313131313131,
 25.757575757575754,
 25.883838383838384,
 26.010101010101007,
 26.136363636363637,
 26.262626262626259,
 26.388888888888886,
 26.515151515151516,
 26.641414141414135,
 26.767676767676765,
 26.893939393939394,
 27.020202020202021,
 27.146464646464647,
 27.27272727272727,
 27.398989898989896,
 27.525252525252522,
 27.651515151515152,
 27.777777777777775,
 27.904040404040401,
 28.030303030303031,
 28.156565656565657,
 28.28282828282828,
 28.409090909090907,
 28.535353535353533,
 28.661616161616156,
 28.787878787878793,
 28.914141414141412,
 29.040404040404038,
 29.166666666666668,
 29.292929292929291,
 29.419191919191917,
 29.545454545454543,
 29.671717171717166,
 29.671717171717173,
 29.797979797979792,
 29.924242424242426,
 30.050505050505048,
 30.050505050505052,
 30.176767676767671,
 30.303030303030301,
 30.429292929292927,
 30.555555555555554,
 30.681818181818183,
 30.808080808080806,
 30.934343434343432,
 31.060606060606062,
 31.186868686868689,
 31.313131313131308,
 31.439393939393938,
 31.565656565656564,
 31.691919191919187,
 31.818181818181817,
 31.944444444444443,
 32.070707070707066,
 32.196969696969695,
 32.323232323232325,
 32.449494949494948,
 32.702020202020201,
 32.828282828282823,
 32.95454545454546,
 33.080808080808076,
 33.207070707070706,
 33.333333333333329,
 33.333333333333336,
 33.459595959595958,
 33.585858585858581,
 33.712121212121211,
 33.838383838383841,
 33.964646464646457,
 34.090909090909086,
 34.217171717171716,
 34.343434343434346,
 34.469696969696962,
 34.469696969696969,
 34.595959595959592,
 34.722222222222221,
 34.848484848484844,
 34.848484848484851,
 34.974747474747474,
 35.101010101010097,
 35.227272727272727,
 35.353535353535356,
 35.479797979797979,
 35.606060606060602,
 35.732323232323232,
 35.858585858585855,
 35.984848484848477,
 35.984848484848484,
 35.984848484848492,
 36.111111111111107,
 36.237373737373737,
 36.36363636363636,
 36.363636363636367,
 36.48989898989899,
 36.616161616161612,
 36.742424242424242,
 36.868686868686865,
 36.994949494949488,
 37.121212121212118,
 37.121212121212125,
 37.247474747474747,
 37.37373737373737,
 37.499999999999993,
 37.5,
 37.626262626262623,
 37.752525252525253,
 37.878787878787875,
 37.878787878787882,
 38.005050505050498,
 38.005050505050505,
 38.131313131313128,
 38.257575757575751,
 38.257575757575758,
 38.383838383838381,
 38.51010101010101,
 38.636363636363633,
 38.762626262626263,
 38.888888888888886,
 39.015151515151508,
 39.015151515151516,
 39.141414141414138,
 39.267676767676761,
 39.267676767676768,
 39.393939393939391,
 39.393939393939398,
 39.520202020202021,
 39.646464646464644,
 39.772727272727266,
 39.772727272727273,
 39.898989898989896,
 40.025252525252519,
 40.151515151515149,
 40.277777777777779,
 40.404040404040394,
 40.404040404040401,
 40.530303030303024,
 40.530303030303031,
 40.656565656565654,
 40.782828282828284,
 40.909090909090907,
 41.035353535353529,
 41.161616161616159,
 41.287878787878782,
 41.287878787878789,
 41.414141414141419,
 41.540404040404034,
 41.540404040404042,
 41.666666666666664,
 41.792929292929294,
 41.919191919191917,
 42.04545454545454,
 42.045454545454547,
 42.171717171717169,
 42.297979797979792,
 42.297979797979799,
 42.424242424242415,
 42.424242424242422,
 42.550505050505052,
 42.676767676767675,
 42.803030303030305,
 42.929292929292927,
 43.05555555555555,
 43.18181818181818,
 43.181818181818187,
 43.308080808080803,
 43.434343434343425,
 43.560606060606055,
 43.560606060606062,
 43.686868686868685,
 43.813131313131315,
 43.939393939393938,
 44.06565656565656,
 44.19191919191919,
 44.318181818181813,
 44.444444444444436,
 44.570707070707066,
 44.696969696969688,
 44.696969696969695,
 44.823232323232311,
 44.823232323232325,
 44.949494949494941,
 44.949494949494948,
 45.075757575757571,
 45.202020202020201,
 45.328282828282823,
 45.328282828282831,
 45.454545454545446,
 45.45454545454546,
 45.580808080808076,
 45.580808080808083,
 45.707070707070706,
 45.833333333333336,
 45.959595959595951,
 45.959595959595958,
 46.085858585858581,
 46.212121212121211,
 46.338383838383834,
 46.464646464646457,
 46.590909090909086,
 46.590909090909093,
 46.717171717171709,
 46.843434343434332,
 46.843434343434346,
 46.969696969696969,
 47.095959595959592,
 47.222222222222221,
 47.348484848484844,
 47.348484848484851,
 47.474747474747467,
 47.601010101010097,
 47.601010101010104,
 47.72727272727272,
 47.727272727272727,
 47.853535353535342,
 47.853535353535356,
 47.979797979797979,
 48.106060606060602,
 48.232323232323232,
 48.358585858585855,
 48.484848484848477,
 48.611111111111107,
 48.73737373737373,
 48.863636363636353,
 48.863636363636367,
 48.989898989898983,
 49.116161616161612,
 49.242424242424242,
 49.368686868686865,
 49.494949494949488,
 49.494949494949502,
 49.621212121212118,
 49.621212121212125,
 49.74747474747474,
 49.747474747474747,
 49.873737373737377,
 50.0,
 50.126262626262616,
 50.252525252525253,
 50.378787878787875,
 50.505050505050498,
 50.631313131313128,
 50.757575757575751,
 50.757575757575758,
 50.883838383838373,
 51.01010101010101,
 51.136363636363626,
 51.136363636363633,
 51.262626262626263,
 51.388888888888886,
 51.515151515151508,
 51.641414141414138,
 51.767676767676761,
 51.893939393939384,
 51.893939393939398,
 52.020202020202014,
 52.146464646464644,
 52.272727272727273,
 52.398989898989896,
 52.525252525252519,
 52.651515151515149,
 52.651515151515156,
 52.777777777777771,
 52.904040404040394,
 53.030303030303024,
 53.030303030303031,
 53.156565656565647,
 53.282828282828284,
 53.409090909090907,
 53.535353535353529,
 53.661616161616159,
 53.787878787878782,
 53.787878787878789,
 53.914141414141405,
 54.040404040404042,
 54.166666666666664,
 54.292929292929294,
 54.419191919191917,
 54.54545454545454,
 54.671717171717169,
 54.924242424242415,
 55.050505050505045,
 55.176767676767675,
 55.30303030303029,
 55.303030303030305,
 55.42929292929292,
 55.55555555555555,
 55.68181818181818,
 55.808080808080803,
 55.934343434343425,
 56.060606060606055,
 56.060606060606062,
 56.186868686868678,
 56.313131313131315,
 56.439393939393938,
 56.56565656565656,
 56.69191919191919,
 56.818181818181813,
 56.81818181818182,
 56.944444444444436,
 57.070707070707066,
 57.196969696969695,
 57.323232323232311,
 57.449494949494948,
 57.575757575757571,
 57.702020202020201,
 57.828282828282823,
 57.954545454545446,
 57.95454545454546,
 58.080808080808076,
 58.207070707070706,
 58.333333333333336,
 58.459595959595958,
 58.585858585858581,
 58.712121212121211,
 58.838383838383834,
 58.964646464646457,
 59.090909090909086,
 59.090909090909093,
 59.217171717171709,
 59.343434343434346,
 59.469696969696962,
 59.469696969696969,
 59.595959595959584,
 59.722222222222221,
 59.848484848484851,
 59.974747474747467,
 60.101010101010097,
 60.227272727272727,
 60.353535353535342,
 60.479797979797979,
 60.606060606060602,
 60.732323232323232,
 60.858585858585855,
 61.111111111111107,
 61.23737373737373,
 61.363636363636367,
 61.489898989898983,
 61.616161616161612,
 61.742424242424242,
 61.868686868686865,
 61.994949494949488,
 62.121212121212125,
 62.24747474747474,
 62.373737373737377,
 62.5,
 62.626262626262616,
 62.752525252525253,
 62.878787878787875,
 63.005050505050498,
 63.131313131313128,
 63.383838383838373,
 63.51010101010101,
 63.636363636363633,
 63.762626262626263,
 63.888888888888886,
 64.015151515151516,
 64.141414141414131,
 64.267676767676761,
 64.267676767676775,
 64.520202020202007,
 64.646464646464651,
 64.898989898989896,
 65.025252525252526,
 65.151515151515142,
 65.277777777777771,
 65.404040404040401,
 65.530303030303031,
 65.656565656565647,
 65.782828282828277,
 66.035353535353522,
 66.161616161616152,
 66.414141414141412,
 66.540404040404042,
 66.666666666666671,
 66.792929292929287,
 66.919191919191917,
 67.045454545454547,
 67.171717171717162,
 67.297979797979792,
 67.424242424242422,
 67.550505050505038,
 67.676767676767682,
 67.803030303030297,
 67.929292929292913,
 68.055555555555557,
 68.181818181818173,
 68.308080808080803,
 68.434343434343432,
 68.560606060606062,
 68.686868686868692,
 68.813131313131308,
 68.939393939393938,
 69.191919191919183,
 69.318181818181827,
 69.570707070707059,
 69.696969696969703,
 69.823232323232318,
 69.949494949494948,
 70.075757575757578,
 70.328282828282823,
 70.454545454545453,
 70.580808080808069,
 70.707070707070713,
 70.833333333333329,
 71.085858585858588,
 71.212121212121204,
 71.464646464646464,
 71.590909090909093,
 71.843434343434339,
 72.222222222222214,
 72.348484848484844,
 72.60101010101009,
 72.727272727272734,
 72.979797979797979,
 73.106060606060609,
 73.358585858585855,
 73.484848484848484,
 73.73737373737373,
 73.86363636363636,
 74.116161616161619,
 74.242424242424235,
 74.494949494949495,
 74.621212121212125,
 74.87373737373737,
 75.0,
 75.252525252525245,
 75.378787878787875,
 75.631313131313121,
 75.757575757575765,
 76.13636363636364,
 76.388888888888886,
 76.515151515151516,
 76.767676767676761,
 77.146464646464651,
 77.272727272727266,
 77.651515151515142,
 77.777777777777771,
 77.904040404040401,
 78.030303030303031,
 79.040404040404042,
 79.166666666666671,
 79.924242424242422,
 80.303030303030297,
 80.934343434343432,
 81.060606060606062,
 81.439393939393938,
 82.575757575757578,
 82.954545454545453,
 83.333333333333329,
 85.227272727272734,
 87.121212121212125,
 89.772727272727266]

In [1038]:
stars_final_df[stars_final_df['Diversity Index'].isnull()]

,ID,Acting Roles Stars Cumulative,Award Nominations and Wins Stars Cumulative,Other Roles Stars Cumulative,TV Appearances Stars Cumulative,Publicity Listings Stars Cumulative,Diversity Index
205,http://www.imdb.com/title/tt0020163/,5,0,0,4,0,NaN
2650,http://www.imdb.com/title/tt0048956/,5,0,0,1,0,NaN
3084,http://www.imdb.com/title/tt0052394/,3,0,0,0,0,NaN
3127,http://www.imdb.com/title/tt0052733/,12,0,0,1,0,NaN
3426,http://www.imdb.com/title/tt0054880/,6,0,0,2,0,NaN
3525,http://www.imdb.com/title/tt0055858/,3,0,0,0,0,NaN
3591,http://www.imdb.com/title/tt0056293/,7,0,0,2,0,NaN
3851,http://www.imdb.com/title/tt0058208/,3,0,0,0,0,NaN
4188,http://www.imdb.com/title/tt0060543/,3,0,0,0,0,NaN
4220,http://www.imdb.com/title/tt0060798/,9,0,0,0,0,NaN
4240,http://www.imdb.com/title/tt0060959/,3,0,0,0,0,NaN
4321,http://www.imdb.com/title/tt0061549/,109,0,0,0,0,NaN
4359,http://www.imdb.com/title/tt0061733/,8,0,0,0,0,NaN
4365,http://www.imdb.com/title/tt0061754/,3,0,0,0,0,NaN
4434,http://www.imdb.com/title/tt0062288/,4,0,0,0,0,NaN
4559,http://www.imdb.com/title/tt0063242/,13,0,0,2,5,NaN
4696,http://www.imdb.com/title/tt0064360/,3,0,0,0,0,NaN
4784,http://www.imdb.com/title/tt0065031/,14,0,0,0,0,NaN
4786,http://www.imdb.com/title/tt0065036/,30,0,0,0,0,NaN
4824,http://www.imdb.com/title/tt0065396/,89,2,0,0,0,NaN
4828,http://www.imdb.com/title/tt0065436/,6,0,0,0,0,NaN
4860,http://www.imdb.com/title/tt0065591/,8,0,0,0,0,NaN
4882,http://www.imdb.com/title/tt0065755/,3,0,0,0,0,NaN
4994,http://www.imdb.com/title/tt0066578/,15,4,0,3,0,NaN
5163,http://www.imdb.com/title/tt0067641/,4,0,0,0,0,NaN
5306,http://www.imdb.com/title/tt0068595/,17,0,12,3,4,NaN
5316,http://www.imdb.com/title/tt0068649/,3,0,0,0,2,NaN
5339,http://www.imdb.com/title/tt0068746/,3,0,0,0,0,NaN
5400,http://www.imdb.com/title/tt0069191/,13,0,0,0,2,NaN
5512,http://www.imdb.com/title/tt0070013/,57,0,5,2,0,NaN
...,...,...,...,...,...,...,...
29617,http://www.imdb.com/title/tt6747242/,84,0,0,1,0,NaN
29622,http://www.imdb.com/title/tt6777056/,3,2,0,0,0,NaN
29625,http://www.imdb.com/title/tt6788942/,6,1,0,0,0,NaN
29626,http://www.imdb.com/title/tt6789140/,7,0,0,1,0,NaN
29631,http://www.imdb.com/title/tt6809030/,20,0,0,0,0,NaN
29632,http://www.imdb.com/title/tt6822518/,13,0,0,3,0,NaN
29638,http://www.imdb.com/title/tt6880058/,54,0,0,1,0,NaN
29643,http://www.imdb.com/title/tt6952604/,3,2,0,1,0,NaN
29645,http://www.imdb.com/title/tt6967980/,44,32,0,15,1,NaN
29649,http://www.imdb.com/title/tt6990206/,20,1,0,2,0,NaN
29650,http://www.imdb.com/title/tt6996016/,42,6,0,1,0,NaN
29651,http://www.imdb.com/title/tt7010156/,46,0,0,0,0,NaN
29653,http://www.imdb.com/title/tt7014110/,4,0,0,3,0,NaN
29654,http://www.imdb.com/title/tt7019812/,3,0,0,0,0,NaN
29656,http://www.imdb.com/title/tt7048622/,14,6,2,2,0,NaN
29659,http://www.imdb.com/title/tt7060460/,31,0,0,0,0,NaN
29662,http://www.imdb.com/title/tt7076834/,45,4,3,3,0,NaN
29666,http://www.imdb.com/title/tt7161122/,6,0,0,0,0,NaN
29670,http://www.imdb.com/title/tt7221896/,14,0,0,3,0,NaN
29678,http://www.imdb.com/title/tt7294534/,11,0,0,1,0,NaN
29686,http://www.imdb.com/title/tt7427856/,3,3,2,4,0,NaN
29689,http://www.imdb.com/title/tt7468056/,50,2,0,0,0,NaN
29690,http://www.imdb.com/title/tt7469726/,32,18,0,5,0,NaN
29693,http://www.imdb.com/title/tt7531040/,4,0,0,0,0,NaN
29695,http://www.imdb.com/title/tt7535792/,9,0,0,1,0,NaN
29696,http://www.imdb.com/title/tt7535868/,4,0,0,0,0,NaN
29698,http://www.imdb.com/title/tt7608028/,44,15,0,12,2,NaN
29702,http://www.imdb.com/title/tt7668842/,3,0,0,1,0,NaN
29703,http://www.imdb.com/title/tt7691572/,14,0,0,0,0,NaN
29705,http://www.imdb.com/title/tt7717440/,4,0,0,0,0,NaN

# Combining Into One DataFrame

## Add in Movie Details

In [944]:
gd_df = pd.merge(genre_df,details_df,on=['ID'],left_index=True)

In [945]:
gd_df.sample(20)

,Certificate,Genre,Metascore,Rating,Runtime,Title_x,Votes,Year,ID,Budget,...,Primary Filming Location,Production Company,Release Date,Star1,Star1_URL,Star2,Star2_URL,Star3,Star3_URL,Title_y
http://www.imdb.com/title/tt3824950/,None,"Comedy, Drama, Romance",NaN,5.1,128 min,See You Tomorrow,704,2016,http://www.imdb.com/title/tt3824950/,NaN,...,None,Jet Tone Films,2016-12-29,Tony Chiu-Wai Leung,http://www.imdb.com/name/nm0504897,Takeshi Kaneshiro,http://www.imdb.com/name/nm0437580,Eason Chan,http://www.imdb.com/name/nm0150873,See You Tomorrow
http://www.imdb.com/title/tt0076240/,Not Rated,"Comedy, Drama, Fantasy",NaN,6.1,106 min,Jubilee,2252,1978,http://www.imdb.com/title/tt0076240/,200000.0,...,"St. Saviour's Dock, Southwark, London, England...",Whaley-Malin Productions,1979-09,Jenny Runacre,http://www.imdb.com/name/nm0750192,Nell Campbell,http://www.imdb.com/name/nm0132752,Toyah Willcox,http://www.imdb.com/name/nm0929679,Jubilee
http://www.imdb.com/title/tt0094834/,PG-13,"Action, Adventure, Comedy",NaN,4.8,90 min,Cannibal Women in the Avocado Jungle of Death,2018,1989,http://www.imdb.com/title/tt0094834/,NaN,...,"University of California Botanic Gardens, Rive...",Beyond Infinity,1989-03-15,Shannon Tweed,http://www.imdb.com/name/nm0000238,Bill Maher,http://www.imdb.com/name/nm0005175,Karen M. Waldron,http://www.imdb.com/name/nm0592960,Cannibal Women in the Avocado Jungle of Death
http://www.imdb.com/title/tt0050957/,Approved,"Fantasy, Horror, Romance",NaN,3.2,77 min,The She-Creature,1221,1956,http://www.imdb.com/title/tt0050957/,100000.0,...,"Paradise Cove - 28128 Pacific Coast Highway, M...",Golden State Productions,1956-08,Chester Morris,http://www.imdb.com/name/nm0606431,Tom Conway,http://www.imdb.com/name/nm0007218,Cathy Downs,http://www.imdb.com/name/nm0236157,The She-Creature
http://www.imdb.com/title/tt0097757/,G,"Animation, Family, Fantasy",NaN,7.6,83 min,The Little Mermaid,192791,1989,http://www.imdb.com/title/tt0097757/,40000000.0,...,None,Walt Disney Pictures,1989-11-17,Jodi Benson,http://www.imdb.com/name/nm0072533,Samuel E. Wright,http://www.imdb.com/name/nm0942787,Rene Auberjonois,http://www.imdb.com/name/nm0041281,The Little Mermaid
http://www.imdb.com/title/tt0052295/,None,"Adventure, Drama, Romance",NaN,6.8,101 min,Tiger of Bengal,1896,1959,http://www.imdb.com/title/tt0052295/,4000000.0,...,"CCC-Atelier, Spandau, Berlin, Germany",Central Cinema Company Film (CCC),1960-10,Debra Paget,http://www.imdb.com/name/nm0656428,Paul Hubschmid,http://www.imdb.com/name/nm0007098,Walther Reyer,http://www.imdb.com/name/nm0721195,Der Tiger von Eschnapur
http://www.imdb.com/title/tt0050894/,Unrated,Horror,NaN,6.9,90 min,The Revenge of Frankenstein,3596,1958,http://www.imdb.com/title/tt0050894/,NaN,...,"Bray Studios, Down Place, Oakley Green, Berksh...",Columbia Pictures,1958-06-01,Peter Cushing,http://www.imdb.com/name/nm0001088,Francis Matthews,http://www.imdb.com/name/nm0560022,Eunice Gayson,http://www.imdb.com/name/nm0311013,The Revenge of Frankenstein
http://www.imdb.com/title/tt0913425/,R,"Drama, Romance, Thriller",76.0,7.2,127 min,Broken Embraces,33874,2009,http://www.imdb.com/title/tt0913425/,18000000.0,...,"Arucas, Gran Canaria, Canary Islands, Spain",Universal Pictures International (UPI),2010-01-15,Penélope Cruz,http://www.imdb.com/name/nm0004851,Lluís Homar,http://www.imdb.com/name/nm0392913,Blanca Portillo,http://www.imdb.com/name/nm0692391,Broken Embraces
http://www.imdb.com/title/tt5858514/,G,"Adventure, Family",NaN,9.7,101 min,The Children of Genghis,777,2017,http://www.imdb.com/title/tt5858514/,1200000.0,...,None,EFilm,2017,Brittany Belt,http://www.imdb.com/name/nm2177398,Ankhnyam Ragchaa,http://www.imdb.com/name/nm1921417,Batmend Baast,http://www.imdb.com/name/nm7417944,Chingisiin huuhduud
http://www.imdb.com/title/tt0480687/,R,"Comedy, Romance",45.0,5.9,105 min,Hall Pass,109238,2011,http://www.imdb.com/title/tt0480687/,36000000.0,...,"Falmouth, Massachusetts, USA",New Line Cinema,2011-02-25,Owen Wilson,http://www.imdb.com/name/nm0005562,Jason Sudeikis,http://www.imdb.com/name/nm0837177,Christina Applegate,http://www.imdb.com/name/nm0000775,Hall Pass
http://www.imdb.com/title/tt3896100/,PG,"Animation, Adventure, Comedy",NaN,5.9,94 min,Capture the Flag,2540,2015,http://www.imdb.com/title/tt3896100/,12500000.0,...,None,Paramount Pictures,2015-08-28,Dani Rovira,http://www.imdb.com/name/nm3657043,Michelle Jenner,http://www.imdb.com/name/nm1043338,Carme Calvell,http://www.imdb.com/name/nm7601459,Atrapa la bandera
http://www.imdb.com/title/tt0258489/,None,"Action, Crime, Thriller",NaN,6.8,89 min,Double Tap,710,2000,http://www.imdb.com/title/tt0258489/,NaN,...,None,Golden Harvest Pictures (China),2000-05-27,Leslie Cheung,http://www.imdb.com/name/nm0002000,Alex Fong,http://www.imdb.com/name/nm0284533,Ruby Wong,http://www.imdb.com/name/nm0939315,Cheong wong
http://www.imdb.com/title/tt0286244/,PG-13,"Animation, Comedy, Drama",91.0,7.8,78 min,The Triplets of Belleville,45469,2003,http://www.imdb.com/title/tt0286244/,9500000.0,...,None,Les Armateurs,2004-02-13,Michèle Caucheteux,http://www.imdb.com/name/nm1379544,Jean-Claude Donda,http://www.imdb.com/name/nm0232357,Michel Robin,http://www.imdb.com/name/nm0732220,The Triplets of Belleville
http://www.imdb.com/title/tt0080923/,R,Horror,NaN,6.7,107 min,Inferno,13953,1980,http://www.imdb.com/title/tt0080923/,3000000.0,...,"Biblioteca Angelica, Rome, Lazio, Italy",Produzioni Intersound,1980-04-02,Leigh McCloskey,http://www.imdb.com/name/nm0565907,Irene Miracle,http://www.imdb.com/name/nm0591968,Eleonora Giorgi,http://www.imdb.com/name/nm0320395,Inferno
http://www.imdb.com/title/tt0855805/,None,Drama,NaN,6.6,91 min,Falkenberg Farewell,2530,2006,http://www.imdb.com/title/tt0855805/,300000.0,...,None,Memfis Film,2006-09-22,John Axel Eriksson,http://www.imdb.com/name/nm2379528,Holger Eriksson,http://www.imdb.com/name/nm2374777,David Johnson,http://www.imdb.com/name/nm2375531,Farväl Falkenberg
http://www.imdb.com/title/tt4116284/,PG,"Animation, Action, Adventure",75.0,7.3,104 min,The LEGO Batman Movie,92611,2017,http://www.imdb.com/title/tt4116284/,80000000.0,...,"Fox Studios, Moore Park, Sydney, New South Wal...",DC Entertainment,2017-02-10,Will Arnett,http://www.imdb.com/name/nm0004715,Michael Cera,http://www.imdb.com/name/nm0148418,Rosario Dawson,http://www.imdb.com/name/nm0206257,The LEGO Batman Movie
http://www.imdb.com/title/tt4550098/,R,"Crime, Drama, Romance",67.0,7.5,116 min,Nocturnal Animals,167757,2016,http://www.imdb.com/title/tt4550098/,22500000.0,...,"Los Angeles, California, USA",Focus Features,2016-12-09,Amy Adams,http://www.imdb.com/name/nm0010736,Jake Gyllenhaal,http://www.imdb.com/name/nm0350453,Michael Shannon,http://www.imdb.com/name/nm0788335,Nocturnal Animals
http://www.imdb.com/title/tt1091989/,None,Action,NaN,6.3,121 min,Nepobedimyy,682,2008,http://www.imdb.com/title/tt1091989/,6000000.0,...,Malta,Park Cinema Production,2008-10-23,Vladimir Epifantsev,http://www.imdb.com/name/nm1596785,Sergey Astakhov,http://www.imdb.com/name/nm1427667,Harry Borg,http://www.imdb.com/name/nm1359111,Nepobedimyy
http://www.imdb.com/title/tt1221188/,None,"Drama, Romance",NaN,6.5,92 min,Eloïse's Lover,1401,2009,http://www.imdb.com/title/tt1221188/,NaN,...,"Badalona, Barcelona, Catalonia, Spain",Els Quatre Gats Audiovisuals S.L.,2009-11-06,Diana Gómez,http://www.imdb.com/name/nm1017221,Ariadna Cabrol,http://www.imdb.com/name/nm1779186,Laura Conejero,http://www.imdb.com/name/nm0174495,Eloïse's Lover
http://www.imdb.com/title/tt0056663/,Not Rated,Drama,NaN,8.1,85 min,My Life to Live,21131,1962,http://www.imdb.com/title/tt0056663/,64000.0,...,"Le Rallye Villiers - 3 Place de la Libération,...",Les Films de la Pléiade,1962-09-20,Anna Karina,http://www.imdb.com/name/nm0439344,Sady Rebbot,http://www.imdb.com/name/nm0714236,André S. Labarthe,http://www.imdb.com/name/nm0479351,My Life to Live

In [946]:
len(gd_df)

29717

In [947]:
check_titles = gd_df[gd_df['Title_x'] != gd_df['Title_y']]

In [948]:
check_titles[['Title_x','Title_y','Director']]

,Title_x,Title_y,Director
http://www.imdb.com/title/tt0034928/,The Jungle Book,Jungle Book,Zoltan Korda
http://www.imdb.com/title/tt0055832/,Swords of Blood,Cartouche,Philippe de Broca
http://www.imdb.com/title/tt0058692/,The Black Tulip,La tulipe noire,Christian-Jaque
http://www.imdb.com/title/tt0060330/,Don't Lose Your Head,Carry On... Don't Lose Your Head,Gerald Thomas
http://www.imdb.com/title/tt0061369/,Asterix the Gaul,Astérix le Gaulois,Ray Goossens
http://www.imdb.com/title/tt0061597/,The One-Armed Swordsman,Du bei dao,Cheh Chang
http://www.imdb.com/title/tt0064387/,Goyokin,Goyôkin,Hideo Gosha
http://www.imdb.com/title/tt0065555/,Violent City,The Family,Sergio Sollima
http://www.imdb.com/title/tt0067148/,Godzilla vs. Hedorah,Gojira tai Hedora,Yoshimitsu Banno
http://www.imdb.com/title/tt0073535/,The Night Caller,Peur sur la ville,Henri Verneuil
http://www.imdb.com/title/tt0077292/,Crippled Avengers,Can que,Cheh Chang
http://www.imdb.com/title/tt0077563/,Cop or Hood,Flic ou voyou,Georges Lautner
http://www.imdb.com/title/tt0077864/,Uppercut,Lo chiamavano Bulldozer,Michele Lupo
http://www.imdb.com/title/tt0078187/,Lupin the 3rd: The Mystery of Mamo,Rupan sansei,Sôji Yoshikawa
http://www.imdb.com/title/tt0078243/,The 36th Chamber of Shaolin,Shao Lin san shi liu fang,Chia-Liang Liu
http://www.imdb.com/title/tt0078435/,Message from Space,Uchu kara no messeji,Kinji Fukasaku
http://www.imdb.com/title/tt0079315/,The Fearless Hyena,Xiao quan guai zhao,Jackie Chan
http://www.imdb.com/title/tt0079484/,Dragon Fist,Long quan,Wei Lo
http://www.imdb.com/title/tt0080172/,Shaolin Challenges Ninja,Zhong hua zhang fu,Chia-Liang Liu
http://www.imdb.com/title/tt0081499/,The Young Master,Shi di chu ma,Jackie Chan
http://www.imdb.com/title/tt0084036/,Ironmaster,La guerra del ferro: Ironmaster,Umberto Lenzi
http://www.imdb.com/title/tt0084267/,Ninja in the Dragon's Den,Long zhi ren zhe,Corey Yuen
http://www.imdb.com/title/tt0085327/,Who Finds a Friend Finds a Treasure,Chi trova un amico trova un tesoro,Sergio Corbucci
http://www.imdb.com/title/tt0085994/,Savage Islands,Nate and Hayes,Ferdinand Fairfax
http://www.imdb.com/title/tt0086605/,Winners & Sinners,Qi mou miao ji: Wu fu xing,Sammo Kam-Bo Hung
http://www.imdb.com/title/tt0086606/,The 8 Diagram Pole Fighter,Wu Lang ba gua gun,Chia-Liang Liu
http://www.imdb.com/title/tt0087068/,Code Name: Wild Geese,Geheimcode Wildgänse,Antonio Margheriti
http://www.imdb.com/title/tt0087578/,Wheels on Meals,Kuai can che,Sammo Kam-Bo Hung
http://www.imdb.com/title/tt0089177/,My Lucky Stars,Fuk sing go jiu,Sammo Kam-Bo Hung
http://www.imdb.com/title/tt0089371/,Mr. Vampire,Geung si sin sang,Ricky Lau
...,...,...,...
http://www.imdb.com/title/tt0991351/,Will Not End Here,Nije kraj,Vinko Bresan
http://www.imdb.com/title/tt1034427/,Alexandra,Aleksandra,Aleksandr Sokurov
http://www.imdb.com/title/tt1068664/,The Third Day,Ruz-e-sevom,Mohammad Hossein Latifi
http://www.imdb.com/title/tt1094627/,Buddha Collapsed Out of Shame,Buda as sharm foru rikht,Hana Makhmalbaf
http://www.imdb.com/title/tt1130989/,Long Flat Balls II,Lange flate ballær II,Harald Zwart
http://www.imdb.com/title/tt1249306/,Giovanna's Father,Il papà di Giovanna,Pupi Avati
http://www.imdb.com/title/tt1313230/,In the Name of the Father,Be name pedar,Ebrahim Hatamikia
http://www.imdb.com/title/tt1351672/,The Man Who Will Come,L'uomo che verrà,Giorgio Diritti
http://www.imdb.com/title/tt1388418/,Deportees,Ekhrajiha,Masoud Dehnamaki
http://www.imdb.com/title/tt1508290/,Caterpillar,Kyatapirâ,Kôji Wakamatsu
http://www.imdb.com/title/tt1517805/,20 Cigarettes,20 sigarette,Aureliano Amadei
http://www.imdb.com/title/tt1699202/,4 Days in May,4 Tage im Mai,Achim von Borries
http://www.imdb.com/title/tt1822255/,My Best Enemy,Mein bester Feind,Wolfgang Murnberger
http://www.imdb.com/title/tt2014266/,Hans Kloss: More Than Death at Stake,Hans Kloss. Stawka wieksza niz smierc,Patryk Vega
http://www.imdb.com/title/tt2171815/,Calm at Sea,La mer à l'aube,Volker Schlöndorff
http://www.imdb.com/title/tt2401711/,Time and the Wind,O Tempo e o Vento,Jayme Monjardim
http://www.imdb.com/title/tt3032028/,Inbetween Worlds,Zwischen Welten,Feo Aladag
http://www.imdb.com/title/tt3470928/,Stones for the Rampart,Kamienie na szaniec,Robert Glinski
http://www.imdb.com/title/tt0061636/,Face to Face,Faccia a faccia,Sergio Sollima
http://www.imdb.com/title/tt0062645/,Beyond the Law,Al di là della legge,Giorgio Stegani
http://www.imdb.com/title/tt0063501/,The Big Gundown,La resa dei conti,Sergio Sollima
http://www.imdb.com/title/tt0067672/,Return of Sabata,È tornato Sabata... hai chiuso un'altra volta!,Gianfranco Parolini
http://www.imdb.com/title/tt0069035/,The New Land,Nybyggarna,Jan Troell
http://www.imdb.com/title/tt0071784/,Blood Money,"El kárate, el Colt y el impostor",Antonio Margheriti
http://www.imdb.com/title/tt0074575/,God's Gun,Diamante Lobo,Gianfranco Parolini
http://www.imdb.com/title/tt0082835/,Buddy Goes West,Occhio alla penna,Michele Lupo
http://www.imdb.com/title/tt0093113/,Django Strikes Again,Django 2 - Il grande ritorno,Nello Rossati
http://www.imdb.com/title/tt0136997/,The Unhanged,Hirttämättömät,Vesa-Matti Loiri
http://www.imdb.com/title/tt1388402/,Bad Day to Go Fishing,Mal día para pescar,Álvaro Brechner
http://www.imdb.com/title/tt2140381/,Bald Mountain,Serra Pelada,Heitor Dhalia

In [949]:
gd_df.drop(columns = ['Title_y'],inplace=True)

In [950]:
gd_df.rename(columns={'Title_x':'Title'},inplace=True)

In [954]:
gd_df.columns

Index(['Certificate', 'Genre', 'Metascore', 'Rating', 'Runtime', 'Title',
       'Votes', 'Year', 'ID', 'Budget', 'Country',
       'Cumulative Worldwide Gross', 'Director', 'Director_URL', 'Gross USA',
       'Language', 'Opening Weekend USA', 'Primary Filming Location',
       'Production Company', 'Release Date', 'Star1', 'Star1_URL', 'Star2',
       'Star2_URL', 'Star3', 'Star3_URL'],
      dtype='object')

In [951]:
len(gd_df.columns)

26

In [955]:
gd_df.drop(columns=[
#                     'Certificate', 
#                     'Genre', 
#                     'Metascore', 
#                     'Rating', 
                    'Runtime', 
                    'Title',
                    'Votes', 
#                     'Year', 
#                     'ID', 
#                     'Budget', 
#                     'Country',
#                     'Cumulative Worldwide Gross', 
                    'Director', 
#                     'Director_URL', 
#                     'Gross USA',
#                     'Language', 
#                     'Opening Weekend USA', 
                    'Primary Filming Location',
#                     'Production Company', 
                    'Release Date', 
                    'Star1', 
                    'Star1_URL', 
                    'Star2',
                    'Star2_URL', 
                    'Star3', 
                    'Star3_URL'
                   ],inplace=True)

In [956]:
len(gd_df)

29717

In [957]:
gd_df.head()

,Certificate,Genre,Metascore,Rating,Year,ID,Budget,Country,Cumulative Worldwide Gross,Director_URL,Gross USA,Language,Opening Weekend USA,Production Company
http://www.imdb.com/title/tt0006206/,Not Rated,"Action, Adventure, Crime",NaN,6.9,1915,http://www.imdb.com/title/tt0006206/,NaN,France,NaN,http://www.imdb.com/name/nm0275421,NaN,French,NaN,Société des Etablissements L. Gaumont
http://www.imdb.com/title/tt0009682/,Not Rated,"Action, Adventure",NaN,5.9,1918,http://www.imdb.com/title/tt0009682/,NaN,USA,NaN,http://www.imdb.com/name/nm0796657,3.270000e+06,None,NaN,National Film Corporation of America
http://www.imdb.com/title/tt0015163/,Unrated,"Action, Comedy, Romance",NaN,8.0,1924,http://www.imdb.com/title/tt0015163/,220000.0,USA,NaN,http://www.imdb.com/name/nm0187981,2.958953e+11,None,NaN,Buster Keaton Productions
http://www.imdb.com/title/tt0015324/,Not Rated,"Action, Comedy, Romance",NaN,8.3,1924,http://www.imdb.com/title/tt0015324/,NaN,USA,NaN,http://www.imdb.com/name/nm0000036,NaN,English,NaN,Buster Keaton Productions
http://www.imdb.com/title/tt0017925/,Not Rated,"Action, Adventure, Comedy",NaN,8.2,1926,http://www.imdb.com/title/tt0017925/,750000.0,USA,NaN,http://www.imdb.com/name/nm0115669,NaN,English,NaN,Buster Keaton Productions

## Add in Directors Details

In [991]:
gd_df['Director_URL'][0:4]

http://www.imdb.com/title/tt0006206/    http://www.imdb.com/name/nm0275421
http://www.imdb.com/title/tt0009682/    http://www.imdb.com/name/nm0796657
http://www.imdb.com/title/tt0015163/    http://www.imdb.com/name/nm0187981
http://www.imdb.com/title/tt0015324/    http://www.imdb.com/name/nm0000036
Name: Director_URL, dtype: object

In [992]:
directors_final_df['Director_URL'][0:4]

http://www.imdb.com/name/nm3174584    http://www.imdb.com/name/nm3174584
http://www.imdb.com/name/nm3176551    http://www.imdb.com/name/nm3176551
http://www.imdb.com/name/nm3177320    http://www.imdb.com/name/nm3177320
http://www.imdb.com/name/nm3179860    http://www.imdb.com/name/nm3179860
Name: Director_URL, dtype: object

In [1023]:
gdd_df = pd.merge(gd_df,directors_final_df,on=['Director_URL'],right_index=True)

In [1024]:
gdd_df.sort_values('ID',inplace=True)

In [1025]:
gdd_df.head(50)

,Certificate,Genre,Metascore,Rating,Year,ID,Budget,Country,Cumulative Worldwide Gross,Director_URL,...,Language,Opening Weekend USA,Production Company,Directing Roles Director,Gender Director,Height Director,Publicity Listings Director,TV Appearances Director,Award Nominations and Wins Director,Other Roles Director
http://www.imdb.com/title/tt0002130/,None,"Adventure, Drama, Fantasy",NaN,7.1,1911,http://www.imdb.com/title/tt0002130/,NaN,Italy,NaN,http://www.imdb.com/name/nm0078205,...,Italian,NaN,Milano Film,7,None,NaN,0.0,0.0,0.0,0.0
http://www.imdb.com/title/tt0002423/,None,"Biography, Drama",NaN,6.9,1919,http://www.imdb.com/title/tt0002423/,NaN,Germany,NaN,http://www.imdb.com/name/nm0523932,...,German,NaN,Projektions-AG Union (PAGU),73,Male,1.70,53.0,3.0,9.0,0.0
http://www.imdb.com/title/tt0002844/,Not Rated,"Crime, Drama",NaN,6.9,1913,http://www.imdb.com/title/tt0002844/,NaN,France,NaN,http://www.imdb.com/name/nm0275421,...,French,NaN,Société des Etablissements L. Gaumont,686,Male,NaN,3.0,0.0,0.0,0.0
http://www.imdb.com/title/tt0003037/,Not Rated,"Crime, Drama",NaN,6.8,1913,http://www.imdb.com/title/tt0003037/,NaN,France,NaN,http://www.imdb.com/name/nm0275421,...,French,NaN,Société des Etablissements L. Gaumont,686,Male,NaN,3.0,0.0,0.0,0.0
http://www.imdb.com/title/tt0003165/,Not Rated,"Crime, Drama, Mystery",NaN,6.9,1913,http://www.imdb.com/title/tt0003165/,NaN,France,NaN,http://www.imdb.com/name/nm0275421,...,French,NaN,Société des Etablissements L. Gaumont,686,Male,NaN,3.0,0.0,0.0,0.0
http://www.imdb.com/title/tt0003419/,Approved,"Drama, Fantasy, Horror",NaN,6.6,1913,http://www.imdb.com/title/tt0003419/,NaN,Germany,NaN,http://www.imdb.com/name/nm0917467,...,German,NaN,Deutsche Bioscop GmbH,20,Male,1.98,3.0,1.0,0.0,0.0
http://www.imdb.com/title/tt0003740/,Not Rated,"Adventure, Drama, History",NaN,6.8,1914,http://www.imdb.com/title/tt0003740/,210000.0,Italy,NaN,http://www.imdb.com/name/nm0665163,...,Italian,NaN,Itala Film,20,Male,NaN,0.0,0.0,0.0,0.0
http://www.imdb.com/title/tt0003772/,None,"Fantasy, Drama",NaN,6.7,1914,http://www.imdb.com/title/tt0003772/,NaN,USA,NaN,http://www.imdb.com/name/nm0456804,...,English,NaN,Famous Players Film Company,80,Male,1.83,16.0,5.0,0.0,0.0
http://www.imdb.com/title/tt0004026/,None,Horror,NaN,6.1,1915,http://www.imdb.com/title/tt0004026/,NaN,Germany,NaN,http://www.imdb.com/name/nm0301961,...,German,NaN,Deutsche Bioscop GmbH,12,Male,NaN,2.0,0.0,0.0,0.0
http://www.imdb.com/title/tt0004465/,None,"Action, Adventure, Drama",NaN,7.6,1914,http://www.imdb.com/title/tt0004465/,25000.0,USA,NaN,http://www.imdb.com/name/nm0309163,...,English,NaN,Pathé Frères,103,Male,NaN,13.0,3.0,0.0,0.0
http://www.imdb.com/title/tt0004635/,Not Rated,"Action, Drama, Romance",NaN,6.2,1914,http://www.imdb.com/title/tt0004635/,20000.0,USA,NaN,http://www.imdb.com/name/nm0002177,...,English,NaN,Jesse L. Lasky Feature Play Company,120,Male,NaN,13.0,0.0,0.0,0.0
http://www.imdb.com/title/tt0004972/,Not Rated,"Drama, History, War",NaN,6.7,1915,http://www.imdb.com/title/tt0004972/,100000.0,USA,1.100000e+07,http://www.imdb.com/name/nm0000428,...,None,NaN,David W. Griffith Corp.,520,Male,1.80,160.0,7.0,4.0,0.0
http://www.imdb.com/title/tt0005960/,Passed,"Biography, Crime, Drama",NaN,7.0,1915,http://www.imdb.com/title/tt0005960/,NaN,USA,NaN,http://www.imdb.com/name/nm0909825,...,English,NaN,Fox Film Corporation,139,Male,1.84,41.0,4.0,7.0,93.0
http://www.imdb.com/title/tt0006206/,Not Rated,"Action, Adventure, Crime",NaN,6.9,1915,http://www.imdb.com/title/tt0006206/,NaN,France,NaN,http://www.imdb.com/name/nm0275421,...,French,NaN,Société des Etablissements L. Gaumont,686,Male,NaN,3.0,0.0,0.0,0.0
http://www.imdb.com/title/tt0006333/,Passed,"Action, Adventure, Sci-Fi",NaN,7.0,1916,http://www.imdb.com/title/tt0006333/,200000.0,USA,NaN,http://www.imdb.com/name/nm0665737,...,English,NaN,Williamson Submarine Film Corporation,66,Male,NaN,4.0,0.0,0.0,0.0
http://www.imdb.com/title/tt0006780/,Unrated,"Romance, Western",NaN,6.8,1916,http://www.imdb.com/title/tt0006780/,NaN,USA,NaN,http://www.imdb.com/name/nm0842521,...,English,NaN,Kay-Bee Pictures,42,Male,NaN,2.0,0.0,0.0,0.0
http://www.imdb.com/title/tt0006864/,Not Rated,"Drama, History",NaN,8.0,1916,http://www.imdb.com/title/tt0006864/,385907.0,USA,NaN,http://www.imdb.com/name/nm0000428,...,None,NaN,Triangle Film Corporation,520,Male,1.80,160.0,7.0,4.0,0.0
http://www.imdb.com/title/tt0006886/,None,"Adventure, Crime",NaN,6.7,1916,http://www.imdb.com/title/tt0006886/,NaN,France,NaN,http://www.imdb.com/name/nm0275421,...,French,NaN,Société des Etablissements L. Gaumont,686,Male,NaN,3.0,0.0,0.0,0.0
http://www.imdb.com/title/tt0008188/,None,"Drama, Romance, War",NaN,6.5,1917,http://www.imdb.com/title/tt0008188/,166949.0,USA,4.462370e+05,http://www.imdb.com/name/nm0001124,...,English,NaN,Mary Pickford Company,80,Male,1.78,120.0,30.0,20.0,0.0
http://www.imdb.com/title/tt0008443/,None,"Comedy, Drama, Family",NaN,6.8,1917,http://www.imdb.com/title/tt0008443/,NaN,USA,NaN,http://www.imdb.com/name/nm0869665,...,English,NaN,Artcraft Pictures Corporation,98,Male,NaN,36.0,4.0,3.0,0.0
http://www.imdb.com/title/tt0008519/,None,"Adventure, Comedy, Drama",NaN,6.6,1917,http://www.imdb.com/title/tt0008519/,134832.0,USA,NaN,http://www.imdb.com/name/nm0001124,...,None,NaN,Artcraft Pictures Corporation,80,Male,1.78,120.0,30.0,20.0,0.0
http://www.imdb.com/title/tt0008663/,None,"Drama, War",NaN,7.4,1917,http://www.imdb.com/title/tt0008663/,60000.0,Sweden,NaN,http://www.imdb.com/name/nm0803705,...,None,NaN,Svenska Biografteatern AB,55,Male,1.80,17.0,2.0,5.0,0.0
http://www.imdb.com/title/tt0008891/,None,Fantasy,NaN,7.0,1918,http://www.imdb.com/title/tt0008891/,NaN,USA,NaN,http://www.imdb.com/name/nm0869665,...,English,NaN,Paramount Pictures,98,Male,NaN,36.0,4.0,3.0,0.0
http://www.imdb.com/title/tt0009150/,TV-PG,"Drama, War",NaN,6.6,1918,http://www.imdb.com/title/tt0009150/,NaN,USA,NaN,http://www.imdb.com/name/nm0000428,...,English,NaN,D.W. Griffith Productions,520,Male,1.80,160.0,7.0,4.0,0.0
http://www.imdb.com/title/tt0009611/,Not Rated,"Comedy, War",NaN,6.9,1918,http://www.imdb.com/title/tt0009611/,NaN,USA,NaN,http://www.imdb.com/name/nm0000122,...,English,NaN,Charles Chaplin Productions,71,Male,1.65,275.0,31.0,27.0,0.0
http://www.imdb.com/title/tt0009682/,Not Rated,"Action, Adventure",NaN,5.9,1918,http://www.imdb.com/title/tt0009682/,NaN,USA,NaN,http://www.imdb.com/name/nm0796657,...,None,NaN,National Film Corporation of America,120,Male,NaN,7.0,0.0,0.0,0.0
http://www.imdb.com/title/tt0009878/,Not Rated,"Crime, Drama, History",NaN,6.9,1919,http://www.imdb.com/title/tt0009878/,NaN,Germany,NaN,http://www.imdb.com/name/nm0652650,...,English,NaN,Richard-Oswald-Produktion,114,Male,NaN,1.0,1.0,0.0,0.0
http://www.imdb.com/title/tt0009892/,None,"Drama, History, Romance",NaN,6.6,1919,http://www.imdb.com/title/tt0009892/,NaN,USA,NaN,http://www.imdb.com/name/nm0002177,...,None,NaN,First National Pictures,120,Male,NaN,13.0,0.0,0.0,0.0
http://www.imdb.com/title/tt0009900/,Unrated,"Adventure, Romance",NaN,6.9,1919,http://www.imdb.com/title/tt0009900/,67000.0,Canada,NaN,http://www.imdb.com/name/nm0366689,...,None,NaN,Canadian Photoplays Ltd.,19,Male,1.80,2.0,1.0,0.0,0.0
http://www.imdb.com/title/tt0009937/,Not Rated,"Drama, Romance",NaN,6.9,1919,http://www.imdb.com/title/tt0009937/,42000.0,USA,1.000000e+11,http://www.imdb.com/name/nm0002233,...,English,NaN,Universal Film Manufacturing Company,12,Male,1.68,42.0,9.0,5.0,0.0
http://www.imdb.com/title/tt0009968/,Not Rated,"Drama, Romance",NaN,7.6,1919,http://www.imdb.com/title/tt0009968/,88000.0,USA,NaN,http://www.imdb.com/name/nm0000428,...,None,NaN,D.W. Griffith Productions,520,Male,1.80,160.0,7.0,4.0,0.0
http://www.imdb.com/title/tt0009976/,Not Rated,"Drama, Sport",NaN,6.6,1919,http://www.imdb.com/title/tt0009976/,NaN,USA,NaN,http://www.imdb.com/name/nm0832584,...,English,NaN,Thomas H. Ince Corporation,47,Male,NaN,16.0,0.0,0.0,0.0
http://www.imdb.com/title/tt0010247/,None,"Drama, History",NaN,7.2,1919,http://www.imdb.com/title/tt0010247/,NaN,Sweden,NaN,http://www.imdb.com/name/nm0830249,...,Swedish,NaN,Svenska Biografteatern AB,48,Male,NaN,3.0,0.0,1.0,0.0
http://www.imdb.com/title/tt0010281/,Not Rated,"Comedy, Romance",NaN,7.1,1918,http://www.imdb.com/title/tt0010281/,NaN,Germany,NaN,http://www.imdb.com/name/nm0523932,...,German,NaN,Projektions-AG Union (PAGU),73,Male,1.70,53.0,3.0,9.0,0.0
http://www.imdb.com/title/tt0010307/,None,"Drama, Horror, War",NaN,7.3,1919,http://www.imdb.com/title/tt0010307/,NaN,France,NaN,http://www.imdb.com/name/nm0304098,...,French,NaN,Pathé Frères,52,Male,NaN,13.0,10.0,5.0,0.0
http://www.imdb.com/title/tt0010323/,Not Rated,"Fantasy, Horror, Mystery",NaN,8.1,1920,http://www.imdb.com/title/tt0010323/,18000.0,Germany,NaN,http://www.imdb.com/name/nm0927468,...,None,NaN,Decla-Bioscop AG,52,Male,NaN,1.0,1.0,0.0,0.0
http://www.imdb.com/title/tt0010418/,Not Rated,"Adventure, Drama",NaN,7.9,1919,http://www.imdb.com/title/tt0010418/,NaN,USA,NaN,http://www.imdb.com/name/nm0001124,...,English,NaN,Paramount Pictures,80,Male,1.78,120.0,30.0,20.0,0.0
http://www.imdb.com/title/tt0010600/,Not Rated,"Comedy, Fantasy",NaN,7.3,1919,http://www.imdb.com/title/tt0010600/,NaN,Germany,NaN,http://www.imdb.com/name/nm0523932,...,None,NaN,Projektions-AG Union (PAGU),73,Male,1.70,53.0,3.0,9.0,0.0
http://www.imdb.com/title/tt0010635/,Passed,"Comedy, Drama, Sport",NaN,6.6,1919,http://www.imdb.com/title/tt0010635/,NaN,USA,NaN,http://www.imdb.com/name/nm0190516,...,English,NaN,Paramount Pictures,74,Male,NaN,26.0,1.0,2.0,0.0
http://www.imdb.com/title/tt0010726/,Not Rated,"Adventure, Western",NaN,6.6,1919,http://www.imdb.com/title/tt0010726/,NaN,Germany,NaN,http://www.imdb.com/name/nm0000485,...,None,NaN,Decla-Bioscop AG,46,Male,1.80,42.0,15.0,8.0,0.0
http://www.imdb.com/title/tt0011130/,Unrated,"Drama, Horror, Sci-Fi",NaN,7.0,1920,http://www.imdb.com/title/tt0011130/,NaN,USA,NaN,http://www.imdb.com/name/nm0731910,...,English,NaN,Famous Players-Lasky Corporation,61,Male,1.83,9.0,1.0,0.0,0.0
http://www.imdb.com/title/tt0011157/,Not Rated,"Comedy, Romance",NaN,6.7,1920,http://www.imdb.com/title/tt0011157/,NaN,Sweden,NaN,http://www.imdb.com/name/nm0830249,...,Swedish,NaN,Svensk Filmindustri (SF),48,Male,NaN,3.0,0.0,1.0,0.0
http://www.imdb.com/title/tt0011221/,None,Horror,NaN,6.0,1920,http://www.imdb.com/title/tt0011221/,NaN,Germany,NaN,http://www.imdb.com/name/nm0927468,...,German,NaN,Decla-Bioscop AG,52,Male,NaN,1.0,1.0,0.0,0.0
http://www.imdb.com/title/tt0011237/,Unrated,"Fantasy, Horror",NaN,7.2,1920,http://www.imdb.com/title/tt0011237/,NaN,Germany,NaN,http://www.imdb.com/name/nm0091380,...,None,NaN,Projektions-AG Union (PAGU),161,Male,NaN,0.0,0.0,0.0,0.0
http://www.imdb.com/title/tt0011387/,Not Rated,"Adventure, Drama",NaN,6.9,1920,http://www.imdb.com/title/tt0011387/,NaN,USA,NaN,http://www.imdb.com/name/nm0113284,...,English,NaN,Maurice Tourneur Productions,53,Male,NaN,16.0,3.0,10.0,0.0
http://www.imdb.com/title/tt0011439/,Not Rated,"Adventure, Romance, Western",NaN,7.3,1920,http://www.imdb.com/title/tt0011439/,NaN,USA,NaN,http://www.imdb.com/name/nm0629243,...,None,NaN,Douglas Fairbanks Pictures,44,Male,1.83,23.0,8.0,1.0,0.0
http://www.imdb.com/title/tt0011565/,Passed,"Crime, Drama, Horror",NaN,7.5,1920,http://www.imdb.com/title/tt0011565/,88868.0,USA,NaN,http://www.imdb.com/name/nm0941637,...,English,NaN,Eminent Authors Pictures Inc.,29,Male,NaN,5.0,0.0,0.0,0.0
http://www.imdb.com/title/tt0011607/,TV-14,"Comedy, Drama, Horror",NaN,7.4,1920,http://www.imdb.com/title/tt0011607/,NaN,Sweden,NaN,http://www.imdb.com/name/nm0003433,...,Swedish,NaN,Svensk Filmindustri (SF),22,Male,1.70,14.0,6.0,6.0,0.0
http://www.imdb.com/title/tt0011723/,None,Adventure,NaN,6.5,1920,http://www.imdb.com/title/tt0011723/,NaN,Germany,NaN,http://www.imdb.com/name/nm0000485,...,None,NaN,Decla-Film-Gesellschaft Holz & Co.,46,Male,1.80,42.0,15.0,8.0,0.0
http://www.imdb.com/title/tt0011742/,Not Rated,"Adventure, Drama, Romance",NaN,6.3,1920,http://www.imdb.com/title/tt0011742/,NaN,Germany,NaN,http://www.imdb.com/name/nm0523932,...,German,NaN,Projektions-AG Union (PAGU),73,Male,1.70,53.0,3.0,9.0,0.0

In [1026]:
len(gdd_df)

29711

In [1027]:
len(gdd_df.columns)

21

In [1028]:
gdd_df.columns

Index(['Certificate', 'Genre', 'Metascore', 'Rating', 'Year', 'ID', 'Budget',
       'Country', 'Cumulative Worldwide Gross', 'Director_URL', 'Gross USA',
       'Language', 'Opening Weekend USA', 'Production Company',
       'Directing Roles Director', 'Gender Director', 'Height Director',
       'Publicity Listings Director', 'TV Appearances Director',
       'Award Nominations and Wins Director', 'Other Roles Director'],
      dtype='object')

## Add in Stars Details

In [1058]:
gdd_df['ID'][0:4]

http://www.imdb.com/title/tt0002130/    http://www.imdb.com/title/tt0002130/
http://www.imdb.com/title/tt0002423/    http://www.imdb.com/title/tt0002423/
http://www.imdb.com/title/tt0002844/    http://www.imdb.com/title/tt0002844/
http://www.imdb.com/title/tt0003037/    http://www.imdb.com/title/tt0003037/
Name: ID, dtype: object

In [1059]:
stars_final_df['ID'][0:4]

0    http://www.imdb.com/title/tt0002130/
1    http://www.imdb.com/title/tt0002423/
2    http://www.imdb.com/title/tt0002844/
3    http://www.imdb.com/title/tt0003037/
Name: ID, dtype: object

In [1060]:
gdds_df = pd.merge(gdd_df,stars_final_df,on=['ID'],right_index=True)

In [1061]:
gdds_df.sample(50)

,Certificate,Genre,Metascore,Rating,Year,ID,Budget,Country,Cumulative Worldwide Gross,Director_URL,...,Publicity Listings Director,TV Appearances Director,Award Nominations and Wins Director,Other Roles Director,Acting Roles Stars Cumulative,Award Nominations and Wins Stars Cumulative,Other Roles Stars Cumulative,TV Appearances Stars Cumulative,Publicity Listings Stars Cumulative,Diversity Index
http://www.imdb.com/title/tt0110684/,R,"Comedy, Drama",86.0,7.4,1994,http://www.imdb.com/title/tt0110684/,2.000000e+07,USA,NaN,http://www.imdb.com/name/nm0000914,...,2.0,24.0,55.0,0.0,200,188,17,380,294,61.868687
http://www.imdb.com/title/tt2358911/,TV-MA,"Animation, Action, Adventure",NaN,7.9,2012,http://www.imdb.com/title/tt2358911/,NaN,Japan,NaN,http://www.imdb.com/name/nm0473549,...,0.0,1.0,2.0,0.0,167,20,3,7,3,24.494949
http://www.imdb.com/title/tt4818804/,None,"Comedy, Drama",NaN,6.7,2016,http://www.imdb.com/title/tt4818804/,NaN,Belgium,NaN,http://www.imdb.com/name/nm0112456,...,0.0,1.0,71.0,0.0,127,11,0,16,0,33.459596
http://www.imdb.com/title/tt0429493/,PG-13,"Action, Adventure, Comedy",47.0,6.8,2010,http://www.imdb.com/title/tt0429493/,1.100000e+08,USA,1.772388e+14,http://www.imdb.com/name/nm0138620,...,1.0,29.0,7.0,0.0,199,169,16,382,98,42.045455
http://www.imdb.com/title/tt0045073/,Approved,"Drama, Sci-Fi",NaN,4.9,1952,http://www.imdb.com/title/tt0045073/,NaN,USA,NaN,http://www.imdb.com/name/nm0395105,...,2.0,0.0,3.0,0.0,168,8,0,59,16,50.883838
http://www.imdb.com/title/tt1329404/,PG-13,"Adventure, Horror, Mystery",NaN,3.8,2012,http://www.imdb.com/title/tt1329404/,NaN,USA,NaN,http://www.imdb.com/name/nm0150170,...,0.0,0.0,0.0,0.0,110,0,0,0,0,30.429293
http://www.imdb.com/title/tt0109370/,PG,Comedy,NaN,5.9,1995,http://www.imdb.com/title/tt0109370/,1.100000e+07,USA,NaN,http://www.imdb.com/name/nm0601619,...,111.0,136.0,76.0,0.0,132,140,16,276,37,38.636364
http://www.imdb.com/title/tt0040558/,Passed,"Drama, History, War",NaN,7.6,1948,http://www.imdb.com/title/tt0040558/,9.000000e+05,USA,NaN,http://www.imdb.com/name/nm0000080,...,148.0,151.0,42.0,223.0,265,50,79,165,160,36.363636
http://www.imdb.com/title/tt2236182/,TV-14,"Action, Horror, Thriller",NaN,4.0,2012,http://www.imdb.com/title/tt2236182/,NaN,USA,NaN,http://www.imdb.com/name/nm0528963,...,3.0,0.0,4.0,0.0,143,67,18,241,72,40.530303
http://www.imdb.com/title/tt0065466/,NC-17,"Comedy, Drama, Music",NaN,6.2,1970,http://www.imdb.com/title/tt0065466/,9.000000e+05,USA,NaN,http://www.imdb.com/name/nm0000540,...,33.0,21.0,1.0,106.0,3,0,0,26,33,57.828283
http://www.imdb.com/title/tt0283026/,PG-13,"Drama, Thriller",29.0,5.0,2002,http://www.imdb.com/title/tt0283026/,8.500000e+06,USA,NaN,http://www.imdb.com/name/nm0689852,...,3.0,11.0,11.0,0.0,54,17,8,95,31,34.848485
http://www.imdb.com/title/tt0996930/,None,"Drama, Romance",NaN,7.1,2008,http://www.imdb.com/title/tt0996930/,NaN,France,NaN,http://www.imdb.com/name/nm0065449,...,0.0,13.0,12.0,0.0,150,33,0,80,2,59.217172
http://www.imdb.com/title/tt2781832/,R,Horror,NaN,5.7,2013,http://www.imdb.com/title/tt2781832/,NaN,UK,NaN,http://www.imdb.com/name/nm3283841,...,0.0,0.0,0.0,0.0,129,3,6,19,0,37.878788
http://www.imdb.com/title/tt0045468/,Approved,"Comedy, Fantasy, Sci-Fi",NaN,6.4,1953,http://www.imdb.com/title/tt0045468/,7.540000e+05,USA,NaN,http://www.imdb.com/name/nm0006943,...,5.0,1.0,0.0,0.0,181,7,0,33,45,16.792929
http://www.imdb.com/title/tt1885331/,Not Rated,"Comedy, Romance",36.0,6.1,2012,http://www.imdb.com/title/tt1885331/,NaN,France,NaN,http://www.imdb.com/name/nm1523943,...,0.0,0.0,0.0,0.0,56,3,0,139,13,39.772727
http://www.imdb.com/title/tt2170593/,PG-13,"Comedy, Drama",64.0,7.3,2014,http://www.imdb.com/title/tt2170593/,1.300000e+07,USA,5.483723e+12,http://www.imdb.com/name/nm0577647,...,6.0,3.0,19.0,0.0,89,369,14,316,162,52.020202
http://www.imdb.com/title/tt0094712/,R,"Drama, War",NaN,6.4,1988,http://www.imdb.com/title/tt0094712/,NaN,USA,NaN,http://www.imdb.com/name/nm0548533,...,0.0,0.0,6.0,0.0,313,139,45,349,36,17.171717
http://www.imdb.com/title/tt1800338/,None,Drama,NaN,7.1,2014,http://www.imdb.com/title/tt1800338/,NaN,Netherlands,NaN,http://www.imdb.com/name/nm0644309,...,0.0,8.0,39.0,0.0,87,17,0,16,3,39.772727
http://www.imdb.com/title/tt0047119/,Approved,"Crime, Drama, Mystery",NaN,7.5,1954,http://www.imdb.com/title/tt0047119/,NaN,UK,NaN,http://www.imdb.com/name/nm0357891,...,2.0,26.0,3.0,0.0,113,1,0,1,17,22.979798
http://www.imdb.com/title/tt0427152/,PG-13,Comedy,56.0,5.9,2010,http://www.imdb.com/title/tt0427152/,NaN,USA,8.685574e+07,http://www.imdb.com/name/nm0005366,...,2.0,37.0,20.0,0.0,183,185,12,338,64,30.429293
http://www.imdb.com/title/tt3922754/,Unrated,"Action, War",NaN,2.2,2014,http://www.imdb.com/title/tt3922754/,NaN,USA,NaN,http://www.imdb.com/name/nm0493295,...,0.0,1.0,0.0,0.0,80,1,24,8,2,33.333333
http://www.imdb.com/title/tt7399470/,None,"Comedy, Romance",NaN,7.2,2017,http://www.imdb.com/title/tt7399470/,NaN,India,NaN,http://www.imdb.com/name/nm0151511,...,0.0,0.0,0.0,0.0,150,49,5,8,0,44.444444
http://www.imdb.com/title/tt1087832/,None,"Action, Adventure",NaN,4.7,2007,http://www.imdb.com/title/tt1087832/,4.000000e+08,Russia,NaN,http://www.imdb.com/name/nm1475358,...,0.0,0.0,0.0,0.0,162,27,24,58,6,45.454545
http://www.imdb.com/title/tt0451094/,R,"Crime, Drama, Thriller",75.0,7.6,2005,http://www.imdb.com/title/tt0451094/,4.200000e+09,South Korea,NaN,http://www.imdb.com/name/nm0661791,...,3.0,11.0,110.0,0.0,36,43,0,2,2,32.070707
http://www.imdb.com/title/tt0974661/,PG-13,"Comedy, Drama, Family",48.0,6.4,2009,http://www.imdb.com/title/tt0974661/,2.000000e+07,USA,1.362675e+13,http://www.imdb.com/name/nm0824882,...,0.0,8.0,8.0,0.0,110,98,7,332,77,29.040404
http://www.imdb.com/title/tt0092991/,R,"Comedy, Horror",69.0,7.8,1987,http://www.imdb.com/title/tt0092991/,3.600000e+06,USA,NaN,http://www.imdb.com/name/nm0000600,...,18.0,44.0,33.0,124.0,157,18,29,93,25,31.186869
http://www.imdb.com/title/tt0345551/,R,"Comedy, Drama, Romance",45.0,7.1,2003,http://www.imdb.com/title/tt0345551/,8.500000e+05,USA,NaN,http://www.imdb.com/name/nm0184947,...,0.0,2.0,3.0,18.0,57,10,0,24,2,34.722222
http://www.imdb.com/title/tt1791681/,None,"Horror, Mystery, Thriller",NaN,3.9,2014,http://www.imdb.com/title/tt1791681/,3.250000e+06,UK,NaN,http://www.imdb.com/name/nm2408930,...,0.0,2.0,0.0,0.0,79,2,2,0,5,34.595960
http://www.imdb.com/title/tt0056014/,None,"Comedy, Crime",NaN,6.3,1962,http://www.imdb.com/title/tt0056014/,NaN,France,NaN,http://www.imdb.com/name/nm0335093,...,0.0,3.0,1.0,0.0,160,13,0,22,38,27.146465
http://www.imdb.com/title/tt0113957/,PG-13,"Action, Crime, Drama",51.0,5.9,1995,http://www.imdb.com/title/tt0113957/,2.200000e+07,USA,1.106280e+08,http://www.imdb.com/name/nm0005563,...,1.0,46.0,21.0,0.0,75,240,15,295,229,37.500000
http://www.imdb.com/title/tt0089572/,R,"Crime, Thriller",NaN,6.1,1985,http://www.imdb.com/title/tt0089572/,7.000000e+06,USA,NaN,http://www.imdb.com/name/nm0097491,...,0.0,0.0,9.0,0.0,152,30,0,202,78,31.313131
http://www.imdb.com/title/tt0337598/,Not Rated,"Horror, Mystery",NaN,2.7,2004,http://www.imdb.com/title/tt0337598/,NaN,UK,NaN,http://www.imdb.com/name/nm1266897,...,0.0,2.0,0.0,0.0,310,5,0,36,4,48.232323
http://www.imdb.com/title/tt1232776/,Not Rated,Drama,81.0,7.3,2009,http://www.imdb.com/title/tt1232776/,NaN,UK,NaN,http://www.imdb.com/name/nm0036349,...,0.0,10.0,86.0,0.0,60,233,0,89,40,50.126263
http://www.imdb.com/title/tt0107889/,R,"Action, Drama, Sport",NaN,6.4,1993,http://www.imdb.com/title/tt0107889/,1.500000e+07,USA,NaN,http://www.imdb.com/name/nm0911486,...,1.0,7.0,11.0,0.0,166,168,0,417,266,34.722222
http://www.imdb.com/title/tt0492881/,R,"Action, Comedy, Crime",NaN,4.7,2008,http://www.imdb.com/title/tt0492881/,NaN,USA,NaN,http://www.imdb.com/name/nm0425364,...,0.0,0.0,8.0,0.0,67,9,0,52,9,40.151515
http://www.imdb.com/title/tt0084109/,PG,"Comedy, Drama",NaN,6.2,1982,http://www.imdb.com/title/tt0084109/,NaN,USA,NaN,http://www.imdb.com/name/nm0006889,...,2.0,17.0,10.0,0.0,107,70,9,266,86,58.080808
http://www.imdb.com/title/tt1555064/,PG-13,"Drama, Music",45.0,6.3,2010,http://www.imdb.com/title/tt1555064/,1.500000e+07,USA,2.052919e+07,http://www.imdb.com/name/nm0275277,...,0.0,1.0,2.0,0.0,26,91,4,266,342,38.636364
http://www.imdb.com/title/tt0481499/,PG,"Animation, Action, Adventure",55.0,7.2,2013,http://www.imdb.com/title/tt0481499/,1.350000e+08,USA,5.872047e+08,http://www.imdb.com/name/nm0210320,...,0.0,5.0,8.0,0.0,164,335,14,367,183,42.424242
http://www.imdb.com/title/tt0080549/,PG,"Biography, Drama, Music",87.0,7.5,1980,http://www.imdb.com/title/tt0080549/,NaN,USA,NaN,http://www.imdb.com/name/nm0000776,...,4.0,54.0,39.0,0.0,101,220,8,194,80,25.631313
http://www.imdb.com/title/tt3014910/,None,"Drama, History",57.0,5.9,2016,http://www.imdb.com/title/tt3014910/,8.500000e+06,UK,NaN,http://www.imdb.com/name/nm0399853,...,2.0,20.0,18.0,0.0,196,32,5,125,46,39.772727
http://www.imdb.com/title/tt0089338/,None,"Adventure, Horror, Thriller",NaN,5.9,1985,http://www.imdb.com/title/tt0089338/,NaN,Italy,NaN,http://www.imdb.com/name/nm0219959,...,6.0,29.0,1.0,0.0,83,8,6,38,13,27.146465
http://www.imdb.com/title/tt0037465/,Unrated,"Biography, Drama, History",NaN,6.8,1944,http://www.imdb.com/title/tt0037465/,4.000000e+06,USA,NaN,http://www.imdb.com/name/nm0454771,...,17.0,7.0,15.0,0.0,193,14,0,39,26,58.080808
http://www.imdb.com/title/tt1244668/,None,"Comedy, Drama",76.0,7.3,2009,http://www.imdb.com/title/tt1244668/,4.000000e+06,Germany,NaN,http://www.imdb.com/name/nm0015359,...,2.0,23.0,76.0,0.0,145,22,0,32,3,37.121212
http://www.imdb.com/title/tt0040098/,Approved,"Drama, Romance",NaN,6.7,1948,http://www.imdb.com/title/tt0040098/,NaN,UK,NaN,http://www.imdb.com/name/nm0245213,...,1.0,4.0,15.0,0.0,142,27,2,54,71,52.777778
http://www.imdb.com/title/tt0462579/,Not Rated,"Comedy, Drama, Romance",54.0,5.9,2006,http://www.imdb.com/title/tt0462579/,9.000000e+05,USA,NaN,http://www.imdb.com/name/nm0748589,...,1.0,0.0,9.0,0.0,171,58,8,124,99,57.323232
http://www.imdb.com/title/tt1303828/,R,"Comedy, Crime, Drama",57.0,6.8,2009,http://www.imdb.com/title/tt1303828/,3.500000e+06,Canada,NaN,http://www.imdb.com/name/nm0824220,...,1.0,1.0,10.0,0.0,96,163,3,251,68,53.914141
http://www.imdb.com/title/tt0337563/,PG-13,"Comedy, Fantasy, Romance",57.0,6.1,2004,http://www.imdb.com/title/tt0337563/,3.700000e+07,USA,3.922395e+07,http://www.imdb.com/name/nm0935095,...,1.0,8.0,9.0,0.0,68,213,14,311,105,36.363636
http://www.imdb.com/title/tt1268987/,R,"Action, Comedy",NaN,4.9,2010,http://www.imdb.com/title/tt1268987/,NaN,USA,NaN,http://www.imdb.com/name/nm3087552,...,0.0,0.0,0.0,0.0,129,27,6,125,27,43.939394
http://www.imdb.com/title/tt0808276/,Not Rated,"Horror, Thriller",NaN,6.3,2006,http://www.imdb.com/title/tt0808276/,NaN,Norway,NaN,http://www.imdb.com/name/nm1012385,...,0.0,0.0,5.0,0.0,30,5,0,8,0,28.914141
http://www.imdb.com/title/tt0482606/,R,"Horror, Mystery, Thriller",47.0,6.2,2008,http://www.imdb.com/title/tt0482606/,1.000000e+07,USA,8.239114e+07,http://www.imdb.com/name/nm1052162,...,0.0,0.0,3.0,0.0,41,46,0,106,154,60.101010

In [1035]:
gdds_df.columns

Index(['Certificate', 'Genre', 'Metascore', 'Rating', 'Year', 'ID', 'Budget',
       'Country', 'Cumulative Worldwide Gross', 'Director_URL', 'Gross USA',
       'Language', 'Opening Weekend USA', 'Production Company',
       'Directing Roles Director', 'Gender Director', 'Height Director',
       'Publicity Listings Director', 'TV Appearances Director',
       'Award Nominations and Wins Director', 'Other Roles Director',
       'Acting Roles Stars Cumulative',
       'Award Nominations and Wins Stars Cumulative',
       'Other Roles Stars Cumulative', 'TV Appearances Stars Cumulative',
       'Publicity Listings Stars Cumulative', 'Diversity Index'],
      dtype='object')

In [1063]:
gdds_df[gdds_df.index != gdds_df['ID']]

Empty DataFrame
Columns: [Certificate, Genre, Metascore, Rating, Year, ID, Budget, Country, Cumulative Worldwide Gross, Director_URL, Gross USA, Language, Opening Weekend USA, Production Company, Directing Roles Director, Gender Director, Height Director, Publicity Listings Director, TV Appearances Director, Award Nominations and Wins Director, Other Roles Director, Acting Roles Stars Cumulative, Award Nominations and Wins Stars Cumulative, Other Roles Stars Cumulative, TV Appearances Stars Cumulative, Publicity Listings Stars Cumulative, Diversity Index]
Index: []

[0 rows x 27 columns]

In [1064]:
gdds_df.drop(columns=['ID','Director_URL'])

,Certificate,Genre,Metascore,Rating,Year,Budget,Country,Cumulative Worldwide Gross,Gross USA,Language,...,Publicity Listings Director,TV Appearances Director,Award Nominations and Wins Director,Other Roles Director,Acting Roles Stars Cumulative,Award Nominations and Wins Stars Cumulative,Other Roles Stars Cumulative,TV Appearances Stars Cumulative,Publicity Listings Stars Cumulative,Diversity Index
http://www.imdb.com/title/tt0002130/,None,"Adventure, Drama, Fantasy",NaN,7.1,1911,NaN,Italy,NaN,NaN,Italian,...,0.0,0.0,0.0,0.0,37,0,92,0,0,33.333333
http://www.imdb.com/title/tt0002423/,None,"Biography, Drama",NaN,6.9,1919,NaN,Germany,NaN,NaN,German,...,53.0,3.0,9.0,0.0,245,6,6,12,79,50.126263
http://www.imdb.com/title/tt0002844/,Not Rated,"Crime, Drama",NaN,6.9,1913,NaN,France,NaN,NaN,French,...,3.0,0.0,0.0,0.0,269,0,8,0,1,26.767677
http://www.imdb.com/title/tt0003037/,Not Rated,"Crime, Drama",NaN,6.8,1913,NaN,France,NaN,NaN,French,...,3.0,0.0,0.0,0.0,269,0,8,0,1,26.767677
http://www.imdb.com/title/tt0003165/,Not Rated,"Crime, Drama, Mystery",NaN,6.9,1913,NaN,France,NaN,NaN,French,...,3.0,0.0,0.0,0.0,269,0,8,0,1,26.767677
http://www.imdb.com/title/tt0003419/,Approved,"Drama, Fantasy, Horror",NaN,6.6,1913,NaN,Germany,NaN,NaN,German,...,3.0,1.0,0.0,0.0,73,0,23,1,4,61.237374
http://www.imdb.com/title/tt0003740/,Not Rated,"Adventure, Drama, History",NaN,6.8,1914,210000.0,Italy,NaN,NaN,Italian,...,0.0,0.0,0.0,0.0,34,0,0,0,5,38.257576
http://www.imdb.com/title/tt0003772/,None,"Fantasy, Drama",NaN,6.7,1914,NaN,USA,NaN,NaN,English,...,16.0,5.0,0.0,0.0,288,4,39,45,193,62.373737
http://www.imdb.com/title/tt0004026/,None,Horror,NaN,6.1,1915,NaN,Germany,NaN,NaN,German,...,2.0,0.0,0.0,0.0,78,0,23,1,6,39.015152
http://www.imdb.com/title/tt0004465/,None,"Action, Adventure, Drama",NaN,7.6,1914,25000.0,USA,NaN,NaN,English,...,13.0,3.0,0.0,0.0,484,2,0,6,58,39.772727
http://www.imdb.com/title/tt0004635/,Not Rated,"Action, Drama, Romance",NaN,6.2,1914,20000.0,USA,NaN,5.334460e+05,English,...,13.0,0.0,0.0,0.0,87,1,0,3,35,40.909091
http://www.imdb.com/title/tt0004972/,Not Rated,"Drama, History, War",NaN,6.7,1915,100000.0,USA,1.100000e+07,1.000000e+07,None,...,160.0,7.0,4.0,0.0,330,14,2,54,139,39.393939
http://www.imdb.com/title/tt0005960/,Passed,"Biography, Crime, Drama",NaN,7.0,1915,NaN,USA,NaN,NaN,English,...,41.0,4.0,7.0,93.0,77,1,0,11,32,46.717172
http://www.imdb.com/title/tt0006206/,Not Rated,"Action, Adventure, Crime",NaN,6.9,1915,NaN,France,NaN,NaN,French,...,3.0,0.0,0.0,0.0,192,0,10,1,1,37.878788
http://www.imdb.com/title/tt0006333/,Passed,"Action, Adventure, Sci-Fi",NaN,7.0,1916,200000.0,USA,NaN,8.000000e+06,English,...,4.0,0.0,0.0,0.0,42,0,37,1,10,52.777778
http://www.imdb.com/title/tt0006780/,Unrated,"Romance, Western",NaN,6.8,1916,NaN,USA,NaN,NaN,English,...,2.0,0.0,0.0,0.0,133,2,72,11,93,42.424242
http://www.imdb.com/title/tt0006864/,Not Rated,"Drama, History",NaN,8.0,1916,385907.0,USA,NaN,2.180000e+06,None,...,160.0,7.0,4.0,0.0,225,13,2,55,125,33.712121
http://www.imdb.com/title/tt0006886/,None,"Adventure, Crime",NaN,6.7,1916,NaN,France,NaN,NaN,French,...,3.0,0.0,0.0,0.0,139,0,12,1,1,32.449495
http://www.imdb.com/title/tt0008188/,None,"Drama, Romance, War",NaN,6.5,1917,166949.0,USA,4.462370e+05,NaN,English,...,120.0,30.0,20.0,0.0,611,5,37,66,196,35.227273
http://www.imdb.com/title/tt0008443/,None,"Comedy, Drama, Family",NaN,6.8,1917,NaN,USA,NaN,NaN,English,...,36.0,4.0,3.0,0.0,95,3,37,44,190,62.752525
http://www.imdb.com/title/tt0008519/,None,"Adventure, Comedy, Drama",NaN,6.6,1917,134832.0,USA,NaN,4.247190e+05,None,...,120.0,30.0,20.0,0.0,256,4,37,47,197,43.939394
http://www.imdb.com/title/tt0008663/,None,"Drama, War",NaN,7.4,1917,60000.0,Sweden,NaN,NaN,None,...,17.0,2.0,5.0,0.0,56,5,61,2,17,36.363636
http://www.imdb.com/title/tt0008891/,None,Fantasy,NaN,7.0,1918,NaN,USA,NaN,NaN,English,...,36.0,4.0,3.0,0.0,3,0,0,0,2,44.823232
http://www.imdb.com/title/tt0009150/,TV-PG,"Drama, War",NaN,6.6,1918,NaN,USA,NaN,NaN,English,...,160.0,7.0,4.0,0.0,79,13,4,55,117,47.348485
http://www.imdb.com/title/tt0009611/,Not Rated,"Comedy, War",NaN,6.9,1918,NaN,USA,NaN,NaN,English,...,275.0,31.0,27.0,0.0,122,27,108,33,306,37.121212
http://www.imdb.com/title/tt0009682/,Not Rated,"Action, Adventure",NaN,5.9,1918,NaN,USA,NaN,3.270000e+06,None,...,7.0,0.0,0.0,0.0,246,1,0,0,26,27.525253
http://www.imdb.com/title/tt0009878/,Not Rated,"Crime, Drama, History",NaN,6.9,1919,NaN,Germany,NaN,NaN,English,...,1.0,1.0,0.0,0.0,156,1,4,3,20,56.944444
http://www.imdb.com/title/tt0009892/,None,"Drama, History, Romance",NaN,6.6,1919,NaN,USA,NaN,NaN,None,...,13.0,0.0,0.0,0.0,150,4,97,14,47,60.479798
http://www.imdb.com/title/tt0009900/,Unrated,"Adventure, Romance",NaN,6.9,1919,67000.0,Canada,NaN,NaN,None,...,2.0,1.0,0.0,0.0,419,0,15,3,31,37.878788
http://www.imdb.com/title/tt0009937/,Not Rated,"Drama, Romance",NaN,6.9,1919,42000.0,USA,1.000000e+11,NaN,English,...,42.0,9.0,5.0,0.0,195,5,16,9,56,52.020202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
http://www.imdb.com/title/tt7279180/,None,"Comedy, Drama",NaN,6.9,2017,NaN,Sweden,NaN,NaN,Swedish,...,1.0,40.0,10.0,0.0,24,5,2,43,0,39.015152
http://www.imdb.com/title/tt7294534/,Not Rated,"Action, Drama, Romance",NaN,8.7,2017,25000000.0,India,NaN,NaN,Telugu,...,0.0,0.0,0.0,0.0,11,0,0,1,0,11.111111
http://www.imdb.com/title/tt7296862/,PG-13,Romance,NaN,3.4,2017,NaN,USA,NaN,NaN,English,...,0.0,0.0,0.0,0.0,3,28,14,261,304,69.696970
http://www.imdb.com/title/tt7312940/,PG-13,Sci-Fi,NaN,4.4,2017,NaN,Switzerland,NaN,4.176302e+09,English,...,2.0,0.0,0.0,0.0,311,26,4,94,28,41.161616
http://www.imdb.com/title/tt7322850/,None,Action,NaN,6.7,2017,NaN,India,NaN,NaN,Telugu,...,0.0,0.0,0.0,0.0,69,1,0,0,0,44.444444
http://www.imdb.com/title/tt7355718/,None,Comedy,NaN,8.1,2017,NaN,India,NaN,NaN,Malayalam,...,0.0,0.0,0.0,0.0,197,2,0,1,0,33.333333
http://www.imdb.com/title/tt7369722/,R,Horror,NaN,4.9,2017,NaN,USA,NaN,NaN,English,...,0.0,0.0,1.0,0.0,149,16,0,83,5,49.621212
http://www.imdb.com/title/tt7372916/,None,Drama,NaN,6.9,2017,NaN,Turkey,NaN,NaN,Turkish,...,0.0,0.0,11.0,0.0,173,6,0,9,1,18.939394
http://www.imdb.com/title/tt7399470/,None,"Comedy, Romance",NaN,7.2,2017,NaN,India,NaN,NaN,Hindi,...,0.0,0.0,0.0,0.0,150,49,5,8,0,44.444444
http://www.imdb.com/title/tt7427856/,None,"Comedy, Horror, Romance",NaN,8.7,2017,NaN,Canada,NaN,NaN,English,...,0.0,1.0,0.0,0.0,3,3,2,4,0,33.333333
http://www.imdb.com/title/tt7431894/,None,"Comedy, Fantasy, Sport",NaN,6.3,2017,NaN,China,NaN,NaN,Mandarin,...,0.0,0.0,0.0,0.0,6,0,0,1,0,44.444444
http://www.imdb.com/title/tt7441032/,None,"Horror, Romance, Thriller",NaN,5.1,2017,NaN,USA,NaN,NaN,English,...,0.0,1.0,4.0,0.0,114,1,0,16,1,44.444444
http://www.imdb.com/title/tt7468056/,None,"Action, Crime",NaN,7.1,2017,NaN,South Korea,NaN,NaN,Korean,...,0.0,0.0,1.0,0.0,50,2,0,0,0,0.000000
http://www.imdb.com/title/tt7469726/,None,"Drama, Family, Romance",NaN,8.3,2017,NaN,India,NaN,NaN,Hindi,...,0.0,0.0,0.0,0.0,32,18,0,5,0,22.222222
http://www.imdb.com/title/tt7471004/,None,Horror,NaN,7.2,2017,NaN,India,NaN,NaN,Telugu,...,0.0,0.0,0.0,0.0,118,18,0,5,0,44.444444
http://www.imdb.com/title/tt7516778/,None,Comedy,NaN,5.7,2017,NaN,India,NaN,NaN,Telugu,...,0.0,0.0,0.0,0.0,29,13,0,2,0,44.191919
http://www.imdb.com/title/tt7531040/,None,Romance,NaN,7.1,2017,NaN,India,NaN,NaN,Tamil,...,0.0,0.0,0.0,0.0,4,0,0,0,0,11.111111
http://www.imdb.com/title/tt7533846/,None,"Comedy, Romance",NaN,8.5,2017,NaN,Turkey,NaN,NaN,Turkish,...,0.0,0.0,0.0,0.0,53,1,0,4,1,41.666667
http://www.imdb.com/title/tt7535792/,None,Comedy,NaN,6.3,2017,NaN,Turkey,NaN,NaN,Turkish,...,0.0,0.0,0.0,0.0,9,0,0,1,0,22.222222
http://www.imdb.com/title/tt7535868/,None,Comedy,NaN,2.8,2017,NaN,Turkey,NaN,NaN,Turkish,...,0.0,0.0,0.0,0.0,4,0,0,0,0,0.000000
http://www.imdb.com/title/tt7549484/,None,"Comedy, Drama",NaN,5.0,2017,NaN,India,NaN,NaN,Hindi,...,0.0,0.0,0.0,0.0,10,3,0,3,0,42.297980
http://www.imdb.com/title/tt7608028/,None,"Horror, Thriller",NaN,3.4,2018,100000.0,USA,NaN,NaN,English,...,0.0,0.0,0.0,0.0,44,15,0,12,2,22.222222
http://www.imdb.com/title/tt7608418/,TV-PG,"Comedy, Romance",NaN,5.6,2017,NaN,USA,NaN,NaN,English,...,0.0,4.0,3.0,0.0,17,11,0,19,8,68.813131
http://www.imdb.com/title/tt7608534/,None,Romance,NaN,5.6,2017,NaN,USA,NaN,NaN,English,...,0.0,0.0,0.0,0.0,27,20,0,99,86,56.186869
http://www.imdb.com/title/tt7642818/,None,Comedy,NaN,8.1,2017,NaN,Turkey,NaN,NaN,Turkish,...,0.0,0.0,1.0,0.0,60,6,0,5,0,34.343434
http://www.imdb.com/title/tt7668842/,None,Comedy,NaN,6.6,2018,NaN,Turkey,NaN,NaN,Turkish,...,0.0,0.0,0.0,0.0,3,0,0,1,0,0.000000
http://www.imdb.com/title/tt7691572/,None,War,NaN,9.6,2017,1700000.0,Ukraine,NaN,NaN,Ukrainian,...,0.0,0.0,1.0,0.0,14,0,0,0,0,0.000000
http://www.imdb.com/title/tt7711342/,None,"Action, Drama",NaN,5.5,2018,NaN,India,NaN,NaN,Telugu,...,0.0,0.0,5.0,0.0,30,4,3,1,1,55.555556
http://www.imdb.com/title/tt7717440/,None,Animation,NaN,8.5,2018,230000000.0,Thailand,NaN,NaN,Thai,...,0.0,0.0,0.0,0.0,4,0,0,0,0,11.111111
http://www.imdb.com/title/tt7871636/,None,Comedy,NaN,3.4,2018,NaN,Turkey,NaN,NaN,Turkish,...,0.0,1.0,0.0,0.0,25,7,0,2,0,40.404040

In [1065]:
gdds_df.columns

Index(['Certificate', 'Genre', 'Metascore', 'Rating', 'Year', 'ID', 'Budget',
       'Country', 'Cumulative Worldwide Gross', 'Director_URL', 'Gross USA',
       'Language', 'Opening Weekend USA', 'Production Company',
       'Directing Roles Director', 'Gender Director', 'Height Director',
       'Publicity Listings Director', 'TV Appearances Director',
       'Award Nominations and Wins Director', 'Other Roles Director',
       'Acting Roles Stars Cumulative',
       'Award Nominations and Wins Stars Cumulative',
       'Other Roles Stars Cumulative', 'TV Appearances Stars Cumulative',
       'Publicity Listings Stars Cumulative', 'Diversity Index'],
      dtype='object')

In [1066]:
gdds_df.to_csv('final_movies_df.csv')