# Importing and Dropping Duplicates

In [1]:
import pandas as pd
import json

In [2]:
imports = []
import_numbers = [1,2,3,5,6,7,10,11,12,15,16,17,20,21,22,25,26,27,30,31,32,35,36,37,40,41,42,45,46,47]   
for num in import_numbers:
    imports.append('movie_details_exports/movie_details_export_%s.json' %(str(num)))

In [3]:
imports

['movie_details_exports/movie_details_export_1.json',
 'movie_details_exports/movie_details_export_2.json',
 'movie_details_exports/movie_details_export_3.json',
 'movie_details_exports/movie_details_export_5.json',
 'movie_details_exports/movie_details_export_6.json',
 'movie_details_exports/movie_details_export_7.json',
 'movie_details_exports/movie_details_export_10.json',
 'movie_details_exports/movie_details_export_11.json',
 'movie_details_exports/movie_details_export_12.json',
 'movie_details_exports/movie_details_export_15.json',
 'movie_details_exports/movie_details_export_16.json',
 'movie_details_exports/movie_details_export_17.json',
 'movie_details_exports/movie_details_export_20.json',
 'movie_details_exports/movie_details_export_21.json',
 'movie_details_exports/movie_details_export_22.json',
 'movie_details_exports/movie_details_export_25.json',
 'movie_details_exports/movie_details_export_26.json',
 'movie_details_exports/movie_details_export_27.json',
 'movie_details_exports/movie_details_export_30.json',
 'movie_details_exports/movie_details_export_31.json',
 'movie_details_exports/movie_details_export_32.json',
 'movie_details_exports/movie_details_export_35.json',
 'movie_details_exports/movie_details_export_36.json',
 'movie_details_exports/movie_details_export_37.json',
 'movie_details_exports/movie_details_export_40.json',
 'movie_details_exports/movie_details_export_41.json',
 'movie_details_exports/movie_details_export_42.json',
 'movie_details_exports/movie_details_export_45.json',
 'movie_details_exports/movie_details_export_46.json',
 'movie_details_exports/movie_details_export_47.json']

In [4]:
details_df = pd.DataFrame()

In [5]:
for imp in imports:
    details_df = details_df.append(pd.read_json(imp, orient='index'))

# mov = mov.append(pd.read_json('export_2.json', orient='index'))
# mov = mov.append(pd.read_json('export_3.json', orient='index'))

In [6]:
len(details_df)

29717

In [7]:
details_df.head()

,Budget,Country,Cumulative Worldwide Gross,Director,Director_URL,Gross USA,Language,Opening Weekend USA,Primary Filming Location,Production Company,Release Date,Star1,Star1_URL,Star2,Star2_URL,Star3,Star3_URL,Title
http://www.imdb.com/title/tt4937564/,2500000.0,UK,NaN,Sylvie Verheyde,http://www.imdb.com/name/nm0894173,NaN,English,NaN,None,Les Films du Veyrier,2017-02-10,Hafsia Herzi,http://www.imdb.com/name/nm2082567,Ash Stymest,http://www.imdb.com/name/nm7514839,Karole Rocher,http://www.imdb.com/name/nm0734039,Sex Doll
http://www.imdb.com/title/tt4937812/,500000000.0,India,NaN,Rajesh M. Selva,http://www.imdb.com/name/nm4301161,NaN,Tamil,NaN,"Chennai, Tamil Nadu, India",Raajkamal Films International,2015-11-13,Kamal Haasan,http://www.imdb.com/name/nm0352032,Prakash Raj,http://www.imdb.com/name/nm0695177,Trisha Krishnan,http://www.imdb.com/name/nm1375534,Thoongaavanam
http://www.imdb.com/title/tt4939066/,12620000.0,South Korea,NaN,John H. Lee,http://www.imdb.com/name/nm0497565,1.022720e+12,Korean,3.166272e+09,"Seoul, South Korea",Taewon Entertainment,2016-08-12,Liam Neeson,http://www.imdb.com/name/nm0000553,Jung-jae Lee,http://www.imdb.com/name/nm0497631,Beom-su Lee,http://www.imdb.com/name/nm1045934,Battle for Incheon: Operation Chromite
http://www.imdb.com/title/tt4940370/,63000000.0,Sweden,NaN,Felix Herngren,http://www.imdb.com/name/nm0379773,NaN,Swedish,NaN,None,NICE FLX Pictures,2017-04-25,Robert Gustafsson,http://www.imdb.com/name/nm0349052,Iwar Wiklander,http://www.imdb.com/name/nm0928002,David Wiberg,http://www.imdb.com/name/nm2433382,The 101-Year-Old Man Who Skipped Out on the Bi...
http://www.imdb.com/title/tt4940456/,NaN,India,NaN,Rakeysh Omprakash Mehra,http://www.imdb.com/name/nm1018493,NaN,Hindi,NaN,None,Cinestaan Film Company,2016-10-07,Harshvardhan Kapoor,http://www.imdb.com/name/nm7561367,Saiyami Kher,http://www.imdb.com/name/nm7517362,Art Malik,http://www.imdb.com/name/nm0539562,Mirzya

In [8]:
details_df.columns

Index(['Budget', 'Country', 'Cumulative Worldwide Gross', 'Director',
       'Director_URL', 'Gross USA', 'Language', 'Opening Weekend USA',
       'Primary Filming Location', 'Production Company', 'Release Date',
       'Star1', 'Star1_URL', 'Star2', 'Star2_URL', 'Star3', 'Star3_URL',
       'Title'],
      dtype='object')

# Get List of unique Stars and URLS

In [9]:
star1_df = details_df[['Star1_URL','Star1']].copy()

In [10]:
star1_df.rename(columns = {'Star1_URL':'StarURL','Star1':'Star'}, inplace=True)

In [11]:
star2_df = details_df[['Star2_URL','Star2']].copy()

In [12]:
star2_df.rename(columns = {'Star2_URL':'StarURL','Star2':'Star'}, inplace=True)

In [13]:
star3_df = details_df[['Star3_URL','Star3']].copy()

In [14]:
star3_df.rename(columns = {'Star3_URL':'StarURL','Star3':'Star'}, inplace=True)

In [15]:
stars_df = pd.concat([star1_df,star2_df,star3_df])

In [16]:
stars_df.head()

,StarURL,Star
http://www.imdb.com/title/tt4937564/,http://www.imdb.com/name/nm2082567,Hafsia Herzi
http://www.imdb.com/title/tt4937812/,http://www.imdb.com/name/nm0352032,Kamal Haasan
http://www.imdb.com/title/tt4939066/,http://www.imdb.com/name/nm0000553,Liam Neeson
http://www.imdb.com/title/tt4940370/,http://www.imdb.com/name/nm0349052,Robert Gustafsson
http://www.imdb.com/title/tt4940456/,http://www.imdb.com/name/nm7561367,Harshvardhan Kapoor

In [17]:
len(stars_df)

89151

counts = [type(x) for x in stars_df['StarURL']]

counts.index(float)

stars_df.iloc[4017]['StarURL']
.split('?')[0]

In [18]:
stars_df = stars_df.dropna(subset = ['StarURL'])

In [19]:
len(stars_df)

89075

In [20]:
stars_df = stars_df.drop_duplicates(subset='StarURL',keep='first')

In [21]:
len(stars_df)

33838

In [22]:
star_urls = list(stars_df['StarURL'])

In [23]:
star_urls = sorted(star_urls, reverse = True)

In [24]:
star_urls[:10]

['http://www.imdb.com/name/nm9585396',
 'http://www.imdb.com/name/nm9578606',
 'http://www.imdb.com/name/nm9572036',
 'http://www.imdb.com/name/nm9572029',
 'http://www.imdb.com/name/nm9557596',
 'http://www.imdb.com/name/nm9557587',
 'http://www.imdb.com/name/nm9557586',
 'http://www.imdb.com/name/nm9552585',
 'http://www.imdb.com/name/nm9549343',
 'http://www.imdb.com/name/nm9521432']

star_urls.pop()

star_urls[22525]

import re
import requests
from bs4 import BeautifulSoup
url = 'http://www.imdb.com/name/nm0000233/'
# url= 'http://www.imdb.com/name/nm0002354/'
response = requests.get(url)
page = response.text
soup = BeautifulSoup(page, 'html.parser')

star_details = {}
star_details[url] = {}

gender = soup.find(id='name-job-categories')
gender = gender.findAll('a') if gender else None
gender = [x['href'] for x in gender] if gender else None
gender = [re.sub('[^a-z]+','',x) for x in gender] if gender else None
if gender:
    if 'actor' in gender:
        gender = 'Male'
    elif 'actress' in gender:
        gender = 'Female'
    else:
        gender = soup.find(id='name-bio-text')
        gender = gender.text if gender else None
        gender = re.sub('\n', '', gender) if gender else None
        gender = re.sub('  +',' ', gender) if gender else None
        gender = gender.split(' ') if gender else None
        male_count = gender.count('His') + gender.count('his') + gender.count('He') + gender.count('he') if gender else None
        female_count = gender.count('Her') + gender.count('her') + gender.count('She') + gender.count('she') if gender else None
        if gender:
            if male_count > female_count:
                gender = 'Male'
            elif female_count > male_count:
                gender = 'Female'
            else:
                gender = None
                    
gender

height = soup.find('h2',text=re.compile('Personal Details'))
height = height.parent if height else None
height = height.find(id='details-height') if height else None
height = height.text if height else None
height = height.split('(')[-1] if height else None
height = re.sub('[^0-9.]+','',height) if height else None
# star_details[url]['Height in m'] = height
height

publicity_listings = soup.find('h2',text=re.compile('Personal Details'))
publicity_listings = publicity_listings.parent if publicity_listings else None
publicity_listings = publicity_listings.find(id='details-publicity-listings') if publicity_listings else None
publicity_listings = publicity_listings.text if publicity_listings else None
publicity_listings = re.sub('[^0-9]+',' ',publicity_listings) if publicity_listings else None
publicity_listings = publicity_listings.strip() if publicity_listings else None
publicity_listings = publicity_listings.split(' ') if publicity_listings else None
publicity_listings = [int(x) for x in publicity_listings] if publicity_listings else None
publicity_listings = sum(publicity_listings) if publicity_listings else None
star_details[url]['Publicity Listings'] = publicity_listings
publicity_listings

star_sign = soup.find('h4',text=re.compile('Star Sign'))
star_sign = star_sign.parent if star_sign else None
star_sign = star_sign.text if star_sign else None
star_sign = star_sign.strip() if star_sign else None
star_sign = star_sign.split('\n')[-1] if star_sign else None
star_details[url]['Star Sign'] = star_sign

star_sign

gender = soup.find(id='name-job-categories')
gender = gender.findAll('a')
gender = [x['href'] for x in gender] if gender else None
gender = [re.sub('[^a-z]+','',x) for x in gender] if gender else None
if gender:
    if 'actor' in gender:
        gender = 'Male'
    elif 'actress' in gender:
        gender = 'Female'
    else:
        gender = None
star_details[url]['Gender'] = gender

gender

born_info = soup.find(id='name-born-info')

birthdate = born_info.find('time') if born_info else None
if birthdate.has_attr('datetime'):
    birthdate = birthdate['datetime']
else:
    birthdate = None
# star_details[url]['Birthdate'] = birthdate
    
birthplace = born_info.findAll('a') if born_info else None
birthplace = birthplace[-1] if birthplace else None
birthplace = birthplace.text if birthplace else None
# star_details[url]['Birthplace'] = birthplace
  
birthcountry = birthplace.split(', ') if birthplace else None
birthcountry = birthcountry[-1] if len(birthcountry)>2 else None
# star_details[url]['Birth Country'] = birthcountry

birthdate
# birthplace
# birthcountry

acting_roles = soup.find(id='filmo-head-actor')
acting_roles = acting_roles.text if acting_roles else None
acting_roles = acting_roles.strip() if acting_roles else None
acting_roles = acting_roles.split('(')[-1] if acting_roles else None
acting_roles = re.sub('[^0-9]+','',acting_roles) if acting_roles else None
acting_roles = int(acting_roles) if acting_roles else None
# star_details[url]['Acting Roles'] = action_roles
    
acting_roles

tv_appearances = soup.find(id='filmo-head-self')
tv_appearances = tv_appearances.text if tv_appearances else None
tv_appearances = tv_appearances.strip() if tv_appearances else None
tv_appearances = tv_appearances.split('(')[-1] if tv_appearances else None
tv_appearances = re.sub('[^0-9]+','',tv_appearances) if tv_appearances else None
star_details[url]['producing Roles'] = tv_appearances    
tv_appearances


# star_details[url]['producing Roles'] = tv_appearances

star_name = soup.find('h1')
star_name = star_name.text if star_name else None
star_name = star_name.strip() if star_name else None
star_name = star_name.split('\n') if star_name else None

deathyear = star_name[-1] if len(star_name)>=2 else None
deathyear = deathyear.split('–')[-1] if deathyear else None
deathyear = re.sub('[^0-9]+','',deathyear) if deathyear else None
deathyear = int(deathyear) if deathyear else None

star_name = star_name[0] if star_name else None

birthyear = birthdate[0:4] if birthdate and len(birthdate)>=10 else None
birthyear = int(birthyear) if birthyear else None

age_at_death = deathyear-birthyear if deathyear and birthyear else None

birthyear

award_highlight = soup.find('div', class_='article highlighted')
award_highlight = award_highlight.find('span') if award_highlight else None
award_highlight = award_highlight.text if award_highlight else None
award_highlight = award_highlight.strip() if award_highlight else None
award_highlight = award_highlight.split('\n') if award_highlight else None
award_highlight = [x.strip() for x in award_highlight] if award_highlight else None
award_highlight = ' '.join(award_highlight) if award_highlight else None

#     star_details[url]['Award Info'] = award_highlight
award_highlight

star_details

In [25]:
len(star_urls)

33838

## Scrape Star Details

In [25]:
# star Details
import re
import requests
from bs4 import BeautifulSoup
from datetime import datetime
import time

stars_scraped = 0
star_details = {}
star_index = 30000                    
prefix = 'http://www.imdb.com'
export_number = 50
export_no = str(export_number)
load_attempts = 0

def star_scraper():
    global star_index
    
    print(str(datetime.now()),': working on export ' + export_no)
    
    for url in star_urls[star_index:33000]:
#         print(url)
        if (star_index+1) % 20 == 0:
            time.sleep(1.5)
            print('%d: %s' %(star_index+1, url))
        page = request_page(url)
        get_star_details(url, page)
        star_index += 1
    
    export_to_json(star_details)
    print("Done")
    
def request_page(url):
    global load_attempts
    response = requests.get(url)
    
    if response.status_code == 200:
        return(response.text)
        load_attempts = 0
    else:
        print(response.status_code,'for %s' %(url))
        if response.status_code != 404:
            if load_attempts == 10:
                time.sleep(60)
            else:
                time.sleep(10)
            request_page(url)
            load_attempts += 1

def get_star_details(url, page):
    soup = BeautifulSoup(page, 'html.parser')

    star_details[url] = {}
    
    gender = soup.find(id='name-job-categories')
    gender = gender.findAll('a') if gender else None
    gender = [x['href'] for x in gender] if gender else None
    gender = [re.sub('[^a-z]+','',x) for x in gender] if gender else None
    if gender:
        if 'actor' in gender:
            gender = 'Male'
        elif 'actress' in gender:
            gender = 'Female'
        else:
            gender = soup.find(id='name-bio-text')
            gender = gender.text if gender else None
            gender = re.sub('\n', '', gender) if gender else None
            gender = re.sub('  +',' ', gender) if gender else None
            gender = gender.split(' ') if gender else None
            male_count = gender.count('His') + gender.count('his') + gender.count('He') + gender.count('he') if gender else None
            female_count = gender.count('Her') + gender.count('her') + gender.count('She') + gender.count('she') if gender else None
            if gender:
                if male_count > female_count:
                    gender = 'Male'
                elif female_count > male_count:
                    gender = 'Female'
                else:
                    gender = None
    star_details[url]['Gender'] = gender
    
    
    star_name = soup.find('h1')
    star_name = star_name.text if star_name else None
    star_name = star_name.strip() if star_name else None
    star_name = star_name.split('\n') if star_name else None

    deathyear = star_name[-1] if len(star_name)>=2 else None
    deathyear = deathyear.split('–')[-1] if deathyear else None
    deathyear = re.sub('[^0-9]+','',deathyear) if deathyear else None
    deathyear = int(deathyear) if deathyear else None
    star_details[url]['Deathyear'] = deathyear
    

    star_name = star_name[0] if star_name else None
    star_details[url]['Name'] = star_name    
    
    
    born_info = soup.find(id='name-born-info')

    birthdate = born_info.find('time') if born_info else None
    if birthdate:
        if birthdate.has_attr('datetime'):
            birthdate = birthdate['datetime']
        else:
            birthdate = None
    star_details[url]['Birthdate'] = birthdate

    birthyear = birthdate[0:4] if birthdate and len(birthdate)>=8 else None
    birthyear = int(birthyear) if birthyear else None
    star_details[url]['Birthyear'] = birthyear

    age_at_death = deathyear-birthyear if deathyear and birthyear else None
    star_details[url]['Age at Death'] = age_at_death

    
    birthplace = born_info.findAll('a') if born_info else None
    birthplace = birthplace[-1] if birthplace else None
    birthplace = birthplace.text if birthplace else None
    star_details[url]['Birthplace'] = birthplace

    
    birthcountry = birthplace.split(', ') if birthplace else None
    birthcountry = birthcountry[-1] if birthcountry and len(birthcountry)>=1 else None
    star_details[url]['Birth Country'] = birthcountry
 

    award_highlight = soup.find('div', class_='article highlighted')
    award_highlight = award_highlight.findAll('span') if award_highlight else None
    award_highlight = [x.text for x in award_highlight] if award_highlight else None
    award_highlight = [x.strip() for x in award_highlight] if award_highlight else None
    award_highlight = [x.split('\n') for x in award_highlight] if award_highlight else None
    award_highlight = [''.join(x) for x in award_highlight[:-1]] if award_highlight else None
    award_highlight = [re.sub("  +", " ", x) for x in award_highlight] if award_highlight else None
    award_highlight = ' '.join(award_highlight) if award_highlight else None    
    star_details[url]['Award Info'] = award_highlight    
    
    acting_roles = soup.find(id='filmo-head-actor')
    acting_roles = acting_roles.text if acting_roles else None
    acting_roles = acting_roles.strip() if acting_roles else None
    acting_roles = acting_roles.split('(')[-1] if acting_roles else None
    acting_roles = re.sub('[^0-9]+','',acting_roles) if acting_roles else None
    acting_roles = int(acting_roles) if acting_roles else None
    star_details[url]['Acting Roles'] = acting_roles
    
    directing_roles = soup.find(id='filmo-head-director')
    directing_roles = directing_roles.text if directing_roles else None
    directing_roles = directing_roles.strip() if directing_roles else None
    directing_roles = directing_roles.split('(')[-1] if directing_roles else None
    directing_roles = re.sub('[^0-9]+','',directing_roles) if directing_roles else None
    directing_roles = int(directing_roles) if directing_roles else None
    star_details[url]['Directing Roles'] = directing_roles  
    
    producing_roles = soup.find(id='filmo-head-producer')
    producing_roles = producing_roles.text if producing_roles else None
    producing_roles = producing_roles.strip() if producing_roles else None
    producing_roles = producing_roles.split('(')[-1] if producing_roles else None
    producing_roles = re.sub('[^0-9]+','',producing_roles) if producing_roles else None
    producing_roles = int(producing_roles) if producing_roles else None
    star_details[url]['Producing Roles'] = producing_roles 
    
    tv_appearances = soup.find(id='filmo-head-self')
    tv_appearances = tv_appearances.text if tv_appearances else None
    tv_appearances = tv_appearances.strip() if tv_appearances else None
    tv_appearances = tv_appearances.split('(')[-1] if tv_appearances else None
    tv_appearances = re.sub('[^0-9]+','',tv_appearances) if tv_appearances else None
    tv_appearances = int(tv_appearances) if tv_appearances else None
    star_details[url]['TV Appearances'] = tv_appearances
    

    height = soup.find('h2',text=re.compile('Personal Details'))
    height = height.parent if height else None
    height = height.find(id='details-height') if height else None
    height = height.text if height else None
    height = height.split('(')[-1] if height else None
    height = re.sub('[^0-9.]+','',height) if height else None
    star_details[url]['Height in m'] = height

    publicity_listings = soup.find('h2',text=re.compile('Personal Details'))
    publicity_listings = publicity_listings.parent if publicity_listings else None
    publicity_listings = publicity_listings.find(id='details-publicity-listings') if publicity_listings else None
    publicity_listings = publicity_listings.text if publicity_listings else None
    publicity_listings = re.sub('[^0-9]+',' ',publicity_listings) if publicity_listings else None
    publicity_listings = publicity_listings.strip() if publicity_listings else None
    publicity_listings = publicity_listings.split(' ') if publicity_listings else None
    publicity_listings = [int(x) for x in publicity_listings] if publicity_listings else None
    publicity_listings = sum(publicity_listings) if publicity_listings else None
    star_details[url]['Publicity Listings'] = publicity_listings
        
    star_sign = soup.find('h4',text=re.compile('Star Sign'))
    star_sign = star_sign.parent if star_sign else None
    star_sign = star_sign.text if star_sign else None
    star_sign = star_sign.strip() if star_sign else None
    star_sign = star_sign.split('\n')[-1] if star_sign else None
    star_details[url]['Star Sign'] = star_sign

    go_to_next_and_export()

def go_to_next_and_export():
    global stars_scraped
    global star_details
    
    stars_scraped+=1

    if len(star_details) == 1000:                                         
        export_to_json(star_details)
        stars_scraped = 0
        star_details = {}

def export_to_json(star_details):
    global export_no
    global export_number
    with open('star_details_exports/star_details_export_%s.json' %(export_no),'w')  as f:
        json.dump(star_details,f)

    export_number += 1
    export_no = str(export_number)
    print(str(datetime.now()),': working on export ' + export_no)

start = time.time()
star_scraper()
end = time.time()
print(round(end-start,3))

2018-01-30 00:17:23.624977 : working on export 50
30020: http://www.imdb.com/name/nm0070250
30040: http://www.imdb.com/name/nm0068949
30060: http://www.imdb.com/name/nm0068311
30080: http://www.imdb.com/name/nm0067118
30100: http://www.imdb.com/name/nm0066028
30120: http://www.imdb.com/name/nm0065183
30140: http://www.imdb.com/name/nm0063914
30160: http://www.imdb.com/name/nm0062866
30180: http://www.imdb.com/name/nm0061472
30200: http://www.imdb.com/name/nm0060607
30220: http://www.imdb.com/name/nm0059934
30240: http://www.imdb.com/name/nm0058831
30260: http://www.imdb.com/name/nm0058039
30280: http://www.imdb.com/name/nm0057208
30300: http://www.imdb.com/name/nm0056336
30320: http://www.imdb.com/name/nm0055549
30340: http://www.imdb.com/name/nm0054413
30360: http://www.imdb.com/name/nm0052996
30380: http://www.imdb.com/name/nm0052051
30400: http://www.imdb.com/name/nm0051536
30420: http://www.imdb.com/name/nm0050468
30440: http://www.imdb.com/name/nm0049121
30460: http://www.imdb.com/name/nm0048273
30480: http://www.imdb.com/name/nm0047818
30500: http://www.imdb.com/name/nm0046993
30520: http://www.imdb.com/name/nm0046217
30540: http://www.imdb.com/name/nm0045136
30560: http://www.imdb.com/name/nm0044300
30580: http://www.imdb.com/name/nm0043453
30600: http://www.imdb.com/name/nm0042524
30620: http://www.imdb.com/name/nm0041614
30640: http://www.imdb.com/name/nm0040911
30660: http://www.imdb.com/name/nm0039989
30680: http://www.imdb.com/name/nm0039240
30700: http://www.imdb.com/name/nm0038690
30720: http://www.imdb.com/name/nm0037816
30740: http://www.imdb.com/name/nm0036663
30760: http://www.imdb.com/name/nm0035730
30780: http://www.imdb.com/name/nm0035007
30800: http://www.imdb.com/name/nm0034147
30820: http://www.imdb.com/name/nm0033165
30840: http://www.imdb.com/name/nm0032417
30860: http://www.imdb.com/name/nm0031698
30880: http://www.imdb.com/name/nm0030609
30900: http://www.imdb.com/name/nm0029875
30920: http://www.imdb.com/name/nm0029018
30940: http://www.imdb.com/name/nm0028125
30960: http://www.imdb.com/name/nm0027402
30980: http://www.imdb.com/name/nm0026254
31000: http://www.imdb.com/name/nm0025523
2018-01-30 00:41:29.162892 : working on export 51
31020: http://www.imdb.com/name/nm0024425
31040: http://www.imdb.com/name/nm0023574
31060: http://www.imdb.com/name/nm0022323
31080: http://www.imdb.com/name/nm0021502
31100: http://www.imdb.com/name/nm0020739
31120: http://www.imdb.com/name/nm0019922
31140: http://www.imdb.com/name/nm0019136
31160: http://www.imdb.com/name/nm0018273
31180: http://www.imdb.com/name/nm0017733
31200: http://www.imdb.com/name/nm0016864
31220: http://www.imdb.com/name/nm0015777
31240: http://www.imdb.com/name/nm0015391
31260: http://www.imdb.com/name/nm0014977
31280: http://www.imdb.com/name/nm0014277
31300: http://www.imdb.com/name/nm0013329
31320: http://www.imdb.com/name/nm0012443
31340: http://www.imdb.com/name/nm0011775
31360: http://www.imdb.com/name/nm0010772
31380: http://www.imdb.com/name/nm0009900
31400: http://www.imdb.com/name/nm0009017
31420: http://www.imdb.com/name/nm0008311
31440: http://www.imdb.com/name/nm0007599
31460: http://www.imdb.com/name/nm0007155
31480: http://www.imdb.com/name/nm0006969
31500: http://www.imdb.com/name/nm0006764
31520: http://www.imdb.com/name/nm0006603
31540: http://www.imdb.com/name/nm0005579
31560: http://www.imdb.com/name/nm0005535
31580: http://www.imdb.com/name/nm0005497
31600: http://www.imdb.com/name/nm0005454
31620: http://www.imdb.com/name/nm0005408
31640: http://www.imdb.com/name/nm0005365
31660: http://www.imdb.com/name/nm0005325
31680: http://www.imdb.com/name/nm0005286
31700: http://www.imdb.com/name/nm0005256
31720: http://www.imdb.com/name/nm0005216
31740: http://www.imdb.com/name/nm0005177
31760: http://www.imdb.com/name/nm0005143
31780: http://www.imdb.com/name/nm0005097
31800: http://www.imdb.com/name/nm0005048
31820: http://www.imdb.com/name/nm0005013
31840: http://www.imdb.com/name/nm0004983
31860: http://www.imdb.com/name/nm0004922
31880: http://www.imdb.com/name/nm0004885
31900: http://www.imdb.com/name/nm0004848
31920: http://www.imdb.com/name/nm0004802
31940: http://www.imdb.com/name/nm0004753
31960: http://www.imdb.com/name/nm0004717
31980: http://www.imdb.com/name/nm0004571
32000: http://www.imdb.com/name/nm0004429
2018-01-30 01:14:45.273528 : working on export 52
32020: http://www.imdb.com/name/nm0004282
32040: http://www.imdb.com/name/nm0003857
32060: http://www.imdb.com/name/nm0003193
32080: http://www.imdb.com/name/nm0002850
32100: http://www.imdb.com/name/nm0002326
32120: http://www.imdb.com/name/nm0002154
32140: http://www.imdb.com/name/nm0002123
32160: http://www.imdb.com/name/nm0002094
32180: http://www.imdb.com/name/nm0002069
32200: http://www.imdb.com/name/nm0002043
32220: http://www.imdb.com/name/nm0002017
32240: http://www.imdb.com/name/nm0001989
32260: http://www.imdb.com/name/nm0001960
32280: http://www.imdb.com/name/nm0001931
32300: http://www.imdb.com/name/nm0001886
32320: http://www.imdb.com/name/nm0001857
32340: http://www.imdb.com/name/nm0001834
32360: http://www.imdb.com/name/nm0001809
32380: http://www.imdb.com/name/nm0001787
32400: http://www.imdb.com/name/nm0001764
32420: http://www.imdb.com/name/nm0001742
32440: http://www.imdb.com/name/nm0001718
32460: http://www.imdb.com/name/nm0001694
32480: http://www.imdb.com/name/nm0001668
32500: http://www.imdb.com/name/nm0001646
32520: http://www.imdb.com/name/nm0001623
32540: http://www.imdb.com/name/nm0001600
32560: http://www.imdb.com/name/nm0001575
32580: http://www.imdb.com/name/nm0001550
32600: http://www.imdb.com/name/nm0001528
32620: http://www.imdb.com/name/nm0001505
32640: http://www.imdb.com/name/nm0001480
32660: http://www.imdb.com/name/nm0001454
32680: http://www.imdb.com/name/nm0001433
32700: http://www.imdb.com/name/nm0001411
32720: http://www.imdb.com/name/nm0001385
32740: http://www.imdb.com/name/nm0001364
32760: http://www.imdb.com/name/nm0001335
32780: http://www.imdb.com/name/nm0001309
32800: http://www.imdb.com/name/nm0001285
32820: http://www.imdb.com/name/nm0001258
32840: http://www.imdb.com/name/nm0001234
32860: http://www.imdb.com/name/nm0001209
32880: http://www.imdb.com/name/nm0001184
32900: http://www.imdb.com/name/nm0001159
32920: http://www.imdb.com/name/nm0001131
32940: http://www.imdb.com/name/nm0001105
32960: http://www.imdb.com/name/nm0001079
32980: http://www.imdb.com/name/nm0001055
33000: http://www.imdb.com/name/nm0001029
2018-01-30 01:47:54.728076 : working on export 53
2018-01-30 01:47:54.730328 : working on export 54
Done
5431.106

In [26]:
import json
import pandas as pd
stars_import = pd.read_json('star_details_exports/star_details_export_52.json',orient='index')

In [27]:
len(stars_import)

1000

In [28]:
stars_import

,Acting Roles,Age at Death,Award Info,Birth Country,Birthdate,Birthplace,Birthyear,Deathyear,Directing Roles,Gender,Height in m,Name,Producing Roles,Publicity Listings,Star Sign,TV Appearances
http://www.imdb.com/name/nm0001029,40.0,NaN,4 wins & 6 nominations.,USA,1968-9-26,"Mount Vernon, Washington, USA",1968.0,NaN,NaN,Male,1.88,Jim Caviezel,NaN,26.0,Libra,47.0
http://www.imdb.com/name/nm0001030,8.0,43.0,Nominated for 1 Golden Globe.,USA,1935-8-12,"Boston, Massachusetts, USA",1935.0,1978.0,NaN,Male,1.79,John Cazale,NaN,5.0,Leo,2.0
http://www.imdb.com/name/nm0001032,NaN,57.0,4 wins & 1 nomination.,USA,1952-4-22,"Providence, Rhode Island, USA",1952.0,2009.0,NaN,Female,1.70,Marilyn Chambers,1.0,68.0,Taurus,31.0
http://www.imdb.com/name/nm0001033,197.0,67.0,None,USA,1906-2-10,"Oklahoma City, Oklahoma, USA",1906.0,1973.0,NaN,Male,1.88,Lon Chaney Jr.,NaN,27.0,Aquarius,9.0
http://www.imdb.com/name/nm0001034,NaN,NaN,1 win & 2 nominations.,USA,1957-9-23,"Anaheim, California, USA",1957.0,NaN,NaN,Female,1.68,Rosalind Chao,NaN,3.0,Libra,4.0
http://www.imdb.com/name/nm0001035,50.0,NaN,1 win.,UK,1970-7-31,"London, England, UK",1970.0,NaN,NaN,Male,1.80,Ben Chaplin,NaN,5.0,Leo,11.0
http://www.imdb.com/name/nm0001036,NaN,NaN,Nominated for 3 Golden Globes. Another 24 wins...,USA,1944-7-31,"Santa Monica, California, USA",1944.0,NaN,NaN,Female,1.65,Geraldine Chaplin,NaN,22.0,Leo,68.0
http://www.imdb.com/name/nm0001037,28.0,48.0,1 nomination.,UK,1941-1-8,"Leicester, Leicestershire, England, UK",1941.0,1989.0,NaN,Male,1.93,Graham Chapman,2.0,12.0,Capricorn,29.0
http://www.imdb.com/name/nm0001038,54.0,NaN,Nominated for 1 Golden Globe. Another 1 win & ...,USA,1971-9-15,"Baltimore, Maryland, USA",1971.0,NaN,1.0,Male,1.80,Josh Charles,NaN,4.0,Virgo,31.0
http://www.imdb.com/name/nm0001039,11.0,NaN,1 nomination.,France,1972-5-15,"Lyon, Rhône, France",1972.0,NaN,NaN,Male,1.80,David Charvet,NaN,8.0,Taurus,26.0
http://www.imdb.com/name/nm0001040,NaN,NaN,22 wins & 13 nominations.,China,1961-4-26,"Shanghai, China",1961.0,NaN,3.0,Female,1.63,Joan Chen,3.0,28.0,Taurus,22.0
http://www.imdb.com/name/nm0001041,NaN,NaN,24 wins & 14 nominations.,Hong Kong,1964-9-20,Hong Kong,1964.0,NaN,NaN,Female,1.68,Maggie Cheung,NaN,72.0,Virgo,8.0
http://www.imdb.com/name/nm0001042,NaN,NaN,None,USA,1947-4-15,"Houston, Texas, USA",1947.0,NaN,NaN,Female,1.71,Lois Chiles,NaN,7.0,Aries,10.0
http://www.imdb.com/name/nm0001043,NaN,NaN,Nominated for 5 Primetime Emmys. Another 8 win...,USA,1980-12-3,"Chicago, Illinois, USA",1980.0,NaN,NaN,Female,1.57,Anna Chlumsky,NaN,2.0,Sagittarius,37.0
http://www.imdb.com/name/nm0001044,NaN,NaN,1 win.,Canada,1961-2-28,"Edmonton, Alberta, Canada",1961.0,NaN,1.0,Female,1.73,Rae Dawn Chong,1.0,11.0,Pisces,26.0
http://www.imdb.com/name/nm0001045,57.0,NaN,1 win & 4 nominations.,Canada,1938-5-24,"Edmonton, Alberta, Canada",1938.0,NaN,6.0,Male,1.78,Tommy Chong,3.0,26.0,Gemini,86.0
http://www.imdb.com/name/nm0001046,NaN,NaN,Won 1 Oscar. Another 46 wins & 28 nominations.,India],1940-4-14,"Chabua, Assam Province, British India [now Ass...",1940.0,NaN,NaN,Female,1.60,Julie Christie,NaN,48.0,Aries,46.0
http://www.imdb.com/name/nm0001048,40.0,NaN,1 win & 4 nominations.,USA,1957-9-29,"Brooklyn, New York, USA",1957.0,NaN,NaN,Male,1.80,Andrew Dice Clay,10.0,7.0,Libra,69.0
http://www.imdb.com/name/nm0001049,NaN,66.0,Nominated for 2 Oscars. Another 2 wins & 15 no...,USA,1944-4-30,"New York City, New York, USA",1944.0,2010.0,NaN,Female,1.73,Jill Clayburgh,NaN,10.0,Taurus,13.0
http://www.imdb.com/name/nm0001050,18.0,46.0,Nominated for 4 Oscars. Another 2 wins & 3 nom...,USA,1920-10-17,"Omaha, Nebraska, USA",1920.0,1966.0,NaN,Male,1.78,Montgomery Clift,NaN,58.0,Libra,9.0
http://www.imdb.com/name/nm0001055,NaN,93.0,Won 1 Oscar. Another 5 wins & 3 nominations.,France,1903-9-13,"Saint-Mandé, Seine [now Val-de-Marne], France",1903.0,1996.0,NaN,Female,1.64,Claudette Colbert,NaN,74.0,Virgo,24.0
http://www.imdb.com/name/nm0001056,173.0,NaN,Won 1 Golden Globe. Another 5 wins & 8 nominat...,USA,1932-1-3,"Austin, Texas, USA",1932.0,NaN,NaN,Male,1.85,Dabney Coleman,NaN,4.0,Capricorn,35.0
http://www.imdb.com/name/nm0001057,NaN,NaN,Nominated for 1 Oscar. Another 26 wins & 51 no...,Australia,1972-11-1,"Sydney, New South Wales, Australia",1972.0,NaN,NaN,Female,1.73,Toni Collette,6.0,22.0,Scorpio,85.0
http://www.imdb.com/name/nm0001058,NaN,NaN,Won 1 Golden Globe. Another 7 wins & 15 nomina...,UK,1933-5-23,"Paddington, London, England, UK",1933.0,NaN,NaN,Female,1.63,Joan Collins,5.0,117.0,Gemini,242.0
http://www.imdb.com/name/nm0001059,108.0,NaN,Nominated for 1 BAFTA Film Award. Another 11 w...,UK,1950-3-30,"Rutherglen, Scotland, UK",1950.0,NaN,1.0,Male,1.85,Robbie Coltrane,1.0,7.0,Aries,79.0
http://www.imdb.com/name/nm0001061,NaN,NaN,1 win & 3 nominations.,USA,1973-12-3,"San Diego, California, USA",1973.0,NaN,NaN,Female,1.57,Holly Marie Combs,8.0,15.0,Sagittarius,27.0
http://www.imdb.com/name/nm0001062,129.0,NaN,4 wins & 5 nominations.,USA,1954-9-9,"Oxnard, California, USA",1954.0,NaN,NaN,Male,1.70,Jeffrey Combs,NaN,8.0,Virgo,22.0
http://www.imdb.com/name/nm0001064,73.0,NaN,1 win & 1 nomination.,UK,1963-1-11,"London, England, UK",1963.0,NaN,5.0,Male,1.83,Jason Connery,4.0,7.0,Capricorn,13.0
http://www.imdb.com/name/nm0001065,29.0,NaN,Won 2 Primetime Emmys. Another 4 nominations.,USA,1967-9-11,"New Orleans, Louisiana, USA",1967.0,NaN,NaN,Male,1.85,Harry Connick Jr.,4.0,23.0,Virgo,164.0
http://www.imdb.com/name/nm0001066,80.0,NaN,Nominated for 1 Golden Globe. Another 2 wins.,USA,1935-3-1,"Chicago, Illinois, USA",1935.0,NaN,8.0,Male,1.73,Robert Conrad,NaN,9.0,Pisces,56.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
http://www.imdb.com/name/nm0004133,NaN,NaN,1 win & 1 nomination.,Portugal,1970-7-12,"Monte Estoril, Portugal",1970.0,NaN,2.0,Female,1.75,Aure Atika,NaN,2.0,Cancer,20.0
http://www.imdb.com/name/nm0004134,NaN,NaN,2 wins & 3 nominations.,Australia,1973-8-19,"Geraldton, Western Australia, Australia",1973.0,NaN,NaN,Female,NaN,Tasma Walton,NaN,2.0,Leo,9.0
http://www.imdb.com/name/nm0004147,38.0,NaN,1 nomination.,Finland,1975-4-26,"Tampere, Finland",1975.0,NaN,NaN,Male,1.87,Mikko Nousiainen,NaN,1.0,Taurus,9.0
http://www.imdb.com/name/nm0004149,118.0,NaN,15 wins & 19 nominations.,Sweden,1941-2-13,"Gothenburg, Västra Götalands län, Sweden",1941.0,NaN,8.0,Male,1.97,Bo Svenson,8.0,16.0,Aquarius,14.0
http://www.imdb.com/name/nm0004193,NaN,NaN,16 wins & 10 nominations.,Canada,1968-11-3,"Vancouver, British Columbia, Canada",1968.0,NaN,3.0,Female,1.65,Debbie Rochon,11.0,64.0,Scorpio,52.0
http://www.imdb.com/name/nm0004236,52.0,NaN,7 wins & 7 nominations.,Brazil,1964-6-4,"Curvelo, Minas Gerais, Brazil",1964.0,NaN,NaN,Male,NaN,Ângelo Antônio,1.0,10.0,Gemini,3.0
http://www.imdb.com/name/nm0004244,16.0,75.0,Nominated for 1 Oscar. Another 8 wins & 5 nomi...,France,1907-10-9,"Le Pecq, Seine-et-Oise [now Yvelines], France",1907.0,1982.0,8.0,Male,1.91,Jacques Tati,2.0,16.0,Libra,19.0
http://www.imdb.com/name/nm0004248,87.0,NaN,5 wins & 1 nomination.,France,1952-12-7,"Paris, France",1952.0,NaN,NaN,Male,1.83,Georges Corraface,5.0,17.0,Sagittarius,13.0
http://www.imdb.com/name/nm0004254,2.0,NaN,None,None,None,None,NaN,NaN,NaN,Male,1.70,Edward Terry,1.0,NaN,None,NaN
http://www.imdb.com/name/nm0004266,NaN,NaN,Won 1 Oscar. Another 64 wins & 104 nominations.,USA,1982-11-12,"Brooklyn, New York City, New York, USA",1982.0,NaN,NaN,Female,1.73,Anne Hathaway,5.0,134.0,Scorpio,158.0
http://www.imdb.com/name/nm0004282,NaN,81.0,Won 1 Golden Globe. Another 1 win & 1 nomination.,USA,1930-9-16,"Ossining, New York, USA",1930.0,2011.0,NaN,Female,1.73,Anne Francis,NaN,11.0,Virgo,20.0
http://www.imdb.com/name/nm0004286,111.0,NaN,Nominated for 1 Primetime Emmy. Another 4 wins...,USA,1970-6-16,"Los Angeles, California, USA",1970.0,NaN,2.0,Male,1.73,Clifton Collins Jr.,6.0,1.0,Gemini,24.0
http://www.imdb.com/name/nm0004291,NaN,52.0,2 wins.,British India,1929-6-1,"Calcutta, Bengal Presidency, British India",1929.0,1981.0,NaN,Female,NaN,Nargis,NaN,NaN,Gemini,1.0
http://www.imdb.com/name/nm0004292,69.0,64.0,12 wins & 5 nominations.,British India,1924-12-14,"Peshawar, North-West Frontier Province, Britis...",1924.0,1988.0,10.0,Male,1.70,Raj Kapoor,17.0,NaN,Sagittarius,5.0
http://www.imdb.com/name/nm0004294,NaN,NaN,1 nomination.,USA,1980-8-2,"Newport, Rhode Island, USA",1980.0,NaN,NaN,Female,1.73,Nadia Bjorlin,NaN,1.0,Leo,26.0
http://www.imdb.com/name/nm0004309,NaN,NaN,Nominated for 2 Oscars. Another 6 wins & 16 no...,USA,1936-7-5,"Goessel, Kansas, USA",1936.0,NaN,NaN,Female,NaN,Shirley Knight,1.0,4.0,Cancer,29.0
http://www.imdb.com/name/nm0004310,234.0,73.0,2 wins.,USA,1902-10-5,"Philadelphia, Pennsylvania, USA",1902.0,1975.0,NaN,Male,1.63,Larry Fine,NaN,18.0,Libra,20.0
http://www.imdb.com/name/nm0004334,NaN,NaN,9 wins & 14 nominations.,India,1954-10-10,"Madras, Madras State, India",1954.0,NaN,NaN,Female,1.70,Rekha,NaN,18.0,Libra,12.0
http://www.imdb.com/name/nm0004335,35.0,NaN,28 wins & 23 nominations.,India,1974-1-10,"Bombay, Maharashtra, India",1974.0,NaN,NaN,Male,1.78,Hrithik Roshan,NaN,140.0,Capricorn,24.0
http://www.imdb.com/name/nm0004349,NaN,NaN,None,USA,1973-5-8,"Grand Forks, North Dakota, USA",1973.0,NaN,NaN,Female,1.70,Kam Heskin,NaN,1.0,Taurus,2.0
http://www.imdb.com/name/nm0004354,17.0,NaN,3 wins & 5 nominations.,USA,1960-4-29,"Washington, District of Columbia, USA",1960.0,NaN,16.0,Male,NaN,Caveh Zahedi,12.0,NaN,Taurus,14.0
http://www.imdb.com/name/nm0004363,91.0,NaN,14 wins & 14 nominations.,India,1949-9-6,"Bombay, State of Bombay, India",1949.0,NaN,14.0,Male,NaN,Rakesh Roshan,19.0,NaN,Virgo,12.0
http://www.imdb.com/name/nm0004365,129.0,NaN,2 nominations.,USA,1938-3-5,"Gary, Indiana, USA",1938.0,NaN,23.0,Male,1.91,Fred Williamson,21.0,10.0,Pisces,49.0
http://www.imdb.com/name/nm0004376,NaN,NaN,9 wins & 7 nominations.,Germany,1974-7-22,"Münster, North Rhine-Westphalia, Germany",1974.0,NaN,1.0,Female,1.74,Franka Potente,NaN,23.0,Cancer,24.0
http://www.imdb.com/name/nm0004380,36.0,NaN,4 wins & 1 nomination.,France,1953-12-1,"Paris, France",1953.0,NaN,8.0,Male,NaN,Antoine de Caunes,4.0,5.0,Sagittarius,93.0
http://www.imdb.com/name/nm0004381,NaN,NaN,3 wins & 1 nomination.,France,1976-9-9,"Paris, France",1976.0,NaN,1.0,Female,1.65,Emma de Caunes,NaN,4.0,Virgo,35.0
http://www.imdb.com/name/nm0004395,111.0,NaN,2 wins & 9 nominations.,USA,1973-4-3,"Santa Cruz, California, USA",1973.0,NaN,3.0,Male,1.75,Adam Scott,8.0,8.0,Aries,62.0
http://www.imdb.com/name/nm0004416,33.0,NaN,6 wins & 3 nominations.,India,1946-6-4,"Konetampet, Pallipattu, Chittoor District, And...",1946.0,NaN,NaN,Male,NaN,Balasubramaniam S.P.,5.0,NaN,Gemini,4.0
http://www.imdb.com/name/nm0004417,259.0,73.0,None,India,1923-5-28,"Nimmakuru, Krishna District, Andhra Pradesh, I...",1923.0,1996.0,16.0,Male,NaN,Taraka Rama Rao Nandamuri,3.0,NaN,Gemini,NaN
http://www.imdb.com/name/nm0004418,NaN,NaN,13 wins & 7 nominations.,India,1974-8-5,"Bombay, Maharashtra, India",1974.0,NaN,NaN,Female,1.60,Kajol,NaN,1.0,Leo,8.0